### ISSUE TITLE
Is it possible to run puppeteer on electron window?

### ISSUE THREAD

**Issue by s0thl** [puppeteer/puppeteer#4655] opened 2019-07-02 13:39 UTC
In nightmare.js, there is a possibility to take advantage of the electron window. That doesn't require us to use external chromium nor google chrome executables, because chromium is already bundled into electron.

So, can I take an advantage of that? Been slightly looking through docs and found out that `puppeteer` always requires to specify the chromium executable path to be used and there seem to be no way to overcome this and work nicely within electron process. 

Regards

**Comment by jbures** [comment] 2019-07-05 09:52
If you want to run puppeteer on an already running chromium environment, there's a workaround somewhere that requires you to download a separate chromium instance and include it in the window... which i don't recommend cuz it's heavy af...
I recommend you setup a nodejs server that only runs puppeteer and you can communicate with using endpoints.

I'm currently running electron with reactjs on the frontend, calling endpoints on nodejs that runs puppeteer... i used the create-react-app to setup like 95% of the stuff automatically

**Comment by s0thl** [comment] 2019-07-05 10:03
Meanwhile I was digging a bit and actually [found a way to attach puppeteer to electron instance](https://discuss.atom.io/t/solved-control-automate-an-electron-application-with-puppeteer/64126/8) however, it doesn't seem like this solution is still working, due to the electron not supporting the DevTools protocols which is mentioned in several issues like https://github.com/electron/electron/issues/17776, #3793 and acknowledged in #4283 
Thats why I had to use other solutions available around like `nightmare.js`.

**Comment by AnthoniG** [comment] 2019-07-15 13:26
I've found a way around this and feel really silly that I did not see if before.
To cut a long story short, YES you can use puppeteer WITH electron.

In your JavaScript file to boot electron up, you use puppeteer inside there.
I am using Electron IPC and that calls into the JavaScript boot file and then I use puppeteer from there.
**Works like a charm and no need to go hacking or changing anything**

**Comment by WilliamChiu** [comment] 2019-07-16 03:31
@AnthoniG If you have the time, would you be able to include a code snippet? I am having trouble with this same task right now

**Comment by AnthoniG** [comment] 2019-07-16 09:07
@WilliamChiu 
I was going to try and put up some snippets but was proving to be more work.
I will create a demo project showing it and then I will upload to github and share the link.

Here is the [**link**](https://github.com/AnthoniG/puppeteer-electron). It's not fully fleshed out as it's all I had time for. However the basics are there.

It uses Typescript and I use Yarn rather than npm (hence yarn.lock)
It also presumes that you know how to use Electron's **IPCMain** and **IPCRenderer** as that is the only way to get puppeteer working **without** any hacks

Let me know if you have any problems or questions :)
Just add them as issues on the project itself, this way it keeps this clean :grinning:

**Comment by WilliamChiu** [comment] 2019-07-24 21:25
Thank you! This was very helpful

**Comment by TrevorSundberg** [comment] 2019-08-08 15:56
I wrote a small library to take care of this for my own projects:
https://www.npmjs.com/package/puppeteer-in-electron

It uses the above webSocketDebuggerUrl approach. This does work in the latest version of puppeteer and electron. Disclaimer, the whole library needs a lot of testing.

The other thing I spent a long time trying to solve was how to associate an electron BrowserWindow with a puppeteer Page. I ended up writing a routine that injects JavaScript into the BrowserWindow and searches for that specific Page in puppeteer.

I would note that there are a few limitations in puppeteer, for example you cannot intercept requests due to electron not supporting the network service.

**Comment by lvkins** [comment] 2019-08-08 20:00
> I wrote a small library to take care of this for my own projects:
> https://www.npmjs.com/package/puppeteer-in-electron
> 
> It uses the above webSocketDebuggerUrl approach. This does work in the latest version of puppeteer and electron. Disclaimer, the whole library needs a lot of testing.
> 
> The other thing I spent a long time trying to solve was how to associate an electron BrowserWindow with a puppeteer Page. I ended up writing a routine that injects JavaScript into the BrowserWindow and searches for that specific Page in puppeteer.
> 
> I would note that there are a few limitations in puppeteer, for example you cannot intercept requests due to electron not supporting the network service.

**Comment by robomantis19** [comment] 2019-08-09 04:10
its very interesting. npm test worked for me, but npm start did not. no start script

**Comment by thenat97** [comment] 2019-11-27 07:14
Hello, im trying to make puppeteer run with the instance of chromium from electron, my code is based from @AnthoniG but i keep getting errors, could you guys help me? 
Here is my github repository of this tiny integration

https://github.com/thenat97/electron-puppeteer

**Comment by AnthoniG** [comment] 2019-11-28 11:11
> Hello, im trying to make puppeteer run with the instance of chromium from electron, my code is based from @AnthoniG but i keep getting errors, could you guys help me?
> Here is my github repository of this tiny integration
> 
> https://github.com/thenat97/electron-puppeteer
Hi, from the small tests that I have done:- it's saying that it cannot find puppeteer in puppeterTest
It looks like you are mixing import styles. This is not the place for this and I will open an issue on your repo and we can discuss it there :smile:

**Comment by JustinELRoberts** [comment] 2020-01-04 16:03
@TrevorSundberg Would you mind adding a code snippet showing how you were able to render a Puppeteer `Page` in an ElectronJS `BrowserWindow`? I'm not able to recreate it.

**Comment by TrevorSundberg** [comment] 2020-01-04 20:46
@JustinELRoberts I'm not sure I understand what you mean by render? Basically once you connect puppeteer to electron, puppeteer can control all the pages (including browser windows). The only problem is that puppeteer identifies everything using target-ids, whereas the BrowserWindow does not expose these target-ids so I had to come up with a way to associate these two together. I did this by looping over all the pages in puppeteer, and setting some Javascript on the BrowserWindow so that I could find the right one:

https://github.com/TrevorSundberg/puppeteer-in-electron/blob/d1794c257daa7b585f8f397352c8521f5ebd53c5/index.ts#L62

Does this answer your question? If not feel free to elaborate and I'll try and help

**Comment by JustinELRoberts** [comment] 2020-01-04 20:55
@TrevorSundberg Sorry I'm finding it difficult to word exactly what I'm trying to do. From my understanding, your library allows us to use Puppeteer to control Electron `BrowserWindow`s. In my case I would like to use Puppeteer to open a new instance of Chromium, but have it display inside a `BrowserWindow` rather than inside of a new Chromium window. The reason I want to do this the way I'm mentioning rather than simply use a `BrowserView` or your library is that if I run [this](https://antoinevastel.com/bots/) test with a `BrowserView`, it fails because a it is missing the `window.chrome` object. However, Chromium passes with flying colors.

I specifically @'ed you because I thought that's what you were saying you did in the second to last paragraph of your [this](https://github.com/puppeteer/puppeteer/issues/4655#issuecomment-519579145) message.

**Comment by TrevorSundberg** [comment] 2020-01-04 21:15
I see, I'm not sure that I know how to achieve that. Provided my understanding of everything is correct*, electron is running it's own compiled version of Chromium, which means you can't just have puppeteer run a full blown instance of real Chromium and have it somehow link into electron; different processes, different binaries, etc. I haven't used electron extensively, but there might be a way to expose `window.chrome` through some call or to emulate it to make it as close to a real browser as possible. Although I imagine if your BrowserView is getting fingerprinted there's probably a large amount of things you'd need to expose or mimic to pass bot tests :/

The thing I was talking about in that paragraph, and in general with what I wrote, was that since electron was still a build of Chromium, it still happens to include the Chrome Devtools Protocol (a websocket protocol to control Chrome). Puppeteer was built around this, so through some hacky process I was able to expose the protocol in electron apps and connect puppeteer to it. This does not however create a real Chromium instance at all, it merely just controls electron with limitations, since again it's a fork of Chromium with things removed, such as your finding with `window.chrome` and many other things.

**Comment by TrevorSundberg** [comment] 2020-01-04 21:16
The only other idea I can think of is that you do some sort of remoting where you run a full non-headless version of chromium but you either hide it and broadcast the screen, or do something very hacky where you place or parent the window to the electron window.

**Comment by JustinELRoberts** [comment] 2020-01-04 21:19
Sorry to keep bothering you but could you please elaborate a bit more on how I could hack this together? My current solution is already running a non-headless version of Chromium through puppeteer so that bit isn't much of an issue. I just wanted to make these Chromium instances child windows of my `BrowserWindow`.

**Comment by blohamen** [comment] 2020-02-27 12:41
> I wrote a small library to take care of this for my own projects:
> https://www.npmjs.com/package/puppeteer-in-electron
> 
> It uses the above webSocketDebuggerUrl approach. This does work in the latest version of puppeteer and electron. Disclaimer, the whole library needs a lot of testing.
> 
> The other thing I spent a long time trying to solve was how to associate an electron BrowserWindow with a puppeteer Page. I ended up writing a routine that injects JavaScript into the BrowserWindow and searches for that specific Page in puppeteer.
> 
> I would note that there are a few limitations in puppeteer, for example you cannot intercept requests due to electron not supporting the network service.

About intercepting requests. Any workarounds on how we can deal with it? The problem is when you try to respond on intercepted request puppeteer thinks that request finished but in chrome dev tools I can see that something strange happened with the request: status finished and I can see the response but I can't set up headers and status to 200. And also response not appeared in javascript code. 
```javascript
await chartPage.on('request', (req) => {
    if (req.url().includes('TracsProxy')) {
      console.log(req);
      req.respond({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(tracsProxyMock),
      });
    } else {
      req.continue();
    }
  });
```

**Comment by TrevorSundberg** [comment] 2020-02-28 00:00
@blohamen 
I have to look into it more, but I saw this issue over on electron: https://github.com/electron/electron/issues/15791

It's marked as closed so I'll have to investigate, not sure if there's another good workaround but let me know if you find one.

**Closed as completed** 2022-07-26 22:02 UTC
Labels: unconfirmed

**Comment by hayzedDev** [comment] 2023-03-06 10:29
> > Hello, im trying to make puppeteer run with the instance of chromium from electron, my code is based from @AnthoniG but i keep getting errors, could you guys help me?
> > Here is my github repository of this tiny integration
> > https://github.com/thenat97/electron-puppeteer
> > Hi, from the small tests that I have done:- it's saying that it cannot find puppeteer in puppeterTest
> > It looks like you are mixing import styles. This is not the place for this and I will open an issue on your repo and we can discuss it there 😄

Has anyone tried this and it worked?

**Comment by JuanBovier** [comment] 2024-05-26 15:21
![image](https://github.com/puppeteer/puppeteer/assets/131731281/43ac1b66-a70d-44d5-acdb-e471c7da516f)

```import { BrowserWindow, app } from 'electron'
import { join } from 'path'
import puppeteer from 'puppeteer-core'

let mainWindow

async function createWindow(): Promise<void> {
  mainWindow = new BrowserWindow({
    webPreferences: {
      sandbox: false,
      contextIsolation: true
    }
  })

  mainWindow.once('ready-to-show', async () => {
    mainWindow.show()

    try {
      const response = await fetch('http://localhost:9222/json/version')
      const debugEndpoints = await response.json()
      const webSocketDebuggerUrl = debugEndpoints.webSocketDebuggerUrl

      const browser = await puppeteer.connect({
        browserWSEndpoint: webSocketDebuggerUrl
      })

      const pages = await browser.pages()
      const page = pages[0]
      await page.goto('https://example.com')
    } catch (error) {
      console.error('Error al conectar con Puppeteer:', error)
    }
  })

  mainWindow.loadFile(join(__dirname, '../renderer/index.html'))
}

app.commandLine.appendSwitch('remote-debugging-port', '9222')

app.whenReady().then(async () => {
  await createWindow()
})
```

**Comment by AnthoniG** [comment] 2024-05-27 05:27
@hayzedDev What's not working for you?
