### ISSUE TITLE
[Bug]: exposeFunction() sometimes gets stuck waiting forever, yet there's no documented timeout parameter.

### ISSUE THREAD

**Issue by php4fan** [puppeteer/puppeteer#8106] opened 2022-03-06 13:58 UTC
### Bug description

Steps to reproduce the problem:

```
console.log("Exposing function...");

await page.exposeFunction('myFunction', () => {
    // whatever...
    return;
});

console.log("Function exposed.");
```

About 80% of the times this works as expected.
Occasionally, however, this will get stuck waiting forever after this output:
```
Exposing functions...
```

As far as I understand, exposing a function is an instantaneous operation except for the part of sending a request to the browser (or in my case to chrome.browserless.io) and getting a response from it, so the only case where I can imagine this remaining stuck waiting without throwing an exception, is a network issue or the browser failing to respond.

But then there should be a configurable timeout parameter and I don't see any documented.

### Puppeteer version

13.4.0

### Node.js version

17.0.1

### npm version

8.1.0

### What operating system are you seeing the problem on?

Linux

**Comment by tomaszferens** [comment] 2022-05-17 09:42
Having the same issue. Any ideas how to resolve it or are there any workarounds?

I found similar issue, but it got closed:
https://github.com/puppeteer/puppeteer/issues/2709

**Comment by croqaz** [comment] 2022-05-24 10:15
Having the same issue.
I'm restoring a live page from local cache, page looks OK, hangs when I try to expose even a super basic function like console.log.
puppeteer: 14.1.1

Actually I had to do this hack of exposing this function because the request interception hangs forever, but this also hangs.

**Comment by php4fan** [comment] 2022-07-23 11:22
> We're marking this issue as unconfirmed because it has not had recent activity

This is stupid. If there hasn't been any recent activity, then do some activity and fix it, or at least start investigating it. That's not a reason for closing a bug

> and we weren't able to confirm it yet.

There's no indication that you tried, there has been no response from any human being on your side. Plus, multiple users have confirmed it.

> It will be closed if no further activity occurs within the next 30 days.

That's even more stupid, I don't even know where to start.

**Comment by php4fan** [comment] 2022-07-23 11:31
Regarding workarounds, here's the one I use (not to avoid the timeout but at least detect and catch it), I am a complete dummy with nodejs so this is probably c**p but it does the trick for me and for my use case:

```
const awaitTimeout = (delay, reason) =>
    new Promise((resolve, reject) =>
        setTimeout(
            () => (reason === undefined ? resolve() : reject(reason)),
            delay
        )
    );

const wrapPromise = (promise, delay, reason) =>
    Promise.race([promise, awaitTimeout(delay, reason)]);

var exposeFunctions = async function() {
  await page.exposeFunction('someFunction', async (g) => {
      // whatever
  });
  await page.exposeFunction('someOtherFunction', async (g) => {
      // whatever
  });
  // .....
}

try {
    await wrapPromise(
        exposeFunctions(),
        10000, // or whatever you see fit
        "Timeout waiting for exposeFunction()"
    );
} catch (e) {
    // this part is probably specific to my particular use case
    browser.close();
    throw e;
}
```

**Comment by php4fan** [comment] 2022-09-21 13:46
Again??

**Comment by gaaasstly** [comment] 2022-10-03 22:42
I can confirm this is an issue for me as well.

```await page.exposeFunction('foo', mutationRecords => {
  console.info('begin exposeFunction');
  for (const mutationRecord of mutationRecords) {
    switch (mutationRecord.type) {
      case 'attributes':
        ...
        break;
    }
  }
});
console.info('post exposeFunction');```

Seems to be 50/50 on if it hangs indefinitely.

**Comment by gaaasstly** [comment] 2022-10-03 22:44
I can confirm this is an issue for me as well.

```
await page.exposeFunction('foo', mutationRecords => {
  console.info('begin exposeFunction');
  for (const mutationRecord of mutationRecords) {
    switch (mutationRecord.type) {
      case 'attributes':
        ...
        break;
    }
  }
});
console.info('post exposeFunction')
;
```

Seems to be 50/50 on if it hangs indefinitely.

**Comment by nightpool** [comment] 2022-10-06 18:52
I'm having the same issue—it works most of the time, but sometimes it just completely hangs. Not sure yet what might be causing it

**Comment by lusvelt** [comment] 2022-10-29 00:23
Hi, I'm having the same issue here. Still no word?

**Comment by OrKoN** [comment] 2022-11-04 10:47
Please provide an executable repro script that demonstrates the issue using a local chromium version bundled with a recent version of puppeteer.

**Comment by php4fan** [comment] 2022-11-04 10:58
By local do you mean Chromium has to be running on the same machine as puppeteer??
It's possible that a necessary condition to reproducing the issue is precisely that Chromium is remote. In fact I strongly suspect that is the case.
The choices that reproduces is provided in my initial report. What conditions exactly are needed to reproduce it I don't know. I use Browser less.

**Comment by php4fan** [comment] 2022-11-04 10:59
And note that, as stated, it reproduces randomly and not frequently.

**Comment by OrKoN** [comment] 2022-11-04 11:03
@php4fan it might be a problem with the browserless, then? We have many places where we have no timeouts on the RPC calls and the browser is expected to respond if it's not disconnecting the session. Can you get the CDP log for when it happens at least? so that we are able to confirm that the browser is not sending a response?

**Comment by php4fan** [comment] 2022-11-04 11:12
> We have many places where we have no timeouts on the RPC calls and the browser is expected to respond if it's not disconnecting the session

That sounds to me like an issue in itself. Everything that involves a round trip of data through the network must have a timeout. Also, "expected to respond" means nothing. What if it responds in a hour? "Expected to respond" should be "expected to respond within a given time", and therefore there must be a timeout (which also must be configurable).

> Can you get the CDP log for when it happens at least?

I don't know how to do that

**Comment by OrKoN** [comment] 2022-11-04 11:18
> That sounds to me like an issue in itself. Everything that involves a round trip of data through the network must have a timeout. Also, "expected to respond" means nothing. What if it responds in a hour? "Expected to respond" should be "expected to respond within a given time", and therefore there must be a timeout (which also must be configurable).

That's debatable and it'd be a feature request. You can implement it yourself if you see time outs on your network using e.g., `Promise.race`. In this particular case, it could be there is a browser issue and the browser indeed does not send a response. That should be fixed on the browser site and it's hard to locate the issue without a somewhat reliable repro.

> I don't know how to do that
Run with the env var `DEBUG=puppeteer:*`, that would stdout the logs for the browser communication.

**Comment by php4fan** [comment] 2022-11-04 11:19
> it might be a problem with the browserless, then?

That could be, or it could be a network issue. Either way, there's no scenario where it can be acceptable for the client to wait forever and never either succeed or fail.

**Comment by OrKoN** [comment] 2022-11-04 11:20
> That could be, or it could be a network issue. Either way, there's no scenario where it can be acceptable for the client to wait forever and never either succeed or fail.

Please file a feature request for CDP timeout!

**Comment by php4fan** [comment] 2022-11-04 11:22
> That's debatable and it'd be a feature request.

It's not debatable and it would be a design flaw. What's debatable is where the limit is, and if there is a difference at all, between a design flaw and a bug. To me the distinction is pointless unless it serves the purpose to assign it to a different person or team; in the end both are things that are wrong and need fixing.

> You can implement it yourself if you see time outs on your network using e.g., Promise.race. 

I know, that's the workaround

**Comment by chrisk8er** [comment] 2023-06-15 08:12
I have the same issue.

**Comment by wilsonssss** [comment] 2023-08-01 07:09
stuck at page.exposeFunction,  that's what i m happening.

**Comment by AmirAchhodi** [comment] 2023-08-29 14:34
I have the same issue.

**Comment by jasonswearingen** [comment] 2023-09-27 21:45
I am seeing `page.exposeFunction` hang 100% of the time with pptr `v21.3.5`.  reverting to `v21.2.1` fixes the issue.

This is on Win10x64 nodejs `v16.13.1`

**Comment by AstralJaeger** [comment] 2023-10-11 07:27
I can confirm @jasonswearingen I'm seeing the same behavior on Windows Server 2022 21H2 with pptr ``v21.3.8`` and Chrome/120.0.6059.0 where ``page.exposeFunction()`` will never return (or atleast within a timeout of 50 or 100s).
This is on nodejs ``v18.15.0``

**Comment by dbuteyn** [comment] 2023-10-19 15:01
Experiencing this issue with puppeteer-core@21.3.8, chromium118.0.5993.70-1~deb11u1.

Ran single browser, created three incognito context, created three pages, tried to register three functions. This time only registration succeeded. Relevant log entries with `DEBUG=puppeteer:*` below.

@OrKoN  Note the absence of `Runtime.evaluate` commands for the first two registration attempts.
```
exposing event_triggered d38lyas8aq
2023-10-19T14:43:57.233Z puppeteer:protocol:SEND ► [
  '{"method":"Runtime.addBinding","params":{"name":"event_triggered"},"id":18,"sessionId":"E5C066BF68B72260570FD059622CB0AB"}'
]
2023-10-19T14:43:57.234Z puppeteer:protocol:RECV ◀ [
  '{"id":18,"result":{},"sessionId":"E5C066BF68B72260570FD059622CB0AB"}'
]
2023-10-19T14:43:57.235Z puppeteer:protocol:SEND ► [
  '{"method":"Page.addScriptToEvaluateOnNewDocument","params":{"source":"(function addPageBinding(type, name) {...);\\n})(\\"exposedFun\\",\\"event_triggered\\")"},"id":19,"sessionId":"E5C066BF68B72260570FD059622CB0AB"}'
]
2023-10-19T14:43:57.235Z puppeteer:protocol:RECV ◀ [
	'{"id":19,"result":{"identifier":"2"},"sessionId":"E5C066BF68B72260570FD059622CB0AB"}'
  ]

exposing event_triggered 7gr381z85v
2023-10-19T14:43:57.234Z puppeteer:protocol:SEND ► [
  '{"method":"Runtime.addBinding","params":{"name":"event_triggered"},"id":18,"sessionId":"B46203B8A21E92568B7996F2811EA4BB"}'
]
2023-10-19T14:43:57.235Z puppeteer:protocol:RECV ◀ [
  '{"id":18,"result":{},"sessionId":"B46203B8A21E92568B7996F2811EA4BB"}'
]
2023-10-19T14:43:57.236Z puppeteer:protocol:SEND ► [
  '{"method":"Page.addScriptToEvaluateOnNewDocument","params":{"source":"(function addPageBinding(type, name) {...);\\n})(\\"exposedFun\\",\\"event_triggered\\")"},"id":19,"sessionId":"B46203B8A21E92568B7996F2811EA4BB"}'
]
2023-10-19T14:43:57.237Z puppeteer:protocol:RECV ◀ [
	'{"id":19,"result":{"identifier":"2"},"sessionId":"B46203B8A21E92568B7996F2811EA4BB"}'
  ]

exposing event_triggered guuyfxruo2
2023-10-19T14:43:57.236Z puppeteer:protocol:SEND ► [
  '{"method":"Runtime.addBinding","params":{"name":"event_triggered"},"id":18,"sessionId":"318BA597542960B206FC066956FF522F"}'
]
2023-10-19T14:43:57.237Z puppeteer:protocol:RECV ◀ [
  '{"id":18,"result":{},"sessionId":"318BA597542960B206FC066956FF522F"}'
]
2023-10-19T14:43:57.237Z puppeteer:protocol:SEND ► [
  '{"method":"Page.addScriptToEvaluateOnNewDocument","params":{"source":"(function addPageBinding(type, name) {...);\\n})(\\"exposedFun\\",\\"event_triggered\\")"},"id":19,"sessionId":"318BA597542960B206FC066956FF522F"}'
]
2023-10-19T14:43:57.238Z puppeteer:protocol:RECV ◀ [
  '{"id":19,"result":{"identifier":"2"},"sessionId":"318BA597542960B206FC066956FF522F"}'
]
2023-10-19T14:43:57.238Z puppeteer:protocol:SEND ► [
  '{"method":"Runtime.evaluate","params":{"expression":"(function addPageBinding(type, name) {...);\\n})(\\"exposedFun\\",\\"event_triggered\\")\\n//# sourceURL=pptr:;CdpFrame.%3Canonymous%3E%20(%2Fopt%2Fnode-v18.18.2-linux-x64%2Flib%2Fnode_modules%2Fpuppeteer-core%2Flib%2Fcjs%2Fpuppeteer%2Futil%2Fdecorators.js%3A108%3A27)\\n","contextId":1,"returnByValue":true,"awaitPromise":true,"userGesture":true},"id":20,"sessionId":"318BA597542960B206FC066956FF522F"}'
]
2023-10-19T14:43:57.239Z puppeteer:protocol:RECV ◀ [
  '{"id":20,"result":{"result":{"type":"undefined"}},"sessionId":"318BA597542960B206FC066956FF522F"}'
]
exposed event_triggered guuyfxruo2
```

**Comment by OrKoN** [comment] 2023-10-19 20:23
I am unable to reproduce your scenario @dbuteyn is anything else going? perhaps any alert dialogs shown on some of the pages?

```
import puppeteer from "puppeteer";

(async () => {
  const browser = await puppeteer.launch();

  async function test() {
    const context = await browser.createIncognitoBrowserContext();
    const page = await context.newPage();
    await page.exposeFunction('test', () => {
      console.log('test called');
    });
    await page.evaluate('test()');
  }

  await Promise.all([
    test(),
    test(),
    test(),
  ]);

  console.log('done')
})();
```

**Comment by dbuteyn** [comment] 2023-10-22 09:15
@OrKoN its timing-sensitive. It won't happen all the time, just sometimes. I was also loading a page, yes. Though I don't think it matters. As stated in my previous comment, two out of tree attempts failed. Other runs only one failed, or none at all. I experienced this issue ~15% of the time.

As a workaround I've removed all exposeFunction calls though I would really like to be able to register callbacks. Waiting for promises on the remote causes protocol errors whenever the page navigates elsewhere and something is still waiting on a remote promise. Waiting on local promises resolved via callbacks doesn't exhibit that problem and will simply time out (because the page is no more).

**Comment by LevanKvirkvelia** [comment] 2023-10-26 02:51
Confirming this issue

**Comment by dbuteyn** [comment] 2023-10-26 13:28
With `page.exposeFunction` broken, `page.waitForFunction()` setting your CPU on fire and waiting on promises returned by `page.evaluate()` not being an option as doing so will throw protocol errors on unexpected page navigation, there are not many options left.

Honestly, all the `page.waitFor...` functions are not very friendly to use as they all require wrapping in `Promise.race()`, set your CPU on fire and/or throw protocol errors on navigation. But I digress.

Came up with this workaround by abusing the page Event Emitter.

```js
await new Promise(async (resolve, reject) => {
	const timeout_error = new Error("Timeout"); // define here so trace makes sense
	const timer = setTimeout(() => reject(timeout_error), 5000);
	await page.evaluate(() => {
		// use MutationObserver, addEventListener, whatever you need as a trigger
		setTimeout(() => {
			console.log("event", "your message here");
		}, 1000);
	});
	page.on("console", async (message) => {
		if (message.type() == "log") {
			const [ type, event ] = message.args();
			if (type && event && await type.jsonValue() == "event") {
				// filter particular event, etc
				clearTimeout(timer);
				resolve(await event.jsonValue());
			}
		}
	});
	// fill out forms, click buttons, etc
});
```

**Comment by php4fan** [comment] 2023-12-18 00:29
I just updated Puppeteer, and now, instead of randomly and very rarely, `exposeFunction` **gets stuck systematically**.

This is my code, which was a workaround to deal with the issue of `exposeFunction` sometimes getting stuck (this times out instead):
```
const awaitTimeout = (delay, reason) =>
    new Promise((resolve, reject) =>
        setTimeout(
            () => (reason === undefined ? resolve() : reject(reason)),
            delay
        )
    );

const wrapPromise = (promise, delay, reason) =>
    Promise.race([promise, awaitTimeout(delay, reason)]);

    var exposeFunctions = async function() {
       await page.exposeFunction('someFunction', (text) => {
            // whatever
        });

    }

    try {
        await wrapPromise(
            exposeFunctions(),
            10000,
            "Timeout waiting for exposeFunction()"
        );
    } catch (e) {
        browser.close();
        throw e;
    }

```
IIRC this workaround was suggested by someone in this thread.

Now I **systematically** get timeout every single time.

**Comment by unravelers-tech** [comment] 2023-12-27 14:28
Confirming that the issue persists for `21.6.1`. Reverting to `21.2.1` helped.

Hanging occurs in 75% or something.

**Comment by php4fan** [comment] 2023-12-27 14:47
When I originally reported the issue, hanging on `exposeFunction` only happened a small percentage of times. The original issue was about the lack of a built-in timeout mechanism (assuming that occasional failures were unavoidable) like EVERYTHING that has a chance of hanging (no matter how remote) should have.

But recently I updated puppeteer from version 13.4 to the latest (or fairly recent), and since then, as the previous commenter said, **`exposeFunction` now hangs most of the time**.
The issue is now that it hangs so frequently that it's basically unusable, and this is a regression.

**Comment by unravelers-tech** [comment] 2023-12-27 14:50
@php4fan Apologies.

It happens with a frequency of 10%. Tested it again on a larger dataset. 21 pages in parallel, 7 parallel cloud functions. 3 pages per cloud function.

2 pages stuck. => `~10%`

**Comment by LevanKvirkvelia** [comment] 2023-12-27 14:56
i just switched to playwright and it works well

**Comment by php4fan** [comment] 2023-12-27 15:18
> So roughly 5%

With what puppeteer version?

**Comment by OrKoN** [comment] 2023-12-27 16:27
@php4fan could you provide a standalone script that demonstrates the issue? I was not able to reproduce so far. See my attempt at reproducing the issue here https://github.com/puppeteer/puppeteer/issues/8106#issuecomment-1771652741

**Comment by unravelers-tech** [comment] 2023-12-27 17:28
@OrKoN 

```
import puppeteer from 'puppeteer';

async function run(): Promise<void> {
  const browser = await puppeteer.launch({ headless: 'new' });

  const pageUrl = 'https://css-tricks.com/making-calendars-with-accessibility-and-internationalization-in-mind/';

  await Promise.all(Array(10).fill(pageUrl).map(async (url, index) => {
    console.log('Start', index);

    const page = await browser.newPage();

    await page.goto(url, { waitUntil: 'networkidle2' });

    const selector = '.article-content';

    await page.waitForSelector(selector);

    const elementHandle = await page.$(selector);

    const propertyName = 'textContent';

    console.log('==== Start exposeFunction()', index);
    await page.exposeFunction('getPropName', () => propertyName);
    console.log('==== Complete exposeFunction()', index);

    await page.evaluate(
      // @ts-ignore
      async (element) => (element as HTMLElement)[await window['getPropName']()],
      elementHandle,
    );

    await page.removeExposedFunction('getPropName');

    await page.close();

    console.log('Complete', index);
  }));

  console.log('Complete all.');

  await browser.close();
}

run();

```

**Comment by unravelers-tech** [comment] 2023-12-27 17:47
@OrKoN I added `race` as you suggested. It all works like a charm. It exposes function correctly. I wonder why it gets stuck without `race`.

```
import puppeteer from 'puppeteer';

async function run(): Promise<void> {
  const browser = await puppeteer.launch({ headless: false });

  const pageUrl = 'https://css-tricks.com/making-calendars-with-accessibility-and-internationalization-in-mind/';

  await Promise.all(Array(10).fill(pageUrl).map(async (url, index) => {
    console.log('Start', index);

    const page = await browser.newPage();

    await page.goto(url, { waitUntil: 'networkidle2' });

    const selector = '.article-content';

    await page.waitForSelector(selector);

    const elementHandle = await page.$(selector);

    const propertyName = 'textContent';

    console.log('==== Start exposeFunction()', index);

    await Promise.race([
      page.exposeFunction('getPropName', () => propertyName),
      new Promise((resolve) => setTimeout(resolve, 1000)),
    ]);

    console.log('==== Complete exposeFunction()', index);

    const res = await page.evaluate(
      // @ts-ignore
      async (element) => (element as HTMLElement)[await window['getPropName']()],
      elementHandle,
    );

    await Promise.race([
      page.removeExposedFunction('getPropName'),
      new Promise((resolve) => setTimeout(resolve, 1000)),
    ]);

    console.log(`----------> Result len:${!!res ? res.length : 0 }`, index);

    await page.close();

    console.log('Complete', index);
  }));

  console.log('Complete all.');

  await browser.close();
}

run();
```

**Comment by OrKoN** [comment] 2023-12-27 18:08
Thanks for this example. In this case, it looks like one of several frames on the site does not have the execution context properly reported by the browser. That sounds like a bug in the browser. I wonder if other reports have the same underlying issue?

**Comment by php4fan** [comment] 2023-12-28 15:25
Here's mine:

```
const pup = require('puppeteer-core');
const sleep = ms => new Promise(r => setTimeout(r, ms));

const awaitTimeout = (delay, reason) =>
    new Promise((resolve, reject) =>
        setTimeout(
            () => (reason === undefined ? resolve() : reject(reason)),
            delay
        )
    );

const wrapPromise = (promise, delay, reason) =>
    Promise.race([promise, awaitTimeout(delay, reason)]);


(async function () {

    try {
        await main();
    } catch (e) {
        await console.log("!!!!! Failed with ERROR: ", e);
    }
})();


async function main() {

    await console.log("Connecting with Puppeteer...");
    const browser = await pup.connect({browserWSEndpoint: "wss://chrome.browserless.io?token=XXXXXXX"});

    await console.log("Puppeteer connected. Opening new page...");
    const page = await browser.newPage();

    var URL = 'https://www.nytimes.com/games/wordle/index.html';

    await console.log("All ready. Requesting URL '"+URL+"'");
    await page.goto(URL, {timeout: 10000});

    await console.log("Navigated to URL. Exposing functions...");

    var exposeFunctions = async function() {
        await page.exposeFunction('emulateWriteToClipboard', (text) => {
            shareText = text;
        });
    }

    try {
        await wrapPromise(
            exposeFunctions(),
            10000,
            "Timeout waiting for exposeFunction()"
        );
    } catch (e) {
        browser.close();
        throw e;
    }
    browser.close();
    console.log("Done.");

}
```

When it works I get:
```
Connecting with Puppeteer...
Puppeteer connected. Opening new page...
All ready. Requesting URL 'https://www.nytimes.com/games/wordle/index.html'
Navigated to URL. Exposing functions...
Done.
```
When it hangs I get:
```
Connecting with Puppeteer...
Puppeteer connected. Opening new page...
All ready. Requesting URL 'https://www.nytimes.com/games/wordle/index.html'
Navigated to URL. Exposing functions...
!!!!! Failed with ERROR:  Timeout waiting for exposeFunction()
```

**Comment by OrKoN** [comment] 2023-12-28 17:14
I have opened a PR based on https://github.com/puppeteer/puppeteer/pull/11600 based on findings from https://github.com/puppeteer/puppeteer/issues/8106#issuecomment-1870508448 Please give the patch a try to see if it helps.

**Closed as completed** 2024-01-02 12:58 UTC
Labels: confirmed

**Comment by Kle0s** [comment] 2024-08-22 13:41
To me this is still happening (puppeteer version 23.0.2) :/
