### ISSUE TITLE
[Bug]: Puppeteer crashes on waitForDevicePrompt()

### ISSUE THREAD

**Issue by outofambit** [puppeteer/puppeteer#11072] opened 2023-10-03 22:05 UTC
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
  });
  const mainPage = await browser.newPage();
  await mainPage.goto("http://google.com");
  await mainPage.waitForDevicePrompt();
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I've been working on automating running the manual web bluetooth tests in https://github.com/WebBluetoothCG/manual-tests. (see https://github.com/WebBluetoothCG/manual-tests/issues/38 for more details). I ran into this issue while trying to use puppeteer's API to connect to a bluetooth device.

I've verified that:
- running `navigator.bluetooth.getDevices` in the console of a Chrome for Testing opened by puppeteer doesn't crash
- manually sending a message over CDP to enable DeviceAccess on a Chrome for Testing instance opened by puppeteer also doesn't crash

These are equivalent to what should happen with a call to `waitForDevicePrompt()`, leading me to believe this is a bug in puppeteer itself. (I've also reproduced this crash with a headless setup, but I'm not sure this can work in a headless environment anyway).

From looking through this repo's git history, it seems that this feature itself has been minimally changed since it was added in https://github.com/puppeteer/puppeteer/pull/9299/, so I'm wondering if perhaps something changed elsewhere in the codebase to break this behavior?

Please let me know if any more information would be helpful!

---
**Note:** The minimal script to achieve my goal is below, but the minimal script I provided above is enough to trigger the crash.

```ts
import puppeteer from "puppeteer";

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
  });
  const mainPage = await browser.newPage();
  await mainPage.goto(
    "http://googlechrome.github.io/samples/web-bluetooth/get-devices-async-await.html"
  );
  await mainPage.waitForNetworkIdle();
  const [devicePrompt] = await Promise.all([
    mainPage.waitForDevicePrompt(),
    mainPage.locator("#requestBluetoothDevice").click(),
  ]);
  console.log(devicePrompt.devices);
  await browser.close();
})();
```

### Expectation

In the above script, I would expect puppeteer to timeout while waiting for the bluetooth menu to appear. In my actual use case, I would add code 

### Reality

Puppeteer crashes immediately on calling `waitForDevicePrompt()` with the following stack trace:

```shell
/Users/user-name/src/bluetooth-puppeteer/node_modules/puppeteer-core/src/util/assert.ts:29
    throw new Error(message);
          ^
Error
    at assert (/Users/user-name/src/bluetooth-puppeteer/node_modules/puppeteer-core/src/util/assert.ts:29:11)
    at CdpFrame.#deviceRequestPromptManager (/Users/user-name/src/bluetooth-puppeteer/node_modules/puppeteer-core/src/cdp/Frame.ts:299:11)
    at CdpFrame.waitForDevicePrompt (/Users/user-name/src/bluetooth-puppeteer/node_modules/puppeteer-core/src/cdp/Frame.ts:307:50)
    at CdpFrame.<anonymous> (/Users/user-name/src/bluetooth-puppeteer/node_modules/puppeteer-core/src/util/decorators.ts:71:21)
    at CdpPage.waitForDevicePrompt (/Users/user-name/src/bluetooth-puppeteer/node_modules/puppeteer-core/src/cdp/Page.ts:1215:35)
    at run (/Users/user-name/src/bluetooth-puppeteer/index.ts:9:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Puppeteer version

21.3.6

### Node version

18.17.1

### Package manager

npm

### Package manager version

9.6.7

### Operating system

macOS

**Comment by outofambit** [comment] 2023-10-03 22:20
I'm a little confused by the parsing used for errors by the issue analyzer Action above but hopefully the stack trace I included in the rest of the form makes the expected output from my example clear!

**Comment by OrKoN** [comment] 2023-10-04 07:50
@mzgoddard do you have thoughts? It looks like we actually missed the coverage for this case and I think #deviceRequestPromptManager might be not working as expected.

**Comment by outofambit** [comment] 2023-10-05 16:44
@mzgoddard and i chatted offline about this and we looked at these lines, where the assert fails and the crash starts:

https://github.com/puppeteer/puppeteer/blob/377cd83ccfe5c0ced2d69ea6cbed758a3b2629df/packages/puppeteer-core/src/cdp/Frame.ts#L298-L299

The best guess we had there was that perhaps something has changed with Frames or the Frame lifecycle in puppeteer in the last ~6 months that would cause this to behave differently? I don't see any obvious things from the git history.

@thiagowfx let us know if you have any ideas! 🙏

**Comment by OrKoN** [comment] 2023-10-06 06:07
@outofambit I am not sure anything has changed either but perhaps the assertion was not correct? I believe the main frame always has no parent frame.

**Comment by thiagowfx** [comment] 2023-10-12 10:03
I can reproduce it.

**Comment by thiagowfx** [comment] 2023-10-15 16:36
@outofambit Please try again. I believe this should be fixed now.

**Closed as completed** 2023-10-16 13:50 UTC
Labels: confirmed

**Comment by outofambit** [comment] 2023-10-16 16:21
@thiagowfx thanks so much for looking at this! 🙏🏽 i'll give it a try today and report back. i'll also take a look at the e2e tests and see if i have something i can propose.

**Comment by Lightning00Blade** [comment] 2023-10-16 16:27
Note: there is no new release for this it will be part of `v21.4.0`, when #11095 gets merged.

**Comment by outofambit** [comment] 2023-10-19 17:21
@thiagowfx i was able to run this in my application with a locally built version of puppeteer and it worked great! 🎉 thanks again!
