### ISSUE TITLE
Add ability to close a page from the main puppeteer instance

### ISSUE THREAD

**Issue by tmpace** [puppeteer/puppeteer#851] opened 2017-09-21 21:22 UTC
There didn't seem to be a format for creating a feature request, so here goes:

### Problem

Currently, there is no way to close a page other than where you have access to the page itself. We should have a way to close the page from the root puppeteer instance. Here's my current setup:

1.) Master node process creates an instance of Browser by calling `puppeteer.launch()` and then spins up workers.

2.) Works individually use `puppeteer.connect()` to connect to chromium, creating an instance of Browser within the workers, and then a page is created on the browser.

3.) Workers do some work that takes time. This work, in some situations, might be infinite. In this instance, we have to force-kill the worker. When doing this, the page that the crawler was working with remains open. Since we had to force-kill, we can not set up a way within the worker so that it gracefully shuts down and closes the page before exiting the process.

Providing a way to be able to close a page through `puppeteer` would be ideal here. I've looked at the source and am having a hard time following the flow of events throughout, I'd be happy to submit a PR for a way to do what I describe if someone would like to walk me through how events are propagated to pages.

Sorry if this isn't the correct format for a feature request, if I can do better at explaining the issue please let me know!

**Comment by ebidel** [comment] 2017-09-21 22:42
https://github.com/GoogleChrome/puppeteer/pull/554 should help.

**Comment by aslushnikov** [comment] 2017-10-04 23:51
Closing as a dupe of #386

**Closed as completed by aslushnikov** 2017-10-04 23:51 UTC
