### ISSUE TITLE
[Bug]: Puppeteer v21.11 fails to install with yarn or npm

### ISSUE THREAD

**Issue by hsinha** [puppeteer/puppeteer#12094] opened 2024-03-15 03:59 UTC
### Minimal, reproducible example

```TypeScript
run `npm install puppeteer@21.11`

The command stalls and nothing happens for a long time. We have to kill the process.

Note: npm install works with puppeteer >=22
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

Install successfully

### Reality

Doesn't install and stalls the process

### Puppeteer version

21.11.0

### Node version

20.9.0

### Package manager

npm

### Package manager version

10.1.0

### Operating system

macOS

**Comment by RopoMen** [comment] 2024-03-15 07:00
We have similar issues when running `npm ci` with package-lock.json that has Puppeteer 21.11.0

We have also tried to use flag `--dns-result-order=ipv4first` but it does not work anymore, when using flag `--ignore-scripts` installation continues, but of course this does not download browser.

So, I belive that there is some issues to download that browser. We previously added this flag about 4 months ago `--dns-result-order=ipv4first` and it has worked this far.

**Comment by RopoMen** [comment] 2024-03-15 07:02
https://github.com/puppeteer/puppeteer/issues/11060

**Comment by AllBogs** [comment] 2024-03-15 08:55
We seem to be running into the same issue as of yesterday. Node.js 20.9.0, NPM 10.1.0, Puppeteer 21.6.1.

On my local machine, I observe that process `node install.mjs` seems to get stuck.

The installer seems to work as expected. I can see it download and then extract a Zip archive containing Chrome. It just doesn't seem to terminate properly.

In case it's related, we're using a custom `.puppeteerrc.cjs` file with the following content:

```
const { join } = require('path');
module.exports = {
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
```

**Comment by vasylshylov** [comment] 2024-03-15 09:27
Same issue. We are using `puppeteer@21.11.0` with the same config as mentioned above and it is not installing. Installation script is stuck after [this line](https://github.com/puppeteer/puppeteer/blob/9b7b443f9e66cab2eb5bd30306da367e65621ce3/packages/puppeteer/src/node/install.ts#L139). Installation was successful after I added `process.exit(0)` below this line.

Also, everything works fine if the needed version of chrome is already in the cache.

**Comment by schdaniel20** [comment] 2024-03-15 09:54
We had the same problem with "puppeteer": "21.3.6". In a newly created container. Node version: 18.19.1. NPM 10.2.4.

We updated the puppeteer package to 22.4.1

**Comment by RopoMen** [comment] 2024-03-15 10:05
This has also similar symptoms https://github.com/npm/cli/issues/7288

**Comment by Lightning00Blade** [comment] 2024-03-15 10:16
It seems some issue with the server not closing the connection for the old download url (We changed endpoints in https://github.com/puppeteer/puppeteer/pull/11923). 
A workaround for this would be to set the baseUrl to the new endpoint - 
```
PUPPETEER_DOWNLOAD_BASE_URL="https://storage.googleapis.com/chrome-for-testing-public"

**Comment by RopoMen** [comment] 2024-03-15 10:38
@Lightning00Blade Thank you !!! this worked!

**Comment by Lightning00Blade** [comment] 2024-03-15 17:39
The issue should now be resolved even without the workaround mentioned earlier.

Please report if the issue is still present for you!

**Comment by isaac-svg** [comment] 2024-04-13 21:20
@Lightning00Blade the issue still persists without the work around 

![image](https://github.com/puppeteer/puppeteer/assets/109481712/b2f8d369-a87a-4912-8513-6a39804dd059)

node version : 18.20.2
npm version:  10.5.7
OS: Ubuntu 22.04

**Comment by Lightning00Blade** [comment] 2024-04-15 09:44
@isaac-svg when using `npm i puppeteer` that will install the latest version so this issue is unrelated what you are observing.
I tried reproducing but it works as expected, please open a separate issue with all the information and provide logs.

**Comment by Lightning00Blade** [comment] 2024-04-26 13:34
Closing as the issue is resolved.
At some point all users are expected to switch to using the new endpoint via 
PUPPETEER_DOWNLOAD_BASE_URL="https://storage.googleapis.com/chrome-for-testing-public".
Or better yet consider updating `puppeteer` to version after `v22.1.0` that point to that URL by default.

**Closed as completed by Lightning00Blade** 2024-04-26 13:34 UTC
Labels: confirmed, @puppeteer/browsers, P3
