### ISSUE TITLE
[BUG] Browser closes after 5s timeout if notification with requireInteraction flag is opened

### ISSUE THREAD

**Issue by skyiea** [puppeteer/puppeteer#1696] opened 2017-12-30 22:06 UTC
I'm trying to switch to `puppeteer` to test Chrome extension, and facing an issue that drastically increases time needed for tests to run - from 1s to 6s.
I've nailed exact culprit. [On extension install](https://developer.chrome.com/extensions/management#event-onInstalled) I'm showing notification with a flag `requireInteraction` set to `true`.
>Indicates that the notification should remain visible on screen until the user activates or dismisses the notification. This defaults to false.
With that flag `browser.close()` holds for 5 seconds longer than without it (the flag).

I've created repo-example: https://github.com/skyiea/puppeteer-issue-example
Here is the test itself:
```js
const puppeteer = require('puppeteer');

const runTest = async (extPath) => {
    const browser = await puppeteer.launch({
        headless: false,
        args: [
            `--disable-extensions-except=${extPath}`,
            `--load-extension=${extPath}`,
        ],
    });

    const page = await browser.newPage();
    await page.goto('http://example.com');

    const start = Date.now();
    await browser.close();

    return Date.now() - start;
};

(async () => {
    console.log('When requireInteraction === false, browser closes in:', await runTest('./ext-interaction-not-required'));
    console.log('When requireInteraction === true, browser closes in:', await runTest('./ext-interaction-required'));
})();
```

Results:
```
> node test.js

When requireInteraction === false, browser closes in: 53
When requireInteraction === true, browser closes in: 5058
```

I would assume that when `browser.close` is called, no matter whether notification _requires interaction_ - it should be forcefully closed.

**Comment by ebidel** [comment] 2018-01-01 00:31
What if you use the web notification api instead of the crx api?  

```js
const n = new Notification('Title', {body: 'Body!', requireInteraction: true});
...
n.close();
```

I created a page without extensions involved which registers an empty service worker and displays a notification. After the user grants access, the notification shows but doesn't hang on `await browser.close()`. You may also want to try closing it yourself (`Notification.close()`) to see if that works (what the script does although that wasn't needed). 

I should note that when testing, `requireInteraction: true` doesn't seem to work with the Chromium we bundle. The notification is dismissible like `requireInteraction: false`. Are you seeing the same in chrome extensions? Switching to Canary worked. 

sw.html:

```html
<script>navigator.serviceWorker.register('sw.js');</script>
```

test.js:

```js 
const puppeteer = require('puppeteer');

puppeteer.launch({
  headless: false,
  executablePath: '/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary'
}).then(async browser => {
  const page = await browser.newPage();

  await page.goto('http://localhost:5000/sw.html', {waitUntil: 'networkidle2'});

  await page.evaluate(async () => {
    const permission = await Notification.requestPermission();
    if (permission === 'granted') {
      return new Promise(resolve => {
        const n = new Notification('Title', {body: 'Body!', requireInteraction: true});
        n.onshow = e => setTimeout(() => n.close(), 2000); // display notification for 2s.
        n.onclose = resolve;
      });
    }
  });

  await browser.close(); // doesn't hang.
});
```

**Comment by aslushnikov** [comment] 2018-01-04 05:09
@skyiea indeed, `browser.close()` doesn't close right away: at the very least, it awaits beforeunload hooks and some downloads. We should fix this upstream.

**Comment by aslushnikov** [comment] 2019-01-10 21:46
Dupe of https://github.com/GoogleChrome/puppeteer/issues/3673

**Closed as completed by aslushnikov** 2019-01-10 21:46 UTC
Labels: upstream, chromium
