### ISSUE TITLE
Not all domains cookies are retrieved by .cookies()

### ISSUE THREAD

**Issue by ashutoshSce** [puppeteer/puppeteer#3728] opened 2019-01-05 18:18 UTC
I am looking for a solution where I can retieve all cookies of different domains created for that url.
.cookies() only retrieves for that specific url, but that url has many thrid party scripts which creates cookies for other domain also.

Ex: [Nomad.travel](https://nomad.travel/) got extra cookies other then nomad.travel itself.
```
{
domain: ".facebook.com",
expires: "Fri, 05 Apr 2019 18:26:00 GMT",
expiry: 1554488760,
httponly: true,
name: "fr",
path: "/",
secure: true,
value: "<dummy value>"
},
{
domain: ".static.zdassets.com",
expires: "Sun, 05 Jan 2020 18:25:59 GMT",
expiry: 1578248759,
httponly: true,
name: "__cfduid",
path: "/",
secure: true,
value: "<dummy value>"
},
{
domain: ".doubleclick.net",
expires: "Sat, 05 Jan 2019 18:40:59 GMT",
expiry: 1546713659,
httponly: false,
name: "test_cookie",
path: "/",
secure: false,
value: "<dummy value>"
}
```

**Comment by benjamingr** [comment] 2019-01-07 14:55
You can pass urls to `.cookies` and retrieve those cookies. (For example in that case you'd pass `https://facebook.com` etc)

**Comment by ashutoshSce** [comment] 2019-01-08 06:44
Thanks @benjamingr,
It is working.

As there can be many 3rd parties domains on given website. It will be a iterative task to list them all domain first and then call `.cookies` one by one for different domains.
Is there any way to retireve all 3rd party cookies without calling by domain one by one?

**Comment by benjamingr** [comment] 2019-01-08 08:16
@ashutoshSce You can pass multiple URLs to `.cookies` to grab cookies from multiple domains in one go. It's explained in [the docs](https://github.com/GoogleChrome/puppeteer/blob/v1.11.0/docs/api.md#pagecookiesurls).

**Comment by ashutoshSce** [comment] 2019-01-08 12:17
@benjamingr 
I should know all list of domains, which I feel is a extra task.
page.cookies() with no list of domains should retrieve all cookies from cookiejar.
So I am introducing `Network.getAllCookies` message in this function.
If user needs to get any specific domain cookie then can pass anyway.

Sorry for too many logs here, this is the first time I am creating PR here.
Let me know your view on this.

**Comment by aslushnikov** [comment] 2019-01-10 00:14
@ashutoshSce this is a dupe of #645. This requires some Chromium work, and in fact should be per browser context rather than browser.

**Closed as completed by aslushnikov** 2019-01-10 00:14 UTC
