### ISSUE TITLE
[Bug]: Can't set user agent for new tab on click

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#8308] opened 2022-05-03 20:45 UTC
### Bug description

Steps to reproduce the problem:

1. Create a file tests.html on the serve with contentr:
```
<a class="link" href="/tests2.html" target="_blank">url</a>
```
2. Create an index.js file with content:
```
const puppeteer = require('puppeteer-core');

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    defaultViewport: null,
    executablePath: '/usr/bin/chromium',
devtools: false,
    args: [
'--start-maximized'
 ]
  });

const useragent = 'Mozilla/5.0 (Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0';

  const page = await browser.newPage();
  await page.setUserAgent(useragent);
  await page.setDefaultNavigationTimeout(0);

  let newPage;

  await page.goto('https://localhost/tests.html', {waitUntil: 'networkidle0'});

let newPagePromise = new Promise(x => browser.once('targetcreated', target => x(target.page())));
let s1 = await page.evaluate(() => navigator.userAgent)
console.log(s1)
await page.click('.link');
newPage = await newPagePromise;
newPage.setUserAgent(useragent);
let s2 = await newPage.evaluate(() => navigator.userAgent)
console.log(s2)

  await browser.close();
})();

```
3. Run code
4. In the server logs there will be a request for /test2.html with the header ```Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/100.0.4896.88 Safari/537.36``` means the useragent does not change

### Puppeteer version

13.5.2

### Node.js version

v16.15.0

### npm version

8.5.5

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/100.0.4896.88 Safari/537.36
```

**Comment by OrKoN** [comment] 2022-05-06 06:04
I think you might be missing the await for the `setUserAgent` for the second page if you get the wrong user agent in s2. Also, Puppeteer cannot currently intercept target creation so some requests in the new tab might happen before the user agent is set by the code. I think it's essentially a duplicate of https://github.com/puppeteer/puppeteer/issues/3667

**Closed as completed by OrKoN** 2022-05-06 06:04 UTC
