### ISSUE TITLE
[Bug]: npx @puppeteer/browsers install firefox fails because .tar.bz2 no longer present (only .tar.xz) on https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/

### ISSUE THREAD

**Issue by Nathalie-C8** [puppeteer/puppeteer#13401] opened 2024-12-13 08:06 UTC
### Steps to reproduce

npx @puppeteer/browsers install firefox

Error: Download failed: server returned code 404. URL: https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/firefox-135.0a1.en-US.linux-x86_64.tar.bz2

Looks like the .tar.bz2 file is not longer present on the download site, instead .tar.xz is used.

### Expected results

Latest firefox download for linux succeeds

### Actual results

Error: Download failed: server returned code 404. URL: https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/firefox-135.0a1.en-US.linux-x86_64.tar.bz2

**Comment by OrKoN** [comment] 2024-12-13 08:31
Please update the browsers versions. E.g., `npx @puppeteer/browsers@latest install firefox@nightly`.  Duplicate of https://github.com/puppeteer/puppeteer/issues/13390

**Closed as not planned by OrKoN** 2024-12-13 08:31 UTC
Labels: @puppeteer/browsers
