### ISSUE TITLE
[Bug]: Page.evaluate cannot be run in the code in the Chinese directory

### ISSUE THREAD

**Issue by 1226085293** [puppeteer/puppeteer#10173] opened 2023-05-13 20:51 UTC
### Bug expectation

code:
```
let result_s = await page.evaluate(() => 123);
```
should return 123
But an error is thrown: DOMException {stack: 'InvalidCharacterError: Invalid character

I found the error after debugging, because the judgment statement in the `globalThis.btoa` function throws an error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
// The code is in the Chinese directory

const browser = await puppeteer.launch({ headless: false });
const page = await browser.newPage();
await page.goto("https://baidu.com");
let result_s = await page.evaluate(() => 123);
```

### Error string

DOMException {stack: 'InvalidCharacterError: Invalid character

### Puppeteer configuration

```TypeScript
{ headless: false }
```

### Puppeteer version

20.2.0

### Node version

v19.1.0

### Package manager

npm

### Package manager version

9.3.0

### Operating system

Windows

**Comment by OrKoN** [comment] 2023-05-14 15:12
I was not able to reproduce but I think what happens is that globalThis.btoa fails if special characters are used in the exception stacktrace. Also, globalThis.btoa is marked as deprecated. PTAL

**Comment by 1226085293** [comment] 2023-05-14 15:26
> I was not able to reproduce but I think what happens is that globalThis.btoa fails if special characters are used in the exception stacktrace. Also, globalThis.btoa is marked as deprecated. PTAL

![image](https://github.com/puppeteer/puppeteer/assets/45589707/f1a2b988-974e-4649-8f31-615b72f886eb)

**Comment by 1226085293** [comment] 2023-05-14 15:45
a minimal example

[工具.zip](https://github.com/puppeteer/puppeteer/files/11472312/default.zip)

**Closed as completed** 2023-05-15 10:09 UTC
Labels: confirmed
