### ISSUE TITLE
on headless:false the window pops up each time a new tab is opened

### ISSUE THREAD

**Issue by avimar** [puppeteer/puppeteer#1386] opened 2017-11-14 19:08 UTC
**Tell us about your environment:**

* Puppeteer version: 0.13.0-alpha
* Platform / OS version: Windows

**What steps will reproduce the problem?**
Click links that open a new tab or create a new tab.

**What is the expected result?**
If the window is minimized, it would stay minimized, and allow me to monitor it when I wanted.

**What happens instead?**
It pops up from the task bar and grabs the keyboard focus.

**Comment by aslushnikov** [comment] 2018-01-12 02:48
Closing as a dupe of #1083.

**Closed as completed by aslushnikov** 2018-01-12 02:48 UTC
