### ISSUE TITLE
[Bug]: Youtube link crahing chromium

### ISSUE THREAD

**Issue by danieldeepak1212** [puppeteer/puppeteer#10082] opened 2023-04-26 06:59 UTC
### Bug expectation

 I want to scrap video link of a you tube page (https://www.youtube.com/results?search_query=data+science) all the websites are working fine but the you tube link crash the chromium browser and link is not opening

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const express = require("express");
const puppeteer = require("puppeteer");
const cors = require("cors");
const app = express();
app.use(cors());

app.get("/scrapVideo", async (req, res) => {
  const browser = await puppeteer.launch({
    headless: false,
  });
  const page = await browser.newPage();
  await page.goto("https://www.youtube.com");
  await page.screenshot({ path: "youtube.png" });
  await browser.close();
  res.send("working");
});

app.listen(3300);
```

### Error string

TimeoutError: Navigation timeout of 30000 ms exceeded
    at LifecycleWatcher._LifecycleWatcher_createTimeoutPromise

### Puppeteer version

19.11.1

### Node version

18.15.0

### Package manager

npm

### Package manager version

9.5.0

### Operating system

Linux

**Comment by OrKoN** [comment] 2023-04-26 07:51
Probably duplicate of https://github.com/puppeteer/puppeteer/issues/10033

**Closed as not planned by OrKoN** 2023-04-26 07:51 UTC
Labels: needs-feedback, not-reproducible
