### ISSUE TITLE
wrong viewport in headful mode by default

### ISSUE THREAD

**Issue by DanielRuf** [puppeteer/puppeteer#2558] opened 2018-05-16 19:48 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: Windows 10
* URLs (if applicable): 
* Node.js version: 10

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
```
const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://www.ssllabs.com/ssltest/');
  await page.type('.submitBox input[type="text"][name="d"]', 'https://google.com', {delay: 100});
  await page.click('#hideResults')
  await page.click('.submitBox input[type="submit"]');
```
1. run the code
2. check the size of the viewport and browser window

**What is the expected result?**
The viewport should be as big as the browser window by default.

**What happens instead?**
The viewport is somehow smaller and there are two white areas and scrollbars.
See the screenshot.
![image](https://user-images.githubusercontent.com/827205/40140192-8b5a799c-5952-11e8-865d-d0a59a23550d.png)

**Comment by vsemozhetbyt** [comment] 2018-05-16 19:56
See https://github.com/GoogleChrome/puppeteer#usage

> Puppeteer sets an initial page size to 800px x 600px, which defines the screenshot size. The page size can be customized with [`Page.setViewport()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetviewportviewport).

**Comment by DanielRuf** [comment] 2018-05-16 21:09
So it does not use the full browser window in headful mode? How can this be set to behave like in the normal Chrome browser (viewport = window size)?

**Comment by aslushnikov** [comment] 2018-05-17 00:14
Dupe of #1183.

There's a workaround posted in the issue; we're blocked on upstream fixes to do this the right way (see https://github.com/GoogleChrome/puppeteer/pull/2364).

**Closed as completed by aslushnikov** 2018-05-17 00:14 UTC

**Comment by DanielRuf** [comment] 2018-05-17 04:40
Thanks @aslushnikov, that's definitely what I mean. As per my comment:

> Definitely the same issue that I have.
> 
> Would make sense to disable the viewport emulation in headful mode.
> 
> Or provide an option like in the linked PR.

At least the Google I/O demo looked like there was no viewport emulation or it was probably disabled with some extra flags.
