### ISSUE TITLE
[Bug]: Cannot use socks5 proxy

### ISSUE THREAD

**Issue by slendertaker** [puppeteer/puppeteer#12906] opened 2024-08-07 21:48 UTC
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
puppeteer.use(StealthPlugin());

async function scrape(i) {
    let browser;
    try {
        console.log('Launching browser...');
        browser = await puppeteer.launch({
            headless: true,
            args: [
                '--proxy-server=socks5://123.123.123.123:1234',
                '--no-sandbox',
                '--disable-setuid-sandbox',
            ],
        });

        const page = await browser.newPage();

        console.log('Authenticating proxy...');
        await page.authenticate({
            username: 'username',
            password: 'password',
        });

        console.log('Navigating to Google...');
        await page.goto('https://www.google.com/', { waitUntil: 'networkidle2' });
        console.log('Successfully navigated to Google');
    } catch (error) {
        if (error.message.includes('net::ERR_SOCKS_CONNECTION_FAILED')) {
            console.error('Proxy connection failed. Please check the proxy server and credentials.');
        } else {
            console.error('Error during scraping:', error);
        }
    } finally {
        if (browser) {
            await browser.close()
                .then(() => console.log(`[${i}] Done scraping`))
                .catch((err) => console.error(`[${i}] Error closing browser:`, err));
        }
    }
}

(async () => {
    await scrape(0);
})();
```

### Background

Ive using http proxy before, and its working fine. But when i use socks5 proxy, its getting error.

### Expectation

I expected it can use the socks5 proxies

### Reality

I got net::ERR_SOCKS_CONNECTION_FAILED

### Puppeteer version

22.14.0

### Node version

20.14.0

### Package manager

npm

### Package manager version

10.8.1

### Operating system

Linux

**Comment by OrKoN** [comment] 2024-08-08 04:37
Thanks for filing the issue. I think it is duplicate of https://github.com/puppeteer/puppeteer/issues/4170

**Closed as not planned by OrKoN** 2024-08-08 04:37 UTC
