### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 868618** [puppeteer/puppeteer#13144] opened 2024-09-29 08:36 UTC
### Minimal, reproducible example

```TypeScript
await page.goto('https://creator.xiaohongshu.com/login', { waitUntil: 'domcontentloaded' });

await page.waitForNetworkIdle()
```

### Expectation

run ok 

### Reality

every time its timeout error

### Puppeteer version

puppeteer-core

### Node version

v18.20.3

### Package manager

pnpm

### Package manager version

9.6.0

### Operating system

macOS

**Comment by OrKoN** [comment] 2024-09-30 06:13
Duplicate of https://github.com/puppeteer/puppeteer/issues/13131 ?

**Closed as not planned by OrKoN** 2024-09-30 06:13 UTC
