### ISSUE TITLE
Incorrect screenshot dimensions

### ISSUE THREAD

**Issue by positlabs** [puppeteer/puppeteer#802] opened 2017-09-15 19:15 UTC
I'm attempting to use chrome as a video renderer. It takes a screenshot of the page at a specific resolution (e.g. 1280x544) and then requests the next frame.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: Debian Jessie via docker image node:8.4
* Hosted on container engine
* Cluster is running n1-highcpu-16 nodes

**What steps will reproduce the problem?**

Rapidly take screenshots.

```
const run = async () => {
    let running = true
    setTimeout(() => running = false, 10000)
    let frameNum = 0
    while(running){
        await page.screenshot({
            path: frameNum + '.png',
            fullPage: true
        })
        frameNum ++
    }
}
```

**What is the expected result?**

Screenshots should be the exact size specified by clip, or the exact size of the window if using `fullPage`.

**What happens instead?**

Images are the wrong size. The width becomes 800px, or the height becomes 600px (sometimes both), which I'm guessing is somehow related to the default window size of 800x600.

--------------

I've also filed a ticket at the devtools-protocol. https://github.com/ChromeDevTools/devtools-protocol/issues/57

I'm working on a more thorough code example. It will include a dockerfile.

**Comment by positlabs** [comment] 2017-09-15 21:03
Here is a test case. 

https://github.com/positlabs/puppeteer-screenshot

I actually got the 800x600 issue on my local machine when trying to grab a larger frame size (1920x1080).

OK... got 1920x1080
![6](https://user-images.githubusercontent.com/1918844/30503160-10e7e364-9a1e-11e7-9f38-be752068d5ef.png)

Not OK... got 800x600
![7](https://user-images.githubusercontent.com/1918844/30503161-1101734c-9a1e-11e7-98b7-6e95c93e6305.png)

**Comment by pierre-moire** [comment] 2017-09-26 03:59
I noticed the same thing

**Comment by aslushnikov** [comment] 2017-10-05 00:09
Dupe of #800

**Closed as completed by aslushnikov** 2017-10-05 00:09 UTC
