### ISSUE TITLE
net::ERR_CONNECTION_CLOSED when going from 1.11 to 1.12

### ISSUE THREAD

**Issue by mikaelgramont** [puppeteer/puppeteer#3912] opened 2019-02-05 13:49 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.1
* Platform / OS version: Linux/Debian (running official node:8.9.4 Docker image)
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

1. Launch the Docker image on a Linux/Debian environment
2. Start an npm package and install Puppeteer: `npm init && npm install puppeteer@1.12.1`
3. Save the following script to `example.js` and then run it with `node example.js`:
```
(async () => {
  const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
  const page = await browser.newPage();
  await page.goto('https://example.com').then(async () => {
    await page.screenshot({path: 'example.png'});
  }).catch(async (e) => {
    console.log(e);
  });
  await browser.close();
})();
```
**What is the expected result?**
The expected result (which you get if you install Puppeteer version 1.11.0) is the script running successfully and silently and creating an `example.png` file.

**What happens instead?**
Instead, the script fails and displays the following:
```
Error: net::ERR_CONNECTION_CLOSED at https://example.com
    at navigate (/usr/src/puppeteer-tests/1.12/node_modules/puppeteer/lib/FrameManager.js:101:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  -- ASYNC --
    at Frame.<anonymous> (/usr/src/puppeteer-tests/1.12/node_modules/puppeteer/lib/helper.js:108:27)
    at Page.goto (/usr/src/puppeteer-tests/1.12/node_modules/puppeteer/lib/Page.js:662:49)
    at Page.<anonymous> (/usr/src/puppeteer-tests/1.12/node_modules/puppeteer/lib/helper.js:109:23)
    at __dirname (/usr/src/puppeteer-tests/1.12/example.js:6:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I suspect that may be an issue with the Chromium version linked, but don't know how to diagnose that.

**Comment by mikaelgramont** [comment] 2019-02-05 14:11
Only now do I see that https://github.com/GoogleChrome/puppeteer/issues/3880 may be linked to this. :/

**Comment by aslushnikov** [comment] 2019-02-05 19:25
Dupe of #3880

**Closed as completed by aslushnikov** 2019-02-05 19:25 UTC
