### ISSUE TITLE
Goto referer as option

### ISSUE THREAD

**Issue by schelkun** [puppeteer/puppeteer#1187] opened 2017-10-27 13:56 UTC
I was looking into `goto` method source code.
The only way to set referrer parameter is using extra HTTP headers.

```js
 const referrer = this._networkManager.extraHTTPHeaders()['referer'];
    try {
      // Await for the command to throw exception in case of illegal arguments.
      await this._client.send('Page.navigate', {url, referrer});
    } catch (e) {
      watcher.cancel();
      helper.removeEventListeners([listener]);
      throw e;
    }
```
[https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L465](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L465)

This is very bad way for me. I'm forced to change or reset `extraHTTPHeaders` for every `goto`. But this method is ready to accept referrer as parameter.
What if we rewrite this method like this?

```js
async goto(url, options, refferer) {
    const mainFrame = this._frameManager.mainFrame();
    const watcher = new NavigatorWatcher(this._client, mainFrame._id, this._ignoreHTTPSErrors, options);
    const responses = new Map();
    const listener = helper.addEventListener(this._networkManager, NetworkManager.Events.Response, response => responses.set(response.url, response));
    const navigationPromise = watcher.waitForNavigation();

    if (typeof referrer != 'string')
      referrer = this._networkManager.extraHTTPHeaders()['referer'];

    try {
      // Await for the command to throw exception in case of illegal arguments.
      await this._client.send('Page.navigate', {url, referrer});
    } catch (e) {
      watcher.cancel();
      helper.removeEventListeners([listener]);
      throw e;
    }
    const error = await navigationPromise;
    helper.removeEventListeners([listener]);
    if (error)
      throw error;
    if (this._frameManager.isMainFrameLoadingFailed())
      throw new Error('Failed to navigate: ' + url);
    return responses.get(this.mainFrame().url()) || null;
  }
```

**Comment by GuilloOme** [comment] 2017-10-27 18:17
@schelkun, I already fill a feature request to set headers while calling`page.goto()`(like `Referer`), see #1062 (I invite you to upvote it).

The workaround proposed here should work also for headers (by simply set the referer header in the `overrides`) **BUT** there is a bug making it NOT functional at this time (see #686).

**Comment by aslushnikov** [comment] 2017-10-27 20:50
Closing as dupe of #1062.

**Closed as completed by aslushnikov** 2017-10-27 20:50 UTC
