### ISSUE TITLE
[Bug]: Docker image not running on Macos m1

### ISSUE THREAD

**Issue by eryk-vieira** [puppeteer/puppeteer#9763] opened 2023-03-02 14:51 UTC
### Bug expectation

Dockerfile not running on Macos m1

Here's the output
![image](https://user-images.githubusercontent.com/59400564/222461972-5d6ec64c-9302-4ac7-9917-8364410919a3.png)

### Minimal, reproducible example

```Dockerfile
#Base dockerfile 

FROM node:18

RUN apt-get update \
 && apt-get install -y chromium \
    fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
    --no-install-recommends
    
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

# /...Copy project and install dependencies
```

### Error string

Error: Failed to launch the browser process! Error: Can't open display:

### Puppeteer configuration

```TypeScript
const browser = await puppeteer.launch({
    timeout: 0,
    headless: true,
    executablePath: "/usr/bin/chromium",
    args: ['--no-sandbox']
  });
```

### Puppeteer version

19.7.2

### Node version

18.0.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by Lightning00Blade** [comment] 2023-03-02 17:19
Hey @eryk-vieira, is this issue reproducible with the official [Puppeteer Docker Image](https://pptr.dev/guides/docker) ?

**Comment by eryk-vieira** [comment] 2023-03-02 17:46
Hey @Lightning00Blade with the Puppeteer Official image I get another error but it also doesn't work.

The error running with the official image:
`Error: Failed to launch the browser process! spawn /usr/bin/chromium ENOENT`

That's why I'm trying to create a Docker container installing the Chromium manually. 
On Linux it works perfectly but on Arm64 docker doesn't.

**Comment by Lightning00Blade** [comment] 2023-03-03 09:50
I don't have a Mac ARM on hand to test. I will ask one of the other maintainers to check it out.
I would suggest you try the official image without specifying the `executablePath`, that way Puppeteer will use the one it installs.

**Comment by eryk-vieira** [comment] 2023-03-03 11:05
@Lightning00Blade Already tried that. Unfortunately, it doesn't work as well.

**Comment by OrKoN** [comment] 2023-03-07 13:27
Can you try without custom attributes and timeouts?

**Comment by definder** [comment] 2023-03-10 15:07
I have the same problem with running puppeteer on Mac M1. I tried to fix it different ways and spend more than 10 hours.
Little bit context: puppeteer used inside `react-snap` library, on the local machine it works fine, no issues but when I try to build a Docker image it looks like it's impossible. Tried FROM images like `node:18`, `node:18-slim`, `node:18-alpine` in each case after solving all errors during the build process I get script which performs endlessly. I mean, that on Mac M1 the last script `yarn run snap` never finish In Docker.

All those config works ok on OS Ubuntu and `react-snap` ends without any problem! In order to run script locally on Mac OS, I need to remove `"puppeteerExecutablePath": "google-chrome-stable"` from `package.json`.

I google this problem a lot and didn't find anything helpful. BTW maybe my comment will be useful. 
I believe one day this problem will be fixed 🙂
If anyone knew how to avoid Mac M1 problem with the script which is never finish, type an answer, please. All the best.

**package.json**:
``` 
"reactSnap": {
    "concurrency": 1,
    "ignoreHTTPSErrors": true,
    "include": [
      "/"
    ],
    "inlineCss": true,
    "skipThirdPartyRequests": true,
    "puppeteerExecutablePath": "google-chrome-stable",
    "headless": true,
    "puppeteerArgs": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--single-process"
    ]
  }
```
**Dockerfile**:
``` 
FROM --platform=linux/amd64 node:18

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/googlechrome-linux-keyring.gpg \
    && sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-khmeros fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y curl jq python3 python3-pip
RUN pip3 install awscli

COPY package.json yarn.lock ./
RUN yarn install

COPY . ./

RUN yarn run build
RUN yarn run snap
```

**Comment by ilackovic** [comment] 2023-04-06 13:19
@eryk-vieira , did you manage to solve the issue? I'm having the same error - `Can't open display: ` . I tried several Dockerfile configurations, using node / alpine images, with / without executablePath and playing around with args but no luck.

**Comment by eryk-vieira** [comment] 2023-04-09 13:11
@ilackovic Definitely not, I had to use my Linux computer.

**Comment by ilyahoilik** [comment] 2023-04-14 17:35
I can confirm the issue with official Docker images on M1 MacBook Pro

**Comment by OrKoN** [comment] 2023-04-17 06:18
Have you enabled the beta feature 'Use Rosetta for x86/amd64 emulation on Apple Silicon' via the docker settings? I think it is very likely the cpu architecture mismatch.

**Comment by OrKoN** [comment] 2023-04-27 10:56
The root cause is that the docker image for linux is built with x64 chromium inside and that causes the mismatch in cpu architecture between the host system and the image. We currently don't have linux binaries for amr64 https://github.com/puppeteer/puppeteer/issues/7740

**Comment by eryk-vieira** [comment] 2023-05-23 17:20
@OrKoN @DenisRukavitsa Yes even with Rosetta for x86/amd64 turned on and puppeteer with headless mode. it doesn't work.

**Comment by akimabs** [comment] 2023-06-02 14:44
same issue :(

**Comment by wardnyt** [comment] 2023-08-20 19:02
I'm also having this issue :(

**Comment by Senforge** [comment] 2023-08-20 22:59
same issue

**Comment by someoneinthe** [comment] 2023-10-03 06:19
same :'(

**Comment by jrandolf** [comment] 2023-10-04 07:34
Duplicate of https://github.com/puppeteer/puppeteer/issues/7740

**Closed as not planned by jrandolf** 2023-10-04 07:34 UTC
Labels: confirmed

**Comment by issa-evooq** [comment] 2023-10-12 08:22
> Have you enabled the beta feature 'Use Rosetta for x86/amd64 emulation on Apple Silicon' via the docker settings? I think it is very likely the cpu architecture mismatch.

thanks for this. was experiencing something similar but in jsreports but this did the trick lol

**Comment by anandakumar-ds** [comment] 2024-12-10 02:48
> #7740

This worked for me
