### ISSUE TITLE
puppeteer-firefox: page.cookies()  [failed to call method 'Browser.getCookies']

### ISSUE THREAD

**Issue by Artik-Man** [puppeteer/puppeteer#4525] opened 2019-06-05 08:29 UTC
[Puppetier Firefox  (0.5.0) ] `page.cookies()` is not working.
[Puppetier Chrome (1.16.0) ] `page.cookies()` working ok.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:  puppeteer-firefox: 0.5.0
* Platform / OS version: Linux Mint 19
* Node.js version: 10.15.0

**What steps will reproduce the problem?**

```javascript
(async () => {
    const launchFirefox = require('puppeteer-firefox');
    const browser = await launchFirefox.launch();
    const page = await browser.newPage();
    await page.goto('https://google.com/');
    const cookies = await page.cookies(); // ERROR
    console.log(cookies);
    await browser.close();
})();
```

**What is the expected result?**
List of cookies

**What happens instead?**
```
(node:22191) UnhandledPromiseRejectionWarning: 
 Error: Protocol error (Browser.getCookies): 
  ERROR: failed to call method 'Browser.getCookies' with parameters 
{
  "browserContextId": null,
  "urls": [
    "https://www.google.com/"
  ]
}
Expected "<root>.browserContextId" to be |string|; found |object| `null` instead. 
_dispatch@chrome://juggler/content/protocol/Dispatcher.js:100:15

    at Promise (...../node_modules/puppeteer-firefox/lib/Connection.js:74:56)
    at new Promise (<anonymous>)
    at Connection.send (...../node_modules/puppeteer-firefox/lib/Connection.js:73:12)
    at Page.cookies (...../node_modules/puppeteer-firefox/lib/Page.js:90:30)
    at Page.<anonymous> (...../node_modules/puppeteer-firefox/lib/helper.js:32:23)
    at ...../test.js:6:32
(node:22191) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
This error originated either by throwing inside of an async function without
 a catch block, or by rejecting a promise which was not handled with .catch(). 
 (rejection id: 1)
(node:22191) [DEP0018] DeprecationWarning: Unhandled promise rejections 
 are deprecated. In the future, promise rejections that are not handled 
 will terminate the Node.js process with a non-zero exit code.
```

**Comment by aslushnikov** [comment] 2019-06-06 02:58
@Artik-Man Thanks for filing! Dupe of #4470

**Closed as completed by aslushnikov** 2019-06-06 02:58 UTC
