### ISSUE TITLE
[Bug]: Exposed function is not defined

### ISSUE THREAD

**Issue by 11Firefox11** [puppeteer/puppeteer#10783] opened 2023-08-25 13:19 UTC
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer/lib/esm/puppeteer/puppeteer";

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    defaultViewport: null,
    product: "chrome"
  });
  const page = await browser.newPage();
  page.exposeFunction("myExposed", async () => {
    console.log("myExposed called!");
  });
  await page.goto("https://codepen.io/DeyJordan/pen/MWZwRMm");

  // Calling it on the main frame
  await page.evaluate("myExposed();"); // Works

  for (let frame of page.frames()) {
    await frame.evaluate("myExposed();"); // Throws an error
  }
})();
```

### Error string

myExposed is not defined

### Bug behavior
- [ ] Flaky
- [ ] PDF

### Background

I had a project where I added a document event listener to every frame. If it gets triggered, an [exposed function](https://pptr.dev/api/puppeteer.page.exposefunction) is called. I tested my script out on a simple page, it worked there smoothly. But, it doesn't work as it should on some sites which have iframes. A site like this is codepen. The exposed function works in the main frame (and in a hidden iframe), but it doesn't in the preview of the codepen (the bottom part). 

### Expectation

`myExposed` function should work in iframes too

### Reality

`myExposed` function is not defined in the iframe thus it can't be referenced

### Puppeteer version

21.1.0

### Node version

16.14.0

### Package manager

npm

### Package manager version

9.2.0

### Operating system

Linux

**Comment by OrKoN** [comment] 2023-08-25 14:22
This is another instance of https://github.com/puppeteer/puppeteer/issues/10017 It only works if the frame is in-process. It does not work for any out-of-process iframes. E.g., the following would work.

```
import puppeteer from "puppeteer";

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
  });
  const page = await browser.newPage();
  await page.exposeFunction("myExposed", async () => {
    console.log("myExposed called!");
  });
  await page.goto("https://codepen.io/DeyJordan/pen/MWZwRMm");
  // Calling it on the main frame
  await page.evaluate("myExposed();"); // Works
  for (let frame of page.frames()) {
    if (!frame.isOOPFrame())
      await frame.evaluate("myExposed();"); // Throws an error
  }
})();

```

**Comment by 11Firefox11** [comment] 2023-08-25 14:39
So, there is no way to make `myExposed` work in the bottom frame at the example website I included?
How can be a frame "out-of-process"?

**Comment by OrKoN** [comment] 2023-08-25 14:59
It is only possible in the old headless mode (headless: true) or in other modes with the OOPIFs feature disabled.

**Comment by 11Firefox11** [comment] 2023-08-25 15:19
Thank you!

**Comment by 11Firefox11** [comment] 2023-08-25 15:35
Is there a roadmap about what features will be implemented in the future? I am curious because I see that #10017 was opened in April.

**Comment by OrKoN** [comment] 2023-08-28 06:24
Currently, there is no roadmap

**Comment by OrKoN** [comment] 2024-08-08 20:35
I believe it was fixed in the latest version and I cannot reproduce with v23+

**Closed as completed by OrKoN** 2024-08-08 20:35 UTC
Labels: confirmed, P3
