### ISSUE TITLE
response class

### ISSUE THREAD

**Issue by dpanic** [puppeteer/puppeteer#3596] opened 2018-11-26 19:56 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.10.0
* Platform / OS version: Linux Ubuntu 18.04
* URLs (if applicable):
* Node.js version: 10.13.0

**What is the expected result?**
It will be good that in response class we see protocol as it is in dev protocol of Chrome, also securityDetails can be shared completelly, now we can't see ciphers and keyExchange.

"protocol":"h2",
"securityState":"secure",
"securityDetails":{
"protocol":"TLS 1.2",
"keyExchange":"ECDHE_ECDSA",
"keyExchangeGroup":"X25519",
"cipher":"AES_128_GCM",
"certificateId":0,
"subjectName":"*.google.com",
"sanList":[
...

**What happens instead?**
We see cutted results

**Comment by aslushnikov** [comment] 2018-11-26 23:03
> It will be good that in response class we see protocol as it is in dev protocol of Chrome

We're wary of what we expose in Puppeteer - CDP changes and evolves together with Chromium, whereas Puppeteer aims to provide a long-term stable API for our clients.

Other than that, that's a dupe of #719 - please upvote to follow updates and bump priority.

**Closed as completed by aslushnikov** 2018-11-26 23:03 UTC
