### ISSUE TITLE
Preventing download depending on content_type or size

### ISSUE THREAD

**Issue by Linux999** [puppeteer/puppeteer#1432] opened 2017-11-20 18:01 UTC
I'm trying to NOT download large files or certain mime types, i.e. image or video.
If a link points to i.e. http://sample.com/video.mp4, I want to skip/end the page.goto(). 
Of course, this would work in case the link name reveals the type, like in the example above.
But in other cases, where the content is provided dynamically, this will not work.
i.e. http://sample.com/download.php?call=1 (and this call returns a video, for examples sake).

I can block out downloading images or videos using page.on('request'). But this concerns images on the page I'm calling with goto().
I need this functionality a step earlier, when I'm calling a link that's i.e. a video, which I generally do not want to download.

By reading out the response headers, I can determine whether the file is a type I want to ignore or too large to download:

	
	await page.setRequestInterceptionEnabled(true);	// not working in v0.13.0 anymore???
	
	page.on('request', request => {
	console.log('Url:'+request.url+' - type: '+request.resourceType);
	if (request.resourceType === 'image' || request.resourceType === 'media')
	{
		console.log('Abort file!');
		request.abort();
	}
	else
		request.continue();
	});

	await page.goto(curl, { waitUntil: 'networkidle', timeout: 60000 })
						
	.then(response => {
		var content_type = '';
		// get content type
		if (response.headers['content-type'] != undefined) content_type = response.headers['content-type'];
		else if (response.headers['Content-Type'] != undefined) content_type = response.headers['Content-Type'];
		
		// remove extra info / charset
		if (content_type.indexOf(' ') != -1) content_type = content_type.substring(0, content_type.indexOf(' '));
		if (content_type.slice(-1) == ';') content_type = content_type.substring(0, content_type.length-1);
		
		// if it's an image or a video...
		if (content_type.indexOf('image') > -1 || content_type.indexOf('video') > -1) 
		{
			// here is my problem!!!
			console.log('Aborting!');
		}
	});

			  		
The question is: How can I abort the download (or not even start bestcase, only get the headers and go from there)? I could abort a request, but I can't find a way to abort it in the response code...

**Comment by aslushnikov** [comment] 2017-11-20 23:33
You need response interception. We have an issue for this: #1191 

There is some upstream work that made it possible on the protocol level; it's not yet implemented in the puppeteer though.

Closing this as dupe of #1191. Please upvote it if you'd like it to be implemented!

**Closed as completed by aslushnikov** 2017-11-20 23:33 UTC
