### ISSUE TITLE
Opening a Tab in existing profile and session

### ISSUE THREAD

**Issue by BenHayak** [puppeteer/puppeteer#512] opened 2017-08-24 00:29 UTC
Hey, is it possible to launch as a new tab in an existing profile? 

I have an existing session with cookies and authentication bearer, problem is that puppeteer opens a dedicated chrome without the session or profile I want. 

heres my code:
```js
(async () => {
  const browser = await puppeteer.launch({
  	headless: false,
  	executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  	args: ['--user-data-dir']
  }); 
  const page = await browser.newPage();
})();
```
if i don't use executablePath it opens a whole new profile and there's no error, but when I do it opens a new window at the correct profile/session yet errors with the following:

(node:26977) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aslushnikov** [comment] 2017-08-24 00:40
Dupe of #411

**Closed as completed by aslushnikov** 2017-08-24 00:40 UTC

**Comment by BenHayak** [comment] 2017-08-24 00:50
well, #411 refers to #53 which is adding a cookie api, and not what I described, I have "Auth" header that I must keep, so not just cookies have to be saved, new tab with same session is a must.

Using 
```
const CDP = require('chrome-remote-interface');
 const protocol = await CDP({
    port: chrome.port
  }); 
Page.navigate({
url : "http://example.org"
})
```

works, but it lacks the great API you built with puppeteer.

**Comment by aslushnikov** [comment] 2017-08-24 01:09
@BenHayak renamed #411 so that it's not confusing any more. You'll be able to pass your own data directory which will be used for chromium.

**Comment by BenHayak** [comment] 2017-08-24 12:53
does the project have a support forum we can use? ask operational questions?

can you add "how to start puppeteer in an existing browser session" best practice to the readme? 
code snippet would be nice

**Comment by BenHayak** [comment] 2017-08-24 13:15
If found the solution, 
Can't use tild "~" in in --user-data-dir switch, it'd be added to relative path like so

/tmp/pupeteer.../~/Library...../etc

That was the problem, thanks!
Tip: after launching browse to "chrome://version" to make sure the profile path wasn't handled as relative path.

**Comment by aslushnikov** [comment] 2017-08-24 16:47
@BenHayak the stackoverflow should work fine for this purpose: https://stackoverflow.com/questions/tagged/puppeteer

**Comment by lvvittor** [comment] 2018-01-03 00:28
Hi, i want to do the same thing. I don't understand the solution. I'm noob at web scraping.

**Comment by it-sumanp** [comment] 2019-01-17 16:40
Passing **_userDataDir_** results in the below error on mac
`(node:9717) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
[9718:775:0117/220913.387231:ERROR:browser_dm_token_storage_mac.mm(153)] Error retrieving the machine serial number.`

**Comment by ORESoftware** [comment] 2020-04-28 01:33
#411  does not explain how to use puppeteer against an existing chrome session.
