### ISSUE TITLE
why the method page.on('request') can't intercept fetch request

### ISSUE THREAD

**Issue by zhaobingss** [puppeteer/puppeteer#4695] opened 2019-07-12 09:30 UTC
why the method page.on('request') can't intercept fetch request like this:
![image](https://user-images.githubusercontent.com/14836112/61118164-b8114780-a4ca-11e9-9c78-395c95952630.png)
any one help

**Comment by LeMoussel** [comment] 2019-07-12 10:54
Do you test with [page.setRequestInterception()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetrequestinterceptionvalue) to intercept request?

Example :
```
const puppeteer = require('puppeteer');

(async() => {
const browser = await puppeteer.launch();
const page = await browser.newPage()
await page.setRequestInterception(true)
page.on('request', interceptedRequest => {
  // Do some stuff ...

  interceptedRequest.continue()
})

await page.goto('https://example.org/')

browser.close();
})();
```

**Comment by zhaobingss** [comment] 2019-07-12 12:56
@LeMoussel yes of course, other request is no problem except fetch

**Comment by aslushnikov** [comment] 2019-07-14 23:25
@zhaobingss fetch requests are intercepted just fine - when they come from the main page.

We don't yet surface network traffic from webworkers though; see #2781. And given the initiators on your screenshot, these fetches are coming from web workers. 

(closing as a dupe of the workers network bug).

**Closed as completed by aslushnikov** 2019-07-14 23:25 UTC
