### ISSUE TITLE
Redirect from GET request - res.redirect(response.location) - doesn't open correct URL when headless but works fine headful

### ISSUE THREAD

**Issue by TudorTacal** [puppeteer/puppeteer#2900] opened 2018-07-17 16:18 UTC
I have this Cucumber step where a link is clicked that makes a GET request to my Express route which responds with a redirect to a PDF page ```res.redirect(response.location)```. It works fine in headful but fails in headless with ```AssertionError: expected ':' to include 'correctPdfUrl'```. Did anyone encounter this kind of behavior?

Unfortunately, I can't post an example that can be downloaded and ran locally because it's work code, I have to be very mindful about what i show.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.6.0
* Platform / OS version: macOS Sierra
* URLs (if applicable): Unable to provide.
* Node.js version: 8.11.3

**What steps will reproduce the problem?**
1. Browser setup
```
Before(async function before() {
  this.browser = await puppeteer.launch({
    executablePath: process.env.NODE_ENV && '/usr/bin/chromium-browser',
    headless: false,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--allow-insecure-localhost', '--disable-popup-blocking', '--disable-gpu'],
    ignoreHTTPSErrors: true,
  });

  this.page = await this.browser.newPage();
  await this.page.setViewport({
    height: 800,
    width: 1280,
  });
});

After(async function after(scenario) {
  if (scenario.result.status === Status.FAILED) {
    const screenshot = await this.page.screenshot({
      fullPage: true,
    });
    await this.attach(screenshot, 'image/png');

    const dir = `${__dirname}/../../../build/test/screenshots`;
    const filename = scenario.pickle.name
      .toLowerCase()
      .replace(/ /g, '-');

    fs.writeFileSync(`${dir}/${filename}.png`, screenshot);
  }

  return this.browser.close();
});
```
2. Cucumber steps that are displaying inconsistent behavior. 

```
Then('the user opts to view the PDF', async function step() {
  await this.page.click('[data-name="view-pdf"]');
  await this.page.waitFor(3000);
});
```
```
Then('a new window with a PDF is opened', async function step() {
  const [tabOne, tabTwo, tabThree] = await this.browser.pages(); 
  expect(tabThree.url()).to.include('https://myRedactedUrl');
});
```
**What is the expected result?**

Everything works as expected when I run headful. I can see the GET request to my server and straight away the redirect to the PDF URL.
```
Then('a new window with a PDF is opened', async function step() {
  const [tabOne, tabTwo, tabThree] = await this.browser.pages(); 

  console.log(tabOne.url(), 'tabOne.url()');       // about:blank tabOne.url()
  console.log(tabTwo.url(), 'tabTwo.url()');        // http://localhost:3000/myRedactedUrl
  console.log(tabThree.url(), 'tabThree.url()');  // https://correctPdfURL

  console.log('pages', (await this.browser.pages()).length);      // 3
  expect(tabThree.url()).to.include('https://correctPdfURL')  ;  // passes
});
```

**What happens instead?**

This time running headless.
```
Before(async function before() {
  this.browser = await puppeteer.launch({
    executablePath: process.env.NODE_ENV && '/usr/bin/chromium-browser',
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--allow-insecure-localhost', '--disable-popup-blocking', '--disable-gpu'],
    ignoreHTTPSErrors: true,
  });

  this.page = await this.browser.newPage();
  await this.page.setViewport({
    height: 800,
    width: 1280,
  });
});

After(async function after(scenario) {
  if (scenario.result.status === Status.FAILED) {
    const screenshot = await this.page.screenshot({
      fullPage: true,
    });
    await this.attach(screenshot, 'image/png');

    const dir = `${__dirname}/../../../build/test/screenshots`;
    const filename = scenario.pickle.name
      .toLowerCase()
      .replace(/ /g, '-');

    fs.writeFileSync(`${dir}/${filename}.png`, screenshot);
  }

  return this.browser.close();
});
```
```
Then('a new window with a PDF is opened', async function step() {
  const [tabOne, tabTwo, tabThree] = await this.browser.pages(); 

  console.log(tabOne.url(), 'tabOne.url()');            // about:blank tabOne.url()
  console.log(tabTwo.url(), 'tabTwo.url()');             // http://localhost:3000/myRedactedUrl
  console.log(tabThree.url(), 'tabThree.url()');       // :

  console.log('pages', (await this.browser.pages()).length);            // 3
  expect(tabThree.url()).to.include('https://correctPdfURL');          // fails
});
```

Link Click -> GET /pdf Express -> res.redirect(response.location) -> Browser opens a new tab with the http://correctPdfUrl -> Works headful vs Doesn't work headless

Thank a lot, you're doing a great job.

**Comment by aslushnikov** [comment] 2018-07-19 02:13
It looks like the issue is with PDF viewing in headless mode. The thing is, Chrome Headless doesn't know how to show PDFs (PDF viewer is not a part of headless chrome), so it initiates a download instead. And downloads are not properly supported yet, see #299 

Speculatively closing; hope this helps, let me know if it doesn't.

**Closed as completed by aslushnikov** 2018-07-19 02:13 UTC

**Comment by TudorTacal** [comment] 2018-07-19 09:10
It makes sense. 

Thanks for the reply.
