### ISSUE TITLE
PDF documents are timed out with { headless: true }

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#830] opened 2017-09-20 01:39 UTC
### Steps to reproduce
* Puppeteer version: v0.11.0-alpha
* Platform / OS version: Windows 7 x64

This code works quickly and properly:
```js
'use strict';

const puppeteer = require('puppeteer');

const timeout = 60000;

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false });
    const page = await browser.newPage();
    await page.goto('http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf', { timeout });
    await page.goto('http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-131Ar1.pdf', { timeout });
    await page.goto('https://nodejs.org/static/documents/trademark-policy.pdf', { timeout });

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

However, with `{ headless: true }` it causes this error:
```console
Error: Navigation Timeout Exceeded: 60000ms exceeded
    at NavigatorWatcher.waitForNavigation (puppeteer\lib\NavigatorWatcher.js:73:20)
    at <anonymous>
```

If PDF documents are not supported in the headless mode, maybe this should be documented.

**Comment by ebidel** [comment] 2017-09-20 02:04
`headless: false` does not support PDFs. There's a note on https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions.

Are you sure `{ headless: true }` is causing the timeout? Or perhaps you're accidentally using `{ headless: false }`?

**Comment by vsemozhetbyt** [comment] 2017-09-20 02:13
I mean not creating PDF, but opening them. Linked note in the doc concerns creating (generating) PDF.

I've checked once more: `{ headless: false }` allows opening PDF, `{ headless: true }` causes the timeout.

**Comment by ebidel** [comment] 2017-09-20 03:32
Ah sorry. Should have read your code :)

This is a dupe of https://github.com/GoogleChrome/puppeteer/issues/610#issuecomment-326542923. As noted in https://github.com/GoogleChrome/puppeteer/issues/610#issuecomment-327297003, headless doesn't support navigating to a pdf. We should definitely document that. 

Would you like to submit a PR?

**Comment by vsemozhetbyt** [comment] 2017-09-20 08:28
@ebidel I would like to, but I am not sure what is an appropriate place (or even places) for such a note (notes).

**Comment by ebidel** [comment] 2017-09-20 15:16
The API docs: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md

**Comment by vsemozhetbyt** [comment] 2017-09-20 15:25
I mean, in what part? Does `page.goto()` suffice?

**Comment by vsemozhetbyt** [comment] 2017-09-20 20:26
PR: https://github.com/GoogleChrome/puppeteer/pull/836

**Comment by aslushnikov** [comment] 2017-10-04 23:41
The `page.goto('url-to-pdf')` should not timeout in headless browser; on the contrary, it should return a valid response so that it could be inspected.

Otherwise, there's too much of a difference between headless vs headful modes, that results in a terrible workarounds like #852.

**Comment by aslushnikov** [comment] 2018-05-31 08:34
We changed the behavior so that navigation to PDF will result in ERR::Aborted in puppeteer 1.4.0.
Looks like a good compromise.

**Closed as completed by aslushnikov** 2018-05-31 08:34 UTC

**Comment by heaven** [comment] 2021-12-20 18:38
@aslushnikov is there any way to get the content type? I mean, we also use abort for other purposes and show the error to the user. When our crawler faces a pdf document it also returns the aborted error but we need to see the reason.

**Comment by AlessandroLittera** [comment] 2022-05-13 09:38
> @aslushnikov is there any way to get the content type? I mean, we also use abort for other purposes and show the error to the user. When our crawler faces a pdf document it also returns the aborted error but we need to see the reason.

Hi, have you discovered something new? I have the same problem, I have to read and open some urls, only if these urls are pdf it times out, how could you manage this error?

**Comment by heaven** [comment] 2022-05-13 09:43
@AlessandroLittera hi, nope, unfortunately. I've had to switch to other tasks fow now. Please let me know if you find anything.
