### ISSUE TITLE
[Bug]: Chromium revision `1056772` breaks PDF rendering when overflowing content between pages

### ISSUE THREAD

**Issue by PHLAK** [puppeteer/puppeteer#9273] opened 2022-11-14 18:00 UTC
### Bug description

The Chromium revision (`1056772`) included with Puppeteer since v19.2.0 has a bug when rendering PDFs that will prevent overflow of certain elements between pages from rendering on the following page.

See [this reported issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1383890) on the Chromium bug tracker.

I was able to resolve this by setting the `PUPPETEER_BROWSER_REVISION` to the previous revision (i.e. `1045629`) and re-installing puppeteer/downloading the older Chromium version.

### Puppeteer version

v19.2.2

### Node.js version

v19.0.1

### npm version

8.19.2

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment] 2022-11-15 09:02
Looks like a duplicate of https://github.com/puppeteer/puppeteer/issues/9260 which resulted in the mentioned crbug.

**Closed as not planned by OrKoN** 2022-11-15 09:02 UTC
