### ISSUE TITLE
`setRequestInterception(true)` will abort some requests?

### ISSUE THREAD

**Issue by zebulonzh** [puppeteer/puppeteer#3450] opened 2018-10-26 10:11 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.9.0
* Platform / OS version: mac OS X 10.14
* URLs (if applicable):https://m.weibo.cn/u/6385759349?uid=6385759349
* Node.js version: v9.6.1

**What steps will reproduce the problem?**

I wanna log all requests produced by a website until a special request appear.

```js
const puppeteer = require('puppeteer');

(async function main() {
    try {
        const browser = await puppeteer.launch({ headless: false });
        const page = await browser.newPage();

        await page.setRequestInterception(true);
        page.on('request', interceptedRequest => {
            console.log(interceptedRequest.url());
            interceptedRequest.continue();
        });

        // make a promise to wait until a special request finished
        let limit_url = 'containerid=1076';
        let limit_prom = page.waitForResponse(response => {
            return response.url().indexOf(limit_url)>-1
        });

        // start working
        let url = 'https://m.weibo.cn/u/6385759349?uid=6385759349';
        let goto_prom = page.goto(url, {waitUntil : ["load", "domcontentloaded", "networkidle0"]}).catch(e => {console.log(e)});

        // wait both promise finished
        await Promise.all([limit_prom, goto_prom]);

        await page.close();
        await browser.close();
    } catch (err) {
        console.error(err);
    }
})();
```

But here is the problem:when I set `true` to function named `setRequestInterception`, some request wouldn't send. Does `setRequestInterception(true)` conflict with `waitForResponse` or there are something went wrong about `setRequestInterception(true)`

I tried this:
``` js
        /*
        await page.setRequestInterception(true);
        page.on('request', interceptedRequest => {
            console.log(interceptedRequest.url());
            interceptedRequest.continue();
        });
        */
```
log requests with function `waitForResponse` and it worked, but I can't log or do something about every single request with event `request`.

**What is the expected result?**
<img width="831" alt="xnip2018-10-26_17-21-34" src="https://user-images.githubusercontent.com/5405421/47558772-7cd3e600-d946-11e8-8ea8-ee5e64aedc8a.png">

**What happens instead?**
<img width="801" alt="xnip2018-10-26_17-22-44" src="https://user-images.githubusercontent.com/5405421/47558811-99701e00-d946-11e8-8397-c2776e35aaba.png">

**Comment by Paxa** [comment] 2018-10-29 11:53
Having similar issue

**Comment by aslushnikov** [comment] 2018-11-01 07:10
Dupe of #3471; closing this in favor of umbrella bug.

**Closed as completed by aslushnikov** 2018-11-01 07:10 UTC
