### ISSUE TITLE
Add ability to override default args

### ISSUE THREAD

**Issue by cretz** [puppeteer/puppeteer#850] opened 2017-09-21 20:00 UTC
Sadly things like #774 are making it in (and shouldn't)  which is setting args we cannot change. In my case, I don't want headless and I want to load extensions but that CLI param stops `--load-extension`.

Please provide a way for the user to provide the *exact* args for Chrome when automating (headless or not).

**Comment by ebidel** [comment] 2017-09-22 01:10
chrome-launcher allows users to re-enable: https://github.com/GoogleChrome/chrome-launcher#launchopts. We should support something like that.

**Comment by aslushnikov** [comment] 2017-10-04 23:48
Dupe of #872

**Closed as completed by aslushnikov** 2017-10-04 23:48 UTC
