### ISSUE TITLE
[Bug]: On PDF export, hyperlinks do not navigate to the correct page

### ISSUE THREAD

**Issue by catchshyam** [puppeteer/puppeteer#12772] opened 2024-07-17 18:15 UTC
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch();
const page = await browser.newPage();

// Set test content.
await page.setContent(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Table of Contents Example</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        .page {
            page-break-before: always;
            padding: 20px;
        }
        .page:first-of-type {
            page-break-before: auto;
        }
        .toc a {
            text-decoration: none;
            color: blue;
        }
    </style>
</head>
<body>
    <div class="page">
        <h1>Title Page</h1>
        <p>Welcome to this document.</p>
    </div>
    <div class="page toc">
        <h1>Table of Contents</h1>
        <ul>
            <li><a href="#page1">Page 1</a></li>
            <li><a href="#page2">Page 2</a></li>
            <li><a href="#page3">Page 3</a></li>
            <li><a href="#page4">Page 4</a></li>
        </ul>
    </div>
    <div class="page" id="page1">
        <h1>Page 1</h1>
        <p>Content for page 1.</p>
    </div>
    <div class="page" id="page2">
        <h1>Page 2</h1>
        <p>Content for page 2.</p>
    </div>
    <div class="page" id="page3">
        <h1>Page 3</h1>
        <p>Content for page 3.</p>
    </div>
    <div class="page" id="page4">
        <h1>Page 4</h1>
        <p>Content for page 4.</p>
    </div>
</body>
</html>
`);

    const pdfBuffer = await page.pdf({
      // format: 'A4',
      printBackground: false,
      preferCSSPageSize: true,
      waitForFonts: true,
      omitBackground: true,
      tagged: false,
    });

await browser.close();

// send the pdf buffer as API response
```

### Background

I am trying to export my webpage to PDF. Everything seems to workfine except hyperlink navigations

### Expectation

The navigation works fine on the webpage

### Reality

On PDF export, navigation jumps ahead by few pages. There seems to be a pattern to the jump. The number of page breaks before the target seems to influence the jump offset,

### Puppeteer version

22.13.0

### Node version

20

### Package manager

npm

### Package manager version

10.5.0

### Operating system

Windows

**Comment by OrKoN** [comment] 2024-07-18 05:13
Sounds like a duplicate of https://github.com/puppeteer/puppeteer/issues/12601 Please let me know if it's not. The issue should be fixed in latest (Canary) Chrome builds.

**Closed as not planned by OrKoN** 2024-07-18 05:13 UTC
