### ISSUE TITLE
[Bug]: Timeouts after update

### ISSUE THREAD

**Issue by christianh104** [puppeteer/puppeteer#13154] opened 2024-10-04 10:17 UTC
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';
const browser = await puppeteer.launch({ headless: true });
const page = (await browser.pages())[0];
await page.goto('https://google.com', { waitUntil: 'load' });
await page.pdf();
await browser.close();
```

### Background

I am storing web documents as PDFs.

### Expectation

No problems :)

### Reality

On 22.8.2, everything works perfectly.
Starting with 22.9.0, page.pdf() times out.
Starting with 23.2.0, puppeteer.launch({ headless: true }) opens a blank white window (no window chrome, and no icon on taskbar), and times out.

TimeoutError: Timed out after waiting 30000ms
    at file:///.../node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:235:19
    at file:///.../node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:1936:31
    at OperatorSubscriber2._this._next (file:///.../node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:993:9)
    at Subscriber2.next (file:///.../node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:696:12)   
    at AsyncAction2.<anonymous> (file:///.../node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:2280:20)
    at AsyncAction2._execute (file:///.../node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:1360:12)
    at AsyncAction2.execute (file:///.../node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:1349:22)
    at AsyncScheduler2.flush (file:///.../node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:1427:26)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  [cause]: undefined
}

### Puppeteer version

22.9.0

### Node version

22.1.0

### Package manager

npm

### Package manager version

10.8.2

### Operating system

Windows

**Comment by OrKoN** [comment] 2024-10-04 10:32
Sounds like a duplicate of https://github.com/puppeteer/puppeteer/issues/13012 and potentially https://pptr.dev/troubleshooting#chrome-reports-sandbox-errors-on-windows (although latest versions of Puppeteer set the permissions on Windows correctly).

**Closed as not planned by OrKoN** 2024-10-04 10:32 UTC

**Comment by OrKoN** [comment] 2024-10-04 10:35
For https://github.com/puppeteer/puppeteer/issues/13012 you can try using a later Chrome 130+ build as the issue should be fixed in that version and for timeouts try setting the permissions using icacls  and use dumpio: true to confirm the cause of timeouts.
