### ISSUE TITLE
[Feature]: Make the docker container armv8 compatible

### ISSUE THREAD

**Issue by Yoeori** [puppeteer/puppeteer#10858] opened 2023-09-07 09:48 UTC
### Feature description

The current Dockerfile depends on Google's repositories to download the latest version of Chrome, since Google doesn't release a version of Chrome build for linux-arm there's currently only a amd64 container available.

With the introduction of arm mac's and the large number of apple users it would be preferable to have a native container running for development purposes. While the current docker container does run with Docker desktop and Rosetta enabled it is quite slow, often encountering our internal 30s time limit for integration tests. This makes development frustrating and slow, and requires the necessity of a separate machine to run integration tests. While it's possible to build a container specifically for mac, this could cause compatibility issues between the two runners (slightly different rendering due to browser version differences). Thus having a single container source is preferable.

**Related issues:** #10855 #9763 #7740 (could be quite a few more)

**Proposed solution:**
Instead of using Google's repositories we could use chromium directly from Debian's repositories. This is already built for both amd64 and armv8. This can also be setup such that it's only used when making the arm build. However that could cause the two builds to be of different versions.

One other solution could be a darwin/arm build since Google does release chrome binaries for that platform. But I'm not entirely sure what that would entail.

I'm mainly wondering what the drawbacks would be? Will there be rendering differences between the two chrome versions (it should be build from exactly the same source)?

**Comment by OrKoN** [comment] 2023-09-07 09:58
We don't plan to use Chromium. Instead Chrome for Testing will eventually provide arm64 binaries for Linux https://developer.chrome.com/blog/chrome-for-testing/ Note that it does already provide arm64 binaries for Mac (though cannot be used in Docker though).

**Comment by Yoeori** [comment] 2023-09-07 10:52
Ah it's great to hear that arm64 binaries are planned, is there a timeline for this? When they are released the Dockerfile should still be updated to support arm64 builds.

**Comment by OrKoN** [comment] 2023-09-07 11:00
Currently, there is a lack of infra support. E.g., GitHub Actions does not support arm64 linux builders so we cannot test those builds work. The same applies to Chromium infrastructure. There is no definitive timeline on those items.

**Comment by q0rban** [comment] 2023-09-29 17:53
> GitHub Actions does not support arm64 linux builders so we cannot test those builds work.

Is it possible to use QEMU in GHA to get an arm64 emulated build environment that would be sufficient for your needs?

**Comment by jrandolf** [comment] 2023-10-04 07:33
Duplicate of https://github.com/puppeteer/puppeteer/issues/7740

**Closed as completed by jrandolf** 2023-10-04 07:33 UTC

**Comment by q0rban** [comment] 2023-10-04 10:52
In my understanding, this issue is about the published docker image, and the GitHub actions workflow and Dockerfile that produce it. #7740 doesn’t seem to be discussing those.
