### ISSUE TITLE
Getting UnhandledPromiseRejectionWarning on page.select() call

### ISSUE THREAD

**Issue by aureliensibiril** [puppeteer/puppeteer#4604] opened 2019-06-19 14:48 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: Mac Os 10.14.5
* Node.js version: 11.6.0

I'm trying to change the value from a select input, but got this error 100% of the time :

``` UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id```

**What steps will reproduce the problem?**

```javascript
const puppeteer = require('puppeteer');
const fs = require('fs');

(async () => {
    
    // Running in non-headless mode and slowing down for debugging.
    // const browser = await puppeteer.launch({
    //     headless: false,
    //     slowMo: 250 // slow down by 250ms
    // });
    
    // to run in headless
    const browser = await puppeteer.launch();
    
    const page = await browser.newPage();

    await page.goto('https://scrapethissite.com/pages/forms/');

    //await page.waitFor(2000);
    await page.select('#per_page', '100'); // Exception is raised here.
    //await page.waitFor(2000);

     await browser.close();
    })();
```

**What is the expected result?**

Not getting this exception, I guess it's happening because changing the select value trigger a navigation on the page.

**Comment by aslushnikov** [comment] 2019-06-21 07:17
@aureliensibiril  This is a dupe of #4537 - and it is fixed in v1.18.0 that was released today.

**Closed as completed by aslushnikov** 2019-06-21 07:17 UTC
