### ISSUE TITLE
[Bug]: Downloading content only works for specific file types?

### ISSUE THREAD

**Issue by Osiris-Team** [puppeteer/puppeteer#7618] opened 2021-09-30 18:34 UTC
### Bug description

```js
const puppeteer = require('puppeteer');
const fs = require('fs');

(async () => {
try{

const browser = await puppeteer.launch({headless: true});
const page = await browser.newPage();

// Working example for .xml:
var response = await page.goto('https://file-examples-com.github.io/uploads/2017/02/file_example_XML_24kb.xml');
var buffer = await response.buffer();
fs.writeFile("example.xml", buffer, (err) => {
  if (err) throw err;
  console.log('The xml file has been saved!');
});

// Failing example for .mp4:
var response = await page.goto('https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_1920_18MG.mp4');
var buffer = await response.buffer();
fs.writeFile("example.mp4", buffer, (err) => {
  if (err) throw err;
  console.log('The mp4 file has been saved!');
});

await browser.close();

}catch(e){
console.error(e.stack);
}
})();
```
Why does the code above only work for specific file types and not for all of them?
I don't see why the second example must fail.

### Puppeteer version

v10.4.0

### Node.js version

v16.10.0.

### npm version

6.14.4

### What operating system are you seeing the problem on?

Windows

**Comment by Osiris-Team** [comment] 2021-09-30 19:49
It seems to be possible though: https://bugs.chromium.org/p/chromium/issues/detail?id=696481

**Comment by jschfflr** [comment] 2021-10-07 13:16
@Osiris-Team Thanks for taking the time to report this issue!
Marking this as a duplicate of https://github.com/puppeteer/puppeteer/issues/299

**Closed as completed by jschfflr** 2021-10-07 13:16 UTC
