### ISSUE TITLE
[Bug]: Unhandled promise rejection in case of binded function called with detached frame

### ISSUE THREAD

**Issue by mmedvedik** [puppeteer/puppeteer#7814] opened 2021-11-30 21:04 UTC
Steps to reproduce the problem:

1. On a page with an iframe bind puppeteer function using page.exposeFunction;
2. Detach iframe;
3. Call bounded function;

Actual result: Unhandled promise rejection. Output attached.

Detached frame`s lifecycle events from the debugger:
- init
- DOMContentLoaded
- load
- networkAlmostIdle
- networkIdle

Seems that CDPSession does not clean the detached frame from the 'Runtime.addBinding' chrome event listeners.
https://github.com/puppeteer/puppeteer/blob/ac162c561ee43dd69eff38e1b354a41bb42c9eba/src/common/DOMWorld.ts#L113-L115

### Puppeteer version

puppeteer-core 11.0.0

### Node.js version

v14.17.1

### npm version

6.14.13

### What operating system are you seeing the problem on?

Linux, macOS

### Relevant log output

```shell
UnhandledPromiseRejectionWarning: Error: Execution context is not available in detached frame https://www.site.com/iframe_url/index.html (are you trying to evaluate?)

    at DOMWorld.executionContext (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/DOMWorld.js:86:19)

    at DOMWorld._onBindingCalled (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/DOMWorld.js:372:36)

    at /usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/DOMWorld.js:55:66

    at /usr/src/app/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:62

    at Array.map (<anonymous>)

    at Object.emit (/usr/src/app/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:43)

    at CDPSession.emit (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:72:22)

    at CDPSession._onMessage (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:245:18)

    at Connection._onMessage (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:117:25)

    at WebSocket.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:13:32)
```

**Comment by mstr-pezhang** [comment] 2022-01-11 09:49
Encountered the same problem too.
Not sure if it's caused by https://github.com/puppeteer/puppeteer/commit/4d9dc8c0e613f22d4cdf237e8bd0b0da3c588edb

**Comment by jfirebaugh** [comment] 2022-01-19 18:05
On node.js 15+ unhandled promise rejections exit the process immediately by default, so this error ends the puppeteer script entirely.

**Comment by Adeloyd** [comment] 2022-01-31 11:19
This is a problem in chrome. In version 901912, everything works without errors, if you take 950341, then an error.

```
const browserFetcher = puppeteer.createBrowserFetcher();
const revisionInfo = await browserFetcher.download('901912');
let options = {
  executablePath: revisionInfo.executablePath    
}
const browser = await puppeteer.launch(options);
const page = await browser.newPage();
```

**Comment by chopen** [comment] 2022-02-01 22:27
Ran into this same issue this weekend.  LMK if anyone needs help testing or isolating. -ch

**Comment by triplewy** [comment] 2022-02-06 03:48
@Adeloyd Can confirm this works. Do you know the underlying root cause in Chromium that is causing this bug?

**Comment by akhfaern** [comment] 2022-02-10 19:56
i've come across the same issue and fixed with 
https://github.com/aw1875/puppeteer-hcaptcha/issues/22#issuecomment-996251792

can you patch it up ?

**Closed as completed** 2022-02-17 15:52 UTC
