### ISSUE TITLE
Page crash is not handled

### ISSUE THREAD

**Issue by schelkun** [puppeteer/puppeteer#1401] opened 2017-11-16 10:57 UTC
Look at this issue for crash example: https://github.com/GoogleChrome/puppeteer/issues/1373

You will recieve:
```
(node:4181) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Page crashed!
(node:4181) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
That means page crashes is not handled and no special events exist for page crash.

**Comment by ebidel** [comment] 2017-11-16 20:06
You can use `page.on('error', ...)` event to catch page crashes, but +1 to this. 

It would be really nice if crashes could also be handled in existing promise chains and try/catch. I see this error a lot in try-puppeteer.appspot.com and handling it is wonky with needing to add a `process.on('unhandledRejection')` handler.

**Comment by gajus** [comment] 2017-11-17 12:35
> You can use page.on('error', ...) event to catch page crashes, but +1. It would be really nice if crashes could also be handled in the existing promise chain and/or try/catch. I see this a lot in try-puppeteer.appspot.com.

Does Puppeteer project have a delegated resource at Google?

Releases are being made with open bugs. Bug reports get closed without inspecting them. ... Looks really bad.

**Comment by ebidel** [comment] 2017-11-17 14:39
@gajus what does that have to do with my suggestion? 

Can you link me to examples of issues that are closed without looking at them?

Keep in mind that chrome itself releases with bugs (puppeteer uses the latest chromiums). Sometimes we're working around those issues. Other times there are bugs introduced with puppeteer. Hence why this project is still v0.13.0.

**Comment by gajus** [comment] 2017-11-17 14:56
> Can you link me to examples of issues that are closed without looking at them?

https://github.com/GoogleChrome/puppeteer/issues/1140

This was closed clearly ignoring the issue.

https://github.com/GoogleChrome/puppeteer/issues/982

(Albeit, I am happy with the new `new Function` workaround.)

Well, thats one example.

This was reported before v0.13.0 release.

https://github.com/GoogleChrome/puppeteer/issues/132 (possibly related to the issue that you've reported https://github.com/GoogleChrome/puppeteer/issues/827).

Nevertheless, v0.13.0 was still released now causing others to downgrade.

This suggestion to convert Puppeteer to a collection of stateless utilities (which would be a lot easier to maintain and reduce code surface) was discarded without any notice.

https://github.com/GoogleChrome/puppeteer/issues/1139#issuecomment-338778275

The PRs remain open for weeks ...

Overall, the mood is uninviting to collaborate.

**Comment by ebidel** [comment] 2017-11-17 18:10
I'm sorry you feel that way.

Reading through those issues, all of them seem to have discussions. Some asked for more or clarifying information or had a commit/PR to address and close the issue (#1139). Others have workarounds posted (which address the issue). So everything was looked at.

For #1140, I see @aslushnikov was asking for a reproducible script. You gave one (thanks), but it looks specific to some unknown page nor does it include a URL for us to test against. TBH, this makes the issue look specific to your page, creates [unnecessary back and forth](https://github.com/GoogleChrome/puppeteer/issues/1140#issuecomment-341073587), and ultimately prolongs fixing said bug. Since [I'm unable to repro](https://github.com/GoogleChrome/puppeteer/issues/1140#issuecomment-345319037), having something from you that _does_ repro the issue would be really helpful.

When projects see dozens of issues every day, it's critical that bugs are easy to repro 🙏. I see that you do a lot of great work on Github, so I'm sure you'll agree with that ask :) It saves everyone (reporters + maintainers) a lot of time/headache and it's why the project has a [template for issues](https://github.com/GoogleChrome/puppeteer/blob/master/docs/issue_template.md).

Looking at the PRs...I see few that have been open for weeks. FWIW, several of the older ones are POC ideas from the team...not necessarily things we'll incorporate into the project. Others are waiting for an author to respond or Google's silly CLA bot to do it's thing 🤖. Even [really good ideas](https://github.com/GoogleChrome/puppeteer/pull/881) get closed b/c there are [better things in the works](https://bugs.chromium.org/p/chromium/issues/detail?id=781117).

Hope that helps.

**Comment by aslushnikov** [comment] 2017-11-18 09:04
> It would be really nice if crashes could also be handled in existing promise chains and try/catch. I see this error a lot in try-puppeteer.appspot.com and handling it is wonky with needing to add a process.on('unhandledRejection') handler.

@ebidel I'm not sure I follow. Why would you need a `process.on('unhandledRejection')`? The intention with `page.on('error')` was that it is always enough.

**Comment by aslushnikov** [comment] 2017-11-18 09:34
@ebidel ah ok, I think I understand what's going on here.

**Comment by zhaolixin0726** [comment] 2017-11-22 11:57
So what's the answer?  I encountered the same problem.

**Comment by aslushnikov** [comment] 2017-11-23 02:47
@zhaolixin0726 You can handle page crashes with `page.on('error')` event listener. This will mitigate the `unhandled promise rejection`. 

To address @ebidel's concerns, filed https://github.com/GoogleChrome/puppeteer/issues/1454 that describes expected behavior for page crashes.

The issue per se seems to be about handling the `error` event, so closing this.

**Closed as completed by aslushnikov** 2017-11-23 02:47 UTC

**Comment by Hadh** [comment] 2020-11-24 14:31
3 years later, is this issue solved yet? I'm having the same problem !
