### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by vasis7533** [puppeteer/puppeteer#10215] opened 2023-05-20 15:09 UTC
### Bug expectation

i expected code to be run with same speed after I add `headless: true`, 

what happened was it slow dow this part of code by 3-5 second .

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
          executablePath: '/usr/bin/chromium',
          // headless: "new",
          args: ['--font-render-hinting=none', '--no-sandbox', '--disable-setuid-sandbox', '--font-path=/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc']
        });
```

### Error string

no error, just slow down my code if I add headless: "new"

### Puppeteer version

puppeteer@19.11.1

### Node version

 v20.2.0

### Package manager

npm

### Package manager version

9.6.6

### Operating system

Linux

**Comment by jrandolf** [comment] 2023-05-21 09:46
Duplicate of https://github.com/puppeteer/puppeteer/issues/10071

**Closed as not planned by jrandolf** 2023-05-21 09:46 UTC
