### ISSUE TITLE
Response event after setRequestInterception

### ISSUE THREAD

**Issue by vovatolstousov** [puppeteer/puppeteer#3007] opened 2018-08-01 13:50 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.6.1
* Platform / OS version: Ubuntu 16.4
* URLs (if applicable):https://www.britishgas.co.uk/GetAQuote/#/new/quote-details/results
* Node.js version: 8.11.3

**What steps will reproduce the problem?**

    await page.setRequestInterception(true);

    page.on('request',  async req => {
      if(req.url().includes('https://edigitalsurvey.com/l.php')) await req.abort();
      else await req.continue();
    });

    // Start listening to request responses.
    page.on('response', response => {
      if (response.url().includes('api/secure/quotes')) {
        response.json()
          .then((res) => {
            let primaryFilename = (e7)? `${dirName}/quotes_e7.json` : `${dirName}/quotes_standart.json`;
            fs.writeFileSync(primaryFilename, JSON.stringify(res), 'utf8');
          })
          .catch((e) => {
            console.log(e);
          });
      }
    });

**What is the expected result?**

So, I want to write answer to certain API call to a JSON file, but prevent survey popup from spawning, by canceling the request for it. 

**What happens instead?**

Insted, ONLY when setRequestInterception is set to true, I don't get response event to this API call. Page, however seems to be working fine. The if statement never get triggered. The survey popup, fortunately, never appears. :\

**Comment by aslushnikov** [comment] 2018-08-01 20:02
Hey @vovatolstousov,

This looks like a dupe of #2970. Can you please try installing `puppeteer@next` and see if it works for you?

**Comment by aslushnikov** [comment] 2018-08-02 00:02
This does look like #2970, so I'll speculatively close this as a dupe. We've released v1.6.2 that should fix this bug - please, give it a shot. If it doesn't work for you, feel free to shout in this issue.

Thanks!

**Closed as completed by aslushnikov** 2018-08-02 00:02 UTC
