### ISSUE TITLE
page.click - scroll into view

### ISSUE THREAD

**Issue by lflpowell** [puppeteer/puppeteer#2750] opened 2018-06-15 15:42 UTC
* Puppeteer version: 1.5.0
* Platform / OS version: Mac 10.13.4
* URLs (if applicable): 
* Node.js version: 9.4.0

**What steps will reproduce the problem?**
Running against a page where link is obscured behind another fixed position element on small viewport. Link is able to be scrolled into view if needed.

**What is the expected result?**
Using page.click, documentation says target will be scrolled into view. This doesn't seem to be happening. At least now how I would expect _element_.scrollIntoView() to work.

**What happens instead?**
Link doesn't get clicked, instead, the element obscuring the link gets clicked instead.

This works:

```
await page.goto('http://my-url');
await page.evaluate(() => {
  document.querySelector('#theLink').scrollIntoView();
});
await Promise.all([
  page.click('#theLink'),
  page.waitForNavigation()
]);
```

However, I was hoping to avoid the need to `evaluate` the need to scroll it into view, as the documentation says this already happens. However this doesn't work:

```
await page.goto('http://my-url');
await Promise.all([
  page.click('#theLink'),
  page.waitForNavigation()
]);
```

**Comment by aslushnikov** [comment] 2018-06-27 01:00
Closing as a dupe of #2804

**Closed as completed by aslushnikov** 2018-06-27 01:00 UTC
