### ISSUE TITLE
can we have chrome layer in headless chrome ?

### ISSUE THREAD

**Issue by medhamza911** [puppeteer/puppeteer#1777] opened 2018-01-11 10:53 UTC
* Puppeteer version:0.13.0
* Platform / OS version:windows bash linux (i am savage i know :/ )
* URLs (if applicable):
* Node.js version:v9.3.0

**What steps will reproduce the problem?**
is it possible to have chrome layer when headless is true
_Please include code that reproduces the issue._

```
page.evaluate(() => {
            return new Promise(function (resolve, reject) {
                window.chrome.runtime.sendMessage("extID", {extrnalJS: "nothing need"}, resolve);
            });
```

**What is the expected result?**
chrome layer exist

**What happens instead?**
chrome is undefined

**Comment by aslushnikov** [comment] 2018-01-12 00:11
Dupe of #1026; please take a look on the discussion over there.

**Closed as completed by aslushnikov** 2018-01-12 00:11 UTC
