### ISSUE TITLE
concurrent browser context web page crawling issues

### ISSUE THREAD

**Issue by WeihanLi** [puppeteer/puppeteer#4499] opened 2019-05-31 03:55 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.9.0
* Platform / OS version: windows10
* Node.js version: 12.3.1

**What steps will reproduce the problem?**

I use one browser, and different browser context for each crawling job, when one more job executed in parallel, it seemed only one browser context could work.

**What is the expected result?**

different browser context should work independently

**What happens instead?**

when another browser context worked for a period maybe 5-15 , the other browser context would be paused(seemed like that) even when the browser context exec finished and closed, the before browser context still seemed to be paused there

**Comment by aslushnikov** [comment] 2019-06-01 17:08
@WeihanLi  the browser contexts do work in parallel. We ourselves use browser contexts extensively to parallelize tasks - and they work nicely for us.

However, the contexts fight for the same machine resources. So if your host env is under heavy load, OS might de-schedule one of the pages due to resource starvation.

I'll close this. If you have a good reproducible scenario, we can try looking further into this.

**Closed as completed by aslushnikov** 2019-06-01 17:08 UTC
