### ISSUE TITLE
Frame's init event not emitted

### ISSUE THREAD

**Issue by DiegoRBaquero** [puppeteer/puppeteer#1640] opened 2017-12-21 07:37 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Ubuntu 16.04

**What steps will reproduce the problem?**
Load a content and waitForNavigation OR waitForNavigation and immediately setContent

_Please include code that reproduces the issue._
```js
  // ... 
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  await page.setViewport({width: 1024, height: 768})
  try {
    await Promise.all([
      page.waitForNavigation({timeout: 3000, waitUntil: 'networkidle0'}),
      page.setContent(content) // content is valid html
    ])
  } catch (e) {
    // TIMEOUT
  }
```

**What is the expected result?**
`init` event is received by frame's, setting it's loaderId to something different than ''

**What happens instead?**
All events, even networkIdle (networkidle0) are fired, but as init was never called, waitForNavigation times out, as it "dies" [here](https://github.com/GoogleChrome/puppeteer/blob/master/lib/NavigatorWatcher.js#L82)

Made [this](https://github.com/GoogleChrome/puppeteer/pull/1639) naive PR, but I figured the actual issue.

**Comment by yujiosaka** [comment] 2017-12-21 12:46
I believe it's not a puppeteer's bug, because `init` of `Page.lifecycleEvent` is not fired in the first place, so there is no way puppeteer can catch it. It seems that [Chrome DevTools Protocol Viewer](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-lifecycleEvent) is not well documented about the events, but it seems that `init` is not fired for opening a blank page. It's fired when the page is actually navigated to an URL as follows:

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setViewport({width: 1024, height: 768});
  await page.goto('https://github.com/GoogleChrome/puppeteer');
  const frame = page.mainFrame();
  console.log(frame._loaderId);
  await page.close();
  await browser.close();
})();
```

The timeout is occurred for similar reasons. You are setting a content to blank page, which does not cause any navigation. That's why your code keeps waiting for the navigation which will never happens, and ends up with an exception.

**Comment by yujiosaka** [comment] 2017-12-21 12:48
@DiegoRBaquero 

I believe it's not a puppeteer's bug, because `init` of `Page.lifecycleEvent` is not fired in the first place, so there is no way puppeteer can catch it. It seems that [Chrome DevTools Protocol Viewer](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-lifecycleEvent) is not well documented about the events, but it seems that `init` is not fired for opening a blank page. It's fired when the page is actually navigated to an URL as follows:

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setViewport({width: 1024, height: 768});
  await page.goto('https://github.com/GoogleChrome/puppeteer');
  const frame = page.mainFrame();
  console.log(frame._loaderId);
  await page.close();
  await browser.close();
})();
```

The timeout is occurred for similar reasons. You are setting a content to a blank page, which does not cause any navigation at all. That's why your code keeps waiting for navigations and dies by timeout.

**Comment by DiegoRBaquero** [comment] 2017-12-21 13:02
@yujiosaka Thanks for the info! This is a use case that still has navigation and all the rest of the events, specially the ones in waitForNavigation: load, DOMContentLoaded, networkAlmostIdle and networkIdle.

@aslushnikov What would be the implications of removing [both lines](https://github.com/GoogleChrome/puppeteer/blob/master/lib/NavigatorWatcher.js#L82-L83) ?

**Comment by aslushnikov** [comment] 2018-01-04 08:11
@DiegoRBaquero it will break the `page.waitForNavigation` logic.

Overall this is a dupe of #728; see discussion there for possible workarounds.

**Closed as completed by aslushnikov** 2018-01-04 08:11 UTC
