### ISSUE TITLE
[Bug]: White window appear when running puppeteer on Windows (since v23.2.0)

### ISSUE THREAD

**Issue by fraxken** [puppeteer/puppeteer#13064] opened 2024-09-08 22:52 UTC
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";
import timers from "node:timers/promises";

const browser = await puppeteer.launch({
  executablePath: puppeteer.executablePath()
});
console.log(await browser.version());

await timers.setTimeout(10_000);

await browser.close();
```

### Background

Updating dependencies for production services used to convert HTML to PDF.

### Expectation

No white window screen

### Reality

Since puppeteer v23.2.0 when I launch a new browser a white window appear on my desktop.

![image](https://github.com/user-attachments/assets/3beca7bf-e086-4dbc-b832-a64bf73dea9e)

Reproduced with both ESM and CJS.

### Puppeteer version

23.3.0

### Node version

20.17.0

### Package manager

npm

### Package manager version

10.8.2

### Operating system

Windows

**Comment by Lightning00Blade** [comment] 2024-09-10 09:39
Duplicate of #13012, upstream bug  [https://crbug.com/362706121](https://crbug.com/362706121)

**Closed as completed by Lightning00Blade** 2024-09-10 09:39 UTC
