### ISSUE TITLE
Protocol error (Emulation.setTimezoneOverride): Timezone override is already in effect

### ISSUE THREAD

**Issue by devjerry** [puppeteer/puppeteer#6176] opened 2020-07-07 23:15 UTC
**Tell us about your environment:**

* Puppeteer version: 5.0.0
* Platform / OS version: Win 10

**Issue description:**
Calling `page.emulateTimezone()` on page that was open by JS from another page with timezone already emulated throws error.
On the other hand calling `page.emulateTimezone()` even multiple times on the same page created by Puppeteer works without a problem.

**This produces error:**
```javascript
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        headless: false
    });

    browser.on('targetcreated', async function(target) {
        if (target.type() === 'page') {
            await (await target.page()).emulateTimezone('Europe/London');
        }
    });

    const page1 = await browser.newPage();

    await page1.setContent(`
        <!DOCTYPE html>
        <html>
        <head>
            <script>
                window.open('https://github.com/');
            </script>
        </head>
        <body>
        </body>
        </html>
    `);
})();
```

```
UnhandledPromiseRejectionWarning: Error: Protocol error (Emulation.setTimezoneOverride): Timezone override is already in effect
    at Promise (C:\test\node_modules\puppeteer\lib\cjs\common\Connection.js:181:63)
    at new Promise (<anonymous>)
    at CDPSession.send (C:\test\node_modules\puppeteer\lib\cjs\common\Connection.js:180:16)
    at Page.emulateTimezone (C:\test\node_modules\puppeteer\lib\cjs\common\Page.js:842:32)
    at Page.<anonymous> (C:\test\node_modules\puppeteer\lib\cjs\common\helper.js:110:27)
    at C:\test\index.js:10:41
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**This doesn't produce error:**

```javascript
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        headless: false
    });

    browser.on('targetcreated', async function(target) {
        if (target.type() === 'page') {
            await (await target.page()).emulateTimezone('Europe/London');
        }
    });

    const page1 = await browser.newPage();
    const page2 = await browser.newPage();
    const page3 = await browser.newPage();

    await page3.emulateTimezone('Europe/London');
    await page3.emulateTimezone('Europe/London');
})();
```

**What is the expected result?**
It either shouldn't produce error or this behavior should be documented in Puppeteer API.

**Comment by crobinson42** [comment] 2020-09-04 12:33
This has become quite common since the `emulateTimezone` feature was added by  @mathiasbynens about a year ago.

@devjerry if it's not too much to ask, could you provide a failing unit test (https://github.com/puppeteer/puppeteer/blame/ffec2475d0cae61ddb4d6d32956408afe836552e/test/emulation.spec.ts#L260) with your example above or does it only happen to you in the native env?

This issue can happen when using Puppeteer in a server or process that is re-using the same browser instance.  Let me know if I can help debug this issue at all to get a resolution here.

**Comment by crobinson42** [comment] 2020-09-04 12:53
@devjerry here's an interim solution to work around the error, you keep a browser instance per timezone to avoid the bug:

```
/*
    Issue: https://github.com/puppeteer/puppeteer/issues/6176
    Because of this we keep a browser instance per TZ to avoid this
    error.
    
    @note: every Node.js process will start it's own browser instance
 */
const browserInstancesByTz = {}

async function getBrowserInstance(tz = 'America/Los_Angeles') {
  let browserInstance = browserInstancesByTz[tz]

  if (!browserInstance)
    browserInstance = await puppeteer.launch()

  return browserInstance
}
```

**Comment by deaktomi** [comment] 2021-08-05 13:26
@crobinson42 it didn't help me out. I would like to set the same timezone for all chrome pages (tabs), so the `browserInstancesByTz[tz]` call will return the same browser and the issue will happen.

I don't want to handle one instance of browser per tab, as instantiating a browser takes a long time (about 6 seconds), and also I don't see the point of it.

**In my case the issue is:**

I sign up for the `targetCreated` event. (I'm using PuppeteerSharp)
```
cdpBrowser.TargetCreated += async (object sender, TargetChangedArgs e) =>
{
	if (e?.Target?.Type == TargetType.Page)
	{
		var locationInfo = GetLocationInfo(profileId);
		var page = await e.Target.PageAsync();
		if (page != null)
		{
			await page.EmulateTimezoneAsync("Europe/London);
		}
	}
};
```
It works okay when I open a new tab, the timezone is overridden, but as soon as I start to open pages "rapidly" the `Protocol error (Emulation.setTimezoneOverride): Timezone override is already in effect` exception occurs.

I have tried and the same thing is not happening with some other command, for example, Geolocation overriding.

The only solution I can think of now is to implement a queue, where override events with `page` parameters will be posted by my code, and a listener is taking the event from the queue and actually make the CDP communication. **This will ensure that no calls at the same time will happen**. But this feels like a little overkill here. Do you have any fix for this?

**Closed as completed** 2022-07-24 08:40 UTC
Labels: unconfirmed
