### ISSUE TITLE
[Bug]: Error: net::ERR_FAILED

### ISSUE THREAD

**Issue by thisiseddy-ab** [puppeteer/puppeteer#9655] opened 2023-02-12 17:38 UTC
### Bug expectation

Im Trying for the first time the [puppeteer-proxy](https://github.com/gajus/puppeteer-proxy) lib,and Im getting this error.
I don know is an error of [puppeteer-proxy](https://github.com/gajus/puppeteer-proxy) or of the function await page.setRequestInterception(true) because [this](https://stackoverflow.com/questions/67081474/puppeteer-request-interceptor-causes-neterr-failed-errors-with-http-30x-redire) guy has the same error as me

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer-extra')
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
const {proxyRequest} = require('puppeteer-proxy')


puppeteer.use(StealthPlugin())
var browser = null

const func = (async () => {
    browser = await puppeteer.launch({ 
        headless: false,
        executablePath: "chrome-win/chrome.exe"
    })

    const page = await browser.newPage()

    await page.setRequestInterception(true);

    page.on('request', async (request) => {
        await proxyRequest({
        page,
        proxyUrl: "https://username:password@174.25.210.207:6286",
        request,
        });
    });

    await page.goto("https://www.google.com/")

})();
```

### Error string

Error: net::ERR_FAILED 

### Puppeteer version

19.6.3

### Node version

19.6.0

### Package manager

npm

### Package manager version

9.4.0

### Operating system

Windows

**Comment by OrKoN** [comment] 2023-02-13 07:19
Please investigate if the issue is perhaps with the puppeteer-proxy. Also, in the next release we will have a fix related to that https://github.com/puppeteer/puppeteer/issues/9523 If the issue is indeed with Puppeteer, please provide a minimal example using only Puppeteer.

**Comment by OrKoN** [comment] 2023-02-16 10:21
Please provide the details request above and I will re-open the issue. Closing for now.

**Closed as not planned by OrKoN** 2023-02-16 10:21 UTC
Labels: needs-feedback, not-reproducible

**Comment by codemonies** [comment] 2024-11-25 04:42
@thisiseddy-ab Had a similar issue. Try switching the request to https://ipv4.google.com/ and see if it works. If so, disable IPv6 on your server. The issue is likely that your proxy doesn't support IPv6 resolution. Took me a lot of headache to figure this one out.
