### ISSUE TITLE
[Bug]: puppeteer v20 doesn't support WebGL

### ISSUE THREAD

**Issue by Kikobeats** [puppeteer/puppeteer#10175] opened 2023-05-14 22:00 UTC
### Bug expectation

I just noted WebGL looks missing since puppeteer v20.

Also, If I point puppeteer v20, to screenshot https://get.webgl.org/, I get this:

![](https://github.com/puppeteer/puppeteer/assets/2096101/1b54f230-7e9f-4ecb-aeaf-c5d73cb3a34e)

even trying to pass `--enable-webgl` or `--swiftshader-webgl` doesn't seem to work.

is this expected? it is a bit weird, this new binary is less capable than the previous version.

is planned to be supported? what's the alternative?

### Minimal, reproducible example

```TypeScript
const webgl2 = () =>
  page.evaluate(() => {
    const canvas = document.createElement('canvas')
    const ctx =
      canvas.getContext('webgl2') || canvas.getContext('experimental-webgl2')
    const debugInfo = ctx.getExtension('WEBGL_debug_renderer_info')
    return {
      vendor: ctx.getParameter(debugInfo.UNMASKED_VENDOR_WEBGL),
      renderer: ctx.getParameter(debugInfo.UNMASKED_RENDERER_WEBGL)
    }
  })

/* puppeteer@19 */
console.log(await webgl2())
// {
//   vendor: 'Google Inc. (Google)',
//   renderer: 'ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)'
// }

/* puppeteer@20 */
console.log(await webgl2())
// TypeError (Error) {
//   message: 'Cannot read properties of null (reading \'getExtension\')',
// }
```

### Error string

Cannot read properties of null (reading \'getExtension\')

### Puppeteer version

20

### Node version

18.16.0

### Package manager

pnpm

### Package manager version

8.4.0

### Operating system

macOS

**Comment by OrKoN** [comment] 2023-05-15 06:22
Did you try the `--enable-gpu` flag?

**Comment by OrKoN** [comment] 2023-05-15 06:22
See https://peter.sh/experiments/chromium-command-line-switches/#enable-gpu

**Comment by OrKoN** [comment] 2023-05-15 06:27
It seems to work for me without extra flags (so it sounds like it could be a duplicate of https://github.com/puppeteer/puppeteer/issues/10127 if you use custom flags). In general, we have no control over such changes, could you please file an issue at crbug.com if you still experience an issue?
![webgl](https://github.com/puppeteer/puppeteer/assets/399150/2f910be2-9510-44b1-99d6-211c216c25e3)

**Closed as not planned by OrKoN** 2023-05-15 06:27 UTC

**Comment by Kikobeats** [comment] 2023-05-15 21:18
worked after removed `--use-gl=swiftshader` on my code, thanks a lot 🙂
