### ISSUE TITLE
How to store resources only

### ISSUE THREAD

**Issue by ahmedrtx-2** [puppeteer/puppeteer#12080] opened 2024-03-13 12:31 UTC
### Minimal, reproducible example

I want store like:
- css
- js
- images
- media
only and i dont want store cookies and localStorage

### Attention!
I use `page.createBrowserContext()`

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

i dont want store cookies and localStorage on userDataDir puppeteer

### Reality

store cookies and localStorage

### Puppeteer version

21.11.0

### Node version

20.9.0

### Package manager

npm

### Package manager version

10.1.0

### Operating system

Windows

**Comment by Lightning00Blade** [comment] 2024-03-14 09:56
@io-store I sorry to say but I don't understand what the issue is.
Please explain what you are trying to do, what has not worked, and why you are trying to do said things.
Also keep in mind such question are more suited for places like [StackOverflow](https://stackoverflow.com/questions/tagged/puppeteer).

**Comment by io-store** [comment] 2024-03-14 10:04
> @io-store I sorry to say but I don't understand what the issue is. Please explain what you are trying to do, what has not worked, and why you are trying to do said things. Also keep in mind such question are more suited for places like [StackOverflow](https://stackoverflow.com/questions/tagged/puppeteer).

I apologize that I posted the question here, but StackOverflow did not give me a chance to ask and tells me that I have to wait 4 days to ask, and my question was only that I want to download files only once (such as css or js), and if I go to the same page, it does not download the files again. but it downloads it from the path in which I stored it. Do you understand what I mean?

**Comment by OrKoN** [comment] 2024-03-19 18:36
Closing as not planned as it does not sound like a bug report. Consider asking on StackOverflow with more details.

**Closed as not planned by OrKoN** 2024-03-19 18:36 UTC
Labels: needs-feedback, not-reproducible
