### ISSUE TITLE
elementHandle.uploadFile() emit 'change' event with 0-size blob object

### ISSUE THREAD

**Issue by plantain-00** [puppeteer/puppeteer#1042] opened 2017-10-16 11:26 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:0.12.0
* Platform / OS version:mac OS 10.12.6
* URLs (if applicable):demo: https://plantain-00.github.io/file-uploader-component/demo/vue/index.html

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. code

```js
import * as puppeteer from "puppeteer";

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.emulate({ viewport: { width: 1440, height: 900 }, userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" });
    await page.goto(`https://plantain-00.github.io/file-uploader-component/demo/vue/index.html`);

    const fileUploaders = await page.$$("input[type=file]");

    page.on("console", a => {
        console.log(a.args[0]._remoteObject.preview);
    });

    await fileUploaders[0].uploadFile(`./image0.png`);
    await page.waitFor(2000);

    browser.close();
})();
```
```bash
{ type: 'object',
  subtype: 'blob',
  description: 'File(0)',
  overflow: true,
  properties:
   [ { name: 'name', type: 'string', value: 'image0.png' },
     { name: 'lastModified', type: 'number', value: '1508153825902' },
     { name: 'lastModifiedDate',
       type: 'object',
       value: 'Mon Oct 16 2017 19:37:05 GMT+0800 (Central Standard Time)',
       subtype: 'date' },
     { name: 'webkitRelativePath', type: 'string', value: '' },
     { name: 'size', type: 'number', value: '0' } ] } // <- see, the size is 0
```
2.minimal case
```
<input type="file" @change="test($event)">
```
event handler
```js
test(e: Event) {
    const files = (e.currentTarget as HTMLInputElement).files;
    if (files) {
        console.log(files[0].size);
    }
}
```
start a static file server, listen port 8000
```js
import * as puppeteer from "puppeteer";

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.emulate({ viewport: { width: 1440, height: 900 }, userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" });
    await page.goto(`http://localhost:8000`);

    const fileUploaders = await page.$$("input[type=file]");

    page.on("console", a => {
        console.log(a);
    });

    await fileUploaders[0].uploadFile(`./image0.png`);
    await page.waitFor(2000);

    browser.close();
})();
```

**What is the expected result?**

print the size of file: 134435

**What happens instead?**

```bash
ConsoleMessage {
  type: 'log',
  text: '0',
  args:
   [ JSHandle {
       _context: [Object],
       _client: [Object],
       _remoteObject: [Object],
       _disposed: false } ] }
```

**Comment by aslushnikov** [comment] 2018-01-12 11:03
Cannot reproduce on puppeteer v1.0.0 with the following script:

```js
const puppeteer = require('puppeteer');


(async () => {
    const browser = await puppeteer.launch({
      headless: false
    });
    const page = await browser.newPage();
    await page.setContent(`
      <input type='file'></input>
      <script>
        document.body.querySelector('input').addEventListener('change', e => {
          debugger;
          const files = e.currentTarget.files;
          if (files) {
            console.log(files[0].size);
          }
        });
      </script>
    `);
    await page.emulate({ viewport: { width: 1440, height: 900 }, userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" });

    const fileUploaders = await page.$$("input[type=file]");

    page.on("console", a => {
        console.log(a);
    });

    await fileUploaders[0].uploadFile(`./index.js`);
    await page.waitFor(2000);

    browser.close();
})();

```

Speculatively closing this; please don't hesitate to write back / refile if the issue still exists for you.

**Closed as completed by aslushnikov** 2018-01-12 11:03 UTC
