### ISSUE TITLE
[Bug]: page.screenshot (silently) times out when trying to take a screenshot of an alert

### ISSUE THREAD

**Issue by machineghost** [puppeteer/puppeteer#9801] opened 2023-03-07 18:36 UTC
### Bug expectation

I expected that screenshot would never time out (it doesn't even have an option to set the timeout time, as most other Puppeteer functions do).

But, if it were to timeout, I'd expect it to do so in a reasonable amount of time, with an error message explaining why it timed out.

And *really* I'd expect screenshot to just take a screenshot of the alert ... or take a "screenshot" of a black screen and the text "alerts can't be screenshoted" ... but if that's not possible, then failing in a fixed amount of time with an error message would be nice.

And if nothing else, please at least add a line to https://pptr.dev/api/puppeteer.page.screenshot documenting this.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {

    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto(SOME_PAGE);
    // This button should trigger a window.alert
    // Also note that "click" *does* have a timeout option
    // (unlike screenshot)
    await page.click('button', { timeout: 2000 });
    await page.screenshot({ path: 'screenshot.png' })
    // wait for your test runner to time out

})();
```

### Error string

None: no error is ever thrown (that's a big part of the bug)

### Puppeteer version

19.7.2

### Node version

v19.7.0

### Package manager

npm

### Package manager version

9.5.0

### Operating system

Linux

**Comment by OrKoN** [comment] 2023-03-08 05:43
This is a general issue with CDP unfortunately, if the renderer is paused and automation tries to get information from it, the browser never resolves. Timeouts unfortunately has not been consistently part of the Puppeteer API. In the best case, this should be fixed on the both sides, the browser and Puppeteer.

**Comment by OrKoN** [comment] 2023-03-08 05:45
Does it work if you intercept the dialog? E.g., 

```
page.on('dialog', async dialog => {
    console.log(dialog.message());
    await dialog.dismiss();
});
```

**Comment by SATZPrincess** [comment] 2023-03-08 08:30
![GFG](https://user-images.githubusercontent.com/42032630/223662007-66f05a0b-052f-4dce-9a68-fd2a7f8087ab.png)

How to break the cloudflare in nodejs and multiple page loading

**Comment by machineghost** [comment] 2023-03-08 17:36
> Timeouts unfortunately has not been consistently part of the Puppeteer API. 

Don't all of the waitFor* methods take a `timeout` option?  Since there's no `waitForScreenshotToBePossible` method, wouldn't it make sense to add one ... or better yet, just give `screenshot` a `timeout` option?

This seems easy to add code-wise; here's my ghetto version:

```
const screenshotWithTimeout = async (page, options) => {
  let wasSuccessful = false;
  setTimeout(() => {
    if (!wasSuccessful) throw new Error('screenshot timed out');
  }, options.timeout);
  delete options.timeout;
  const shot = await page.screenshot(options);
  wasSuccessful = true;
  return shot;
};
```
I'd be happy to submit a PR (of a less ghetto version) if desired.

**Comment by ggorlen** [comment] 2023-03-08 17:40
I don't think there's anything special about the screenshot method here, so the question/feature request seems to boil down to "why don't all Puppeteer methods have a timeout, including non-`waitForX` methods?" and "can more/all Puppeteer methods offer a timeout?"

**Comment by OrKoN** [comment] 2023-03-09 05:34
It's definitely possible to add timeout parameters too all API but I think it's more ergonomic if we make the CDP client respect the default timeout (https://pptr.dev/api/puppeteer.page.setdefaulttimeout/) for CDP calls.  That should resolve issues when the timing out is caused by the browser and not an internal bug in Puppeteer.

**Closed as completed** 2023-03-21 11:53 UTC
Labels: upstream, confirmed, documentation

**Comment by machineghost** [comment] 2023-03-21 14:56
Great news, thanks OrKoN!
