### ISSUE TITLE
Puppeteer no longer waits page load of the initial `about:blank` page when opening a new browsing context

### ISSUE THREAD

**Issue by whimboo** [puppeteer/puppeteer#11915] opened 2024-02-13 20:49 UTC
Since the landing of #11836 the initial page load for `about:blank` is no longer correctly awaited for.

This can be seen with basically every test that opens a new tab. In my case I used `navigation Page.goto should fail when navigating and show the url at the error message`.

As the log shows Firefox correctly emits all the navigation events for the initial page load of `about:blank` but Puppeteer no longer awaits for the navigation to be complete and immediately fails.

CC @OrKoN @jrandolf

**Comment by tech-doctor** [comment] 2024-02-13 23:57
How can this be resolved, please?

**Comment by OrKoN** [comment] 2024-02-14 06:58
Duplicate of https://github.com/puppeteer/puppeteer/issues/11913

**Closed as not planned by OrKoN** 2024-02-14 06:58 UTC

**Comment by OrKoN** [comment] 2024-02-14 07:09
For this interaction the following is the log:

```
{"id":8,"method":"browsingContext.navigate","params":{"context":"14fd9a71-3b26-47f2-824c-35ea7656a864","url":"https://localhost:62952/redirect/1.html"}}
{"type":"event","method":"browsingContext.navigationStarted","params":{"context":"14fd9a71-3b26-47f2-824c-35ea7656a864","navigation":"53a7ad77-4ec1-4b97-bb7a-fb3e3fd1db0c","timestamp":1707894445069,"url":"https://localhost:62952/redirect/1.html"}}
{"type":"success","id":8,"result":{"navigation":"53a7ad77-4ec1-4b97-bb7a-fb3e3fd1db0c","url":"https://localhost:62952/redirect/1.html"}}
{"type":"event","method":"network.fetchError","params":{"context":"14fd9a71-3b26-47f2-824c-35ea7656a864","isBlocked":false,"navigation":"53a7ad77-4ec1-4b97-bb7a-fb3e3fd1db0c","redirectCount":0,"request":{"bodySize":null,"cookies":[],"headers":[{"name":"Host","value":{"type":"string","value":"localhost:62952"}},{"name":"User-Agent","value":{"type":"string","value":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0"}},{"name":"Accept","value":{"type":"string","value":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"}},{"name":"Accept-Language","value":{"type":"string","value":"en-US,en;q=0.5"}},{"name":"Accept-Encoding","value":{"type":"string","value":"gzip, deflate, br"}},{"name":"Connection","value":{"type":"string","value":"keep-alive"}},{"name":"Upgrade-Insecure-Requests","value":{"type":"string","value":"1"}},{"name":"Sec-Fetch-Dest","value":{"type":"string","value":"document"}},{"name":"Sec-Fetch-Mode","value":{"type":"string","value":"navigate"}},{"name":"Sec-Fetch-Site","value":{"type":"string","value":"none"}},{"name":"Sec-Fetch-User","value":{"type":"string","value":"?1"}}],"headersSize":466,"method":"GET","request":"11","timings":{"timeOrigin":0,"requestTime":1707894445068972,"redirectStart":0,"redirectEnd":0,"fetchStart":1707894445071100,"dnsStart":1707894445071100,"dnsEnd":1707894445071107,"connectStart":1707894445071177,"connectEnd":1707894445075453,"tlsStart":1707894445071687,"tlsEnd":1707894445075453,"requestStart":0,"responseStart":0,"responseEnd":0},"url":"https://localhost:62952/redirect/1.html"},"timestamp":1707894445079,"errorText":"NS_ERROR_GENERATE_FAILURE(NS_ERROR_MODULE_SECURITY, MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT)"}}
{"type":"event","method":"browsingContext.domContentLoaded","params":{"context":"14fd9a71-3b26-47f2-824c-35ea7656a864","timestamp":1707894445111,"url":"about:certerror?e=nssBadCert&u=https%3A//localhost%3A62952/redirect/1.html&c=UTF-8&d=%20","navigation":"53a7ad77-4ec1-4b97-bb7a-fb3e3fd1db0c"}}
```

I believe the navigation failed event should be expected in this case, but it is missing.
