### ISSUE TITLE
[Bug]: esbuild-bundled script crashes with ENOENT (related to `vm2`?)

### ISSUE THREAD

**Issue by karlhorky** [puppeteer/puppeteer#10352] opened 2023-06-08 11:58 UTC
### Bug expectation

I expected to be able to bundle my Puppeteer script with `esbuild`

My `esbuild`-bundled Puppeteer script failed (see full error output below) because of the transitive dependency on `vm2` (via `puppeteer-core` -> `proxy-agent` -> `pac-proxy-agent` -> `pac-resolver` -> `degenerator` -> `vm2`)

```bash
$ node abc.mjs
node:fs:601
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/home/runner/work/project/project/bridge.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at ../../node_modules/@puppeteer/browsers/node_modules/vm2/lib/vm.js (file:///home/runner/work/project/project/abc.mjs:52297:66)
    at __require2 (file:///home/runner/work/project/project/abc.mjs:20:50)
    at ../../node_modules/@puppeteer/browsers/node_modules/vm2/lib/main.js (file:///home/runner/work/project/project/abc.mjs:54169:9)
    at __require2 (file:///home/runner/work/project/project/abc.mjs:20:50)
    at ../../node_modules/@puppeteer/browsers/node_modules/vm2/index.js (file:///home/runner/work/project/project/abc.mjs:54197:22)
    at __require2 (file:///home/runner/work/project/project/abc.mjs:20:50)
    at ../../node_modules/@puppeteer/browsers/node_modules/degenerator/dist/index.js (file:///home/runner/work/project/project/abc.mjs:54211:17)
    at __require2 (file:///home/runner/work/project/project/abc.mjs:20:50) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/work/project/project/bridge.js'
}

Node.js v18.16.0
```

It appears to be related to this current problem with bundling `vm2`:

- https://github.com/patriksimek/vm2/issues/528

This has also been reported in the repos for `proxy-agent`:

- https://github.com/TooTallNate/node-proxy-agent/issues/68
- https://github.com/TooTallNate/proxy-agents/issues/197

Seems like the first version that this happens with is [`puppeteer-core@20.4.0`](https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-v20.4.0), which upgraded `@puppeteer/browsers` from `1.3.0` to [`1.4.0`](https://github.com/puppeteer/puppeteer/releases/tag/browsers-v1.4.0), which added `proxy-agent`.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

Bundle any Puppeteer script such as the simple script below via `esbuild` like this:

```bash
$ esbuild index.ts --bundle --outfile=abc.mjs --platform=node --target=node18 --format=esm --banner:js=\"import { createRequire as createRequire99 } from 'module'; import { dirname as dirname99 } from 'node:path'; import { fileURLToPath as fileURLToPath99 } from 'node:url'; const __filename = fileURLToPath99(import.meta.url); const __dirname = dirname99(__filename); const require = createRequire99(import.meta.url);\"
```

`index.ts`

```TypeScript
import puppeteer from 'puppeteer';

function wait(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export async function puppeteerWorkflow(urlToTest: string) {
  const browser = await puppeteer.launch({
    ...(process.platform === 'linux'
      ? {
          executablePath: '/usr/bin/google-chrome-stable',
        }
      : {
          // If we're not on Linux, then maybe we're in development,
          // where we don't want a headless browser (we want to see what
          // is going on)
          headless: false,
        }),
  });
  const page = await browser.newPage();

  await page.goto(urlToTest);
  await wait(5000);
  await page.close();
  await browser.close();
}

puppeteerWorkflow('https://example.com');
```

### Error string

ENOENT: no such file or directory, open '/home/runner/work/project/project/bridge.js'

### Puppeteer version

20.5.0

### Node version

18.16.0

### Package manager

pnpm

### Package manager version

8.6.1

### Operating system

macOS

**Comment by cnlewis3** [comment] 2023-06-08 21:58
Having this same issue when trying to deploy to our AWS Lambda. Worked fine with previous versions, but getting a `ENOENT: no such file or directory, open '/var/task/bridge.js` which we have also narrowed down to vm2, which is only in the dependency tree through puppeteer-core for us.

**Comment by karlhorky** [comment] 2023-06-09 09:14
To be clear, you're seeing the following error? This error seems like a related issue which is also from the `vm2` package (I think I saw similar errors in some issues, IIRC):

```bash
$ node abc.mjs
file:///Users/k/p/puppeteer-esbuild-vm2/abc.mjs:13
  throw new Error('Dynamic require of "' + x + '" is not supported');
        ^

Error: Dynamic require of "stream" is not supported
    at file:///Users/k/p/puppeteer-esbuild-vm2/abc.mjs:13:9
    at node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/stream.js (file:///Users/k/p/puppeteer-esbuild-vm2/abc.mjs:11585:22)
    at __require2 (file:///Users/k/p/puppeteer-esbuild-vm2/abc.mjs:19:50)
    at node_modules/.pnpm/ws@8.13.0/node_modules/ws/wrapper.mjs (file:///Users/k/p/puppeteer-esbuild-vm2/abc.mjs:15071:29)
    at __init (file:///Users/k/p/puppeteer-esbuild-vm2/abc.mjs:16:56)
    at node_modules/.pnpm/puppeteer-core@20.4.0_typescript@5.1.3/node_modules/puppeteer-core/lib/esm/puppeteer/common/NodeWebSocketTransport.js (file:///Users/k/p/puppeteer-esbuild-vm2/abc.mjs:15096:5)
    at __init (file:///Users/k/p/puppeteer-esbuild-vm2/abc.mjs:16:56)
    at file:///Users/k/p/puppeteer-esbuild-vm2/abc.mjs:79315:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

I'm working on making a reproduction repo that shows the error.

**Comment by karlhorky** [comment] 2023-06-09 09:25
Sorry, this error was actually related to globals not available in `esbuild` by default, I forgot to copy in the banner that is required.

Here's a new reproduction (run `pnpm build` and `node abc.mjs`) - I've also updated the description above:

**Comment by OrKoN** [comment] 2023-06-12 07:50
As you pointed out the problem is in the `vm2` module as it requires `__dirname`. For example, in Webpack it means `__dirname: true` needs to be set. I am not sure if the corresponding feature is available in esbuild but you can probably safely exclude the module from the bundler as it is only required by the installation.

**Comment by karlhorky** [comment] 2023-06-12 08:46
`__dirname` is not the issue here, that is already fixed using the `--banner` option:

https://github.com/karlhorky/puppeteer-esbuild-vm2-reproduction/blob/99d9478af4896c735eba19e1faad3fbba397927c/package.json#L6

**Comment by karlhorky** [comment] 2023-06-12 08:49
The issue is that `vm2` expects that there are extra files which it can `fs.readFileSync` at runtime:

```
Error: ENOENT: no such file or directory, open '/home/runner/work/project/project/bridge.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
```

**Comment by OrKoN** [comment] 2023-06-12 08:49
@karlhorky I believe it is the issue https://github.com/patriksimek/vm2/blob/1663f231ec02db473ed5b743e3b91b8a2ffc7982/lib/vm.js#L145 the __dirname in the esbuild-produced bundle appears to be incorrect

**Comment by OrKoN** [comment] 2023-06-12 08:51
> The issue is that vm2 expects that there are extra files which it can fs.readFileSync at runtime:

yeah it expects the node_modules to be around and the __dirname to point to the vm2's lib folder.

**Comment by karlhorky** [comment] 2023-06-12 08:52
The way that we're bundling + deploying, we do not have a `node_modules` folder anymore which contains `bridge.js` (it's a similar approach to a [Single Executable Application](https://nodejs.org/api/single-executable-applications.html))

So anyone taking a similar approach with their bundling will also have this issue

**Comment by karlhorky** [comment] 2023-06-12 08:55
## Workaround

A possible (ugly) workaround would be to require all of your users who want to bundle to copy the necessary files out from Puppeteer's transitive dependency `vm2`, similar to [the approach described here](https://github.com/patriksimek/vm2/issues/528#issuecomment-1566572179):

> ```
> 1. add post build in NPM script
> "build": "webpack --config ./webpack.prod.config.js && node prepare-package.js postBuild",
> 
> 2. copy files from node_modules to output directory after build in prepare-package.js
> const postBuild = async () => {
>   await cpvm2("bridge.js");
>   await cpvm2("events.js");
>   await cpvm2("setup-sandbox.js");
>   await cpvm2("setup-node-sandbox.js");
> };
> 
> 3. add them in package.json files property to bundle them
> ```

**Comment by karlhorky** [comment] 2023-06-12 08:55
But maybe Puppeteer could do something about this so that bundling is zero-config 🤞

**Comment by OrKoN** [comment] 2023-06-12 08:55
@karlhorky you can probably work around it by specifying `--external:vm2` as you are unlikely to need those files.

**Comment by karlhorky** [comment] 2023-06-12 09:11
## Workaround

Confirmed, using [the esbuild `--external` flag](https://esbuild.github.io/api/#external) with `--external:vm2` also works for us.

> You can mark a file or a package as external to exclude it from your build. Instead of being bundled, the import will be preserved (using `require` for the `iife` and `cjs` formats and using `import` for the `esm` format) and will be evaluated at run time instead.

I guess this may not work for everyone, but represents a simpler workaround for bundling Puppeteer with `esbuild`

**Comment by tranlehaiquan** [comment] 2023-07-03 04:55
I add external and got this error, I'm using puppeteer-core 20.7.4

<img width="669" alt="image" src="https://github.com/puppeteer/puppeteer/assets/17347993/19373077-46a0-4ed5-ab25-fe7a01953d82">

**Comment by gabrielo91** [comment] 2023-07-04 04:35
Having the exact same issue, we are using node `v16.17.0` and puppeteer `20.7.4`, we run and API which calls the function that runs  ` const browser = await puppeteer.launch();`, however we get the exact same error: `Error: ENOENT: foo/dist/apps/api/bridge.js`. We run the project using `nx`, just like this:

npx nx run api:serve

**Comment by gabrielo91** [comment] 2023-07-05 21:20
How we solve was changing `build` section in `project.json`, just removed the `"externalDependencies": "none"` option

**Comment by PluviaCon** [comment] 2023-07-12 10:16
> ## Workaround 2
> Confirmed, using [the esbuild `--external` flag](https://esbuild.github.io/api/#external) with `--external:vm2` also works for us:
> 
> ```json
> "build": "esbuild index.ts --bundle --external:vm2 --outfile=abc.mjs --platform=node --target=node18 --format=esm --banner:js=\"import { createRequire as createRequire99 } from 'module'; import { dirname as dirname99 } from 'node:path'; import { fileURLToPath as fileURLToPath99 } from 'node:url'; const __filename = fileURLToPath99(import.meta.url); const __dirname = dirname99(__filename); const require = createRequire99(import.meta.url);\""
> ```
> 
> Description of the `--external` flag:
> 
> > You can mark a file or a package as external to exclude it from your build. Instead of being bundled, the import will be preserved (using `require` for the `iife` and `cjs` formats and using `import` for the `esm` format) and will be evaluated at run time instead.
> 
> I guess this may not work for everyone, but represents a simpler workaround for the `ENOENT: no such file or directory ... bridge.js` errors with bundling Puppeteer with `esbuild`

I've also encountered the same issue and have tried both methods. It seems that this problem occurs in versions above 20.0. Temporarily switching to version 19.10.0 seems to work for now.

**Comment by edw1882** [comment] 2023-07-12 10:23
> ## Workaround 1
> A possible (ugly) workaround would be to require all of your users who want to bundle to copy the necessary files out from Puppeteer's transitive dependency `vm2`, similar to [the approach described here](https://github.com/patriksimek/vm2/issues/528#issuecomment-1566572179):
> 
> > ```
> > 1. add post build in NPM script
> > "build": "webpack --config ./webpack.prod.config.js && node prepare-package.js postBuild",
> > 
> > 2. copy files from node_modules to output directory after build in prepare-package.js
> > const postBuild = async () => {
> >   await cpvm2("bridge.js");
> >   await cpvm2("events.js");
> >   await cpvm2("setup-sandbox.js");
> >   await cpvm2("setup-node-sandbox.js");
> > };
> > 
> > 3. add them in package.json files property to bundle them
> > ```

A more straightforward approach if you use CopyPlugin in your webpack is

`new CopyPlugin({
		patterns: [
			{ from: '../node_modules/vm2/lib/bridge.js', to: 'server' },
			{ from: '../node_modules/vm2/lib/events.js', to: 'server' },
			{
				from: '../node_modules/vm2/lib/setup-node-sandbox.js',
				to: 'server',
			},
			{ from: '../node_modules/vm2/lib/setup-sandbox.js', to: 'server' },
		],
	}),`

**Comment by OrKoN** [comment] 2023-07-13 07:15
fixed via https://github.com/puppeteer/puppeteer/pull/10548

**Closed as completed by OrKoN** 2023-07-13 07:15 UTC
Labels: confirmed

**Comment by karlhorky** [comment] 2023-07-13 10:15
Nice, thanks for circling back around here @OrKoN! 🙌  (and for making the PR)

I can confirm that [Workaround 2](https://github.com/puppeteer/puppeteer/issues/10352#issuecomment-1586923545) (the `--external:vm2` flag) is no longer needed with [`puppeteer-core@20.8.2`](https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v20.8.2) and [`@puppeteer/browsers@1.4.5`](https://github.com/puppeteer/puppeteer/releases/tag/browsers-v1.4.5), I reverted and the build is working.

**Comment by gabrielo91** [comment] 2023-07-14 19:06
thanks so much!
