### ISSUE TITLE
Broken Click after upgrading to 0.12.0

### ISSUE THREAD

**Issue by divyamvn** [puppeteer/puppeteer#1294] opened 2017-11-06 21:02 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:0.12.0
* Platform / OS version: Mac OS Sierra
* URLs (if applicable): Testing on LocalHost

**What steps will reproduce the problem?**
My existing working test started failing after upgrading to 0.12.0.
I was looking into similar issues with click. However, this seems different to me and this is the very first Step in my test. Is this because of the 'href' property in my css selector?
First step after launching browser, is to click on a main menu item and then on sub menu item, code for which is provided below.
This was very well working before upgrade.
This is NOT the ONLY place, where Click suddenly started failing. I am getting the "Error: Protocol error (DOM.getBoxModel): Could not compute box model. undefined" for various other buttons.

_Please include code that reproduces the issue._

await page.click("div.menus ul.main a[href='#abc']");
await page.waitForSelector( "div.menus ul.sub a[href='#abc/childOfabc']", { visible: true } );
//I added the below focus just to verify its working and my selector is being recognized    
await page.focus("div.menus ul.sub a[href='#abc/childOfabc']");
await page.click("div.menus ul.sub a[href='#abc/childOfabc']");

**What is the expected result?**
 Expected is that Click works normally.

**What happens instead?**
Nothing happens. After default time out the test fails. Below is the error message.
(node:52818) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: waiting failed: timeout 30000ms exceeded
(node:52818) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JoelEinbinder** [comment] 2017-11-07 08:25
The main problem here should be fixed by #1299, which properly handles retina display with DOM.getBoxModel. But I am very curious about the error `Error: Protocol error (DOM.getBoxModel): Could not compute box model. undefined`. Do you have a repro case for that? Thanks!

**Comment by aslushnikov** [comment] 2017-11-07 09:19
@divyamvn @patrickeakin can you guys please share a repro case where you experience the `DOM.getBoxModel` error?

```
Error: Protocol error (DOM.getBoxModel): Could not compute box model. undefined
```

**Comment by rafagsiqueira** [comment] 2017-11-07 14:15
I can confirm this also happens for puppeteer@0.13.0-alpha.

**Comment by divyamvn** [comment] 2017-11-07 15:51
Thank you for the response.
One of the instances where the DOM.getBoxModel error occurs for me...

   await page.focus( `div.core-appmenu-IndividualSearch input.searchinput.i-input` );
    await page.click( `div.individualSelect.individualSelectAppMenu input.searchinput.i-input` );
    await page.type(`div.individualSelect.individualSelectAppMenu input.searchinput.i-input`, firstName + ' ' + lastName);
//Waiting here for a dropdown of results which also has a button wrap 
    await page.waitFor("div.genericSearchResults div.button-wrap button");
//Error occurs on the below click
    await page.click("div.genericSearchResults div.button-wrap button[data-buttonindex='0']");

**Comment by aslushnikov** [comment] 2017-11-07 17:19
@divyamvn can you please share the HTML as well? The issue seems to be with some specific property of the element you click.

**Comment by divyamvn** [comment] 2017-11-07 17:52
The button wrap appears after searching for any text in an input field. The error occurs on clicking the buttons in the button-wrap.

```
<div class="genericSearchResults core-appmenu-IndividualSearch-Results" style="width: 259px; display: block;"><div class="results_wrapper shadow">
	<div class="results searchResults">		
		<span style="line-height: 30px">No Results.</span>		
	</div>	
		<div class="button-wrap">
			<button class="primary-btn" data-buttonindex="0">a</button>	
			<button class="primary-btn" data-buttonindex="1">b</button>		
			<button class="primary-btn" data-buttonindex="2">c</button>		
	</div>
</div></div>
```

**Comment by aslushnikov** [comment] 2017-11-07 18:28
@divyamvn still doesn't reproduce for me. Can you please also paste CSS rules applied to the `<button class="primary-btn" data-buttonindex="0">a</button>`?

**Comment by JoelEinbinder** [comment] 2017-11-07 21:48
My current hypothesis is that the button is in the dom, but it is set to `display: none`, or a parent of it is set to `display: none`. This would make sense if the drop down didn't open in time. Then the error `Error: Protocol error (DOM.getBoxModel): Could not compute box model. undefined` will be thrown.

I have a patch #1309 which should make this error message clearer: `Node is not visible`

**Comment by divyamvn** [comment] 2017-11-07 22:17
Thanks for the update.
@JoelEinbinder Shouldn't the waitForSelector visible or any of the wait methods work then?
I used waitForSelector for the button with visible true before clicking on it, which should help me wait until the button is visible right?
I anyway don't see any display: none rule on the element or any parent of it
Moreover the test never failed before I upgraded to 0.12.0.

Your suggestion would be helpful. Thank you.

**Comment by JoelEinbinder** [comment] 2017-11-07 22:26
Before 0.12.0, this would just click some arbitrary location and sort of fail silently. I have a follow up patch to make waitForSelector more robust, but right now it doesn't check the visibility of parent nodes.

Having the CSS applied to the button and button-wrap would be very helpful.

**Comment by divyamvn** [comment] 2017-11-10 16:30
@JoelEinbinder @aslushnikov 
I am getting the same " Error: Protocol error (DOM.getBoxModel): Could not compute box model. undefined" when trying to click the options on browser default combos.
<img width="226" alt="screen shot 2017-11-10 at 9 20 22 am" src="https://user-images.githubusercontent.com/33433487/32667632-706447f0-c5f8-11e7-979a-11ffcf4d18bb.png">

```
await page.click("select.ui-datepicker-month");
await page.waitForSelector("#ui-datepicker-div > select.ui-datepicker-month > option");
await page.click( "#ui-datepicker-div > select.ui-datepicker-month > option:nth-child(4)");

```
If we think the combo dropdown is not showing up quickly and hence node is not found. How can I make any of the combos work? Only using keyboard inputs?

The page.select is not working for me on any of the combos including these. page.select results in this 
<img width="249" alt="screen shot 2017-11-10 at 9 24 52 am" src="https://user-images.githubusercontent.com/33433487/32667847-2132e51e-c5f9-11e7-83b3-87ef44cb6160.png">

**Comment by divyamvn** [comment] 2017-11-10 18:46
I could resolve these issues as well, putting some extra hard coded waits.
You can close the issue. Thanks much!!

**Comment by JoelEinbinder** [comment] 2017-11-11 00:17
You should be able to use the `visible` option of `waitFor` now. See #1354.

**Closed as completed by JoelEinbinder** 2017-11-11 00:17 UTC
