### ISSUE TITLE
Possible bug in click using visible center

### ISSUE THREAD

**Issue by mathurs** [puppeteer/puppeteer#2798] opened 2018-06-25 05:50 UTC
### Steps to reproduce

**Tell us about your environment:** 

* Puppeteer version:1.5.0
* Platform / OS version:Ubuntu
* URLs (if applicable):https://www.handelsregister.de/rp_web/mask.do?Typ=e
* Node.js version:v8.10

**What steps will reproduce the problem?**
https://stackoverflow.com/questions/51011466/puppeteer-select-link
Basically these https://bitbucket.org/ytNeskews/puppeteer-attempt/src/master/src/index.js

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**
The expectation is that page.click('p a') should trigger a click. While it appears there is no network request triggered

**What happens instead?**
Click happens but not on the link. Further debugging suggested that the visible center coordinates seem off. Once I changed the viewport of the page to 1366,768, the click successfully generated a navigation

![0](https://user-images.githubusercontent.com/2851262/41832506-f45c0d9e-7869-11e8-8585-13b475191734.png)

Perhaps something to do with elements staggered across the page (in multiple lines if you will).

**Comment by aslushnikov** [comment] 2018-06-27 01:09
@mathurs Looks like a dupe of #2804 that just got fixed; can you please try `puppeteer@next` to see if it works for you?

**Comment by mathurs** [comment] 2018-06-27 10:48
@aslushnikov,  Still not working (tried with 1.5.0-next.1530061501767). Attaching an image to illustrate the case. The bounding box center or element center is not over the element and hence no click.

![0](https://user-images.githubusercontent.com/2851262/41969059-e4f5bc68-7a23-11e8-8c33-1557e84ab1e4.png)

This will happen commonly with links so we should consider it.

Sorry, just trying to help. I know very little about the considerations so pardon my question. From reading various issues and docs it seems the reason Puppeteer is taking this approach is to make sure element is in view. However, is that necessary, can we not simply use DOM click regardless. Or maybe bring the element into view and then invoke DOM click ?

Regards,

**Comment by aslushnikov** [comment] 2018-06-28 02:55
Filed upstream: https://crbug.com/857308

**Closed as completed** 2018-06-29 19:03 UTC
Labels: upstream
