### ISSUE TITLE
Navigation Timeout Exceeded for https://google.com

### ISSUE THREAD

**Issue by dustyhorizon** [puppeteer/puppeteer#1365] opened 2017-11-12 05:44 UTC
* Puppeteer version: 0.13.0
* Platform / OS version: Debian GNU/Linux 8 (jessie) / nodejs 9.1.0 / google-chrome-unstable
* URLs (if applicable): https://google.com

**Note: using in a docker container hence the usage of unstable. Happened on nodejs 8.9.1 too.
***Note: 9c1935b651bfdf78f5ac835496d38a5a797c30c3 works okay

**What steps will reproduce the problem?**

`await Page.goto('https://google.com')` causes the error.

---

Any advice on how to proceed with debugging?

**Comment by Khady** [comment] 2017-11-12 08:41
What happens if you try to go to https://www.google.com instead?

Do you have request interception enabled?

**Comment by aslushnikov** [comment] 2017-11-12 09:01
@dustyhorizon just checked - works for me just fine. Can you please record the log with 'DEBUG=puppeteer:session' and send it here?

**Comment by dustyhorizon** [comment] 2017-11-12 09:30
@Khady nope do not have request interception on. https://www.google.com fails too
@aslushnikov here you go

[logs.txt](https://github.com/GoogleChrome/puppeteer/files/1464478/logs.txt)

**Comment by aslushnikov** [comment] 2018-01-12 11:49
@dustyhorizon I can't reproduce this. Looking to the logs, there's a redirect to some .ph google website that takes long to load. 

We've rolled chromium many times since then and fixed a lot of bugs; please try it out on puppeteer v1.0.0, it should work.

If it doesn't, please don't hesitate to write back. Closing this meanwhile since we have a lot of clients who don't have any issues navigating to `google.com`.

**Closed as completed by aslushnikov** 2018-01-12 11:49 UTC
