### ISSUE TITLE
[Bug]: FrameManager crashes with assertion failing, Missing frame isMainFrame=false

### ISSUE THREAD

**Issue by ThomazPom** [puppeteer/puppeteer#8933] opened 2022-09-09 12:07 UTC
### Bug description

Loading 9gag and accepting cookies is enough to get the error 80% of the time

This minimal example of code is enough tou trigger the bug in less than 20 s

```javascript
  
  import puppeteer from "puppeteer";
  
  (async () => {
  
      
  let launchArgs = {
      headless: false, defaultViewport: null,
      args: [
          
      ],
  }
    const browser = await puppeteer.launch(launchArgs);
    const page = await browser.newPage();
    await page.goto('https://9gag.com');
    page.waitForSelector("[role='dialog'] button:last-child").then(z=>page.click("[role='dialog'] button:last-child"))
  
  })();

```

### Puppeteer version

17.1.3

### Node.js version

v16.15.0

### npm version

8.5.5

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
PS C:\Users\admin\Desktop\Work\Project1> node .\test.js
file:///C:/Users/admin/Desktop/Work/Project1/node_modules/puppeteer/lib/esm/puppeteer/util/assert.js:25
        throw new Error(message);
              ^

Error: Missing frame isMainFrame=false, frameId=B31FE7351CFD830EC50A059DDD411382
    at assert (file:///C:/Users/admin/Desktop/Work/Project1/node_modules/puppeteer/lib/esm/puppeteer/util/assert.js:25:15)
    at complete (file:///C:/Users/admin/Desktop/Work/Project1/node_modules/puppeteer/lib/esm/puppeteer/common/FrameManager.js:274:9)
    at FrameManager._FrameManager_onFrameNavigated (file:///C:/Users/admin/Desktop/Work/Project1/node_modules/puppeteer/lib/esm/puppeteer/common/FrameManager.js:307:9)
    at file:///C:/Users/admin/Desktop/Work/Project1/node_modules/puppeteer/lib/esm/puppeteer/common/FrameManager.js:100:104
    at file:///C:/Users/admin/Desktop/Work/Project1/node_modules/puppeteer/lib/esm/vendor/mitt/src/index.js:49:68
    at Array.map (<anonymous>)
    at Object.emit (file:///C:/Users/admin/Desktop/Work/Project1/node_modules/puppeteer/lib/esm/vendor/mitt/src/index.js:49:43)
    at CDPSession.emit (file:///C:/Users/admin/Desktop/Work/Project1/node_modules/puppeteer/lib/esm/puppeteer/common/EventEmitter.js:66:22)
    at CDPSession._onMessage (file:///C:/Users/admin/Desktop/Work/Project1/node_modules/puppeteer/lib/esm/puppeteer/common/Connection.js:315:18)
    at Connection.onMessage (file:///C:/Users/admin/Desktop/Work/Project1/node_modules/puppeteer/lib/esm/puppeteer/common/Connection.js:153:25)
```

**Comment by OrKoN** [comment] 2022-09-09 12:17
Unable to reproduce on Mac but I suspect that some iframes inside ads might be causing troubles and ads are different for every user. Could you provide the CDP log but running the script with the env variable `DEBUG` set to `puppeteer:*`? E.g., `DEBUG=puppeteer:* node test.mjs` on Linux-like shells.

**Comment by ThomazPom** [comment] 2022-09-09 12:59
Sure, here you go.

* I had to hide my ip from the log file on one log line

[out.log](https://github.com/puppeteer/puppeteer/files/9535552/out.log)

**Comment by ThomazPom** [comment] 2022-09-09 13:13
I noticed [Frame manager from line 338](https://github.com/puppeteer/puppeteer/blob/main/src/common/FrameManager.ts#L338) asumes a frame either is a main frame or frame is defined but both are false statements

**Comment by herecy** [comment] 2022-09-27 22:54
any idea how to fix? rollback to previous version doable as workaround?

**Comment by ThomazPom** [comment] 2022-09-28 06:25
I rolled back to version 8 as a workaround

**Comment by herecy** [comment] 2022-09-28 06:49
8 is quite old though, was more thinking about 17.1.2 or similar. Problem is I cannot reproduce the issue reliably to test, also not with your code example. It happens randomly to me. Maybe another approach to catch the error and restart the browser if it happens? Unfortunately, not sure how to do that.

**Comment by ThomazPom** [comment] 2022-09-28 10:04
8 is not that old puppeteer versions escaleted quickly recently. Of course you could catch and restart, but from my experience its worse to have a non reliable process than an outdated reference.

**Comment by herecy** [comment] 2022-09-28 10:28
You are right, but unfortunately I need the updated chromium version.

**Comment by ThomazPom** [comment] 2022-09-28 12:44
You can launch puppeter 8 with the executablePath arg with the path of your real chromium use the latest chrome version && no crash https://stackoverflow.com/a/62209380/4693790

**Comment by ThomazPom** [comment] 2022-09-28 12:46
```
const browser = await puppeteer.launch({
    executablePath: "C:\\Users\\marti\\Downloads\\chrome-win\\chrome-win\\chrome.exe",
});
```

**Comment by herecy** [comment] 2022-09-28 12:49
Thank you very much for your help, appreciate it.

**Comment by herecy** [comment] 2022-10-03 19:32
Catching this error leaves me no peace. I inserted throw new Error("Missing frame isMainFrame=false, frameId=3427AF206D1A9A044F89F086F2CB9AB6") into Connection.js, but it is not possible to catch the error for me.

```const puppeteer = require('puppeteer');

(async () => {
  try{
    browser = await puppeteer.launch().catch((err) => {
      console.log ("Error1: ", err)
    });
  } catch(e){
    console.log("Error2: "+e)
  }
})().catch((err) => {
  console.log ("Error3: ", err)
});
```

None of the catches work, the script just terminates with:

```
Error: Missing frame isMainFrame=false, frameId=3427AF206D1A9A044F89F086F2CB9AB6
    at Connection.onMessage (C:\Users\User\Documents\project\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:124:15)
    at WebSocket.<anonymous> (C:\Users\User\Documents\project\node_modules\puppeteer\lib\cjs\puppeteer\node\NodeWebSocketTransport.js:45:32)
    at WebSocket.onMessage (C:\Users\User\Documents\project\node_modules\puppeteer\node_modules\ws\lib\event-target.js:199:18)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (C:\Users\User\Documents\project\node_modules\puppeteer\node_modules\ws\lib\websocket.js:1178:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (C:\Users\User\Documents\project\node_modules\puppeteer\node_modules\ws\lib\receiver.js:528:14)
    at Receiver.getData (C:\Users\User\Documents\project\node_modules\puppeteer\node_modules\ws\lib\receiver.js:446:17)
    at Receiver.startLoop (C:\Users\User\Documents\project\node_modules\puppeteer\node_modules\ws\lib\receiver.js:148:22)
    at Receiver._write (C:\Users\User\Documents\project\node_modules\puppeteer\node_modules\ws\lib\receiver.js:83:10)
```

**Comment by OrKoN** [comment] 2022-10-04 05:47
The assertion is no longer part of the code base since v18.0.0 https://github.com/puppeteer/puppeteer/pull/8952 I believe this issue should be considered fixed now.

**Closed as completed by OrKoN** 2022-10-04 05:47 UTC
Labels: confirmed

**Comment by dominusLabs** [comment] 2023-06-30 12:05
Hello!

I'm running puppeteer 20.7.1 and still running into this issue.
