### ISSUE TITLE
ERROR in ./node_modules/puppeteer/node_modules/mime/index.js Module not found: Error: Can't resolve './types/other' in '/node_modules/puppeteer/node_modules/mime'

### ISSUE THREAD

**Issue by sunnykreative** [puppeteer/puppeteer#2720] opened 2018-06-12 06:21 UTC
ERROR in ./node_modules/puppeteer/node_modules/mime/index.js
Module not found: Error: Can't resolve './types/other' in '/node_modules/puppeteer/node_modules/mime'

**Comment by aslushnikov** [comment] 2018-06-29 06:52
Looks like a dupe of https://github.com/GoogleChrome/puppeteer/issues/2754; I'd ask the author over there - looks like he figured the issue.

**Closed as completed by aslushnikov** 2018-06-29 06:52 UTC
