### ISSUE TITLE
[Bug]: n8n-nodes-puppeteer-extended in Docker installation throwing error 'Failed to launch the browser process! spawn'

### ISSUE THREAD

**Issue by Rafurus** [puppeteer/puppeteer#9059] opened 2022-10-05 18:27 UTC
### Bug description

Steps to reproduce the problem:

1. Self host n8n with docker compose installation -> https://docs.n8n.io/hosting/server-setups/docker-compose/ 
2. Install community node in n8n GUI - n8n-nodes-puppeteer-extended -> https://www.npmjs.com/package/n8n-nodes-puppeteer-extended
3. Try using node -> throwing error ENOENT

As far as i know installed chrome from puppeteer is missing depencencies to work out of box.

### Puppeteer version

18.2.0

### Node.js version

17.9.0

### npm version

8.8.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Error: Failed to launch the browser process! spawn /home/node/.n8n/nodes/node_modules/puppeteer/.local-chromium/linux-1002410/chrome-linux/chrome ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

at onClose (/home/node/.n8n/nodes/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:286:20)
at ChildProcess.<anonymous> (/home/node/.n8n/nodes/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:280:24)
at ChildProcess.emit (node:events:527:28)
at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
at onErrorNT (node:internal/child_process:478:16)
at processTicksAndRejections (node:internal/process/task_queues:83:21)`
```

**Comment by jrandolf** [comment] 2022-10-05 19:01
Duplicate of https://github.com/puppeteer/puppeteer/issues/9034.

**Closed as not planned by jrandolf** 2022-10-05 19:01 UTC

**Comment by Rafurus** [comment] 2022-10-05 20:11
@jrandolf 
The indicated package points to the official puppeteer package -> https://www.npmjs.com/package/n8n-nodes-puppeteer-extended?activeTab=dependencies (https://www.npmjs.com/package/puppeteer) 
So the official puppeteer package does not install all the necessary dependencies for the applications put up by docker compose.

**Comment by jrandolf** [comment] 2022-10-05 20:23
https://github.com/hckdotng/n8n-nodes-puppeteer-extended is the official repo for that package.
