### ISSUE TITLE
[Bug]: remoteAddress is missing ip and port properties for redirects

### ISSUE THREAD

**Issue by grcode123** [puppeteer/puppeteer#13055] opened 2024-09-06 19:45 UTC
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

const sleep = (ms) => new Promise((res) => setTimeout(res, ms));

(async () => {
  // Launch the browser and open a new blank page
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();

  page.on("request", (request) => {
    console.log("REQUEST_URL", request.url());
  });

  page.on("requestfinished", (request) => {
    const response = request?.response();
    console.log(
      `RESPONSE: ${response?.status()} - ${response?.url()} - ${JSON.stringify(
        response?.remoteAddress()
      )}`
    );
  });

  await page.goto("http://google.com");

  await sleep(5000);

  await browser.close();
})();
```

### Background

It looks like the puppeteer is missing `remoteAddress` properties for redirects (at least for 307). Easy to reproduce when running against http://google.com but also other websites.

### Expectation

`remoteAddress()` - should return object with ip and port
Something like this:
```
REQUEST_URL http://google.com/
RESPONSE: 307 - http://google.com/ - {"ip":"123.123.123.123","port":80}
REQUEST_URL https://google.com/
RESPONSE: 301 - https://google.com/ - {"ip":"74.125.21.100","port":443}
REQUEST_URL https://www.google.com/
RESPONSE: 200 - https://www.google.com/ - {"ip":"173.194.219.105","port":443}
```

### Reality

```
REQUEST_URL http://google.com/
RESPONSE: 307 - http://google.com/ - {"ip":"","port":0}
REQUEST_URL https://google.com/
RESPONSE: 301 - https://google.com/ - {"ip":"74.125.21.100","port":443}
REQUEST_URL https://www.google.com/
RESPONSE: 200 - https://www.google.com/ - {"ip":"173.194.219.105","port":443}
```

### Puppeteer version

23.3.0

### Node version

20.5.0

### Package manager

npm

### Package manager version

9.8.0

### Operating system

macOS

**Comment by Lightning00Blade** [comment] 2024-09-10 09:35
I think what is happening is that there is no actual request being made by Chrome to any server as you are requesting `http` and not `https`, if you use `https` the issue is not observed.
This is due to a feature in Chrome where HTTP is automatically redirected to HTTPS without an request being made -https://chromestatus.com/feature/6056181032812544

As this is not a bug, I will close this issue for now.

**Closed as completed by Lightning00Blade** 2024-09-10 09:35 UTC
