### ISSUE TITLE
Timeout on CDP interactions

### ISSUE THREAD

**Issue by ks07** [puppeteer/puppeteer#1456] opened 2017-11-23 10:35 UTC
I have a long running Puppeteer script - after some time the browser object starts hanging on `browser.newPage()` calls - the Promise is never resolved or rejected until the script is killed. While this is ongoing, chrome doesn't output anything (I am using `dumpio: true`). Unfortunately I don't have any logs from when this problem has begun, so I'm not able to report the underlying issue.

Puppeteer should have an option to add a timeout to all requests made over the debugging protocol, such that the NodeJS script can easily handle these errors (e.g. by launching a new browser).

**Comment by aslushnikov** [comment] 2018-01-12 02:59
@ks07 this seems to be a dupe of https://github.com/GoogleChrome/puppeteer/issues/1774

Let me know if you disagree.

**Closed as completed by aslushnikov** 2018-01-12 02:59 UTC
