### ISSUE TITLE
cannot type surrogate-pair-characters correctly

### ISSUE THREAD

**Issue by wingsys** [puppeteer/puppeteer#2845] opened 2018-07-05 05:25 UTC
in first, sorry for my bad english.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: Windows 7 SP1 (x64)
* URLs (if applicable): local
* Node.js version: 8.2.1 (x64)

**What steps will reproduce the problem?**

minimum (and confirmed) reproduces code here:

```
"use strict";

const puppeteer = require("puppeteer");
const exam = async () => {
    const browser = await puppeteer.launch({
        headless: false
    });
    const page = await browser.newPage();
    await page.goto("https://developers.google.com/web/");

    // Type into search box
    await page.type("#searchbox input", "𩸽𠮷𠮟");
};
exam();
```

I failed testing with headless-mode, cause stopping at goto.
however, I think it is only a enviroment problem.

**What is the expected result?**
type 𩸽𠮷𠮟 into textbox
(in unicode: \u29E3D\u20BB7\u20B9F - so, yes, surrogate pair charactors)

**What happens instead?**
typed 鸽ஷட into textbox
(in unicode: \u9e3d\u0bb7\u0b9f)

**Comment by aslushnikov** [comment] 2018-07-05 06:49
@JoelEinbinder is this a dupe of #1096?

**Comment by JoelEinbinder** [comment] 2018-07-06 07:12
Yes. Closing as duplicate of #1096.

**Closed as completed by JoelEinbinder** 2018-07-06 07:12 UTC
