### ISSUE TITLE
Allow page use some privacy?

### ISSUE THREAD

**Issue by maicss** [puppeteer/puppeteer#1086] opened 2017-10-18 10:28 UTC
**Tell us about your environment:**

* Puppeteer version: 0.12
* Platform / OS version: Mac OS 10.12.6
* URLs (if applicable): like google.com or maps.google.com

**Comment by ebidel** [comment] 2017-10-18 15:49
It's not clear what this is asking for. Can you elaborate on the request and what you're trying to do?

**Comment by maicss** [comment] 2017-10-19 03:08
![image](https://user-images.githubusercontent.com/9784767/31752473-c2f15b66-b450-11e7-9a22-ebe6407de9a0.png)

How to `Allow` or `Block`.

And others like : Audio etc.

**Comment by Garbee** [comment] 2017-10-19 15:25
Duplicate of #846

**Closed as completed** 2017-10-19 17:55 UTC

**Comment by aslushnikov** [comment] 2017-10-20 02:26
@maicss please upvote the issue if you're interested in it to be fixed. We're looking at the most-upvoted issues first.

**Comment by maicss** [comment] 2017-10-20 02:36
how? add a thumb emoji to https://github.com/GoogleChrome/puppeteer/issues/846 ?

**Comment by ebidel** [comment] 2017-10-20 16:48
@maicss that works

**Comment by saselovejulie** [comment] 2017-10-24 09:59
i really need this..

**Comment by GentJashari** [comment] 2022-12-15 09:02
is this fixed?

**Comment by GentJashari** [comment] 2022-12-15 09:02
@aslushnikov Is this fixed?
