### ISSUE TITLE
Different font family between { headless: false } and { headless: true }

### ISSUE THREAD

**Issue by mizdra** [puppeteer/puppeteer#922] opened 2017-09-30 16:28 UTC
Sorry, I report here because I did not understand where this issue should be reported to (DevTools Protocol or Chromium or Puppeteer) :bow:

A default font family is `Times New Roman` in `headless: true`, however it is `Hiragino Kaku Gothic ProN` in `headless: false`. In my environment, `Hiragino Kaku Gothic ProN` is `Standard font` which is set at `Settings > Customize fonts > Standard font`. Is this behavior expected?

## Test codes
```javascript
const puppeteer = require('puppeteer');

const url = 'http://info.cern.ch';
const selector = 'h1';

const getFontProperty = async (page) => {
  const font = await page.evaluate((selector) => {
    const title = document.querySelector(selector);
    return getComputedStyle(title).font;
  }, selector);
  return font;
}

const printFontProperty = async (headless) => {
  const browser = await puppeteer.launch({headless: headless});
  const page = await browser.newPage();
  await page.goto(url);
  console.log(await getFontProperty(page));
  await browser.close();
}

(async () => {
  await printFontProperty(true);
  await printFontProperty(false);
})();
```

## Output
```bash
$ node main.js
normal normal 700 normal 32px / normal "Times New Roman"
normal normal 700 normal 32px / normal "Hiragino Kaku Gothic ProN"
```

## Environment
- Puppeteer version: 0.11.0
- Platform / OS version: macOS Sierra 10.12.6
- Chrome Version: Chrome/63.0.3205.0 (Lang: Japanese)
- Font config (Chromium)
  - Standard font: Hiragino Kaku Gothic ProN
  - Serif font: Hiragino Mincho ProN
  - Sans-serif font: Hiragino Kaku Gothic ProN
  - Fixed-width font: Osaka

**Comment by aslushnikov** [comment] 2017-10-04 21:27
@mizdra This looks like a different font resolution in chrome headless wrt chrome headful. Could you please file this to chromium ([crbug.com/new](http://crbug.com/new)) and post a link to the bug here?

**Comment by mizdra** [comment] 2017-10-19 15:41
@aslushnikov I filed this. The link is here: https://bugs.chromium.org/p/chromium/issues/detail?id=775794

**Comment by aslushnikov** [comment] 2017-10-27 09:48
Thanks @mizdra.

I can't reproduce this bug as well, it looks like the setup is specific to your environment.

Closing this in favor of the upstream bug.

**Closed as completed by aslushnikov** 2017-10-27 09:48 UTC

**Comment by LyleLaii** [comment] 2018-12-21 10:59
Now I met same issue.

This is in headless mode:
D:\backstopjs>node test1.js
{ fonts:
   [ { familyName: 'Times New Roman',
       isCustomFont: false,
       glyphCount: 47 } ] }

This is in headful mode:
D:\backstopjs>node test1.js
{ fonts:
   [ { familyName: 'Microsoft YaHei',
       isCustomFont: false,
       glyphCount: 47 } ] }

And my Chromium version is : 72.0.3617.0
Still need me to provide more information? Looking forward to your recovery, Thanks!
