### ISSUE TITLE
page.content() is not working?

### ISSUE THREAD

**Issue by isoos** [puppeteer/puppeteer#480] opened 2017-08-22 21:01 UTC
Code:
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com/', {waitUntil: 'networkidle'});

  const title = await page.title();
  console.log(title);

  const html = await page.content();
  console.log(html);

  browser.close();
})();

```

Title works, content is missing:

```
Example Domain
(node:27250) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: page.content is not a function
(node:27250) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
Node version: v8.4.0
puppeteer: 0.9.0
```

**Comment by ebidel** [comment] 2017-08-22 21:01
Dupe of https://github.com/GoogleChrome/puppeteer/issues/470

**Closed as completed by ebidel** 2017-08-22 21:01 UTC
