### ISSUE TITLE
element.screenshot() stalls and the browser window turns grey

### ISSUE THREAD

**Issue by phawxby** [puppeteer/puppeteer#2276] opened 2018-03-28 14:16 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: Windows 10
* Node.js version: 8.10.0
* Jest: 5.6.0

**What steps will reproduce the problem?**

```
    for (const slug of slugs) {
      const buster = (new Date()).getTime();
      const url = `${global.BASE_URL}/patterns/${slug}/${slug}.rendered.html?buster=${buster}`;

      // test.concurrent
      test(slug, async() => {
        let browser;
        let page;

        try {
          browser = await puppeteer.launch({ headless: false });
          page = await browser.newPage();
          await page.setViewport(viewport);

          const response = await page.goto(url);

          expect(response).not.toBeNull();

          await page.waitFor(150);

          if (!response.ok()) {
            throw new Error(`Unable to browse to url, status: ${response.status()}. ${url}`);
          }

          const elm = await page.$('body > *:not(script):not(style):not(link):not(meta)');

          expect(elm).not.toBeNull();

          if (elm) {
            const snapshotId = viewport.name + '--' + slug.replace('99-visual-regression-', '');

            const screenshot = await elm.screenshot({
              path: `${__dirname}/__image_snapshots__/__current__/${snapshotId}.png`
            });

            expect(screenshot).not.toBeNull();

            const config = Object.assign({}, defaultSnapshotConfig, { customSnapshotIdentifier: snapshotId });

            await expect(screenshot).toMatchImageSnapshot(config);
          }
        } finally {
          if (page) {
            await page.close();
          }
          if (browser) {
            await browser.close();
          }
        }
      });

      break;
    }

```

**What is the expected result?**

elm.screenshot() should return a screenshot via a promise.

**What happens instead?**

The code stalls and eventually jest times out. Switching off headless mode reveals the browser window turns grey. Switching to the home tab and the back to the correct tab then allows the browser to continue.

[Video-Wed-Mar-28-2018-15-11-01.zip](https://github.com/GoogleChrome/puppeteer/files/1856323/Video-Wed-Mar-28-2018-15-11-01.zip)

**Comment by phawxby** [comment] 2018-03-28 18:12
Further investigation suggests the bug seems to exist around the `Page.captureScreenshot` command being sent to Chromium. See attached example. 

[Bug demo.zip](https://github.com/GoogleChrome/puppeteer/files/1857119/Mar.28.2018.7_07.PM.zip)

**Comment by phawxby** [comment] 2018-03-28 18:43
With `page.screenshot()` this does not occur. To emulate this I added `params.clip = undefined` to `CDPSession.send()`. This appears to fix the freezing. 

[Mar 28, 2018 7_40 PM.zip](https://github.com/GoogleChrome/puppeteer/files/1857247/Mar.28.2018.7_40.PM.zip)

**Comment by phawxby** [comment] 2018-03-28 19:32
https://bugs.chromium.org/p/chromium/issues/detail?id=826848

**Comment by phawxby** [comment] 2018-03-28 22:15
I have finally found the source of the issue. One of the injected libraries was sometimes inserting a blank div into the top of the body meaning this code got thrown off. `const elm = await page.$('body > *:not(script):not(style):not(link):not(meta)');`

So I think there's a case for checking to see if an element contains a width and height before trying to screenshot it. If it does not throw and error. I'll keep this issue open and submit a PR soon with a fix to do that.

**Comment by Pyrolistical** [comment] 2018-04-13 00:08
any progress on the fix for this? any workaround we can use right now?

I'm blocked by this because I am taking a lot of screenshots.

**Comment by phawxby** [comment] 2018-04-14 13:38
I've been far too busy to work it but there's nothing to stop you checking to make sure you elements contains a with and height before taking a screenshot.

**Comment by yanivefraim** [comment] 2018-04-14 18:15
@phawxby - if I understand your scenario correctly, the following test should fail on timeout:

```
it('should ...', async({page, server}) => {
  await page.setViewport({width: 500, height: 500});
  await page.setContent(`
    something above
    <style>div {
      background: green;
      width: 0;
      height: 0;
    }
    </style>
    <div></div>
  `);
  const elementHandle = await page.$('div');
  const screenshot = await elementHandle.screenshot();
  expect(screenshot).toBeGolden(...);
});
```

But it doesn't... (test fails for me on wrong screenshot assertion. 

Is this the right scenario? Am I missing something?

**Comment by phawxby** [comment] 2018-04-15 16:37
In theory yes, I validated the bug in my own tests but didn't create a stand-alone test. The only different is the code injecting the bad div was this running immediately in a bottom of the page script include. 

```
    var div = document.createElement('div');
    div.setAttribute('id', 'test-div');
    document.body.appendChild(div);
```

**Comment by yanivefraim** [comment] 2018-04-15 19:53
@phawxby - sorry, I was not able to recreate the issue (trying to help here). 

I changed my test to be:

```
it('should ...', async({page, server}) => {
  await page.setViewport({width: 500, height: 500});
  await page.goto(server.EMPTY_PAGE);
  await page.evaluate(() => {
    const div = document.createElement('div');
    div.setAttribute('id', 'test-div');
    document.body.appendChild(div);
  });
  const elementHandle = await page.$('#test-div');
  const screenshot = await elementHandle.screenshot();
  expect(screenshot).toBeGolden(...);
});
```

The test is running just fine... Are you sure there's no other reason for this to happen? Anything else I can try in order to reproduce it?

**Comment by Filipoliko** [comment] 2018-04-16 07:29
I think, that i reproduced the very same issue. It seems to be happening when you try to capture "a" (link) element.

Here is example, where puppeteer will freeze forever.
```javascript
var puppeteer = require('puppeteer');

puppeteer
	.launch({ headless: false }) // The same thing happens when headless: true, but this way you can see the browser window get grey
	.then(browser => browser.newPage())
	.then(async page => {
		await page.setViewport({ width: 500, height: 500 });
		await page.goto('about:blank');
		await page.evaluate(() => {
			const a = document.createElement('a');
			a.setAttribute('id', 'test-lnk');
			const div = document.createElement('div');
			const text = document.createTextNode('Capture me!');
			div.appendChild(text);
			a.appendChild(div);
			document.body.appendChild(a);
		});

		const divElementHandle = await page.$('#test-lnk div');
		const divScreenshot = await divElementHandle.screenshot();
		console.log('Puppeteer can get here.');

		const lnkElementHandle = await page.$('#test-lnk');
		console.log('Puppeteer can get even here.');
		const lnkScreenshot = await lnkElementHandle.screenshot();
		console.log('Puppeteer never reaches this place!');
	});
```

This test creates following html structure:
```html
<html>
	<head></head>
	<body>
		<a id="test-lnk">
			<div>Capture me!</div>
		</a>
	</body>
</html>
```

**Comment by phawxby** [comment] 2018-04-17 14:30
Confirmed. @Filipoliko's test case recreates the issue!

**Comment by yanivefraim** [comment] 2018-04-17 20:04
@Filipoliko @phawxby - I just tried to run this test (as part of Puppeteer's tests):

```
it('should ...', async({page, server}) => {
  await page.setViewport({width: 500, height: 500});
  await page.goto('about:blank');
  await page.evaluate(() => {
    const a = document.createElement('a');
    a.setAttribute('id', 'test-lnk');
    const div = document.createElement('div');
    const text = document.createTextNode('Capture me!');
    div.appendChild(text);
    a.appendChild(div);
    document.body.appendChild(a);
  });
  const divElementHandle = await page.$('#test-lnk div');
  const divScreenshot = await divElementHandle.screenshot();
  console.log(divScreenshot);
  const lnkElementHandle = await page.$('#test-lnk');
  const lnkScreenshot = await lnkElementHandle.screenshot();
  console.log(lnkScreenshot);
  expect(lnkScreenshot).toBeGolden(...);
});
```

Result: I see both screenshot buffers on console + test fails for the wrong png (which is ok). I cannot reproduce your freeze. Any idea?

**Comment by phawxby** [comment] 2018-04-17 22:08
@yanivefraim can you reproduce without jest? I think we've nailed down jest is not required to reproduce the issue. Maybe try running it a few times?

**Comment by yanivefraim** [comment] 2018-04-20 18:26
@phawxby - I did not use Jest here. I wrote the test as part of Puppeteer's tests, using Puppeteer's [test runner](https://github.com/GoogleChrome/puppeteer/blob/master/utils/testrunner/TestRunner.js)

I will try running it several times / running in a different place

**Comment by Filipoliko** [comment] 2018-04-26 13:38
@yanivefraim I tried running the exactly same test you posted as part of the puppeteer's tests and still got the freeze and timeout.

My environment:
Windows 7
Node v8.6.0
NPM 5.3.0
Puppeteer latest version from master branch

Our server environment, where I also get the freeze (it is run inside a docker):
Debian GNU/Linux 8
Node v8.9.4
NPM 5.6.0
Puppeteer 1.3.0

**Comment by ayushporwal1234** [comment] 2021-11-27 10:48
Can i work on this issue @phawxby

**Comment by phawxby** [comment] 2021-11-27 10:52
@ayushporwal1234 you're welcome to, we don't actually use puppeteer anymore.

**Closed as completed** 2022-07-23 20:20 UTC
Labels: good first issue, chromium, unconfirmed
