### ISSUE TITLE
Response empty in headless only

### ISSUE THREAD

**Issue by iliakan** [puppeteer/puppeteer#5491] opened 2020-03-10 01:21 UTC
I have two pages (oauth scenario).

Then I submit a form on one of them and await for a certain response in the other.

Here's the code:

```
let token = await new Promise((resolve, reject) => {
    page.on('response', response => {
      if (response.url() == 'https://api.plnkr.co/v2/auth/token') {
        response.json().then(resolve, reject);
      }
    });
  });
```

The problem is that things work fine in `headless: false`, while in `headless: true` the `response json` is always empty.

What can be the reason?

P.S. Latest `npm install puppeteer` version, MacOS, Chrome.

**Comment by javascriptru** [comment] 2020-03-10 01:29
Sorry close this, the problem is not in response, it's in another aspect of behavior. Which one - no idea =(

**Closed as completed** 2020-03-10 01:29 UTC

**Comment by dinggewennuan** [comment] 2020-03-18 17:10
how to solve it ? can you tell me @iliakan

**Comment by iliakan** [comment] 2020-03-18 17:11
Sorry, there was another issue with puppeteer, not this one. So I closed.
