### ISSUE TITLE
chrome-linux/chrome: undefined symbol: gtk_widget_get_scale_factor

### ISSUE THREAD

**Issue by avlapeto** [puppeteer/puppeteer#873] opened 2017-09-25 13:44 UTC
Hi everyone!

I try to use ChromeHeadless in karma.

// Puppeteer launcher
const ChromiumRevision = require('puppeteer/package.json').puppeteer.chromium_revision;
const Downloader = require('puppeteer/utils/ChromiumDownloader');
const revisionInfo = Downloader.revisionInfo(Downloader.currentPlatform(), ChromiumRevision);

![image](https://user-images.githubusercontent.com/9626018/30810989-80be1804-a20f-11e7-869a-48a914a7e663.png)

On Windows OS browser work fine, but on linux I have an issue:

25 09 2017 12:57:02.881:ERROR [launcher]: Cannot start ChromeHeadless
	/home/travis/build/___/node_modules/puppeteer/.local-chromium/linux-497674/chrome-linux/chrome: symbol lookup error: /home/travis/build/___/node_modules/puppeteer/.local-chromium/linux-497674/chrome-linux/chrome: undefined symbol: gtk_widget_get_scale_factor

![image](https://user-images.githubusercontent.com/9626018/30811202-2dac2ec0-a210-11e7-8369-0b71166ae8ee.png)

Build language: java

Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-107-generic

**Comment by aslushnikov** [comment] 2017-09-25 16:26
@avlapeto This looks like a dupe of #536. I'd recommend checking that your environment has all the dependencies installed properly: [Troubleshooting.md](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md).

**Closed as completed by aslushnikov** 2017-09-25 16:26 UTC
