### ISSUE TITLE
[Bug]: Incognito Proxy doesn't work

### ISSUE THREAD

**Issue by UchihaYuki** [puppeteer/puppeteer#7873] opened 2021-12-24 03:39 UTC
### Bug description

The following work:
```
const browser = await puppeteer.launch({
    headless: false,
    defaultViewport: null,
    args: ["--proxy-server=http://localhost:8001"],
    userDataDir: "user-data-dirs/rotate-proxy",
  });
```
But the following doesn't work
```
const browser = await puppeteer.launch({
    headless: false,
    defaultViewport: null,
    // args: ["--proxy-server=http://localhost:8001"],
    userDataDir: "user-data-dirs/rotate-proxy",
  });
  const context = await browser.createIncognitoBrowserContext({
    proxyServer: "http://localhost:8001",
  });
  const page = await context.newPage();
```
The traffic doesn't go out through the proxy.

### Puppeteer version

13.0.0

### Node.js version

v16.13.1

### npm version

8.1.2

### What operating system are you seeing the problem on?

Windows

**Comment by iJoris** [comment] 2022-02-24 09:28
Having the same problem, seems to be going wrong after 10.2

**Comment by 118set** [comment] 2022-07-19 12:34
Not working for me either on 15.4.0

**Comment by OrKoN** [comment] 2022-09-20 07:04
Unfortunately, this does not work on Windows due to a bug in Chromium. We already have an issue tracking this: https://github.com/puppeteer/puppeteer/issues/8820 so closing this one in favour of the confirmed issue.

**Closed as not planned by OrKoN** 2022-09-20 07:04 UTC
Labels: unconfirmed
