### ISSUE TITLE
[Bug]: (Debugger.enable): Script execution is prohibited

### ISSUE THREAD

**Issue by adamraine** [puppeteer/puppeteer#11138] opened 2023-10-11 20:05 UTC
### Minimal, reproducible example

```TypeScript
import * as puppeteer from 'puppeteer';

const browser = await puppeteer.launch({
  headless: false,
});
const page = await browser.newPage();
const session = await page.target().createCDPSession();

const timeout = 30000;
page.setDefaultTimeout(timeout);

await page.setViewport({
  width: 1903,
  height: 963,
});
await page.goto("http://13.48.26.180/");

{
  const promises = [];
  const startWaitingForEvents = () => {
    promises.push(page.waitForNavigation());
  };
  await puppeteer.Locator.race([
    page.locator("::-p-aria(ABOUT)"),
    page.locator("li:nth-of-type(2) > a"),
    page.locator(
      '::-p-xpath(//*[@id=\\"navbarSupportedContent\\"]/ul/li[2]/a)'
    ),
    page.locator(":scope >>> li:nth-of-type(2) > a"),
  ])
    .setTimeout(timeout)
    .on("action", () => startWaitingForEvents())
    .click({
      offset: {
        x: 46.546875,
        y: 21.5,
      },
    });
  await Promise.all(promises);
}

// This command fails
await session.send('Debugger.enable');

await browser.close();
```

### Error string

ProtocolError: Protocol error (Debugger.enable): Script execution is prohibited

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Lighthouse issue: https://github.com/GoogleChrome/lighthouse/issues/15525

The original script looks like it was made by the replay library, but I was able to minify the script and repro without much replay stuff.

### Expectation

No errors are thrown

### Reality

Error is thrown on the `Debugger.enable` command

### Puppeteer version

21.3.8

### Node version

18.17.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by OrKoN** [comment] 2023-10-12 06:55
Shorter repro:

```
import * as puppeteer from 'puppeteer';

const browser = await puppeteer.launch({
  headless: false,
});
const page = await browser.newPage();
const session = await page.target().createCDPSession();

await page.setViewport({
  width: 1903,
  height: 963,
});
await page.goto("http://13.48.26.180/");

const result = await page.waitForSelector('li:nth-of-type(2) > a');

await result.click()

// This command fails
await session.send('Debugger.enable');

await browser.close();
```

**Comment by OrKoN** [comment] 2023-10-12 07:14
The bug is in Chrome https://bugs.chromium.org/p/chromium/issues/detail?id=1492053

**Comment by OrKoN** [comment] 2023-10-12 07:24
So disabling ProcessPerSiteUpToMainFrameThreshold would fix the issue but ultimately the session is probably wrong here. The page is bfcached and the session is created to the initial target. That target gets put into the bfcache after navigation and while Debugger.enable might work for it, it is probably not what you want.

**Comment by adamraine** [comment] 2023-10-12 18:19
Just to clarify, is there something that needs to change in the script for this to work or is puppeteer using an invalid session somehow?

**Comment by OrKoN** [comment] 2023-10-13 06:01
@adamraine The main reason for the problem is that the heuristics used by ProcessPerSiteUpToMainFrameThreshold to disable Debugger get confused (and the fact that the feature disabled by default somehow got enabled in CfT builds). I think Puppeteer is using the right session here but I am not sure if bfcache implementation in Chrome re-targets the session correctly (I hope the crbug I filed clarifies this). At the same time I believe the same/similar issue might occur during a pre-rendering navigation, and in that case the client code needs to be changed. In this case, I think it would be more robust to create the session after the navigation (and I think this works around the problem too). In general, I think any code that deals with CDP sessions directly should account for the [mparch](https://docs.google.com/document/d/14aeiC_zga2SS0OXJd6eIFj8N0o5LGwUpuqa4L8NKoR4/edit#heading=h.n1atlriavj6v) changes in Chrome.

**Comment by adamraine** [comment] 2023-10-13 17:23
In this instance, creating the session after the page nav doesn't fix the issue for me. I modified the script to look like this:

```js
import * as puppeteer from 'puppeteer';

const browser = await puppeteer.launch({
  headless: false,
});
const page = await browser.newPage();

await page.setViewport({
  width: 1903,
  height: 963,
});
await page.goto("http://13.48.26.180/");

const result = await page.waitForSelector('li:nth-of-type(2) > a');

const navPromise = page.waitForNavigation({
  waitUntil: ['load', 'networkidle0']
});
await result.click()
await navPromise;

const session = await page.target().createCDPSession();

// This command fails
await session.send('Debugger.enable');

await browser.close();
```

**Comment by OrKoN** [comment] 2023-10-18 15:23
@adamraine interesting, I am pretty sure I saw a similar script pass for me but I cannot reproduce anymore. Maybe there are some situations where the page is evicted from bfcache? 🤔

**Comment by OrKoN** [comment] 2024-04-02 13:15
The test site is not available anymore so I am closing the issue as it is not reproducible. The feature ProcessPerSiteUpToMainFrameThreshold is disabled by default now.

**Closed as not planned by OrKoN** 2024-04-02 13:16 UTC
Labels: upstream, confirmed
