### ISSUE TITLE
After setRequestInterception(true), repeatedly accessing a web page, the response returned is null

### ISSUE THREAD

**Issue by djytwy** [puppeteer/puppeteer#2976] opened 2018-07-29 12:22 UTC
my environment:
* Puppeteer version:1.6.1
* Platform / OS version:mac OS 10.13.4
* Node.js version:v8.9.4
* Chromium-version:69.0.3494.0 (x64)

The bug can be reproduced by the following code

```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        headless: false,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    });

    let rep = "";
    const page = await browser.newPage();
    await page.setRequestInterception(true);

    page.on('request',interceptedRequest => {
        if (interceptedRequest.url().endsWith('.png') || interceptedRequest.url().endsWith('.jpg'))
            interceptedRequest.abort();
        else
            interceptedRequest.continue();
    })

    rep = await page.goto('https://www.github.com');
    await page.waitFor(2000);
    console.log("this is response ：" + rep);
    await page.close();

    const page2 = await browser.newPage();
    await page2.setRequestInterception(true);

    page2.on('request',interceptedRequest => {
        if (interceptedRequest.url().endsWith('.png') || interceptedRequest.url().endsWith('.jpg'))
            interceptedRequest.abort();
        else
            interceptedRequest.continue();
    })

    rep = await page2.goto('https://www.github.com');
    await page2.waitFor(2000);
    console.log("this is response ：" + rep);
    await page2.close();

    browser.close();
})()

log:this is response ：[object Object]
log:this is response ：null
```

**Comment by djytwy** [comment] 2018-07-29 13:45
this bug must be from Chromium the code run in Chromium-version:69.0.3425.0 (x64)
result:
```
log:this is response ：[object Object]
log:this is response ：[object Object]
```

**Comment by aslushnikov** [comment] 2018-07-30 23:34
Dupe of #2970.

**Closed as completed by aslushnikov** 2018-07-30 23:34 UTC
