### ISSUE TITLE
Virtually fast forward to take a screenshot after animations

### ISSUE THREAD

**Issue by LukasBombach** [puppeteer/puppeteer#453] opened 2017-08-21 20:27 UTC
_Disclaimer: I really have no idea where to ask this, if this place is absolutely inappropriate, pleas close._

I'm a developer at "Die Welt", one of Germany's biggest daily newspapers. We are taking screenshots of embeds to display them in our apps with a headless Chrome. This works quite well, but we have to set a timeout of 10 seconds after the page has loaded so possible initial animations have completed. This means, our initial request actually takes 10 seconds to finish. Is there—or are there any plans for it—a way to fast forward the browser 10 seconds without actually waiting 10 seconds?

Thank you
Lukas

**Comment by JoelEinbinder** [comment] 2017-08-21 20:47
That depends on how your animations are implemented. You might have luck adding something like `transition: none !important` into your CSS when taking screenshots. You could also iterate through [`document.getAnimations()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/getAnimations) and turn them all off.

**Comment by elisherer** [comment] 2017-08-23 12:13
I thought about it too, and there is a workaround using the `Animation` domain.
```js
await page._client.send('Animation.setPlaybackRate', { playbackRate: 2 });
```
The above will make animations run twice as fast.
Maybe this should be added to the API?

**Comment by thetwosents** [comment] 2017-08-24 23:41
` await page._client.send('Animation.setPlaybackRate', { playbackRate: 2 }); ` worked but I have a slider issue now :(

**Comment by aslushnikov** [comment] 2017-08-24 23:56
Closing as dupe of #511

**Closed as completed by aslushnikov** 2017-08-24 23:56 UTC

**Comment by LukasBombach** [comment] 2017-08-25 06:59
This isn't entirely a dupe of https://github.com/GoogleChrome/puppeteer/issues/511 because although speeding up animations would solve most problems there are still issues with `setTimeout` and `setInterval`. I think virtually fasting forward goes beyond increasing animation speeds.

**Comment by Veejay** [comment] 2017-10-16 21:10
Hi, kind of hijacking this issue, ignore if irrelevant, but I'm interested in detecting _Mixed Content_ on websites to help our customers transition to **HTTPS** and I've seen `page._client` being used to achieve through `page._client.on('Network.loadingFailed', event => {...})`. 

This issue features another use of `page._client` with a call to `.send`. What is `page._client` exactly?

Seeing the property is called `_client`, I suppose it is a non-exposed internal API. Is it documented somewhere? I know I should theoretically avoid private properties, but it seems to open a whole new world of possibilities when interacting with web pages. 

Thanks.

EDIT: 

Reading from the [Chrome DevTools Protocol documentation]( https://chromedevtools.github.io/devtools-protocol/tot/Network/), it seems like `page._client` might actually the client `puppeteer` uses to control the browser through the `DevTools protocol`, am I correct in assuming this?

**Comment by aslushnikov** [comment] 2017-10-16 21:59
> Reading from the Chrome DevTools Protocol documentation, it seems like page._client might actually the client puppeteer uses to control the browser through the DevTools protocol, am I correct in assuming this?

@Veejay You're correct.

**Comment by LukasBombach** [comment] 2017-10-17 16:56
As for my original question, isn't this kind of what I have been looking for?

https://docs.google.com/document/d/1y9KDT_ZEzT7pBeY6uzVt1dgKlwc1OB_vY4NZO1zBQmo/edit#heading=h.tn3gd1y9ifml
