### ISSUE TITLE
Respond with multiple headers in request interception

### ISSUE THREAD

**Issue by jake314159** [puppeteer/puppeteer#4379] opened 2019-05-01 12:41 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.15.0
* Platform / OS version: Linux Ubuntu 18.04
* Node.js version: 10.9.0

**What steps will reproduce the problem?**

Execute the following code which sets up puppeteer with request interception enabled. It attempts to respond to the request with multiple set-cookie headers (but it applies to all headers). I believe this was supported in the previous version.

```javascript
const puppeteer = require('puppeteer');
const browser = await puppeteer.launch();
const page = await browser.newPage();
page.on("request", function(r) {
  r.respond({
    status: 200,
    contentType: "text/plain",
    body: "[BODY]",
    headers: {
      "set-cookie": ["a=1", "b=2"]
    }
  });
});
await page.setRequestInterception(true);
await page.goto('https://example.com');
console.log("Success");
```

**What is the expected result?**

It should respond with multiple Set-Cookie headers ie.

```
< HTTP/1.1 200 
< content-type: text/plain
< set-content: a=1
< set-content: b=2
[BODY]
```

**What happens instead?**

```page.goto()``` will not return for 30s, at which point it'll throw a "```TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded```" exception.

**Comment by jake314159** [comment] 2019-05-01 12:43
I believe it was introduced by this PR: https://github.com/GoogleChrome/puppeteer/pull/4265

**Comment by lebreRafael** [comment] 2019-05-02 16:18
I was having the same problem with the following header: `'Access-Control-Allow-Credentials': true`

This bug was introduced in the last version 1.15

Seems that the problem is that we wasn't defining the value of our headers as text. I was defining a boolean and you was defining an array.

For me the solution was simple. Just using `'true'` instead of `true`. For you I think that the best you can do is to create a single text separating your values with `;` so the header will be `"set-cookie": "a=1;b=2"`

But I think this is a bug because a wrong value in the headers should throw an error instead of never respond the request.

**Comment by jasonswearingen** [comment] 2019-05-04 21:25
@lebreRafael I have the same issue.  ***you can not set multiple cookies*** as you suggest.  (joining with "; ")  doing so results puppeteer only seeing the first cookie.

**Comment by aslushnikov** [comment] 2019-05-13 21:27
> It should respond with multiple Set-Cookie headers ie.

@jake314159  I don't think this has ever worked. The v1.14.0 was simply `JSON.stringify`'ing header values - so there was an impression that things work.

So, if you pass an array of header values in v1.14.0, values will be concatenated into a comma-separated list - and won't be treated as separate headers.

here's what I ran with 1.14.0 to validate the point:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  page.on('request', request => {
    request.respond({
      status: 200,
      headers: {
        'foo': ['bar', 'baz'],
      },
      body: 'Yo, page!',
    });
  });
  const response = await page.goto('https://example.com');
  console.log(response.headers()); // { foo: 'bar,baz', 'content-length': '9' }
  await browser
```

The change proposed in #4380 is nice by itself, but that's a **breaking API change** when it comes to returning header value arrays in `response.headers()`.

**Comment by jake314159** [comment] 2019-05-14 07:13
@aslushnikov I agree it looks like it never handled this as I expected

I can make a new PR that keeps the old behaviour of stringifying the headers but hopefully #4380 can be included in v2?

**Comment by aslushnikov** [comment] 2019-06-01 02:38
> But hopefully #4380 can be included in v2?

Hmm maybe we can just document how things work here. I'll close this as a dupe of #1893 that covers this.

**Closed as completed by aslushnikov** 2019-06-01 02:38 UTC
