### ISSUE TITLE
[Request] Pixel 6 be added to the device descriptors list

### ISSUE THREAD

**Issue by PythonCoderAS** [puppeteer/puppeteer#8071] opened 2022-02-27 14:06 UTC
I would like to be able to use the Pixel 6 as a device. I do not own a Pixel 6 myself so I am unable to manually add the data myself.

### Steps to reproduce

**Tell us about your environment:**

- Puppeteer version: v13.2
- Platform / OS version: MacOS Big Sur/Ubuntu 20.04
- URLs (if applicable):
- Node.js version: 17.4.0

**What steps will reproduce the problem?**

N/A

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

I can use the Pixel 6 as a valid device.

**What happens instead?**

I cannot use the Pixel 6 as a valid device.

**Comment by OrKoN** [comment] 2022-09-05 13:09
Duplicate of https://github.com/puppeteer/puppeteer/issues/7886

**Closed as not planned by OrKoN** 2022-09-05 13:09 UTC
Labels: unconfirmed
