### ISSUE TITLE
Slow screenshots

### ISSUE THREAD

**Issue by samwillis** [puppeteer/puppeteer#476] opened 2017-08-22 18:09 UTC
I'm looking to replace PhantomJS in a project with Puppeteer, however, I have found that it ultimately slows down our app. It seems that taking screenshots with Puppeteer is significantly slower than with PhantomJS.

Using the code below PhantomJS takes 120ms to save the screen shot, whereas Puppeteer takes  569ms. This is obviously a big slowdown from using PhantomJS and wipes out any speed increases due to using Chromium.

I have also found that multiple screenshots of different pages cannot be taken at the same time, they happen one after the other. (I had hoped I could replace multiple PhantomJS processes with one Chromium process)

From looking through the code it looks like there are two issues:

1. Firstly the screenshot is not saved directly to the file by chromium, it is streamed over the websocket to node and then saved to the file. I think this may be the reason for the slow times?
3. Also, it appears that there is a queue that ensures only one screen shot is taken at a time,  I think this is due to a limitation with chromium?

Is it possible for either of these to be improved or are they completely limited by Chromium and the DevTool protocol?

---

test_chrome.js:
```
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setViewport({
    width: 1000,
    height: 1000
  })
  await page.goto('https://example.com');
  const start = Date.now();
  await page.screenshot({path: 'example.png'});
  console.log((Date.now()-start)+'ms')
  await browser.close();
})();
```

test_phantomjs.js:
```
var page = require('webpage').create()
page.viewportSize = { width: 1000, height: 1000 };
page.open('https://example.com', function (status) {
    var start = Date.now();
    page.render('example.png');
    console.log((Date.now()-start)+'ms')
    phantom.exit();
});
```

**Comment by aslushnikov** [comment] 2017-08-22 23:43
> Firstly the screenshot is not saved directly to the file by chromium, it is streamed over the websocket to node and then saved to the file. I think this may be the reason for the slow times?

First thing to mention, screenshots are slow on mac: [crbug.com/741689](https://bugs.chromium.org/p/chromium/issues/detail?id=741689&can=1&q=is%3Astarred%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

I tested your example on Linux, and here are my numbers:
- your script outputs: 138ms
- time chromium captures screenshot itself: 61ms
- time chromium encodes png: 71ms
- time chromium encodes base64: 0.03ms

So it looks like transferring the screenshot over the protocol and decoding it on the puppeteer side took ~6ms. So throwing in streams won't help much.

> Also, it appears that there is a queue that ensures only one screen shot is taken at a time, I think this is due to a limitation with chromium?

Yes, that's currently a chromium limitation: we have to "activate" every tab to take screenshot.

**Closed as completed** 2017-08-24 23:48 UTC

**Comment by aslushnikov** [comment] 2017-08-24 23:53
Will JPEG work for you? It should be faster to convert.

**Comment by samwillis** [comment] 2017-08-30 08:40
@aslushnikov JPEG is an option, it looks a lot faster as well. A quick test myself on Linux shows 101ms for PNG and 53ms for JPEG. May be worth the switch for us.

Do you know if there is any intention of removing the limitation of activating each tab to take the screenshot from chromium?

**Comment by aslushnikov** [comment] 2017-08-30 09:47
> Do you know if there is any intention of removing the limitation of activating each tab to take the screenshot from chromium?

@samwillis No intention so far

**Comment by eliseumds** [comment] 2018-01-12 06:05
On MacOS, taking JPEG screenshots and decoding them with [node-jpeg-turbo](https://github.com/sorccu/node-jpeg-turbo) gave us a speed-up of ~60% on our regression tests. Most of the gains definitely came from the file format change (and not the decoding library).

**Comment by maxweber** [comment] 2018-03-23 10:19
I ran into the same issue on Mac OS. Performance is critical for my use case, since I need to take a lot of screenshots to turn them into a video. On Linux the performance is fine.

I would be very thankful, if you would add a note into the README or the appropriate API [method](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagescreenshotoptions) docs with a warning about the screenshot performance on Mac OS.

**Comment by aslushnikov** [comment] 2018-04-07 03:06
> I would be very thankful, if you would add a note into the README or the appropriate API method docs with a warning about the screenshot performance on Mac OS.

@maxweber Done: https://github.com/GoogleChrome/puppeteer/pull/2326 In future, feel free to send a PR - we'll appreciate it!

> I ran into the same issue on Mac OS. Performance is critical for my use case, since I need to take a lot of screenshots to turn them into a video.

Sounds like https://github.com/GoogleChrome/puppeteer/issues/478 might be interesting for you

**Comment by maxweber** [comment] 2018-04-22 16:44
@aslushnikov great, thank you very much for adding the note.

#478 sounds definitely interesting, thanks.

**Comment by alexsaves** [comment] 2018-04-30 02:35
I would suggest that improving the performance, reliability, and throughput over time of the screenshot API would expand the use cases. It would allow us to move off .NET for some pieces of our stack.

**Comment by aslushnikov** [comment] 2018-04-30 09:25
>  It would allow us to move off .NET for some pieces of our stack.

@alexsaves can you please describe your usecases?
