### ISSUE TITLE
Install [Bug]: 

### ISSUE THREAD

**Issue by motoroller1983** [puppeteer/puppeteer#11109] opened 2023-10-10 08:22 UTC
### Minimal, reproducible example

```TypeScript
ERROR: Failed to set up Chrome r117.0.5938.149! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.                                                                 
│ Error: Download failed: server returned code 403. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.149/linux64/chrome-linux64.zip                 
│     at file:///var/www/www-root/data/www/vetaf.ru/node_modules/.pnpm/@puppeteer+browsers@1.7.1/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:74:31                    
│     at ClientRequest.requestCallback (file:///var/www/www-root/data/www/vetaf.ru/node_modules/.pnpm/@puppeteer+browsers@1.7.1/node_modules/@puppeteer/browsers/lib/esm/htt…  
│     at Object.onceWrapper (node:events:629:26)                                                                                                                               
│     at ClientRequest.emit (node:events:514:28)                                                                                                                               
│     at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)                                                                                                          
│     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)                                                                                                         
│     at TLSSocket.socketOnData (node:_http_client:535:22)                                                                                                                     
│     at TLSSocket.emit (node:events:514:28)                                                                                                                                   
│     at addChunk (node:internal/streams/readable:376:12)                                                                                                                      
│     at readableAddChunk (node:internal/streams/readable:349:9)
```

### Error string

 Error: Download failed: server returned code 403. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.149/linux64/chrome-linux64.zip 

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

correct install

### Reality

Download failed: server returned code 403. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.149/linux64/chrome-linux64.zip  

### Puppeteer version

20

### Node version

20.8.0 

### Package manager

npm

### Package manager version

10

### Operating system

Linux

**Comment by OrKoN** [comment] 2023-10-10 08:50
Duplicate of https://github.com/puppeteer/puppeteer/issues/11060#issuecomment-1748872481

**Closed as not planned by OrKoN** 2023-10-10 08:49 UTC
