### ISSUE TITLE
Event that fires just before the disconnected event?

### ISSUE THREAD

**Issue by Aditya-ds-1806** [puppeteer/puppeteer#7552] opened 2021-09-08 11:15 UTC
I have gone through the Puppeteer api and there doesn't seem to be any event that fires just before the browser closes. I need to run some code just before the browser is closed. Is there a way to do that?

**Comment by iamkarsoft** [comment] 2021-09-24 13:32
Run your event 
```
   await  page.waitForNavigation({
        waitUntil: 'networkidle0',
    })
```

then close your browser.

**Comment by jschfflr** [comment] 2021-09-24 16:25
@Aditya-ds-1806 Thanks for taking the time to report this issue!
Unfortunately, Puppeteer can not prevent the browser from closing. But you can run your code before calling `browser.close`. 
Closing this as it's working as intended but feel free to reopen if you feel otherwise!

**Closed as completed by jschfflr** 2021-09-24 16:25 UTC

**Comment by Aditya-ds-1806** [comment] 2021-09-24 16:38
@jschfflr 
Perhaps I should have given some context.

My script opens a website for the user to log in. The user logs in and he/she closes the browser. Now before closing the browser, I want to grab the cookies and save it on his/her machine so that the script can impersonate him/her the next time and avoids the user having to login repeatedly.

After going through the puppeteer docs, I found a `disconnected` event that fires once the browser is closed. This isn't of much help to me as I can't grab the cookie data after the browser gets closed. That's when I thought it would be nice if we emit an event just before `disconnected`.
