### ISSUE TITLE
[Bug]: Chromium can not be found

### ISSUE THREAD

**Issue by MaxAryus** [puppeteer/puppeteer#9592] opened 2023-01-26 10:23 UTC
### Bug expectation

I wanted to deploy my node app on a server (render.com). So I installed chromium via `npm i chromium`.

Locally works everything great but after deployment via render.com I get this error message:

{"message":"Could not find Chromium (rev. 1083080). This can occur if either\n 1. you did not perform an installation before running the script (e.g. `npm install`) or\n 2. your cache path is incorrectly configured (which is: /opt/render/.cache/puppeteer).\nFor (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration."}

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch();
```

### Error string

{"message":"Could not find Chromium (rev. 1083080). This can occur if either\n 1. you did not perform an installation before running the script (e.g. `npm install`) or\n 2. your cache path is incorrectly configured (which is: /opt/render/.cache/puppeteer).\nFor (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration."}

### Puppeteer version

19.6.1

### Node version

16

### Package manager

npm

### Package manager version

-

### Operating system

Linux

**Comment by OrKoN** [comment] 2023-01-26 10:28
Looks like a duplicate of https://github.com/puppeteer/puppeteer/issues/9581

**Closed as not planned by OrKoN** 2023-01-26 10:28 UTC
