### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: spawn EACCES

### ISSUE THREAD

**Issue by Lone** [puppeteer/puppeteer#1999] opened 2018-02-09 09:41 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v1.0.0
* Platform / OS version: macos 10.13.2
* URLs (if applicable):
* Node.js version: v9.4.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');
  
 puppeteer.launch({
      executablePath: './chromium/Chromium.app'
  }).then(async browser => {
      const page = await browser.newPage();
      await page.goto('https://y.qq.com');
      await page.screenshot({path: 'yqq.png'});
      await browser.close();
  });
```

**What is the expected result?**

**What happens instead?**
(node:73106) UnhandledPromiseRejectionWarning: Error: spawn EACCES
    at _errnoException (util.js:1003:13)
    at ChildProcess.spawn (internal/child_process.js:340:11)
    at Object.exports.spawn (child_process.js:499:9)
    at Function.launch (node_modules/puppeteer/lib/Launcher.js:101:40)
    at <anonymous>

**Comment by petuscov** [comment] 2018-02-12 16:37
Same here, tried with different versions of node, npm, installing puppeteer globally, checking chromium is installed as root, permission issues, etc, nothing worked. In windows everything works fine, (im trying it in ubuntu), and seems its a problem with the chromium that puppeteer installs.

**Comment by ebidel** [comment] 2018-02-13 18:32
Does `./chromium/Chromium.app` exist? Does pptr's bundled version work for you?

**Comment by petuscov** [comment] 2018-02-13 19:46
In my case, considering i am in ubuntu, `./chromium/Chromium.app` does not exists, but it exists  `./node_modules/chromium/lib/chromium/chrome-linux/chrome`, either specifiying it in `executablePath` option or not specifiying it, is the same result. For @Lone a solution could be check `./chromium/Chromium.app` permissions as said here: [issues/1649](https://github.com/GoogleChrome/puppeteer/issues/1649)

**Comment by aslushnikov** [comment] 2018-02-22 04:01
Dupe of #1649.

**Closed as completed by aslushnikov** 2018-02-22 04:01 UTC

**Comment by BlaM** [comment] 2018-02-28 13:55
For people arriving here from Google and looking for a Linux (Debian for me) solution: The locally installed version of Chrome had very restrictive executable permissions for me (700), so if your not the only person running the tool or if your process switches to another user during runtime (process.setuid) you may have to chmod/chown your permissions correctly.

**Comment by jslim89** [comment] 2018-03-14 07:58
It's about the permission issue.
In my case, when I tried to run with **ubuntu** user, it works;
when run with **www-data**, it failed

Thus I changed the permission to the chrome folder, i.e.

```
$ chmod 777 node_modules/puppeteer/.local-chromium/linux-536395/chrome-linux/*
```

P/S: Change all files in that folder, because initially I only change _chrome_ file, but it still doesn't work.

**Comment by voordev** [comment] 2018-03-22 12:52
Also same problem On ubuntu 16
Chmod 777 same user as the node process 
still not working..

this must be one of the most frustrating issues come across so far

```
(node:5062) UnhandledPromiseRejectionWarning: Error: spawn EACCES
    at ChildProcess.spawn (internal/child_process.js:330:11)
    at Object.exports.spawn (child_process.js:500:9)
    at Function.launch (/srv/us/node_modules/puppeteer/lib/Launcher.js:98:40)
    at <anonymous>
(node:5062) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5062) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lixiii** [comment] 2018-04-06 09:16
I tried running `chmod 777 node_modules/puppeteer/.local-chromium/linux-536395/chrome-linux/*` as well but for me the folder `linux-536395` doesn't exist. Mine is a different version `linux-543305`. And it worked on this folder. Maybe you should check whether the folder exists. Hopefully that helps.

**Comment by dosjota** [comment] 2018-04-24 13:09
Run `npm` without `sudo`

**Comment by yangfan0095** [comment] 2019-01-14 11:04
> Also same problem On ubuntu 16
> Chmod 777 same user as the node process
> still not working..
> 
> this must be one of the most frustrating issues come across so far
> 
> ```
> (node:5062) UnhandledPromiseRejectionWarning: Error: spawn EACCES
>     at ChildProcess.spawn (internal/child_process.js:330:11)
>     at Object.exports.spawn (child_process.js:500:9)
>     at Function.launch (/srv/us/node_modules/puppeteer/lib/Launcher.js:98:40)
>     at <anonymous>
> (node:5062) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:5062) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

me too😂

**Comment by IgorUsoltsev** [comment] 2019-05-29 06:57
this article solved it for me - https://jmfeurprier.com/2015/10/02/how-to-install-node-js-with-ubuntu-and-vagrant-in-a-synced-folder/

I use Puppeteer on Vagrant, so had permission issues. The trick was to create a dir into vagrant home folder  (`/home/vagrant/node_modules/`) and then create a symlink for the project in vagrant. worked like a charm!
