### ISSUE TITLE
Add possibility to view logs from a WebWorker

### ISSUE THREAD

**Issue by KristofJannes** [puppeteer/puppeteer#1921] opened 2018-01-30 12:02 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v1.0.0

**What steps will reproduce the problem?**
Call `console.log` from within a WebWorker.

**What is the expected result?**
There should be a way to view these logs, like it is possible for the main page:
`page.on('console', msg => console.log(msg.text()));`

**What happens instead?**
Logs from the WebWorker don't show up.

**Comment by aslushnikov** [comment] 2018-04-11 00:56
We don't expose webworkers currently; once we do, you'll be able to subscribe to their 'console' event.

Closing as a dupe of #2350.

**Closed as completed by aslushnikov** 2018-04-11 00:56 UTC
