### ISSUE TITLE
[Bug]: When two chrome instances are started at the same time, there is a chance that only one can be started

### ISSUE THREAD

**Issue by Vinlic** [puppeteer/puppeteer#9084] opened 2022-10-09 09:08 UTC
### Bug description

**I'm getting weird exception when launching multiple instances of headless chrome on windows**

**Most of the time I was able to start them successfully:**
![image](https://user-images.githubusercontent.com/20235341/194747689-aea78a04-16d2-4124-a6f9-3f6f23859eb5.png)

**But sometimes only one instance can be successfully started, the other instance doesn't seem to start:**
![image](https://user-images.githubusercontent.com/20235341/194747947-b889c78e-d54f-494b-b6ab-9e61f9c51feb.png)

**When debugging in the source code I found that the line event is not fired when this exception occurs:**
![image](https://user-images.githubusercontent.com/20235341/194747860-d9d664b7-5464-4d96-a672-45190aa27892.png)

### Puppeteer version

18.2.1

### Node.js version

16.11.0

### npm version

8.4.1

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r1045629 is guaranteed to work.
    at Timeout.onTimeout (file:///E:/Project/ave-renderer-service-new/node_modules/_puppeteer-core@18.2.1@puppeteer-core/lib/esm/puppeteer/node/BrowserRunner.js:280:20)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

**Comment by OrKoN** [comment] 2022-10-10 10:35
@Vinlic do you have a script to reproduce this? If the DevTools WS URL is not printed, it's very likely that the browser indeed didn't start.

**Comment by Vinlic** [comment] 2022-10-10 11:11
> @Vinlic你有重现这个的脚本吗？如果没有打印 DevTools WS URL，很可能浏览器确实没有启动。

@OrKoN This script will always try to start two instances, there is a chance to reproduce the problem.

import puppeteer from 'puppeteer-core';

//Windows
//Chrome 106.0.5249.103
//Puppeteer 18.2.1

async function launch(name) {
    const browser = await puppeteer.launch({
        channel: "chrome",
        headless: true,
        ignoreHTTPSErrors: true,
        timeout: 30000,
        dumpio: true,
        userDataDir: `./tmp/${name}`,
        args: [
            "--process-per-tab",
            "--no-sandbox",
            "--disable-setuid-sandbox",
            "--disable-dev-shm-usage",
            "--disable-extensions",
            "--hide-scrollbars",
            "--mute-audio",
            "--disable-canvas-aa",
            "--enable-accelerated-2d-canvas",
            "--no-zygote",
            "--disable-timeouts-for-profiling",
            "--autoplay-policy=no-user-gesture-require",
            "--disable-dinosaur-easter-egg",
            "--disable-web-security",
            "--browser-test",
            "--disable-ipc-flooding-protection",
            "--disable-crash-reporter",
            "--performance",
            "--use-gl=egl",
            "--disable-gpu",
            "--enable-surface-synchronization",
            "--disable-threaded-animation",
            "--disable-threaded-scrolling",
            "--disable-checker-imaging",
            "--disable-new-content-rendering-timeout",
            "--disable-image-animation-resync",
            "--enable-features=SurfaceSynchronization",
            "--enable-begin-frame-control",
            "--run-all-compositor-stages-before-draw"
        ]
    });
    console.log(`Launch chrome@${name} completed!`);
    return browser;
}

(async () => {
    while(true) {
        const names = ["A", "B"];
        const browsers = await Promise.all(names.map(name => launch(name)));
        for(let browser of browsers)
            await browser.close();
        console.log("OK");
        await new Promise(resolve => setTimeout(resolve, 2000));
    }
})()
.catch(err => console.error(err));

**Comment by jrandolf** [comment] 2023-01-02 08:31
Could you verify if the timeout is a problem?

**Comment by OrKoN** [comment] 2023-01-26 16:21
Closing as we were not able to reproduce it at this time, perhaps it is some limitation on the reporter's system that leads to timeouts.

**Closed as not planned by OrKoN** 2023-01-26 16:21 UTC
Labels: needs-feedback
