### ISSUE TITLE
[Bug]: ARM support

### ISSUE THREAD

**Issue by Botspot** [puppeteer/puppeteer#10172] opened 2023-05-12 21:32 UTC
### Bug expectation

Puppeteer downloads an x86 Chrome binary, even if the host system architecture is Armhf or Arm64. With puppeteer's integration into other node.js packages, this breaks them too. For example, I cannot render SVG images to PNG using [svgexport](https://github.com/shakiba/svgexport), which uses puppeteer.

Our use-case involves using a Raspberry Pi to do server-side-rendering for a website. Emulation with Rosetta is not feasible.
The OS we are using is Debian but it uses all ARM packages, so obviously trying to run a 64-bit x86 Chrome binary is not going to work.

```
$ file '/home/pi/.nvm/versions/node/v20.1.0/lib/node_modules/svgexport/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome'
/home/pi/.nvm/versions/node/v20.1.0/lib/node_modules/svgexport/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, not strippe
```

Error output:
```
$ svgexport '/home/pi/website/_site/img/app-icons/Color Emoji font/app-selection.svg' '/home/pi/website/_site/img/app-icons/Color Emoji font/app-selection.png'
/home/pi/.nvm/versions/node/v20.1.0/lib/node_modules/svgexport/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
/home/pi/.nvm/versions/node/v20.1.0/lib/node_modules/svgexport/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: 22: Syntax error: "(" unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/pi/.nvm/versions/node/v20.1.0/lib/node_modules/svgexport/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
    at Interface.<anonymous> (/home/pi/.nvm/versions/node/v20.1.0/lib/node_modules/svgexport/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)
    at Interface.emit (node:events:523:35)
    at Interface.close (node:internal/readline/interface:526:10)
    at Socket.onend (node:internal/readline/interface:252:10)
    at Socket.emit (node:events:523:35)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.1.0
```
I would suggest enabling architecture detection. If armhf or arm64 is detected, it should download and extract the chromium binary from a recent Debian `chromium` package like [this one](https://packages.debian.org/bullseye/armhf/chromium/download). 

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
Boot a Raspberry Pi with Raspbian or Raspberry Pi OS (same thing), and see that Puppeteer does not work at all.
```

### Error string

Error: Failed to launch the browser process!

### Puppeteer version

3.3.0

### Node version

20.1.0

### Package manager

npm

### Package manager version

9.6.4

### Operating system

Linux

**Comment by Botspot** [comment] 2023-05-12 23:30
I have been able to prove that swapping in a suitable chromium binary from a Debian chromium package does work in our use-case.
It's a quick fix hack that we do not want to use long term, but it works.
```
ln -s /usr/lib/chromium-browser/chromium-browser '/home/pi/.nvm/versions/node/v20.1.0/lib/node_modules/svgexport/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome'
```

**Comment by OrKoN** [comment] 2023-05-14 15:13
Duplicate of https://github.com/puppeteer/puppeteer/issues/7740

**Closed as not planned by OrKoN** 2023-05-14 15:13 UTC
