### ISSUE TITLE
Mouse drag & drop issues with Rubaxa Sortable

### ISSUE THREAD

**Issue by Thomas-Bolstad** [puppeteer/puppeteer#3735] opened 2019-01-08 10:22 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: Microsoft Windows 10 Pro v 10.0.17763
* URLs (if applicable): http://sortablejs.github.io/Sortable/
* Node.js version: 10.15.0

**What steps will reproduce the problem?**

Use mouse input to simluate drag and drop on a website that uses Rubaxa Sortable

Rubaxa Sortable: https://github.com/SortableJS/Sortable

_Please include code that reproduces the issue._

```
function sleep(time) {
	return new Promise(function(resolve) {
		setTimeout(resolve, time)
	});
}

const puppeteer = require('puppeteer');
var baseurl =  'http://sortablejs.github.io/Sortable/';
var hl = false;

		

(async () => {
		const browser = await puppeteer.launch({headless: hl});
		const page = await browser.newPage();
		const mouse = page.mouse;
		await page.setViewport({width: 1700, height: 1300});
		await page.goto(baseurl);
		await sleep(3000);
		await mouse.move(500, 350);
		await mouse.down();
		//using steps or different amount of steps seems to make no difference here
		await mouse.move(500, 600, {steps: 100});
		await mouse.up();
		await sleep(2000);
		await browser.close();
})();
```

**What is the expected result?**
For puppeteer to click an object in the list, and move it

**What happens instead?**
Puppeteer seems to click an object, and seems to start to move it momentarily, but then stops and never completes the action, and doesn't respond until I manually click the mouse or move the mouse in the chrome window.

**Comment by aslushnikov** [comment] 2019-01-10 00:01
Yeah drag-n-drop is a known issue; this is a dupe of #1376.

**Closed as completed by aslushnikov** 2019-01-10 00:01 UTC
