### ISSUE TITLE
[Bug]: Puppteer instalaation failing for version 21.3.8

### ISSUE THREAD

**Issue by aman909909** [puppeteer/puppeteer#11978] opened 2024-02-22 15:41 UTC
### Minimal, reproducible example

```TypeScript
ERROR: Failed to set up Chrome r117.0.5938.149! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
.../node_modules/puppeteer postinstall: Error: Download failed: server returned code 500. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.149/linux64/chrome-linux64.zip
.../node_modules/puppeteer postinstall:     at file:///home/hudson/inmem_workspace/node_modules/.pnpm/@puppeteer+browsers@1.7.1/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:74:31
```

### Error string

ERROR: Failed to set up Chrome r117.0.5938.149! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

Chrome should be downloaded in default directory.

### Reality

Chrome download is failing.

### Puppeteer version

21.3.8

### Node version

18.17.1

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Linux

**Comment by rsl** [comment] 2024-02-22 16:01
i'm getting this as well. running on heroku.

**Comment by poldixd** [comment] 2024-02-22 16:02
Got the same error. A google service for downloading the headless chrome browser is responding a status code 500.

```
npm ERR!   [cause]: Error: Download failed: server returned code 500. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/linux64/chrome-headless-shell-linux64.zip
npm ERR!       at file:///builds/nils.poltmann/estater.de/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:64:31
```

**Comment by paulovareiro29** [comment] 2024-02-22 16:04
I'm having the same issue on version 21.3.8. Version 22.2.0 is working fine

**Comment by samhoughton123** [comment] 2024-02-22 16:31
Same here on all versions

**Comment by thatdom** [comment] 2024-02-22 16:32
+1

**Comment by rogeriorc** [comment] 2024-02-22 16:36
```
npm ERR! code 1
npm ERR! path /data/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh /tmp/postinstall-5aead971.sh
npm ERR! ERROR: Failed to set up Chrome r119.0.6045.105! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: Download failed: server returned code 500. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chrome-linux64.zip
npm ERR!     at file:///data/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:74:31
npm ERR!     at ClientRequest.requestCallback (file:///data/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:52:13)
npm ERR!     at Object.onceWrapper (node:events:628:26)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at HTTPParser.parserOnIncomingClient (node:_http_client:674:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:521:22)
npm ERR!     at TLSSocket.emit (node:events:513:28)
npm ERR!     at addChunk (node:internal/streams/readable:315:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:289:9)
```

**Comment by IPospelova** [comment] 2024-02-22 16:38
+1

**Comment by chinchang** [comment] 2024-02-22 16:38
+1 Google servers are giving 500!

**Comment by nathancolgate** [comment] 2024-02-22 16:42
This may be a duplicate of #11967. Be sure to check out the proposed solutions there.

**Comment by chinchang** [comment] 2024-02-22 16:44
Can confirm, upgraded to latest 22.2.0. Error is fixed ✅

**Comment by OrKoN** [comment] 2024-02-22 16:46
Duplicate of https://github.com/puppeteer/puppeteer/issues/11967

**Closed as not planned by OrKoN** 2024-02-22 16:46 UTC
Labels: needs-feedback, not-reproducible

**Comment by hugomota** [comment] 2024-02-22 16:53
> This may be a duplicate of #11967. Be sure to check out the proposed solutions there.

Yeah it seems to be.  Adding `PUPPETEER_DOWNLOAD_BASE_URL=https://storage.googleapis.com/chrome-for-testing-public` worked for me. Thanks
