### ISSUE TITLE
select() causes Protocol error (Runtime.callFunctionOn): Cannot find context with specified id

### ISSUE THREAD

**Issue by pauldraper** [puppeteer/puppeteer#4691] opened 2019-07-10 17:47 UTC
### Steps to reproduce

**Tell us about your environment:**

https://try-puppeteer.appspot.com/

**What steps will reproduce the problem?**

https://jsbin.com/leruqutesi/2

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Example</title>
  </head>
  <body>
    <select onchange="location.href = 'https://example.com'">
      <option selected value="here">Here</option>
      <option value="there">There</option>
    </select>
  </body>
</html>
```

Puppeteer

```js
const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.goto('https://jsbin.com/leruqutesi/2');

await Promise.all([
  page.waitForNavigation(),
  page.select('select', 'there'),
]);

console.log('success');

await browser.close();
```

**What is the expected result?**

"success" is printed.

**What happens instead?**

Frequently (say, 50% of the time), there is an error:

> Error running your code. Error: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id

---

Oddly enough  #1591 suggests that this can happen when `page.evaluate` is combined with page navigation.

I'm not using `page.evaluate`. **But if I do use** `page.evaluate`, then the error **doesn't** happen. 

```js
const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.goto('https://jsbin.com/leruqutesi/2');

await Promise.all([
  page.waitForNavigation(),
  page.evaluate(() => {
    const select = document.querySelector('select');
    select.value = 'there';
    select.dispatchEvent(new Event('change'));
  }),
]);

console.log('success');

await browser.close();
```

Also, writing the equivalent code for Selenium/WebDriver also fixes the problem.

**Comment by aslushnikov** [comment] 2019-07-15 04:10
This is a dupe of #4537 which has been fixed awhile ago.

Unfortunately, the try-puppeteer has been running an old version of Puppeteer - it definitely needs some love. ❤️ We'll do something with it.

Meanwhile, closing this as a dupe.

**Closed as completed by aslushnikov** 2019-07-15 04:10 UTC

**Comment by SimonSchick** [comment] 2020-03-05 00:07
Is it possible there is a regression here?
I've migrated some code that previously used `type` to `select` and I'm getting a LOT of these errors on the latest version.
