### ISSUE TITLE
page methods (waitFor, goto, etc.) should reject when page closed

### ISSUE THREAD

**Issue by futurist** [puppeteer/puppeteer#2543] opened 2018-05-14 10:23 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: macOS
* Node.js version: 10.0.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```js
var puppeteer = require('puppeteer')
;(async ()=>{
  var browser = await puppeteer.launch({headless:false})
  var page = await browser.newPage()
  var closed = new Promise(r=>page.on('close', r))
  page.goto('https://github.com', {timeout: 0})
  var pending = page.waitFor(60e3) // anything like '#selector'
  await Promise.race([ closed, pending ])
  await browser.close()
  console.log('end')
})()
```

1. When chromium opened, close the page within 10s

**What is the expected result?**

Node process should be terminated, console should print 'end'

The pending page promises should be rejected after page closed.

**What happens instead?**

console print 'end', but process never end until 1min elapsed.

After page closed, the pending page promises still waiting for events/selectors, etc.

**Comment by aslushnikov** [comment] 2018-05-17 00:43
Dupe of #1454.

**Closed as completed by aslushnikov** 2018-05-17 00:43 UTC
