### ISSUE TITLE
`page.evaluate()` throw an error in 'framenavigated' callback

### ISSUE THREAD

**Issue by GuilloOme** [puppeteer/puppeteer#1214] opened 2017-10-30 15:00 UTC
### Steps to reproduce

* Puppeteer version: `v0.12.0`
* Platform / OS version: Linux Ubuntu or try-puppeteer.appspot.com

**What steps will reproduce the problem?**

1. run: 
``` javascript
const browser = await puppeteer.launch();
const page = await browser.newPage();

page.on('framenavigated',frameTo =>{
  console.log(`framenavigated to ${frameTo.url()}`);
  page.evaluate(()=>{
    // doing anything here
  });
})

await page.goto('https://example.com');
await page.screenshot({path: 'screenshot.png'});
await browser.close();
```

**What is the expected result?**
No error in console

**What happens instead?**
throw this error: 
```log
Error: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined
```

**Comment by aslushnikov** [comment] 2017-10-31 07:31
Dupe of #827

**Closed as completed by aslushnikov** 2017-10-31 07:31 UTC
Labels: P1
