### ISSUE TITLE
Failure to cleanup temp files on Windows machine

### ISSUE THREAD

**Issue by Xirek192** [puppeteer/puppeteer#450] opened 2017-08-21 16:52 UTC
On a windows machine, I am occasionally receiving an exception during the file cleanup process in Launcher.js on line 87 for version 0.9.0. This is causing the temp files to remain in their directories.

`Error: EPERM: operation not permitted, unlink 'PROJECT_DIRECTORY\node_modules\puppeteer\.dev_profile10\CrashpadMetrics-active.pma'
    at Object.fs.unlinkSync (fs.js:1066:18)
    at fixWinEPERMSync (PROJECT_DIRECTORY\node_modules\rimraf\rimraf.js:210:13)
    at rimrafSync (PROJECT_DIRECTORY\node_modules\rimraf\rimraf.js:310:28)
    at PROJECT_DIRECTORY\node_modules\rimraf\rimraf.js:341:5
    at Array.forEach (native)
    at rmkidsSync (PROJECT_DIRECTORY\node_modules\rimraf\rimraf.js:340:26)
    at rmdirSync (PROJECT_DIRECTORY\node_modules\rimraf\rimraf.js:333:7)
    at fixWinEPERMSync (PROJECT_DIRECTORY\node_modules\rimraf\rimraf.js:208:5)
    at rimrafSync (PROJECT_DIRECTORY\node_modules\rimraf\rimraf.js:310:28)
    at ChildProcess.__dirname.launch.chromeProcess.on (PROJECT_DIRECTORY\node_modules\puppeteer\lib\Launcher.js:87:7)`

I was able to resolve this problem locally by changing line 17 to
`const removeRecursive = require('rimraf');`

and changing line 87 to 
`removeRecursive(userDataDir, (err) => {
        if (err) { throw new Error(err); }
      });`

**Comment by aslushnikov** [comment] 2017-08-22 03:14
Thank you for the report!

This should be fixed on tip-of-tree with 271fd093794aeb91b29941a6eea0f1bc7caff2c4 and 11e3343b3d8c5a0cca4cb6abc08c749e71c23233.

**Closed as completed by aslushnikov** 2017-08-22 03:14 UTC

**Comment by codigo47** [comment] 2017-08-22 16:27
How can I update it throught npm?

**Comment by vsemozhetbyt** [comment] 2017-08-22 16:44
@codigo47 You can install as:
```
npm uninstall puppeteer
npm install https://github.com/GoogleChrome/puppeteer/
```
I was trying just `install` first but got an error; with `uninstall` it seems OK (but it will download chromium again).

**Comment by codigo47** [comment] 2017-08-22 17:21
Hi, thanks, I got v0.9.0, how can I get the version with the commits that fixed this bug?

> "Thank you for the report!
> This should be fixed on tip-of-tree with 271fd09 and 11e3343."

**Comment by vsemozhetbyt** [comment] 2017-08-22 17:23
`npm install https://github.com/GoogleChrome/puppeteer/` will install the latest status quo.

**Comment by codigo47** [comment] 2017-08-22 17:26
thanks man

**Comment by laggingreflex** [comment] 2017-08-22 22:55
Still getting the error. It's now creating the profile in temp dir but still unable to delete it:
```
Error: EPERM: operation not permitted, unlink 'C:\Users\<me>\AppData\Local\Temp\puppeteer_dev_profile-gIv5fX\BrowserMetrics-active.pma'
```
I dug into the code and it seems giving rimraf a timeout of 1s helps:

`lib/Launcher.js:101`

```js
    function killChromeAndCleanup() {
      helper.removeEventListeners(listeners);
      chromeProcess.kill('SIGKILL');
      // removeSync(userDataDir) // error
      // setTimeout(() => removeSync(userDataDir))  // error
      // setTimeout(() => removeSync(userDataDir), 100)  // error
      setTimeout(() => removeSync(userDataDir), 1000) // no error!
    }
```
not sure if it's the best solution though. 


edit: also helps async rimraf:

```js
    function killChromeAndCleanup() {
      helper.removeEventListeners(listeners);
      chromeProcess.kill('SIGKILL');
      // removeSync(userDataDir) // error
      require('rimraf')(userDataDir, console.log) // null = no error
    }
```

PS: the error for me only occurs when using `{headless: false}`

**Comment by aslushnikov** [comment] 2017-08-23 03:21
Now this is the dupe of #298
