### ISSUE TITLE
npm package contains wrong chrome binary for Linux ARM (Raspberry Pi 3, Raspbian)

### ISSUE THREAD

**Issue by ujay68** [puppeteer/puppeteer#2124] opened 2018-02-28 22:11 UTC
For Linux ARM, the npm package contains a wrong chrome binary.

**Tell us about your environment:**

* Puppeteer version: 1.1.1
* Platform / OS version: Raspberry Pi 3 / Raspbian Stretch, fully updated as of 2018-02-28
* Node.js version: v8.9.4

**What steps will reproduce the problem?**

$ npm i --save puppeteer
$ ./node_modules/puppeteer/.local-chromium/linux-536395/chrome-linux/chrome
-bash: ./node_modules/puppeteer/.local-chromium/linux-536395/chrome-linux/chrome: **cannot execute binary file: Exec format error**
$ file ./node_modules/puppeteer/.local-chromium/linux-536395/chrome-linux/chrome
./node_modules/puppeteer/.local-chromium/linux-536395/chrome-linux/chrome: ELF 64-bit LSB shared object, **x86-64**, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped

**Comment by secreter** [comment] 2018-03-11 10:20
mark,the same

**Comment by scissorsneedfoodtoo** [comment] 2018-03-29 13:11
I had a similar problem about a month ago. Check out @Austinb's [comment toward the bottom of issue #550](https://github.com/puppeteer/puppeteer/issues/550#issuecomment-360015928) for a workaround.

**Comment by Austinb** [comment] 2018-03-29 18:09
You cant use the chromium built library from puppeteer on PI.  You need to update your built in chromium on the PI and use that one in your code.  See @scissorsneedfoodtoo's comment above.

For builds on ARM they should disable building of the chromium by default since it does not work or fix it so it will run.  Confuses many people it seems.

**Comment by napolux** [comment] 2018-04-08 18:37
@Austinb any step-by-step way to fix this?

**Comment by Austinb** [comment] 2018-04-08 20:17
See #550

**Comment by aslushnikov** [comment] 2018-04-10 01:15
Dupe of #550.

**Closed as completed by aslushnikov** 2018-04-10 01:15 UTC
