### ISSUE TITLE
Long shot content repeat, in about 16000 pixels

### ISSUE THREAD

**Issue by Ryuurock** [puppeteer/puppeteer#1752] opened 2018-01-09 11:16 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:  0.13.0
* Platform / OS version: windows10 (16299)
* URLs (if applicable): 
* Node.js version: 8.9

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

I have a very long web pages need to capture, but the picture around 16000 pixels happened repeatedly

**What happens instead?**
like this( 5000 p tag, but from the 743th began to repeat )
![image](https://user-images.githubusercontent.com/25604544/34718201-c213a4fe-f570-11e7-9032-b810c2ca0017.png)

**Comment by grantstephens** [comment] 2018-01-09 16:57
Think this is related to #1576

**Comment by m9dfukc** [comment] 2018-01-11 10:13
Might be related to [#929](https://github.com/GoogleChrome/puppeteer/issues/929) and [#477](https://github.com/GoogleChrome/puppeteer/issues/477) and [#359](https://github.com/GoogleChrome/puppeteer/issues/359). This [#937](https://github.com/GoogleChrome/puppeteer/pull/937) might help though.

**Comment by aslushnikov** [comment] 2018-01-12 06:35
Dupe of #1576

**Closed as completed by aslushnikov** 2018-01-12 06:35 UTC
