### ISSUE TITLE
[Feature]: Puppeteer on Android

### ISSUE THREAD

**Issue by SunPodder** [puppeteer/puppeteer#9457] opened 2022-12-28 10:17 UTC
### Feature description

I see there are many previous issues requesting this feature. But I think we can use puppeteer on Android through Termux app now. Or atleast I'm using selenium on it. Currently we have firefox support on termux. Please let me know if there are any other requirements we need to make puppeteer work on Android (termux)

**Comment by jrandolf** [comment] 2023-01-02 08:25
Duplicate of https://github.com/puppeteer/puppeteer/issues/9460

**Closed as not planned by jrandolf** 2023-01-02 08:25 UTC
