### ISSUE TITLE
[Bug]: "Error: Execution context was destroyed" exception throw in IsolatedWorld is not caught

### ISSUE THREAD

**Issue by ikreymer** [puppeteer/puppeteer#13056] opened 2024-09-06 20:32 UTC
### Minimal, reproducible example

Unfortunately, there's not a simple reproducible example, as this is caused after many pages are loaded and functions bindings applied, but we do have this stack trace:

```TypeScript
file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:72
            throw new Error('Execution context was destroyed');
                  ^

Error: Execution context was destroyed
    at file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:72:19
    at file:///app/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:1936:31
    at OperatorSubscriber2._this._next (file:///app/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:993:9)
    at Subscriber2.next (file:///app/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:696:12)
    at listener (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:351:24)
    at file:///app/node_modules/puppeteer-core/lib/esm/third_party/mitt/mitt.js:36:7
    at Array.map (<anonymous>)
    at Object.emit (file:///app/node_modules/puppeteer-core/lib/esm/third_party/mitt/mitt.js:35:20)
    at EventEmitter.emit (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/EventEmitter.js:77:23)
    at [nodejs.dispose] (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:151:23)
```

### Background

It seems the callback triggered from a Symbol.dispose handler in Node can result in this exception being thrown and not caught, resulting in an unhandled exception crash.

This might be caused by function bindings in a target that are closed before, seeing some errors like this before the unhandled exception:
```
2024-09-06T07:28:19.542Z puppeteer:error [
  TargetCloseError: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
      at CdpCDPSession.send (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:61:35)
      at #evaluate (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:355:50)
      at ExecutionContext.evaluate (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:270:36)
      at Binding.run (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Binding.js:132:22)
      at async #onBindingCalled (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:595:9)
]
```

### Expectation

Puppeteer should ensure this exception is caught and not crash the Node process as an unhandled exception.

### Reality

There is no exception handler for that stack trace, resulting in this exception crashing the process.

### Puppeteer version

23.0.2

### Node version

20.17.0

### Package manager

yarn

### Package manager version

1.22.22

### Operating system

Linux

**Comment by OrKoN** [comment] 2024-09-16 08:38
Hi, could you please try to create a minimal reproducible example? This error usually happens if a closed page is being interacted with (perhaps it's crashed).

**Comment by OrKoN** [comment] 2024-09-16 08:44
The error in #onBindingCalled looks caught and the uncaught error seems to be thrown for some pending evaluate/evaluateHandle calls which might not be coming from Puppeteer internally so it would be really helpful if you could provide some examples of how you call Pupppeteer.

**Comment by ikreymer** [comment] 2024-09-17 03:41
There's not an easy repro step unfortunately, but the usage pattern is to call evaluate() on the iframes on the page to extract links, a simplified version is:
```
try {
   await Promise.allSettled(
          frames.map((frame) => frame.evaluate(extractLinks, options)))
 } catch (e) {
    console.log("link extraction failed");
 }
``` 

Even though the promise rejection is caught, the above stack trace / crash still happens. Since the frame.evaluate() calls are happening in parallel, it's possible that the page has crashed, yes. I suppose could try calling these in sequence rather than in parallel if you think that is the issue, though this happens very rarely and after some time, so pretty hard to repro. The stack trace points to the `[nodejs.dispose]` so I assume this has to do with the new [resource management / dispose semantics](https://github.com/tc39/proposal-explicit-resource-management) which are now supported in Node, and perhaps another exception handler can be added there somewhere in IsolatedWorld to catch this?

**Comment by OrKoN** [comment] 2024-09-17 06:27
The dispose only dispatches an event to which puppeteer/cdp/IsolatedWorld.js:72 (waiting for execution context) rejects. I think the stacktrace might not be quite correct here since the actual place it throws is whether #waitForExecutionContext started listening for the dispose event. Is there any way to replicate it by artificially closing the iframe randomly?

**Comment by OrKoN** [comment] 2024-09-17 07:06
I am able to trigger the same error with:

```
import puppeteer from "puppeteer";

const browser = await puppeteer.launch();

const page = await browser.newPage();

await page.goto('https://example.com');

async function iframes() {
  const handle = await page.evaluateHandle(() => {
    const iframe = document.createElement('iframe');
    iframe.src = 'https://example.com';
    document.body.append(iframe);
    return iframe;
  });
  await new Promise(resolve => setTimeout(resolve, 100));
  await handle.evaluate((el) => {
    el.remove();
  });
  iframes();
}

for (let i = 0; i < 10; i++) {
  iframes();
}

async function test() {
  try {
    console.log(await Promise.allSettled(
      page.frames().map((frame) => frame.evaluate(() => {
        return true;
      }))));
  } catch (e) {
    console.log("link extraction failed");
  }
  test();
}

test();

await new Promise(resolve => setTimeout(resolve, 6000));

await browser.close();
```

but it is properly caught and I do not experience an uncaught error.

**Comment by ikreymer** [comment] 2024-09-26 16:53
The above example has a rejected promise in a different part of the code, here:
https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/cdp/ExecutionContext.ts#L532
which is indeed caught. The above stack trace has an uncaught exception thrown from here:
https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/cdp/IsolatedWorld.ts#L145

This one is not caught unfortunately, resulting in node crashing. If you could just add a try/catch handler in the above stack trace, perhaps here: https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/cdp/IsolatedWorld.ts#L260
I think this would solve the issue, though I'm not familiar with how the dispose chain is supposed to work - maybe there's a better place for it.

**Comment by OrKoN** [comment] 2024-09-26 17:45
@ikreymer could you please check where the #waitForExecutionContext() that throws in https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/cdp/IsolatedWorld.ts#L145 was called in your code? rxjs would should catch it and it was not caught it means that the caller of #waitForExecutionContext() is not catching it.

**Comment by OrKoN** [comment] 2024-10-07 16:25
With https://github.com/puppeteer/puppeteer/pull/13139 the stack trace should be correct for this case. Could you try to reproduce it again if you have a chance? thanks!

**Comment by ikreymer** [comment] 2024-10-08 00:34
> With #13139 the stack trace should be correct for this case. Could you try to reproduce it again if you have a chance? thanks!

Thanks for the update and all your help trying to debug this! I was able to repro it with the examples above, by add something like `page.title()` after the page crashes, but in our codebase so far (everything appears to be caught).
Hoping that the correct stack trace will pinpoint the problem.

**Closed as not planned** 2024-10-29 01:28 UTC
Labels: needs-feedback, unconfirmed, not-reproducible
