### ISSUE TITLE
[Bug]: Cannot get response from iframe

### ISSUE THREAD

**Issue by StrugglingAndroid** [puppeteer/puppeteer#9699] opened 2023-02-17 07:23 UTC
### Bug expectation

Same as issue: https://github.com/puppeteer/puppeteer/issues/8473, always TimeoutError got

 TimeoutError: Timeout exceeded while waiting for event
      at Timeout.eval (webpack:///./node_modules/puppeteer-core/lib/cjs/puppeteer/common/util.js?:168:28)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)

![6GL4P7)XC96DVHE 6_PQ~{B](https://user-images.githubusercontent.com/20653456/219575262-baaff96a-7d85-4a49-93fd-82a27710200b.png)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const page = await browser.newPage();
        try {
            await page.goto("http://www.10010.com/net5/091/###")
            console.log('start check:' + mobile)
            await page.waitForTimeout(1000)

            // const frameXPath = "/html/body/div/div[4]/div/div[2]/iframe";
            // const frame = await page.waitForXPath(frameXPath);
            // console.log('frame.content',await frame.content())
            // const frames = await page.frames()
            // console.log('frames.length='+frames.length)

            // const div = page.waitForSelector('#aria5iipudb7pq8 > div.width100.banner_div1.ariaskiptheme.skipAutoFix > div > div.banner_right_div.ariaskiptheme.skipAutoFix')
            console.log('result=', Array.from(await page.frames()).map(i => i.url()))

            const frameUrl = 'https://upay.10010.com/npfweb/npfcellweb/phone_speedy.html'
            let frame = await (await page.frames()).find(f => f.url() === frameUrl)
            if (!frame) {
                await page.waitForTimeout(1000)
                frame = await (await page.frames()).find(f => f.url() === frameUrl)
            }
            if (!frame) {
                await page.waitForTimeout(1000)
                frame = await (await page.frames()).find(f => f.url() === frameUrl)
            }
            if (!frame) {
                await page.waitForTimeout(1000)
                frame = await (await page.frames()).find(f => f.url() === frameUrl)
            }
            console.log('frame', !!frame)
            if (!frame) {
                throw 'Target not found'
            }
            const inputSelector = "#number"
            const input = await frame.waitForSelector(inputSelector)
            console.log('input=', input)
            await input.focus()
            await input.click({clickCount: 3})
            await input.type(mobile)
            console.log('inputed')
            /**
             *
             * @type {HTTPResponse}
             */
            console.log('waiting for response')
            let response = await page.waitForResponse(response => /\/npfweb\/getArea\/init/i.test(response.url()))
            if (response.ok()) {
                console.log('response got', response)
                const data = await response.text();
                if (!data.endsWith('success')) {
                    throw new Error(response.status() + " " + data)
                }
            } else {
                throw new Error(response.status() + " " + response.statusText())
            }
            response = await page.waitForResponse(response => /\/npfweb\/NpfWeb\/customInfo\/cellInfoQuery/i.test(response.url()))
            if (response.ok()) {
                const data = await response.text();
                console.log('response', data)
                if (data.endsWith('success')) {
                    return data;
                }
                throw new Error(response.status() + " " + data)
            } else {
                throw new Error(response.status() + " " + response.statusText())
            }
        } finally {
            // page.close()
        }
```

### Error string

TimeoutError: Timeout exceeded while waiting for event

### Puppeteer version

19.4.1

### Node version

v16.18.1

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Windows

**Comment by Yemesoft** [comment] 2023-02-17 07:26
OK, I'll try、、Thanks

**Comment by OrKoN** [comment] 2023-02-17 07:32
Could you also provide a minimal reproducible example for this including a test page? Note that request interception is currently not supported in out-of-process iframes that are enabled in the headful mode.

**Comment by Yemesoft** [comment] 2023-02-17 08:11
> This issue has an outdated Puppeteer version: `19.4.1`. Please verify your issue on the latest `19.7.1` version. Then update the form accordingly.

New error got when updated to version 19.7.1：
![image](https://user-images.githubusercontent.com/20653456/219588608-2c21e0d6-9ba3-4c3b-9223-3fc69720e35b.png)

**Comment by OrKoN** [comment] 2023-02-17 08:19
hm... `chromium-bidi` is an optional peer dependency. I am not sure why it fails here (I am unable to reproduce in my setup).

**Comment by Yemesoft** [comment] 2023-02-17 08:25
Could you tell me your vue-cli、webpack version? It seems like the same problem as issue: https://github.com/puppeteer/puppeteer/issues/9467

**Comment by Yemesoft** [comment] 2023-02-17 08:25
Could you tell me your vue-cli、webpack version? It seems like the same problem as issue: https://github.com/puppeteer/puppeteer/issues/9467

**Comment by OrKoN** [comment] 2023-02-17 08:29
I am not using vue-cli and webpack, it works with npm for me. Yeah, it looks like the module resolution in webpack is not correct here: it does not recognize that the peer dependency is optional and it should not import it. Can you mark chromium-bidi as external in webpack?

**Comment by Yemesoft** [comment] 2023-02-17 08:30
[tests.zip](https://github.com/puppeteer/puppeteer/files/10764801/tests.zip)
Sampe code in node. Run it with 'node index.js' command

**Comment by OrKoN** [comment] 2023-02-17 13:26
The error should be fixed with https://github.com/puppeteer/puppeteer/pull/9703 but I think the element not being found is a different issue and probably the request is not being intercepted. Do you launch in headless or headful mode? Also, note that you can use page.waitForFrame to wait for the right frame to load.

**Comment by Yemesoft** [comment] 2023-02-17 13:48
> > This issue has an outdated Puppeteer version: `19.4.1`. Please verify your issue on the latest `19.7.1` version. Then update the form accordingly.
> 
> New error got when updated to version 19.7.1： ![image](https://user-images.githubusercontent.com/20653456/219588608-2c21e0d6-9ba3-4c3b-9223-3fc69720e35b.png)

By the way, I found thant it works with vite earlier.

**Comment by OrKoN** [comment] 2023-02-17 13:48
The docs are here https://pptr.dev/api/puppeteer.page.waitforframe/ Try using the headless mode. If it works in headless, then it is likely this issue https://github.com/puppeteer/puppeteer/issues/9567

**Comment by Yemesoft** [comment] 2023-02-17 13:51
Ok, I'll have a try tomorrow. Thanks very much!

**Comment by Yemesoft** [comment] 2023-02-17 13:51
It's night in china at the moment

**Comment by Yemesoft** [comment] 2023-02-18 02:50
> 

It didn't work for me in headless mode. I'll migrate webpack to vite and try again with puppeteer@latest

**Comment by Yemesoft** [comment] 2023-02-18 03:09
[sample-code.zip](https://github.com/puppeteer/puppeteer/files/10772946/sample-code.zip)
It's also not working for me with vite and puppeteer-core@^19.7.1、、still TimeoutError got
I am sure that a request with url like '/npfweb/getArea/init' is sent when telphone number inputed.

**Comment by Yemesoft** [comment] 2023-02-20 02:01
It seems that it's nothing about iframe, this request is always not intercepeted.
![image](https://user-images.githubusercontent.com/20653456/219992044-49b05db4-beaf-4efb-b677-5a7773ad5d89.png)

**Comment by Yemesoft** [comment] 2023-02-20 02:07
This is a test url，the request ablove is sent when a right phone number inputed（Example: 18698685520)
https://upay.10010.com/npfweb/npfcellweb/phone_speedy.html

**Comment by shenyue001** [comment] 2023-04-13 06:48
I got same problem with  `"puppeteer": "^19.7.2"` when I want to capture iframe's response.
The program print nothing when I try it  in headful mode. but it print everything in headless mode. 
The program is just like: 
```
page.on("response", (res) => {
    console.log("res", res.url());
})
```

**Comment by OrKoN** [comment] 2023-04-13 06:58
Thanks, I think it is actually the same as https://github.com/puppeteer/puppeteer/issues/9567 since the network manager does not work with out-of-process iframes yet

**Comment by shenyue001** [comment] 2023-04-13 07:05
> 

Thanks for responding,  in addition we got `true` in headful mode when call `frame.isOOPFrame()`, but got `false` in headless mode.

**Comment by OrKoN** [comment] 2023-04-13 07:06
headless does not support OOPIFs by default

**Closed as completed** 2023-08-29 16:12 UTC
Labels: confirmed, needs-feedback
