### ISSUE TITLE
[Bug]: A lot of zombie or orphaned chrome process is still existing on Linux env, when run puppeteer in Dcoker

### ISSUE THREAD

**Issue by zhuzaiye** [puppeteer/puppeteer#12854] opened 2024-07-30 11:32 UTC
### Minimal, reproducible example

```TypeScript
// the main program
async function main() {
    const browser = await puppeteer.launch();
    try {
        while (true) {
            const tasks = await executeSQL(getExportTaskSQL);
            if (tasks.length === 0) {
                await new Promise(resolve => setTimeout(resolve, 5000));
                console.log(">>> stop 5 second, and then loop again");
                continue;
            }

            console.log(">>> process cluster tasks start");
            try {
                await processExportTasks(tasks, browser);
            } catch (error) {
                console.error('Error in processExportTasks:', error);
            }
            console.log("<<< process cluster tasks end");
        }
    } catch (error) {
        console.error('Error in main loop:', error);
    } finally {
        await browser.close();
        console.log(">>> browser closed");
    }
}

// Run the main function
main().catch(error => {
    console.error('Error in main:', error);
});

// ------------ convert the html to pdf -----------------
// In processExportTasks
async function htmlToPdf(htmlS3Url, zipDir, fileName, browser) {
    const pdfPath = `${zipDir}/${fileName}.pdf`;
    const page = await browser.newPage();
    try {
        await page.goto(htmlS3Url, { waitUntil: 'networkidle2' });
        await page.pdf({ path: pdfPath, format: 'A4', printBackground: true });  // preferCSSPageSize: true, margin: {} 
        return pdfPath; 
    } catch (error) {
        console.error("Error converting HTML to PDF:", error);
        return '';
    } 
}
```

## Retrofit image use ghcr.io/puppeteer/puppeteer:latest
```
sudo docker run --name puppeteerbase  --init --cap-add=SYS_ADMIN -ti ghcr.io/puppeteer/puppeteer:latest bash
npm insall adm-zip@^0.5.12 aws-sdk@^2.1614.0 mysql@^2.18.1 pdf-lib@^1.17.1

sudo docker commit -a "xxxx@xxxx.com" -m "puppeteer for pdf" puppeteerbase 123.dkr.ecr.xxxx.amazonaws.com/puppeteer:v1.0.0
sudo docker push 123.dkr.ecr.xxx.amazonaws.com/puppeteer:v1.0.0
```

## Build execution image

```
FROM 123.dkr.ecr.xxxx.amazonaws.com/puppeteer:v1.0.0

MAINTAINER xxx <xxxx@xxxx.com>

USER root

RUN rm -rf /etc/alternatives/fonts-japanese-gothic.ttf

COPY ./nodepdf/font/ /usr/share/fonts/truetype/notosans

RUN fc-cache -f -v

USER pptruser

WORKDIR /home/pptruser

COPY ./nodepdf .

RUN mkdir upload

CMD ["node", "main.js"]
```

### Expectation

I wish I knew what caused so many zombie processes? And how to prevent such a process from occurring when running puppeteer with docker?

### Reality

```
systemd+ 3723948 3723863  0 May20 ?        00:00:43 /home/pptruser/.cache/puppeteer/chrome/linux-124.0.6367.91/chrome-linux64/chrome --type=renderer --crashpad-handler-pid=21 --enable-crash-reporter=, --noerrdialogs --user-data-dir=/tmp/puppeteer_dev_chrome_profile-gxhPsY --change-stack-guard-on-fork=enable --disable-dev-shm-usage --disable-background-timer-throttling --disable-breakpad --enable-automation --force-color-profile=srgb --remote-debugging-port=0 --allow-pre-commit-input --ozone-platform=headless --lang=en-US --num-raster-threads=4 --enable-main-frame-before-activ

systemd+ 3723976 3723888  0 May20 ?        00:45:43 /home/pptruser/.cache/puppeteer/chrome/linux-124.0.6367.91/chrome-linux64/chrome --allow-pre-commit-input --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-hang-monitor --disable-infobars --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-search-engine-choice-screen --disable-sync --enable-automation --export-tagged-pdf --generate-pdf-document-outline --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --disable-features=Translate,AcceptCHFrame,MediaRouter,OptimizationHints,ProcessPerSiteUpToMainFrameThreshold,IsolateSandboxedIframes --enable-features=PdfOopif --headless=new --hide-scrollbars --mute-audio --remote-debugging-port=0 --user-data-dir=/tmp/puppeteer_dev_chrome_profile-tgOl5j --noerrdialogs --ozone-platform=headless --ozone-override-screen-size=800,600 --use-angle=swiftshader-webgl about:blank

systemd+ 3723978 3723828  0 May20 ?        00:00:00 /home/pptruser/.cache/puppeteer/chrome/linux-124.0.6367.91/chrome-linux64/chrome_crashpad_handler --monitor-self --monitor-self-annotation=ptype=crashpad-handler --database=/home/pptruser/.config/google-chrome-for-testing/Crash Reports --annotation=lsb-release=Debian GNU/Linux 12 (bookworm) --annotation=plat=Linux --annotation=prod=Chrome_Linux --annotation=ver=124.0.6367.91 --initial-client-fd=5 --shared-client-connection

systemd+ 3723980 3723828  0 May20 ?        00:00:00 /home/pptruser/.cache/puppeteer/chrome/linux-124.0.6367.91/chrome-linux64/chrome_crashpad_handler --no-periodic-tasks --monitor-self-annotation=ptype=crashpad-handler --database=/home/pptruser/.config/google-chrome-for-testing/Crash Reports --annotation=lsb-release=Debian GNU/Linux 12 (bookworm) --annotation=plat=Linux --annotation=prod=Chrome_Linux --annotation=ver=124.0.6367.91 --initial-client-fd=4 --shared-client-connection

systemd+ 3723984 3723976  0 May20 ?        00:00:00 /home/pptruser/.cache/puppeteer/chrome/linux-124.0.6367.91/chrome-linux64/chrome --type=zygote --no-zygote-sandbox --headless=new --crashpad-handler-pid=21 --enable-crash-reporter=, --noerrdialogs --user-data-dir=/tmp/puppeteer_dev_chrome_profile-tgOl5j --change-stack-guard-on-fork=enable --no-first-run --ozone-platform=headless --ozone-override-screen-size=800,600 --use-angle=swiftshader-webgl

systemd+ 3723985 3723976  0 May20 ?        00:00:00 /home/pptruser/.cache/puppeteer/chrome/linux-124.0.6367.91/chrome-linux64/chrome --type=zygote --headless=new --crashpad-handler-pid=21 --enable-crash-reporter=, --noerrdialogs --user-data-dir=/tmp/puppeteer_dev_chrome_profile-tgOl5j --change-stack-guard-on-fork=enable --no-first-run --ozone-platform=headless --ozone-override-screen-size=800,600 --use-angle=swiftshader-webgl
systemd+ 3723989 3723985  0 May20 ?        00:00:00 /home/pptruser/.cache/puppeteer/chrome/linux-124.0.6367.91/chrome-linux64/chrome --type=zygote --headless=new --crashpad-handler-pid=21 --enable-crash-reporter=, --noerrdialogs --user-data-dir=/tmp/puppeteer_dev_chrome_profile-tgOl5j --change-stack-guard-on-fork=enable --no-first-run --ozone-platform=headless --ozone-override-screen-size=800,600 --use-angle=swiftshader-webgl

systemd+ 3724010 3723984  0 May20 ?        00:04:29 /home/pptruser/.cache/puppeteer/chrome/linux-124.0.6367.91/chrome-linux64/chrome --type=gpu-process --disable-dev-shm-usage --disable-breakpad --headless=new --ozone-platform=headless --use-angle=swiftshader-webgl --crashpad-handler-pid=21 --enable-crash-reporter=, --noerrdialogs --user-data-dir=/tmp/puppeteer_dev_chrome_profile-tgOl5j --change-stack-guard-on-fork=enable --gpu-preferences=WAAAAAAAAAAgAAAMAAAAAAAAAAAAAAAAAABgAAIAAAA4AAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAYAAAAAAAAAA

systemd+ 3724011 3723976  0 May20 ?        00:05:18 /home/pptruser/.cache/puppeteer/chrome/linux-124.0.6367.91/chrome-linux64/chrome --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=network --disable-dev-shm-usage --use-angle=swiftshader-webgl --mute-audio --crashpad-handler-pid=21 --enable-crash-reporter=, --noerrdialogs --user-data-dir=/tmp/puppeteer_dev_chrome_profile-tgOl5j --change-stack-guard-on-fork=enable --shared-files=network_parent_dirs_pipe:100,v8_context_snapshot_data:101 --metrics-shmem-handle=4,i,12504822752596826038,3651189851673974261,524288 --field-trial-handle=3,i,15352545869860866567,8243237450854847176,262144 --enable-features=PdfOopif --disable-features=AcceptCHFrame,IsolateSandboxedIframes,MediaRouter,OptimizationHints,PaintHolding,ProcessPerSiteUpToMainFrameThreshold,Translate --variations-seed-version

systemd+ 3724030 3724011  0 May20 ?        00:00:00 /home/pptruser/.cache/puppeteer/chrome/linux-124.0.6367.91/chrome-linux64/chrome --type=broker

systemd+ 3724043 3723989  0 May20 ?        00:03:06 /home/pptruser/.cache/puppeteer/chrome/linux-124.0.6367.91/chrome-linux64/chrome --type=utility --utility-sub-type=storage.mojom.StorageService --lang=en-US --service-sandbox-type=utility --disable-dev-shm-usage --use-angle=swiftshader-webgl --mute-audio --crashpad-handler-pid=21 --enable-crash-reporter=, --noerrdialogs --user-data-dir=/tmp/puppeteer_dev_chrome_profile-tgOl5j --change-stack-guard-on-fork=enable --shared-files=v8_context_snapshot_data:100 --metrics-shmem-handle=4,i,8964585178338913273,9137652200785005769,5242
```

### Puppeteer version

20.8.1

### Node version

20.9.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Linux

**Comment by OrKoN** [comment] 2024-07-30 11:39
@zhuzaiye are you running using the init process? e.g., using `--init` flag in docker run?

**Comment by OrKoN** [comment] 2024-07-30 11:41
I see that you use it when running bash but it does not look like you use it when running the final container.

**Comment by zhuzaiye** [comment] 2024-07-30 11:55
> @zhuzaiye are you running using the init process? e.g., using `--init` flag in docker run?

Yes, the follwing is my docker run comand:

```
sudo docker run --name ExportMonitor --restart always --init --cap-add=SYS_ADMIN -d export-pdf-monitor:v1.0.0
```

> export-pdf-monitor:v1.0.0 is my rebuild image using puppeteer.

**Comment by OrKoN** [comment] 2024-07-30 11:58
do you also see this with the base image alone?

**Comment by zhuzaiye** [comment] 2024-07-30 12:06
> I see that you use it when running bash but it does not look like you use it when running the final container.

@OrKoN 

```
sudo docker run --name puppeteerbase  --init --cap-add=SYS_ADMIN -ti ghcr.io/puppeteer/puppeteer:latest bash
npm insall adm-zip@^0.5.12 aws-sdk@^2.1614.0 mysql@^2.18.1 pdf-lib@^1.17.1

sudo docker commit -a "xxxx@xxxx.com" -m "puppeteer for pdf" puppeteerbase 123.dkr.ecr.xxxx.amazonaws.com/puppeteer:v1.0.0
sudo docker push 123.dkr.ecr.xxx.amazonaws.com/puppeteer:v1.0.0
```

You mean the reason is `sudo docker run --name puppeteerbase  --init --cap-add=SYS_ADMIN -ti ghcr.io/puppeteer/puppeteer:latest bash`, where I reworked the original image `ghcr.io/puppeteer/puppeteer:latest` through bash command, so that when I run the reworked  docker image `puppeteer:v1.0.0`, the zombie or orpaned chrome processes occur.

**Comment by OrKoN** [comment] 2024-07-30 12:16
I mean: do you get zombie processes if you run `docker run -i --init --cap-add=SYS_ADMIN --rm ghcr.io/puppeteer/puppeteer:latest node -e "$(cat path/to/script.js)"` with path/to/script.js pointing to a Puppeteer only script that launches and closes a browser?

**Comment by OrKoN** [comment] 2024-07-30 12:50
So I am unable to reproduce with:

```
docker run -i --init --cap-add=SYS_ADMIN --rm ghcr.io/puppeteer/puppeteer:latest node -e "$(cat test.cjs)"
```

and `test.cjs` being:

```
const puppeteer = require('puppeteer')

async function main() {
  const browser = await puppeteer.launch();

  try {
    const page = await browser.newPage();

    await page.goto('https://example.com');

    await page.pdf({
      path: 'test.pdf'
    });
  } finally {
    await browser.close();
  }
}

main().then(() => {
  console.log("done");
  return new Promise(resolve => setTimeout(resolve, 100000));
});
```

After the browser is closed and the done is printed, there are not Chrome processes left.

**Comment by zhuzaiye** [comment] 2024-07-31 01:20
> docker run -i --init --cap-add=SYS_ADMIN --rm ghcr.io/puppeteer/puppeteer:latest node -e "$(cat path/to/script.js)"

@OrKoN 
Thank you very much!

I try it yesterevening again, no recurrence. so I try to stop the reworked container and restrat it, even no pdf generation operation, there's still a lot Chrome processes here.

For example:
![image](https://github.com/user-attachments/assets/98e9c28b-475d-4e00-89b1-556db54bdf66)

the main script:

```
async function main() {
    const browser = await puppeteer.launch({ headless: true });
    try {
        while (true) {
            const tasks = await executeSQL(getExportTaskSQL);
            if (tasks.length === 0) {
                await new Promise(resolve => setTimeout(resolve, 5000));
                console.log(">>> stop 5 second, and then loop again");
                continue;
            }

            console.log(">>> process cluster tasks start");
            try {
                await processExportTasks(tasks, browser);
            } catch (error) {
                console.error('Error in processExportTasks:', error);
            }
            console.log("<<< process cluster tasks end");
        }
    } catch (error) {
        console.error('Error in main loop:', error);
    } finally {
        await browser.close();
        console.log(">>> browser closed");
    }
}

// Run the main function
main().catch(error => {
    console.error('Error in main:', error);
});

//using page to gen pdf file
async function htmlToPdf(htmlS3Url, zipDir, fileName, browser) {
    const pdfPath = `${zipDir}/${fileName}.pdf`;
    const page = await browser.newPage();
    try {
        await page.goto(htmlS3Url, { waitUntil: 'networkidle2' });
        await page.pdf({ path: pdfPath, format: 'A4', printBackground: true });  // preferCSSPageSize: true, margin: {} 
        return pdfPath; 
    } catch (error) {
        console.error("Error converting HTML to PDF:", error);
        return '';
    }
}
```

I think the following reasons:
1. using `ghcr.io/puppeteer/puppeteer:latest` reconstruct puppeteer image has problem
2. my pdf generation program causes this problem after the reconstruct docker image starts
3. puppeteer's page and  browser  are not closed properly

the next test step:
1. In current mirror, check and fix my pdf script, make sure that each page and browser is properly closed
2. using `https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile` restruct my puppeteer docker image, then run my pdf process script

If anything happens, I will give you feedback in time.

**Comment by OrKoN** [comment] 2024-07-31 06:15
Alright, I am gonna close the issue as it does not look like the issue with Puppeteer itself though. If docker kills the processes when you run "docker restart", I would expect the Docker's init process to kill the child processes too (but I am no expert in Docker). Another way would be to listen to sigkill/sigint signals in your node app and make sure to call browser.close() on those.

**Closed as not planned by OrKoN** 2024-07-31 06:15 UTC
Labels: needs-feedback, not-reproducible

**Comment by zhuzaiye** [comment] 2024-07-31 06:54
> Alright, I am gonna close the issue as it does not look like the issue with Puppeteer itself though. If docker kills the processes when you run "docker restart", I would expect the Docker's init process to kill the child processes too (but I am no expert in Docker). Another way would be to listen to sigkill/sigint signals in your node app and make sure to call browser.close() on those.

@OrKoN 

Thanks for your patience!

the issue is caused by my codes, not with Puppeteer itself  and the restruct docker image.

The reason is: 

I want to save time on starting the Browser, so when I start main.js on docker, I start a global browser firstly. Like this:

```
async function main() {
    // here, start a global browser when start docker.
    const browser = await puppeteer.launch({ headless: true });
    try {
        while (true) {
            const tasks = await executeSQL(getExportTaskSQL);
            if (tasks.length === 0) {
                await new Promise(resolve => setTimeout(resolve, 5000));
                console.log(">>> stop 5 second, and then loop again");
                continue;
            }

            console.log(">>> process cluster tasks start");
            try {
                await processExportTasks(tasks, browser);
            } catch (error) {
                console.error('Error in processExportTasks:', error);
            }
            console.log("<<< process cluster tasks end");
        }
    } catch (error) {
        console.error('Error in main loop:', error);
    } finally {
        await browser.close();
        console.log(">>> browser closed");
    }
}
```

This will triggers chrome's initialization process when start my restruct puppetter image.
At the same time, if the pdf is generated, the page is not closed, At the same time, if the page is not closed when the pdf is generated, these seemingly zombie processes will be more and more.

so, I fix my code, the following:

```
// html to pdf using Page
async function htmlToPdf(htmlS3Url, pdfPath, browser) {
    const start = performance.now();
    const page = await browser.newPage();
    const end = performance.now();
    console.log(`page execution time: ${end - start} milliseconds`);
    try {
        await page.goto(htmlS3Url, { waitUntil: 'networkidle2' });
        await page.pdf({ path: pdfPath, format: 'A4', printBackground: true });  // preferCSSPageSize: true, margin: {} 
    } catch (error) {
        console.error("Error converting HTML to PDF:", error);
    } finally {
        // ensure page must be closed 
        page.close();
        console.log("chrome page closed");
    }
}

// start one Browser when one cluster of tasks
async function processExportTasks(tasks) {
    const start = performance.now();
    const browser = await puppeteer.launch({ headless: true });
    const end = performance.now();
    console.log(`Browser execution time: ${end - start} milliseconds`);
    try {
       .....
      htmlToPdf(browser);
       .....
    } finally {
        // ensure browser must be closed 
        await browser.close();
        console.log("chrome browser closed");
    }
```

When update the main.js in docker, then restart the docker, these chrome processes don't appear.
![image](https://github.com/user-attachments/assets/a3d7e048-c6a4-4a68-a078-9cda654551ee)

My understanding is as follows:
The browser and page must be able to be closed, otherwise a zombie process like this will occur.
But I don't know if that's correct.

Write at the end:
Each time a new pdf is generated, the browser needs to be restarted, and the time to start the browser exists in two cases:
1. If the two tasks are executed very close to each other, the browser takes 1-2 seconds on average to start
![Image_CH0T-4JOV-6PI0-SPE3](https://github.com/user-attachments/assets/170d6bb0-c413-4b9f-aa1b-353587311215)
2. If the time between the two tasks is long, the browser takes longer than 15 seconds to start
![Image_CH0T-43HM-LDE0-SPE3](https://github.com/user-attachments/assets/b74a4427-9a57-4e5f-b043-ccc0a6672193)

How to shorten browser startup time in docker?
