### ISSUE TITLE
Failed to create a message-only window

### ISSUE THREAD

**Issue by Runedia** [puppeteer/puppeteer#5892] opened 2020-05-19 00:44 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.0.4
* Platform / OS version: Win 10 1909 korean, RAM: 32gb 
* URLs (if applicable):
* Node.js version: v10.20.1

**What steps will reproduce the problem?**

Hello
Puppeteer is in use in the operating environment.

The following error occurs when the usage of the puppeteer increases.

Up to 50 at a time works without a problem, but sometimes more than 100 causes problems.

I would appreciate it if you could tell me what kind of phenomenon the error is caused by.

-Google Translator-

```javascript
        // headless
        ret.browser = await puppeteer.launch({
            ignoreHTTPSErrors: true, // ssl error disable
            headless: true, // process.env['DISPLAY'] = ':0'; in index.js, xorg running.
            devtools: false, // not needed so far, we can see websocket frames and xhr responses without that.
            defaultViewport: {
                //--window-size in args
                width: 400,
                height: 300,
                hasTouch: false,
                isMobile: false,
            },
            // args document https://peter.sh/experiments/chromium-command-line-switches/
            args: [
                '--no-sandbox', // 보안 사용 안함
                '--disable-setuid-sandbox', // 샌드박스 setuid 미사용? (Linux only)
                '--disable-dev-shm-usage', // 공유 메모리 사용 안함?
                '--disable-accelerated-2d-canvas', // gpu 가속 2d 캔버스 사용 안함
                '--no-first-run', // 처음 실행인지 확인 무시 (초기 안내 페이지 말하는듯)
                '--no-zygote', // zygote 프로세스 사용 안함
                '--disable-gpu', // GPU 하드웨어 가속 사용 안 함
                '--disable-extensions', // 확장 프로그램 사용 안함
            ],
        })
```

ERROR LOG

Error: Failed to launch the browser process!
[0519/040003.924:ERROR:message_window.cc(110)] Failed to create a message-only window: �޸� ���ҽ��� �����Ͽ� �� ������ ó���� �� �����ϴ�. (0x8)
[0519/040003.928:FATAL:window_impl.cc(138)] Check failed: atom. 0
Backtrace:
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFEC84D16E2+9913346]
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFEC8451342+9388130]
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFEC845E1AB+9440971]
	GetHandleVerifier [0x00007FFEC8F2A1FD+803261]
	GetHandleVerifier [0x00007FFEC8F2A744+804612]
	GetHandleVerifier [0x00007FFEC8F2A4CE+803982]
	GetHandleVerifier [0x00007FFEC8F20BF6+764854]
	GetHandleVerifier [0x00007FFEC8F20999+764249]
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFEC86BCA62+11925378]
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFEC86BA36A+11915402]
	ovly_debug_event [0x00007FFEC6C9DAB4+12039924]
	ovly_debug_event [0x00007FFEC6FFD7CF+15578127]
	ovly_debug_event [0x00007FFEC6C9D5BC+12038652]
	ovly_debug_event [0x00007FFEC6CA03A5+12050405]
	IsSandboxedProcess [0x00007FFEC8D1FC30+3747724]
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFEC83BCC4B+8780139]
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFEC83BD858+8783224]
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFEC83BD564+8782468]
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFEC83ED0C2+8977890]
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFEC83BCBE4+8780036]
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFEC83EC50C+8974892]
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFEC83EC3D4+8974580]
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFEC83EC1DF+8974079]
	ChromeMain [0x00007FFEC61211EB+339]
	Ordinal0 [0x00007FF7C6A42938+10552]
	Ordinal0 [0x00007FF7C6A418DA+6362]
	GetHandleVerifier [0x00007FF7C6B4DFF2+695666]
	BaseThreadInitThunk [0x00007FFF17C37BD4+20]
	RtlUserThreadStart [0x00007FFF1934CE51+33]

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

**Comment by kevinvenclovas** [comment] 2021-03-03 15:53
Same issue do you have a fix for this?

**Closed as completed** 2022-07-24 17:01 UTC
Labels: unconfirmed

**Comment by justintoth** [comment] 2023-02-08 13:18
@Runedia @kevinvenclovas Did either of you figure out the cause of this, or find a resolution? I'm just running into this issue...

**Comment by EsaxCO** [comment] 2023-05-15 10:41
Same issue

**Comment by KoalaBear84** [comment] 2025-01-09 05:29
OK, other ticket is closed.

**Conclusion:**
It's a Windows only issue (because only Windows has [Atom Tables](https://learn.microsoft.com/en-us/windows/win32/dataxchg/about-atom-tables) which is used through `RegisterClassEx`), and it cannot be solved in any other way than to restart the computer/server (or maybe the user session)..

But because the server is SAAS, I cannot do anything about it.
