### ISSUE TITLE
Puppeteer firefox promise sometimes returns array, sometimes object

### ISSUE THREAD

**Issue by jan0991** [puppeteer/puppeteer#4295] opened 2019-04-17 02:37 UTC
My code that I execute inside browser:
```
const getArticles = async (page) => {
    return await page.evaluate(() => {
        ...
        return Promise.resolve(formated.filter(x => x)) // formated is a normal array
    });
}
```

I have to call it like this:

```
        let newArticles = await getArticles(page)
         if(!Array.isArray(newArticles)) {
            newArticles = newArticles._v
        }
```
It seems very random. Sometimes it returns an array, sometimes object. With chrome, it was array every single time. Any ideas?

**Comment by aslushnikov** [comment] 2019-04-19 08:14
@jan0991 did it resolve itself?

**Comment by jan0991** [comment] 2019-04-22 23:36
I thought so, but nope. Still does this randomly.

**Comment by aslushnikov** [comment] 2019-04-23 06:03
@jan0991 so can you please share a small script that will reproduce this?

**Comment by mjzffr** [comment] 2020-01-13 16:19
Thanks for the report. I'm closing this issue since the experimental `puppeteer-firefox` package is no longer maintained. A replacement will be available
later this year. You can learn more about Mozilla's work on this at https://wiki.mozilla.org/Remote

See also https://github.com/puppeteer/puppeteer/pull/5137

**Closed as completed by mjzffr** 2020-01-13 16:19 UTC
