### ISSUE TITLE
async function inside evaluate fails

### ISSUE THREAD

**Issue by bhoomit** [puppeteer/puppeteer#1665] opened 2017-12-26 18:20 UTC
#### Code
```
await page.evaluate(async () => {
    console.log('1')
})
```
#### Error
```
(node:66796) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Evaluation failed: ReferenceError: fn is not defined
    at <anonymous>:1:26
```

**Comment by vsemozhetbyt** [comment] 2017-12-26 21:28
I cannot reproduce with this code and puppeteer v1.0.0-rc on Windows 7 x64:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    await page.goto('https://example.org/');

    await page.evaluate(async () => {
      console.log('1');
    });

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
Can you provide your configuration and a runnable code fragment with this issue?

**Comment by bhoomit** [comment] 2017-12-27 03:15
puppeteer v1.0.0-rc ( git://github.com/GoogleChrome/puppeteer.git#fc2fc0d ) centos-release-7-3.1611.el7.centos.x86_64 

```
const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
    const page = await browser.newPage();

    await page.goto('https://example.org/');

    await page.evaluate(async () => {
      console.log('1');
    });

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

```
Error: Evaluation failed: ReferenceError: fn is not defined
    at <anonymous>:1:26
    at ExecutionContext.evaluateHandle (...node_modules/puppeteer/lib/ExecutionContext.js:70:13)
    at <anonymous>
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:228:7)
```

**Comment by vsemozhetbyt** [comment] 2017-12-27 08:07
Can anybody reproduce on centos?

**Comment by bhoomit** [comment] 2017-12-27 09:51
I'm able to reproduce the same on Mac OS Sierra

**Comment by aslushnikov** [comment] 2017-12-28 04:06
@bhoomit what's your node.js version and what version of chromium do you run with puppeteer?

**Comment by JoelEinbinder** [comment] 2017-12-28 07:15
Are you transforming your code with babel? The babel async function code isn't compatible with Puppeteer. We call `function.toString` and send your code into Chromium, but babel messes with that and we end up sending an incomplete string. You can get around this by using template strings instead of functions.
```js
await page.evaluate(`(async() => {
   console.log('1');
})()`);

**Comment by yujiosaka** [comment] 2017-12-30 11:33
@JoelEinbinder 
It's good to know. May I make a PR to add the message to the docs not to use transpiler?

**Comment by aslushnikov** [comment] 2018-01-04 07:43
@yujiosaka not sure what would be the good place in the docs. There's been quite a bit discussion on babel on the bugtracker, so it should be searchable now.

Speculatively closing this since the issue seems to be related to transpilation.

**Closed as completed by aslushnikov** 2018-01-04 07:43 UTC

**Comment by Jun711** [comment] 2018-03-02 07:49
@JoelEinbinder, just wonder if 1 from console log within a template literal will be printed? 
In my code snippet below, I have 2 console logs but I can see browser version in my terminal from `await browser.version()`

I found this [page.evaluate documentation ](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args), so, it seems that I have to return a value from evaluate to be able to console log?

```
console.log(await page.evaluate('1 + 2')); // prints "3"
const x = 10;
console.log(await page.evaluate(`1 + ${x}`)); // prints "11"
```

```
describe(('window should contain fnA'), () => {
  let browser;
  // puppeteer options
  const puppeteerOpts = {
    headless: true,
    slowMo: 100,
    timeout: 10000,
    // dumpio: true,
  };
  before(async () => {
    browser = await puppeteer.launch(puppeteerOpts);
  });

  after(async () => {
    await browser.close();
  });
  it('should evaluate fnA', async () => {
    console.log(await browser.version());
    const page = await browser.newPage();
    await page.goto('http://localhost:8000');
    expect(await page.title()).to.equal('pageTitle');
    await page.evaluate(`(async () => {
      console.log('1');
    })()`);
  }).timeout('15s');
});
```


```
 "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.2.1",
    "babel-loader": "^7.1.2",
    "babel-plugin-istanbul": "^4.1.5",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-register": "^6.26.0",
    "chai": "^4.1.2",
    "commitizen": "^2.9.6",
    "coveralls": "^3.0.0",
    "cross-env": "^5.1.3",
    "cz-conventional-changelog": "^2.1.0",
    "eslint": "^4.17.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.8.0",
    "fetch-mock": "^6.0.0",
    "isomorphic-fetch": "^2.2.1",
    "lodash": "^4.17.5",
    "mocha": "^5.0.0",
    "nyc": "10",
    "puppeteer": "^1.1.1",
    "semantic-release": "^12.4.1",
    "sinon": "^4.3.0",
    "webpack": "^3.11.0",
    "webpack-dev-server": "^2.11.1"
  },
```

**Comment by AlphaCodeZero** [comment] 2018-08-01 04:10
@JoelEinbinder Hi~ How can I pass arguments into template string functions? If I want to test an util object, which has a parseUrl method, I would like to write util.test.js like this:
```javascript
// util.test.js
import assert from 'assert'
import puppeteer from 'puppeteer'
import util from '../src/util'

describe('util.js', () => {
  let browser
  let page
  before(async () => {
    browser = await puppeteer.launch()
    page = await browser.newPage()
  })
  after(async () => {
    await browser.close()
  })
  describe('#parseUrl()', () => {
    it('port should be 8080', async () => {
      const result = await page.evaluate(`((x) => x.parseUrl("https://www.example.com:8080/test?q=1&p=2#you_and_me"))(${util})`)
      assert(result.port === '8080')
    })
  })
})
```
Run this script with `./node_modules/.bin/mocha --require babel-register test/util.test.js`, but the console just says `Error: Evaluation failed: SyntaxError: Unexpected identifier`. How can I solve this?
Thank you in advance.

**Comment by JoelEinbinder** [comment] 2018-08-01 04:13
You can't import something from Node and use it in Chromium. You have to navigate Chromium to a webpage that includes your utility script.

**Comment by cancerberoSgx** [comment] 2018-10-12 15:02
same issue, different error, using TypeScript (not babel). The solution for me was to instruct TypeScript to compile to latest ecma version so no pollyfills / artificial code is generated for async function support, in tsconfig.json file: 

```json
{
  "compilerOptions": {
    "target": "es2018"
  }
}
```

## issue details

While the following works OK: 

```
    let result = await page.evaluate( ()=>{
      return Promise.resolve('hello')
    })
```

the equivalent code using async functions throws the following error:

```
    let result = await page.evaluate(async ()=>{
      return 'hello'
    })
```
Error:
```
  Message:
    Error: Evaluation failed: ReferenceError: __awaiter is not defined
        at __puppeteer_evaluation_script__:1:8
  Stack:
    Error: Evaluation failed: ReferenceError: __awaiter is not defined
        at __puppeteer_evaluation_script__:1:8
        at ExecutionContext.evaluateHandle (/home/sg/git/autumn-leaves/imagemagick-browser/node_modules/puppeteer/lib/ExecutionContext.js:106:13)
        at process._tickCallback (internal/process/next_tick.js:68:7)
        at <Jasmine>
        at ExecutionContext.<anonymous> (/home/sg/git/autumn-leaves/imagemagick-browser/node_modules/puppeteer/lib/helper.js:144:27)
        at ExecutionContext.evaluate (/home/sg/git/autumn-leaves/imagemagick-browser/node_modules/puppeteer/lib/ExecutionContext.js:58:31)
        at ExecutionContext.<anonymous> (/home/sg/git/autumn-leaves/imagemagick-browser/node_modules/puppeteer/lib/helper.js:145:23)
        at Frame.evaluate (
```

**Comment by jtara1** [comment] 2018-10-31 16:54
@JoelEinbinder the fact that `toString()` is called on the 1st arg there should maybe be noted in the docs.

This caused a lot of confusion for me when I tried to use shorthand for defining a func in an object then using that function as the 1st arg in `page.evaluate`

breaks
```
module.exports = {
  scrape() { return document.querySelector('body'); },
}
```
works
```
module.exports = {
  scrape: function () { return document.querySelector('body'); },
}
```
`await page.evaluate(require('./some-file').scrape);`

**Comment by aslushnikov** [comment] 2018-11-01 23:44
@jtara1: we made our serialization logic more clever so that it doesn't bite you next time. We'll update our docs to explain the function serialization.

**Comment by reservce** [comment] 2019-09-19 17:38
> Are you transforming your code with babel? The babel async function code isn't compatible with Puppeteer. We call `function.toString` and send your code into Chromium, but babel messes with that and we end up sending an incomplete string. You can get around this by using template strings instead of functions.
> 
> ```js
> await page.evaluate(`(async() => {
>    console.log('1');
> })()`);
> ```

Hi, I'm trying to use with Echart library to generate and get its based64 image.
```
    await page.addScriptTag({path: __dirname + '/echarts-all.js'});
    await page.setContent(`
        <html><body>
                <div id="chartdiv"></div>
                <script>
                    var myChart = echarts.init(document.getElementById('chartdiv')); 
                    myChart.setOption(option); 
                </script>
            </body>            
        </html>  
  `);
   const base64img = await page.evaluate(`(async() => { myChart.getDataURL(); })()`);
   console.log('base64img', base64img);
```
However the base64img is undefined.
Is there any solution to make it works perfectly with Babel?

**Comment by princefishthrower** [comment] 2020-06-23 16:13
@reservce - This solution works great! But I agree, it's obviously not a true solution (after all, a template string is technically just a string, though it will get eval'ed as actual code...)

As a side question: How did you know to do this, or figure out how to do this?
