### ISSUE TITLE
page.goto timeout on url's that contain # or ? when called repeatedly in a loop

### ISSUE THREAD

**Issue by theoutlander** [puppeteer/puppeteer#1869] opened 2018-01-21 23:18 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: MacOS Sierra 10.12.6
* URLs (if applicable): https://www.microsoft.com
* Node.js version: 8.9.1

**What steps will reproduce the problem?**

I'm writing a simple crawler. 

1. A queue starts with a seed URL

2. We create a page instance that will be reused 
     `const page = await browser.newPage()`

3. We loop through the elements in the queue until queue is empty
         Load URL (using the page instance from #1751 
      `   await page.goto(url)`
        On success, we extract all links and add them to the queue
        Go to beginning of loop

In this simple process, it appears that many of the links start to timeout. A pattern I've noticed with these links is that they contain an anchor tag (#) or a query parameter (?) in the url.

If I were to filter those out OR if I were to create a new page instance before I load each URL, it works. So, there appears to be something with reusing the page object in a loop.

#### Some URL's will fail when:
`reusePageInstance = false`

#### Most URL's will pass when: 
**I state that most URL's will pass because all obvious HREF failures aren't filtered yet.**
`reusePageInstance = true`

#### Code to repro:

```const puppeteer = require('puppeteer')
const reusePageInstance = false; // TOGGLE THIS TO MAKE IT PASS

(async () => {
// I have tried a combination of options here:
// headless
// ignoreHTTPSErrors
// waitUntil (load and networkidle0)
  const browser = await puppeteer.launch({
    headless: false
  })

  let page

  if (!reusePageInstance) {
    page = await browser.newPage()
  }

  let q = ['https://microsoft.com']
  let cache = {}
  let failed = []

  while (q.length > 0) {

    if (failed.length > 10) {
      failed.forEach(url => {
        console.log(url)
      })

      failed = []
      return
    }

    let url = q.shift()

    console.log('Loading Page: ' + url)

    try {
      if (reusePageInstance) {
        page = await browser.newPage()
      }

      await page.goto(url, {
        timeout: 10000
      })
      console.log('Page Loaded')

      console.log('Extracting Links')
      let links = await page.evaluate(() => {
        const anchors = Array.from(document.querySelectorAll('a'))

        let hrefs = anchors.map(anchor => anchor.href)

        hrefs = hrefs.filter(href => href !== '')
        hrefs = hrefs.filter(href => href.toLowerCase().indexOf('mailto:') < 0)
        hrefs = hrefs.filter(href => href.toLowerCase().indexOf('javascript:') < 0)

        return hrefs
      })
        .catch(e => {
          console.error('In evaluate error: ')
          console.error(e)
        })
      console.log('Done extracting links')

      for (let i = 0; i < links.length; i++) {
        if (!cache[links[i]]) {
          cache[links[i]] = true
          q.push(links[i])
        }
      }
      if (reusePageInstance) {
        await page.close()
      }
      console.log('Page closed')
    }
    catch (e) {
      failed.push(url)
      console.log('Page Load Failed')
      console.error(e)
    }

  }

  await browser.close()
})()
``` 

**What is the expected result?**
All URL's are loaded successfully without a timeout

**What happens instead?**
When page object is reused in a loop, some URL's load in the browser, but the page.goto request throws a timeout error. In most cases, these url's have an anchor or url parameter in them (# or ?).

**Comment by ebidel** [comment] 2018-02-08 02:31
It's a known issue that hashs don't cause a navigation. Appears to be a dupe of https://github.com/GoogleChrome/puppeteer/issues/257. Please reopen if you think otherwise.

**Closed as completed by ebidel** 2018-02-08 02:31 UTC

**Comment by dsternlicht** [comment] 2018-03-08 20:21
Hey, I'm not following. Was this issue fixed?
At the moment - I'm using version 1.1.1, and still getting timeouts from urls with hashes.
