### ISSUE TITLE
Wait for navigation (networkidle) even if no new requests are instantiated 

### ISSUE THREAD

**Issue by BkSouX** [puppeteer/puppeteer#945] opened 2017-10-03 07:40 UTC
Hi

I am using the code from #913 to set content and wait for navigation.

```javacript
try {
    await Promise.all([
      page.setContent(html),
      page.waitForNavigation({ waitUntil: 'networkidle' }),
    ]);
  } catch (e) {
    logger.error('Issue setting content');
    throw e;
  }
```

But sometimes, I don't have any new requests in the HTML so it waits a long time before crashing i suppose.
Any idea how I can handle that ?

Thank you

**Comment by aslushnikov** [comment] 2017-10-04 21:02
That's today's limitation of the system, should be addressed with the #728 being fixed.
As a workaround, i'd suggest navigating to data URL:

```js
await page.goto('data:text/html,' + html, {waitUntil: 'networkidle'});
```

Closing as a dupe of #728.

**Closed as completed by aslushnikov** 2017-10-04 21:02 UTC
