### ISSUE TITLE
cannot launch in headless mode when userDataDir set

### ISSUE THREAD

**Issue by muratgu** [puppeteer/puppeteer#4681] opened 2019-07-07 18:15 UTC
## Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.1
* Platform / OS version: Win10
* URLs (if applicable):
* Node.js version: 9.4.0

**What steps will reproduce the problem?**

```
    const puppeteer = require('puppeteer');
    const browser = await puppeteer.launch({ 
        userDataDir: './data',
        headless: true,
    });
    console.log('browser launched'); // never reaches here
```

```
    const puppeteer = require('puppeteer');
    const browser = await puppeteer.launch({ 
        //userDataDir: './data',
        headless: true,
    });
    console.log('browser launched'); // OK
```

```
    const puppeteer = require('puppeteer');
    const browser = await puppeteer.launch({ 
        userDataDir: './data',
        headless: false,
    });
    console.log('browser launched'); // OK
```

**Comment by vsemozhetbyt** [comment] 2019-07-07 18:19
See also https://github.com/GoogleChrome/puppeteer/issues/3453

**Comment by aslushnikov** [comment] 2019-07-15 02:10
Looks like a dupe of #3453.

**Closed as completed by aslushnikov** 2019-07-15 02:10 UTC
