### ISSUE TITLE
page.title() promise does not resolve or reject after `Execution context was destroyed`

### ISSUE THREAD

**Issue by TrevorSundberg** [puppeteer/puppeteer#4113] opened 2019-03-05 01:36 UTC
* Puppeteer version: 1.12.2
* Platform / OS version: Ubuntu 18.04.2 LTS
* Node.js version: v11.10.1

**What steps will reproduce the problem?**
We noticed that eventually the title promises would stop returning (no resolve or rejection) after the error `Execution context was destroyed, most likely because of a navigation.` is thrown on ExecutionContext. Note that this doesn't repro instantly and can sometimes take several exceptions before it occurs. Once it occurs, titles or exceptions stop printing and all you'll see is the dashes. You can play with the interval timing below to get the issue to repro (note that if you make it too low, you'll hit the max event emitters issue, which can be raised if needed).

```javascript
const puppeteer = require('puppeteer')

async function main()
{
    const browser = await puppeteer.launch()
    const page = await browser.newPage()

    let counter = 0

    setInterval(() => {
        console.log('-----------------------')
        page.goto(`https://google.com/?test=${counter++}`)
        page.title().then(console.log, console.error)
    }, 200)
}
main()
```

Interestingly, when we use `page.evaluate(() => document.title)` it always appears to work this behavior never occurs. My only explanation is that it has something to do with using the `_mainWorld` vs the `_secondaryWorld` in FrameManager.

**What is the expected result?**
`page.title()` continues to evaluate the title, or at least throw an exception / reject.

**What happens instead?**
`page.title()` completely stops working (no future promises will reject or resolve).

**Comment by ryo-hisano** [comment] 2019-06-09 06:35
Hi!TrevorSundberg.
You can achieve setTimeout by using Promise.

```javascript
const puppeteer = require('puppeteer')

async function main()
{
	const browser = await puppeteer.launch()
	const page = await browser.newPage()
	const delay = d => new Promise(r => setTimeout(r, d))

	async function timer(counter = 0) {
		await delay(200)
		console.log('-----------------------')
		await page.goto(`https://google.com/?test=${counter}`)
		await page.title().then(console.log, console.error)
		return timer(counter + 1)
	}

	timer().then(console.log)
}
main()
```

**Comment by aslushnikov** [comment] 2019-06-09 06:52
@TrevorSundberg we had a few issues with secondary words - but many of those were fixed. I can't repro this on 1.17.0.

Most likely this is a dupe of #4011 that has been fixed.

**Closed as completed by aslushnikov** 2019-06-09 06:52 UTC
