### ISSUE TITLE
page.goto(url) throws Error: Failed to navigate when { headless: true } but not when { headless: false }

### ISSUE THREAD

**Issue by hparadiz** [puppeteer/puppeteer#963] opened 2017-10-05 19:03 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0-alpha and 0.11.0
* Platform / OS version: CentOS 7.4, Ubuntu 17.04, OS X 10.12.6
* URLs (if applicable): https://xocsp.ccp.xcal.tv/comcastSP/protected/auth?tenant=a2t_uuid&continue=https://streaminder.xcal.tv/sessions/create_sso&partner-id=comcast

**What steps will reproduce the problem?**
The error is reproducible with https://try-puppeteer.appspot.com/

```js
var url = "https://xocsp.ccp.xcal.tv/comcastSP/protected/auth?tenant=a2t_uuid&continue=https://streaminder.xcal.tv/sessions/create_sso&partner-id=comcast";
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
	args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });
  const page = await browser.newPage();
  await page.goto(url);
  await page.screenshot({path: 'example.png'});
  await browser.close();
})();
```

**What is the expected result?**
Redirect to SSO ADFS login page

**What happens instead?**
`Failed to navigate: https://xocsp.ccp.xcal.tv/comcastSP/protected/auth?tenant=a2t_uuid&continue=https://streaminder.xcal.tv/sessions/create_sso&partner-id=comcast`

**Comment by forclan** [comment] 2017-10-08 15:12
This error throws in function `Page.goto`
```
    if (this._frameManager.isMainFrameLoadingFailed())
      throw new Error('Failed to navigate: ' + url);
```

`this._frameManager.isMainFrameLoadingFailed()`
```
  isMainFrameLoadingFailed() {
    return !!this._mainFrame._loadingFailed;
  }
```

`_loadingFailed` is set in `FrameManager._onFrameNavigated` which calls `frame._navigated`
```
  _navigated(framePayload) {
    this._name = framePayload.name;
    this._url = framePayload.url;
    this._loadingFailed = !!framePayload.unreachableUrl;
  }
```

`framePayload` have the property `unreachableUrl` which causes the error.

and `framePayload`  is received in websocket connection, sample : 
```
{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"f24a8eed-2339-4ff8-b018-bbbf2d311241:1","message":"{\"method\":\"Page.frameNavigated\",\"params\":{\"frame\":{\"id\":\"30388.1\",\"loaderId\":\"30388.3\",\"url\":\"chrome-error://chromewebdata/\",\"securityOrigin\":\"://\",\"mimeType\":\"text/html\",\"unreachableUrl\":\"https://sts.comcast.com/adfs/ls/?SAMLRequest=nZRBb9pAEIXv%2BRXW3vFiYwqsAImCqiKlrRNoD70ty7hZab3r7owJ%2FffddUhC2ogDJ0vj8bz3vhl5irI2jVi09GDv4XcLSElyrI1F0b2ZsdZb4SRqFFbWgIKU2Cy%2B3Io87YvGO3LKGXazXs0Y5pnKi0m2k3lRjapCqokcVB92alwNR%2FlgOBkDFGqQQ58lP8CjdnbGwhiWrBFbWFskaSmU%2Btmol%2FV7%2FfE2K0QxEsP8J0tWwZq2krqvHogaFJwjYapcrSRSfHK5r5Ab5Cz55LyCLtaMkW8hipQSUR9gxippMFTKk%2F2P2u61%2FXU56%2B6pCcXn7bbsld82W5YsEMFHR0tnsa3Bb8AftILv97evHo9OYZMq1aRHJU1KBzEuigF3DQQR%2Fvwlr4HkwmiJHJuMzW%2Bmkb%2FoyPizjVw2KZ8NsfmZfBr1XylN%2Bdnok1AjvoZh61XpjFZ%2FrjmBSLyWdLk7VvS%2BV3Wtgry0qMESSzZl1L9rpdGVBv%2BG3j%2F2A3Zj3OPSgyQ4LXf%2BlOltipdop8OGfXcPgTjBka6JuHR1I73GeIJwlIqCcMfyfPDShC3cQ3XN0i62KaHi6FCOh%2Fzo%2FD4eMKgQbBtJNs7Tabfv%2BXlh9C6OAIv%2F%2Fy%2BY%2FwU%3D&RelayState=s21c2491ba24f7f4ac9a3f6bc8f5723598ee4c32e0\"}}}","targetId":"f24a8eed-2339-4ff8-b018-bbbf2d311241"}}�~Z{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"f24a8eed-2339-4ff8-b018-bbbf2d311241:1","message":"{\"method\":\"Runtime.executionContextCreated\",\"params\":{\"context\":{\"id\":3,\"origin\":\"://\",\"name\":\"\",\"auxData\":{\"isDefault\":true,\"frameId\":\"30388.1\"}}}}","targetId":"f24a8eed-2339-4ff8-b018-bbbf2d311241"}}�~�{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"f24a8eed-2339-4ff8-b018-bbbf2d311241:1","message":"{\"method\":\"Page.loadEventFired\",\"params\":{\"timestamp\":9534.515639}}","targetId":"f24a8eed-2339-4ff8-b018-bbbf2d311241"}}�~	{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"f24a8eed-2339-4ff8-b018-bbbf2d311241:1","message":"{\"method\":\"Page.lifecycleEvent\",\"params\":{\"name\":\"load\",\"timestamp\":9534.515639}}","targetId":"f24a8eed-2339-4ff8-b018-bbbf2d311241"}}�~�{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"f24a8eed-2339-4ff8-b018-bbbf2d311241:1","message":"{\"method\":\"Page.frameStoppedLoading\",\"params\":{\"frameId\":\"30388.1\"}}","targetId":"f24a8eed-2339-4ff8-b018-bbbf2d311241"}}�~�{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"f24a8eed-2339-4ff8-b018-bbbf2d311241:1","message":"{\"method\":\"Page.domContentEventFired\",\"params\":{\"timestamp\":9534.515898}}","targetId":"f24a8eed-2339-4ff8-b018-bbbf2d311241"}}�~{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"f24a8eed-2339-4ff8-b018-bbbf2d311241:1","message":"{\"method\":\"Page.lifecycleEvent\",\"params\":{\"name\":\"DOMContentLoaded\",\"timestamp\":9534.515898}}","targetId":"f24a8eed-2339-4ff8-b018-bbbf2d311241"}}
```

It seems like chrome can not load [page](https://sts.comcast.com/adfs/ls/?SAMLRequest=nZRBb9pAEIXv%2BRXW3vFiYwqsAImCqiKlrRNoD70ty7hZab3r7owJ%2FffddUhC2ogDJ0vj8bz3vhl5irI2jVi09GDv4XcLSElyrI1F0b2ZsdZb4SRqFFbWgIKU2Cy%2B3Io87YvGO3LKGXazXs0Y5pnKi0m2k3lRjapCqokcVB92alwNR%2FlgOBkDFGqQQ58lP8CjdnbGwhiWrBFbWFskaSmU%2Btmol%2FV7%2FfE2K0QxEsP8J0tWwZq2krqvHogaFJwjYapcrSRSfHK5r5Ab5Cz55LyCLtaMkW8hipQSUR9gxippMFTKk%2F2P2u61%2FXU56%2B6pCcXn7bbsld82W5YsEMFHR0tnsa3Bb8AftILv97evHo9OYZMq1aRHJU1KBzEuigF3DQQR%2Fvwlr4HkwmiJHJuMzW%2Bmkb%2FoyPizjVw2KZ8NsfmZfBr1XylN%2Bdnok1AjvoZh61XpjFZ%2FrjmBSLyWdLk7VvS%2BV3Wtgry0qMESSzZl1L9rpdGVBv%2BG3j%2F2A3Zj3OPSgyQ4LXf%2BlOltipdop8OGfXcPgTjBka6JuHR1I73GeIJwlIqCcMfyfPDShC3cQ3XN0i62KaHi6FCOh%2Fzo%2FD4eMKgQbBtJNs7Tabfv%2BXlh9C6OAIv%2F%2Fy%2BY%2FwU%3D&RelayState=s21c2491ba24f7f4ac9a3f6bc8f5723598ee4c32e0) in headless mode

**Comment by akauppi** [comment] 2017-10-11 12:07
This sounds similar to the issues I have had, where redirects caused by an authentication end point cause different behaviour if I'm running headless or not.

Please ask for more, if you want to know the details. I'll open a separate issue on that one (not sure if these are related).

**Comment by ramgkn** [comment] 2017-10-24 08:46
Have similar issue with Chrome Driver 2.33 Selenium 3.5 and C# code base.

script working fine with headless false but not navigating to webpages with headless true.

Code Snippit added below:

 ChromeOptions chromeOptions = new ChromeOptions();

chromeOptions.AddArguments("--no-sandbox", "--disable-gpu", "--headless");

chromeOptions.AddArgument("window-size=1920,1080");

ChromeDriverService service = ChromeDriverService.CreateDefaultService();

service.HideCommandPromptWindow = false;

IWebDriver _driver = new ChromeDriver(service, chromeOptions);

Any help would be appreciated.

**Comment by martintuk** [comment] 2017-12-03 23:44
Hi @akauppi, I'm having the same problem you mention. I'm reproducing an OAuth flow, and it works fine with {headless: false} but redirects are not following when {headless:true}.

Have you managed to make it work somehow? Did you finally open an issue for this?

Thanks,
Martin

**Comment by ramgkn** [comment] 2017-12-04 05:34
Hi

I opened an issue..  This is something  to do with the headless mode source
code.


Was not able to figure out for chrome. So  gave Firefox headless option..
Which the client  was happy  with.

Regards
Ram

**Comment by DallanQ** [comment] 2018-01-04 22:16
I appear to be having a similar problem where redirects work with headless: false, but not with headless: true.

**Comment by yujiosaka** [comment] 2018-01-05 20:39
I can reproduce this problem without puppeteer:

```
const chromeLauncher = require('chrome-launcher');
const CDP = require('chrome-remote-interface');

const TARGET_URL = 'https://xocsp.ccp.xcal.tv/comcastSP/protected/auth?tenant=a2t_uuid&continue=https://streaminder.xcal.tv/sessions/create_sso&partner-id=comcast';

async function main() {
  const chrome = await chromeLauncher.launch({
    // You can comment out this line to make things work
    // chromeFlags: ['--disable-gpu', '--headless'],
  });
  CDP({ port: chrome.port }, async (client) => {
    const { Network, Page } = client;
    await Promise.all([Network.enable(), Page.enable()]);
    Network.loadingFailed(event => void console.log(event));
    await Page.navigate({url: TARGET_URL});
    await Page.loadEventFired();
    await client.close();
    await chrome.kill();
  });
}

main();
```

It's a chromium's bug, so it should be reported upstream.
[this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=757181) looks similar to this problem, but I'm not sure yet.

I'll create an issue if it looks ok.

**Comment by yujiosaka** [comment] 2018-01-05 20:57
I confirmed that this is exactly the same problem with [this](https://bugs.chromium.org/p/chromium/issues/detail?id=757181).

[This URL](https://xocsp.ccp.xcal.tv/comcastSP/protected/auth?tenant=a2t_uuid&continue=https://streaminder.xcal.tv/sessions/create_sso&partner-id=comcast) leads to a certificate error, and headless chrome handles SSL errors differently from headful.

So I commented and voted for the [chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=757181#c30), and your vote may help increasing the priority.

**Comment by caseq** [comment] 2018-04-05 17:13
This is now fixed upstream:  https://chromium.googlesource.com/chromium/src.git/+/c8f0691b18dc5d941d5b6b3c67a483da02400670

**Comment by aslushnikov** [comment] 2018-04-07 01:26
@caseq awesome, I confirm this is working on tip-of-tree!

**Closed as completed by aslushnikov** 2018-04-07 01:26 UTC
Labels: upstream
