### ISSUE TITLE
[Bug]: New navigation request was received at LifecycleWatcher

### ISSUE THREAD

**Issue by Moyen75** [puppeteer/puppeteer#8841] opened 2022-08-25 12:23 UTC
### Bug description

Steps to reproduce the problem:

/home/moyen/projects/node/daraz/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:137
    (_a = __classPrivateFieldGet(this, _LifecycleWatcher_navigationResponseReceived, "f")) === null || _a === void 0 ? void 0 : _a.reject(new Error('New navigation request was received'));
                                                                                                                                          ^

Error: New navigation request was received
    at LifecycleWatcher._LifecycleWatcher_onRequest (/home/moyen/projects/node/daraz/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:137:139)
    at /home/moyen/projects/node/daraz/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:68
    at Array.map (<anonymous>)
    at Object.emit (/home/moyen/projects/node/daraz/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at NetworkManager.emit (/home/moyen/projects/node/daraz/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at NetworkManager._NetworkManager_onRequest (/home/moyen/projects/node/daraz/node_modules/puppeteer/lib/cjs/puppeteer/common/NetworkManager.js:312:10)
    at NetworkManager._NetworkManager_onRequestWillBeSent (/home/moyen/projects/node/daraz/node_modules/puppeteer/lib/cjs/puppeteer/common/NetworkManager.js:219:93)
    at /home/moyen/projects/node/daraz/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:68
    at Array.map (<anonymous>)
    at Object.emit (/home/moyen/projects/node/daraz/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)

### Puppeteer version

^16.2.0

### Node.js version

v17.4.0

### npm version

8.3.1

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment] 2022-08-25 19:05
I believe it's a duplicate of https://github.com/puppeteer/puppeteer/issues/8811 The fix is scheduled to be releases in the next release.

**Closed as not planned by OrKoN** 2022-08-25 19:05 UTC

**Comment by Moyen75** [comment] 2022-08-29 08:51
I still get this error. Actually, when using puppeteer with firefox I get this error. I don't get this error when using puppeteer with chrome. In my case, I have to use firefox. so, I need a solution to this.
