### ISSUE TITLE
Project build with Warning and Errors.

### ISSUE THREAD

**Issue by solsos** [puppeteer/puppeteer#1242] opened 2017-11-01 13:59 UTC
I am using the version 0.12.0, But when I build the project, I got the below Warnings and Errors.

WARNING in ./node_modules/puppeteer/node_modules/ws/lib/BufferUtil.js
Module not found: Error: Can't resolve 'bufferutil' in 'C:\<project-path>\node_modules\puppeteer\node_modules\ws\lib'
 @ ./node_modules/puppeteer/node_modules/ws/lib/BufferUtil.js 35:21-42
 @ ./node_modules/puppeteer/node_modules/ws/lib/Receiver.js
 @ ./node_modules/puppeteer/node_modules/ws/index.js
 @ ./node_modules/puppeteer/lib/Connection.js
 @ ./node_modules/puppeteer/lib/Launcher.js
 @ ./node_modules/puppeteer/lib/Puppeteer.js
 @ ./node_modules/puppeteer ^\.\/.*\/Puppeteer$
 @ ./node_modules/puppeteer/index.js
 @ ./client/components/printReport/PrintLogoComponent.js
 @ ./client/components ^\.\/.*$
 @ ./client/layouts/CoreLayout/PageContent.js
 @ ./client/layouts/CoreLayout/index.js
 @ ./client/routes/index.js
 @ ./client/containers/Root.js
 @ ./client/main.js
 @ multi react-hot-loader/patch ./client/main.js webpack-hot-middleware/client.js?path=/__webpack_hmr

WARNING in ./node_modules/puppeteer/node_modules/ws/lib/Validation.js
Module not found: Error: Can't resolve 'utf-8-validate' in 'C:\<project-path>\node_modules\puppeteer\node_modules\ws\lib'
 @ ./node_modules/puppeteer/node_modules/ws/lib/Validation.js 10:22-47
 @ ./node_modules/puppeteer/node_modules/ws/lib/Receiver.js
 @ ./node_modules/puppeteer/node_modules/ws/index.js
 @ ./node_modules/puppeteer/lib/Connection.js
 @ ./node_modules/puppeteer/lib/Launcher.js
 @ ./node_modules/puppeteer/lib/Puppeteer.js
 @ ./node_modules/puppeteer ^\.\/.*\/Puppeteer$
 @ ./node_modules/puppeteer/index.js
 @ ./client/components/printReport/PrintLogoComponent.js
 @ ./client/components ^\.\/.*$
 @ ./client/layouts/CoreLayout/PageContent.js
 @ ./client/layouts/CoreLayout/index.js
 @ ./client/routes/index.js
 @ ./client/containers/Root.js
 @ ./client/main.js
 @ multi react-hot-loader/patch ./client/main.js webpack-hot-middleware/client.js?path=/__webpack_hmr

ERROR in ./node_modules/puppeteer/lib/Launcher.js
Module not found: Error: Can't resolve 'child_process' in 'C:\<project-path>\node_modules\puppeteer\lib'
 @ ./node_modules/puppeteer/lib/Launcher.js 19:21-45
 @ ./node_modules/puppeteer/lib/Puppeteer.js
 @ ./node_modules/puppeteer ^\.\/.*\/Puppeteer$
 @ ./node_modules/puppeteer/index.js
 @ ./client/components/printReport/PrintLogoComponent.js
 @ ./client/components ^\.\/.*$
 @ ./client/layouts/CoreLayout/PageContent.js
 @ ./client/layouts/CoreLayout/index.js
 @ ./client/routes/index.js
 @ ./client/containers/Root.js
 @ ./client/main.js
 @ multi react-hot-loader/patch ./client/main.js webpack-hot-middleware/client.js?path=/__webpack_hmr

ERROR in ./node_modules/puppeteer/node6/Launcher.js
Module not found: Error: Can't resolve 'child_process' in 'C:\<project-path>\node_modules\puppeteer\node6'
 @ ./node_modules/puppeteer/node6/Launcher.js 19:21-45
 @ ./node_modules/puppeteer/node6/Puppeteer.js
 @ ./node_modules/puppeteer ^\.\/.*\/Puppeteer$
 @ ./node_modules/puppeteer/index.js
 @ ./client/components/printReport/PrintLogoComponent.js
 @ ./client/components ^\.\/.*$
 @ ./client/layouts/CoreLayout/PageContent.js
 @ ./client/layouts/CoreLayout/index.js
 @ ./client/routes/index.js
 @ ./client/containers/Root.js
 @ ./client/main.js
 @ multi react-hot-loader/patch ./client/main.js webpack-hot-middleware/client.js?path=/__webpack_hmr

ERROR in ./node_modules/https-proxy-agent/index.js
Module not found: Error: Can't resolve 'net' in 'C:\<project-path>\node_modules\https-proxy-agent'
 @ ./node_modules/https-proxy-agent/index.js 5:10-24
 @ ./node_modules/puppeteer/utils/ChromiumDownloader.js
 @ ./node_modules/puppeteer/node6/Launcher.js
 @ ./node_modules/puppeteer/node6/Puppeteer.js
 @ ./node_modules/puppeteer ^\.\/.*\/Puppeteer$
 @ ./node_modules/puppeteer/index.js
 @ ./client/components/printReport/PrintLogoComponent.js
 @ ./client/components ^\.\/.*$
 @ ./client/layouts/CoreLayout/PageContent.js
 @ ./client/layouts/CoreLayout/index.js
 @ ./client/routes/index.js
 @ ./client/containers/Root.js
 @ ./client/main.js
 @ multi react-hot-loader/patch ./client/main.js webpack-hot-middleware/client.js?path=/__webpack_hmr

ERROR in ./node_modules/puppeteer/lib/Launcher.js
Module not found: Error: Can't resolve 'readline' in 'C:\<project-path>\node_modules\puppeteer\lib'
 @ ./node_modules/puppeteer/lib/Launcher.js 23:17-36
 @ ./node_modules/puppeteer/lib/Puppeteer.js
 @ ./node_modules/puppeteer ^\.\/.*\/Puppeteer$
 @ ./node_modules/puppeteer/index.js
 @ ./client/components/printReport/PrintLogoComponent.js
 @ ./client/components ^\.\/.*$
 @ ./client/layouts/CoreLayout/PageContent.js
 @ ./client/layouts/CoreLayout/index.js
 @ ./client/routes/index.js
 @ ./client/containers/Root.js
 @ ./client/main.js
 @ multi react-hot-loader/patch ./client/main.js webpack-hot-middleware/client.js?path=/__webpack_hmr

ERROR in ./node_modules/puppeteer/node6/Launcher.js
Module not found: Error: Can't resolve 'readline' in 'C:\<project-path>\node_modules\puppeteer\node6'
 @ ./node_modules/puppeteer/node6/Launcher.js 23:17-36
 @ ./node_modules/puppeteer/node6/Puppeteer.js
 @ ./node_modules/puppeteer ^\.\/.*\/Puppeteer$
 @ ./node_modules/puppeteer/index.js
 @ ./client/components/printReport/PrintLogoComponent.js
 @ ./client/components ^\.\/.*$
 @ ./client/layouts/CoreLayout/PageContent.js
 @ ./client/layouts/CoreLayout/index.js
 @ ./client/routes/index.js
 @ ./client/containers/Root.js
 @ ./client/main.js
 @ multi react-hot-loader/patch ./client/main.js webpack-hot-middleware/client.js?path=/__webpack_hmr

ERROR in ./node_modules/https-proxy-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\<project-path>\node_modules\https-proxy-agent'
 @ ./node_modules/https-proxy-agent/index.js 6:10-24
 @ ./node_modules/puppeteer/utils/ChromiumDownloader.js
 @ ./node_modules/puppeteer/node6/Launcher.js
 @ ./node_modules/puppeteer/node6/Puppeteer.js
 @ ./node_modules/puppeteer ^\.\/.*\/Puppeteer$
 @ ./node_modules/puppeteer/index.js
 @ ./client/components/printReport/PrintLogoComponent.js
 @ ./client/components ^\.\/.*$
 @ ./client/layouts/CoreLayout/PageContent.js
 @ ./client/layouts/CoreLayout/index.js
 @ ./client/routes/index.js
 @ ./client/containers/Root.js
 @ ./client/main.js
 @ multi react-hot-loader/patch ./client/main.js webpack-hot-middleware/client.js?path=/__webpack_hmr

**Comment by solsos** [comment] 2017-11-01 14:01
node version v8.2.1
npm version v5.5.1

**Comment by aslushnikov** [comment] 2017-11-01 15:06
Looks like a dupe of #1224

**Closed as completed by aslushnikov** 2017-11-01 15:06 UTC
