### ISSUE TITLE
How to handle dynamic id selectors.

### ISSUE THREAD

**Issue by hisingla** [puppeteer/puppeteer#2049] opened 2018-02-18 06:38 UTC
How to handle scenarios where id selector is generated at run time( it changed every time).  Let say i want to click on object having id //*[@id="pt1:r1:0:r0:0:r1:0:r10:0:i3:0:cl11"] which is different every time.

I have read the similar issues, but still not getting.

**Comment by xprudhomme** [comment] 2018-02-18 12:58
Not sure this is related to Puppeteer .. ?

**Comment by hisingla** [comment] 2018-02-18 13:06
i am using puppeteer to automate an scenario, where i need to click on element having id generated dynamically.

![capture](https://user-images.githubusercontent.com/36498946/36352187-2e794d36-14db-11e8-8eca-9cfe6d70231a.PNG)

**Comment by vsemozhetbyt** [comment] 2018-02-18 13:51
You can try other unique parameters, like in this xpath:
```
'//a[@href = "#" and text() = "Manage Implementation Projects"]'
```

**Comment by ebidel** [comment] 2018-02-18 16:34
Closing as this is not a bug or feature request for the library.

**Closed as completed by ebidel** 2018-02-18 16:34 UTC

**Comment by jsan4christ** [comment] 2023-07-20 17:50
<img width="545" alt="image" src="https://github.com/puppeteer/puppeteer/assets/4986950/aa898047-7806-4924-9191-593cdc987dbb">

I have a similar scenario -  I see that data-object-name is the best bet for me, but it not obvious how to grap it.
