### ISSUE TITLE
Unhandled promise rejection (rejection id: 1): Error: Protocol error (Network.enable): Target closed

### ISSUE THREAD

**Issue by codenoid** [puppeteer/puppeteer#362] opened 2017-08-18 00:47 UTC
hi, this is my first time using puppeteer, then i try example (screenshot webpage) from readme.md, and i got : 

```
$ node app.js
(node:29070) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Network.enable): Target closed.
(node:29070) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by codenoid** [comment] 2017-08-18 00:50
Ubuntu 16.04 v1
node 8.4.0

**Comment by aslushnikov** [comment] 2017-08-18 03:49
A few questions to debug this further: 
1. Could you please paste the code in `app.js`?
2. Could you please launch the chromium instance manually (it is inside the `node_modules/puppeteer/.local-chromium` folder and see if the chromium is operational?

**Comment by codenoid** [comment] 2017-08-18 07:22
```
const puppeteer = require('puppeteer');

(async () => {

  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'example.png'});

  browser.close();
})();
```

`i was delete my project folder :O ` - but wait

**Comment by aslushnikov** [comment] 2017-08-19 02:50
@codenoid Any updates on this?

**Comment by codenoid** [comment] 2017-08-19 07:46
```
oderlo@oderlo:/var/pup/node_modules/puppeteer$ cd .local-chromium
oderlo@oderlo:/var/pup/node_modules/puppeteer/.local-chromium$ ls
linux-494755
oderlo@oderlo:/var/pup/node_modules/puppeteer/.local-chromium$ cd linux-494755
oderlo@oderlo:/var/pup/node_modules/puppeteer/.local-chromium/linux-494755$ ls
chrome-linux
oderlo@oderlo:/var/pup/node_modules/puppeteer/.local-chromium/linux-494755$ cd chrome-linux
oderlo@oderlo:/var/pup/node_modules/puppeteer/.local-chromium/linux-494755/chrome-linux$ ls
chrome                  chrome_200_percent.pak  icudtl.dat                libEGL.so     nacl_helper            nacl_irt_x86_64.nexe  resources          swiftshader
chrome.1                chrome_sandbox          libclearkeycdmadapter.so  libGLESv2.so  nacl_helper_bootstrap  natives_blob.bin      resources.pak      xdg-mime
chrome_100_percent.pak  chrome-wrapper          libclearkeycdm.so         locales       nacl_helper_nonsfi     product_logo_48.png   snapshot_blob.bin  xdg-settings
oderlo@oderlo:/var/pup/node_modules/puppeteer/.local-chromium/linux-494755/chrome-linux$ 
```

**Comment by SantoshSrinivas79** [comment] 2017-08-19 10:11
I am getting the same error on my digital ocean instance. 

Ubuntu 16.04 LTS
node v8.4.0

**Comment by aslushnikov** [comment] 2017-08-19 16:21
Seems like chrome headless doesn't launch properly; closing as a dupe of #290

**Closed as completed by aslushnikov** 2017-08-19 16:21 UTC

**Comment by SantoshSrinivas79** [comment] 2017-08-31 02:09
@girishpatil solution [here](https://github.com/GoogleChrome/puppeteer/issues/290#issuecomment-324838511) worked perfectly me on similar system configuration

**Comment by jsrj** [comment] 2018-01-22 16:36
Encountering this error on Mac OS, so this isn't exclusively Debian related.
