### ISSUE TITLE
TypeError: Cannot read property 'send' of null

### ISSUE THREAD

**Issue by graingert** [puppeteer/puppeteer#957] opened 2017-10-05 11:12 UTC
### Steps to reproduce
Unsure of repo.

**Tell us about your environment:**

* Puppeteer version: 0.11.0
* Platform / OS version: Ubuntu Zesty docker: ubuntu:zesty-20170915

**What steps will reproduce the problem?**

Open page, ???, close page

**What is the expected result?**

closes page

**What happens instead?**
```
      "TypeError: Cannot read property 'send' of null",
      "    at Session.dispose (/usr/src/app/node_modules/puppeteer/lib/Connection.js:204:27)",
      "    at Page.close (/usr/src/app/node_modules/puppeteer/lib/Page.js:655:24)",
      "    at <redacted>:26:16",
      "    at Generator.throw (<anonymous>)",
      "    at step (/usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)",
      "    at /usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13",
      "    at <anonymous>",
      "    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"
```

**Comment by vsemozhetbyt** [comment] 2017-10-05 11:15
Can you provide a minimal code that causes this error?

**Comment by graingert** [comment] 2017-10-05 11:22
```js
import _ from 'lodash/fp';
import puppeteer from 'puppeteer';

const extraFlags = [
  '--no-sandbox',
  '--disable-web-security',
];

const launch = _.once(() => puppeteer.launch({ args: extraFlags }));

async function create(html) {
  const browser = await launch();
  const page = await browser.newPage();
  try {
    await page.setJavaScriptEnabled(false);
    await page.goto(`data:text/html,${html}`, { waitUntil: 'networkidle' });
    return await page.pdf({ printBackground: true, scale: 0.63 });
  } finally {
    await page.close();
  }
}
```

@vsemozhetbyt but it's intermittent

**Comment by ChristianDavis** [comment] 2017-10-13 04:32
Your try ... finally doesn't have a catch, so when some exception kills your page, the connection cleans itself up, but your finally clause still runs and then this fails cause the connection is gone
```javascript
  async dispose() {
    await this._connection.send('Target.closeTarget', {targetId: this._targetId});
  }
```

**Comment by graingert** [comment] 2017-10-13 06:29
@ChristianDavis page.close should probably ignore this error then

**Comment by aslushnikov** [comment] 2017-10-14 00:26
@graingert I can't repro with the following code:

```js
const puppeteer = require('puppeteer');

(async function () {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  try {
    await page.setJavaScriptEnabled(false);
    await page.goto(`data:text/html,hello!`, { waitUntil: 'networkidle' });
    return await page.pdf({ printBackground: true, scale: 0.63 }).then(() => console.log('pdf finished'));
  } finally {
    console.log('finally!');
    await page.close().then(() => console.log('finallyufinished'));
  }
})();
```

**Comment by graingert** [comment] 2017-10-14 09:01
Yeah it's intermittent

**Comment by ChristianDavis** [comment] 2017-10-14 17:15
My point earlier is that if you add a catch, you'll see the error that's causing the intermittent problem. You're letting it go uncaught

**Comment by graingert** [comment] 2017-10-14 20:34
@ChristianDavis no I'm not. I caught the exception and posted it!

**Comment by ChristianDavis** [comment] 2017-10-14 22:23
Only one exception will propagate to the outer scope, this code demonstrates the issue with what you posted:
```javascript
async function create(html) {
  const browser = await launch();
  const page = await browser.newPage();
  try {
    throw new Error("Error you won't see")
    await page.setJavaScriptEnabled(false);
    await page.goto(`data:text/html,${html}`, { waitUntil: 'networkidle' });
    return await page.pdf({ printBackground: true, scale: 0.63 });
  } finally {
    throw new Error('Error you will see')
    await page.close();
  }
}
```

**Comment by graingert** [comment] 2017-10-14 22:25
So what you're saying is that the page closes automatically if there's an
error from puppeteer. So I need to ignore errors when closing the page?

**Comment by ChristianDavis** [comment] 2017-10-14 22:38
No. You are trying to close a page that is already closed. I'm saying you don't know what is causing your error because you're missing a catch. 

Any action here would be that page.close() could throw a better error, but closing a page that doesn't exist is still an error.

**Comment by graingert** [comment] 2017-10-16 08:20
@ChristianDavis well I didn't close the page, so who did?

**Comment by pringshia** [comment] 2017-10-17 21:30
Running into the same issue, it seems that the page randomly "closes" while I'm still interfacing with it.

**Comment by aslushnikov** [comment] 2017-10-17 22:43
@graingert can you reproduce this with `DEBUG=puppeteer:protocol` env variable and post the log here?

**Comment by limarc** [comment] 2017-10-28 12:50
I have the same problem. @aslushnikov In your example, the content is very small. It seems the problem occurs on large pages, for example (tested 0.12.0, 0.13.0-alpha):

```js
const puppeteer = require('puppeteer');

(async function () {
  const browser = await puppeteer.launch({ args: ['--no-sandbox'] });
  const page = await browser.newPage();
  try {
    await page.setViewport({ width: 1200, height: 600, deviceScaleFactor: 2 });
    await page.goto(`https://avito.ru/moskva`, { waitUntil: 'networkidle2' });
    return await page.screenshot({ fullPage: true }).then(() => console.log('screenshot finished'));
  } finally {
    console.log('finally!');
    await page.close().then(() => console.log('finallyufinished'));
  }
})();
```
This example works on my MacBook, but falls into the docker container:

```
Error TypeError: Cannot read property 'send' of null
    at Session.dispose (/app/node_modules/puppeteer/lib/Connection.js:204:27)
    at Page.close (/app/node_modules/puppeteer/lib/Page.js:728:24)
    at Renderer.screenshot (/app/src/renderer.js:26:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by aslushnikov** [comment] 2017-10-31 07:55
@limarc ah yeah, looks like chrome or page crashed behind the scenes. We'll have a better handling for this with #952

**Closed as completed by aslushnikov** 2017-10-31 07:55 UTC
