### ISSUE TITLE
Iframe element and context comparsion

### ISSUE THREAD

**Issue by schelkun** [puppeteer/puppeteer#1594] opened 2017-12-13 14:06 UTC
How can I compare `iframe` element and context?

I was trying to add `name` attribute for each `<iframe>` element and than find it in `childFrames`:
```js
            for (let child of currentFrame.childFrames()) {
                const listName = await child.evaluate(() => {
                    if (window.frameElement !== null)
                        return window.frameElement.getAttribute('Name');
                });

                if (listName === frameName) {
                    searchResult = child;
                }
            }
```

But that's not work in 80% cases! How can I compare context and frame **without**:
* adding `name`
* adding `hash` to the end of the URL
* using `parent.document`

**Comment by schelkun** [comment] 2017-12-13 14:13
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#framename return empty string btw

**Comment by aslushnikov** [comment] 2017-12-20 05:25
@schelkun do you try to find a parent frame for the execution context?

**Comment by aslushnikov** [comment] 2018-01-04 09:49
I assume the OP required the `executionContext.frame()` method that would return the parent frame. This should be easy to add.

```js
const context = await frame.executionContext();
context.frame() === frame();
```

**Comment by schelkun** [comment] 2018-01-05 11:43
I just want to get `iframe` element from DOM as `ElementHandle` and get `Frame` object of this element. Can I do this with existing methods?

**Comment by schelkun** [comment] 2018-01-08 15:45
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandleexecutioncontext for iframe element returns page execution context, not frame execution context. And I want to know frame execution context of elementhandle.

**Comment by aslushnikov** [comment] 2018-01-09 02:56
Ah ok, this is dupe of #433.

**Closed as completed by aslushnikov** 2018-01-09 02:56 UTC
Labels: good first issue
