### ISSUE TITLE
[Bug]: setcontent times out. 

### ISSUE THREAD

**Issue by Lock23Supply** [puppeteer/puppeteer#12466] opened 2024-05-20 14:05 UTC
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
const fs = require('fs');

async function generatePDF(content, outputPath) {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent(content);
const.log("it reaches here...");
    const pdf = await page.pdf({ format: 'A4' }); // this crashes in the latest
console.log("but not here...");
    await browser.close();
    fs.writeFileSync(outputPath, pdf);
}

(async () => {
    // Generate two PDFs
    await generatePDF('<h1>First PDF</h1>', 'first.pdf');
    await generatePDF('<h1>Second PDF</h1>', 'second.pdf');

    console.log('PDFs generated');
})();
```

### Error string

async timeout 

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

it should create a pdf as it does in "puppeteer": "^22.3.0",

### Reality

the app times out after 30000ms

### Puppeteer version

22.9.0

### Node version

20.11.1

### Package manager

npm

### Package manager version

10.5.0

### Operating system

Windows

**Comment by OrKoN** [comment] 2024-05-21 07:05
Probably duplicate of https://github.com/puppeteer/puppeteer/issues/12470

**Closed as not planned by OrKoN** 2024-05-21 07:05 UTC
Labels: needs-feedback, not-reproducible
