### ISSUE TITLE
Page.setRequestInterception(true) is not working when post method redirection

### ISSUE THREAD

**Issue by codesorter2015** [puppeteer/puppeteer#3748] opened 2019-01-10 09:20 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: Windows 10 Pro
* URLs (if applicable): 
* Node.js version: v8.10.0

**What steps will reproduce the problem?**

const puppeteer = require('puppeteer');
(async () => {

    const browser = await puppeteer.launch({headless: false,devtools: true,args: ['--disable-gpu', '--no-sandbox', '--disable-setuid-sandbox', '--ignoreHTTPSErrors']})

    const page = await browser.newPage();
    var loadUrl = 'http://demo7.vtexperts.com/vtigercrm7demo/index.php';
    page.goto(loadUrl,{
        timeout: 0,
        waitUntil: ['networkidle0','load']
    });
    await page.setRequestInterception(true);
    page.on('request', request => {
        console.log(request.url());
        request.continue();
    });  
    page.on('requestfailed', request => {
      console.log(request.url() + ' ' + request.failure().errorText);
    });
    try{
        const navigationPromise = page.waitForNavigation({timeout:0})
        await navigationPromise
        await page.$eval('#username', el => el.value = 'demo');
        await page.$eval('#password', el => el.value = 'demo');
        await page.click('#loginFormDiv > form > div:nth-child(6) > button');
        await navigationPromise
    }catch(err){
        console.log(err);
    }
})();
_Please include code that reproduces the issue._

1. Save the code in the file and run it with Node

**What is the expected result?**
Redirect to the dashboard page 

**What happens instead?**
Page.setRequestInterception -> true it's not redirecting to the dashboard page
if you comment out the page.setRequestInterception everything works perfectly but I need to intercept the requests for cache implementation

**Comment by aslushnikov** [comment] 2019-01-10 19:07
This is a dupe of #3471.

@codesorter2015 btw please try installing `puppeteer@next` - we've just switched to use network service which might fix this issue.

**Closed as completed by aslushnikov** 2019-01-10 19:07 UTC

**Comment by codesorter2015** [comment] 2019-01-23 08:23
@aslushnikov The problem is resolved by using puppeteer@next, thanks!
