### ISSUE TITLE
how do i set a custom locations based on lattitude and longtitude in node js puppeteer?

### ISSUE THREAD

**Issue by AshwinDNair** [puppeteer/puppeteer#1184] opened 2017-10-27 08:54 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:0.12.0
* Platform / OS version:ubuntu
* URLs (if applicable):www.google.com

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

const puppeteer = require('puppeteer');
var url="https://www.google.com/search?q=";
var keyword="hotels";
var urls;
const response=[];
var i=0;
(async () => 
  const browser = await puppeteer.launch({headless: false });
  const page = await browser.newPage();
  urls=url+keyword;
await page.addScriptTag({path: 'changeGeo.js'});
page.setUserAgent(userAgent);
  response[i]=await page.goto(urls);
  console.log(await browser.version());
})();

**What is the expected result?**
when browsers open I want it to show the hotels near a custom location that I can decide using latitude and longitude.

**What happens instead?**
It shows me hotels near my location.

**Comment by AshwinDNair** [comment] 2017-10-27 09:02
@ebidel @aslushnikov please tell me a way to do this.

**Comment by aslushnikov** [comment] 2017-10-27 10:36
Dupe of #1077

**Closed as completed by aslushnikov** 2017-10-27 10:36 UTC
