### ISSUE TITLE
[Bug]: new .cache browser download directory breaks running as different user

### ISSUE THREAD

**Issue by jribbens** [puppeteer/puppeteer#9162] opened 2022-10-25 11:56 UTC
### Bug description

Steps to reproduce the problem:

1. Install puppeteer then run it as a different user from the one you installed it as.
2. puppeteer tells you you haven't run `npm install`, which is untrue.

I realise you may well think this is fine, but it's a significant change from the previous behaviour and I can't find it documented (it doesn't help that you've deleted the CHANGELOG!) and it took me considerable time to work out that what I needed to do was set `PUPPETEER_EXECUTABLE_PATH` and even longer to work out what I needed to set it to.

### Puppeteer version

19.1.0

### Node.js version

16.18.0

### npm version

8.19.2

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
$ node .
<successful run>
$ sudo -ufoo node .
Error: Run `npm install` to download the correct Chromium revision (1045629).
```

**Comment by OrKoN** [comment] 2022-10-25 12:41
The changelog is here https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer/CHANGELOG.md#-breaking-changes and documentation is here https://pptr.dev/guides/configuring-puppeteer#changing-the-default-cache-directory

**Comment by jrandolf** [comment] 2022-10-25 13:24
Duplicate of https://github.com/puppeteer/puppeteer/issues/9162.

Some documentation has migrated due to monorepo changed, however everything still exists (in better shape in fact).

**Closed as completed by jrandolf** 2022-10-25 13:24 UTC
