### ISSUE TITLE
RequestInterception: request.continue does nothing when site requires client certificate

### ISSUE THREAD

**Issue by paolocaminiti** [puppeteer/puppeteer#3028] opened 2018-08-06 18:32 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.6.2
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 8.11

**What steps will reproduce the problem?**

```
  const page = await browser.newPage()
  await page.setRequestInterception(true)

  page.on('request', interceptedRequest => {
    interceptedRequest.continue()
  })

  await page.goto(url)
```

where url points to a webstite requiring a client certificate
and the user manually press ok with the valid certificate in the certificates popup

**What is the expected result?**
page.goto should navigate to the page after the certificate is manually selected

**What happens instead?**
page stays on "about:blank"

**Comment by aslushnikov** [comment] 2018-08-07 21:41
This is a dupe of #1159.

try running with `--enable-features=NetworkService` as a woraround.

**Closed as completed by aslushnikov** 2018-08-07 21:41 UTC
