### ISSUE TITLE
[Bug]: Frame navigated event did not trigger

### ISSUE THREAD

**Issue by tzbo** [puppeteer/puppeteer#9264] opened 2022-11-14 07:12 UTC
### Bug description

Steps to reproduce the problem:

``` js
 try {
            const iframe = document.createElement('iframe')
            iframe.setAttribute('style', 'display:none')
            iframe.src = location.href
            document.body.append(iframe)
            const data = await getData(iframe.contentWindow)
            iframe.parentNode.removeChild(iframe)
            return data
        } catch (error) {
            console.error(error)
            return
        }
```

This code will not trigger [frameattached] and [framenavigated].

If add break point at [const iframe = document.createElement('iframe')], then the event can be triggered again.

### Puppeteer version

19.2.2

### Node.js version

18

### npm version

8.4

### What operating system are you seeing the problem on?

macOS

**Comment by Lightning00Blade** [comment] 2022-11-14 14:28
@tzbo Presumable the code you show is in your HTML. Are you setting up listeners before navigating to the page, like so:
``` 
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on("frameattached", () => {
    console.log(`It attached.`);
  });
  page.on("framedetached", () => {
    console.log(`It detached.`);
  });
  await page.goto("http://127.0.0.1:8080/");
  await browser.close();
```

This worked for me. Setting of Listeners should happen before navigation, else they may be added after the event has occurred.

**Comment by Lightning00Blade** [comment] 2022-11-14 15:26
Is it possible you are closing the window as soon as the page load.? It looks like your code is Async and would need a way to await the changes. Example with `page.waitForNetworkIdle()` worked with your code: 
```
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on("frameattached", () => {
    console.log(`It attached.`);
  });
  page.on("framedetached", () => {
    console.log(`It detached.`);
  });
  await page.goto("https://abrahamjuliot.github.io/creepjs/tests/iframes.html");

  await page.waitForNetworkIdle();

  await browser.close();
```

That can also be `page.waitForSelector()` if you want to check a element or
a simple `await new Promise((resolve) => setTimeout(resolve, X));` can also work.

**Comment by tzbo** [comment] 2022-11-14 22:48
Please try to open this link. The [same origin] frame will not trigger [frameattached] event. 

You can find 8 [frameattached] events if you open this link. But there should be 9 events. The code creates 8 iframes and there is another main frame. So there should be 9 events.

**Comment by Lightning00Blade** [comment] 2022-11-16 13:50
@tzbo Can you provide your Puppeteer Script that the issue is happening?

**Comment by tzbo** [comment] 2022-11-16 13:55
``` js
const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on("frameattached", () => {
    console.log(`It attached.`);
  });
  page.on("framedetached", () => {
    console.log(`It detached.`);
  });
  await page.goto("https://abrahamjuliot.github.io/creepjs/tests/iframes.html");

  await page.waitForNetworkIdle();

  await browser.close();
```

This script is okay. There should be nine [It attached] events. But got 8.

**Comment by OrKoN** [comment] 2022-11-16 15:14
@tzbo @Lightning00Blade IMO, sounds like it is working as expected. The main frame is never attached/detached as it exists since the creation of the page and can only be navigated (which the goto handles).

**Comment by tzbo** [comment] 2022-11-17 06:55
May be same problem with [1106](https://github.com/puppeteer/puppeteer/issues/1106)

**Closed as completed** 2023-01-02 08:36 UTC
Labels: needs-feedback
