### ISSUE TITLE
evaluateOnNewDocument is not working on new tab

### ISSUE THREAD

**Issue by schelkun** [puppeteer/puppeteer#1443] opened 2017-11-21 16:36 UTC
Try to execute this code:

```js
const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch({
        headless: false,
        timeout: 10000,
        devtools: true
    });

    browser.on('targetcreated', async (target) => {
        console.log(`Created target type ${target.type()} url ${target.url()}`);
        if (target.type() !== 'page') {
            return;
        } else {
            var page = await target.page();
        }
        await page.evaluateOnNewDocument(() => {
            console.log('evaluateOnNewDocument');
        });
    });

    const page = await browser.newPage();

    await page.goto('https://example.com/');

    await page.evaluate(() => {
        var a = document.createElement('a');
        a.href = 'https://example.com/?404';
        a.target = '_blank';
        a.innerHTML = 'Click me';
        a.id = 'click';
        document.body.appendChild(a);
    });

    await page.waitFor(1000);

    await page.click('#click');
})();
```

`console.log('evaluateOnNewDocument');` will not be executed on new opened tab. How can I fix that?

**Comment by vc1** [comment] 2017-11-21 17:01
`page.evaluate` can work normally

**Comment by schelkun** [comment] 2017-11-21 17:07
@vc1 
```
page.evaluateOnNewDocument
The function is invoked after the document was created but before any of its scripts were run. This is useful to amend JavaScript environment, e.g. to seed Math.random.
```
So I want to evaluate *before* page scripts will be evaluated.

**Comment by vc1** [comment] 2017-11-21 17:28
i know
[https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-addScriptToEvaluateOnNewDocument](url)
`targetcreated` event can catch the new page, `evaluateOnNewDocument` is executed, i guess it may be Chromium's bug

**Comment by aslushnikov** [comment] 2017-11-21 23:44
@schelkun the reason the code doesn't work for you is because you're too late connecting to the page. The document has already been created, so the `evaluateOnNewDocument` does nothing.

It's a good usecase though. I'll keep this open until we have a nice solution for this.

**Comment by aslushnikov** [comment] 2018-01-12 12:11
Closing as a dupe of #1378: both issues suffer from inability to "pause" on target creation.

**Closed as completed by aslushnikov** 2018-01-12 12:11 UTC
