### ISSUE TITLE
Full page screenshots with overflow content regions

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#746] opened 2017-09-11 16:35 UTC
Filing this so we can figure out ways to make the scenario easier....

https://news.google.com/news/ is an example of a page that fills the viewport (100vh/vw), but has a central scrolling region. When you take a fullpage screenshot, only the filled viewport is included:

<img width="1211" alt="screen shot 2017-09-11 at 9 27 05 am" src="https://user-images.githubusercontent.com/238208/30285580-67dd22f4-96d3-11e7-92bf-b6c58f384a53.png">

While Puppeteer is probably correct, it feels unexpected.

**Comment by aslushnikov** [comment] 2017-09-11 17:09
@ebidel thanks for filing this.

Screenshotting these kind of websites (apps?) is a hard task and should be tackled on a case-by-case basis. Web sites can define multiple nested scrolling areas, some of them could be viewported.
Understanding website structure would require neural network :)

I don't see how we can help with this problem as a part of puppeteer project.

**Comment by ebidel** [comment] 2017-09-11 17:16
Yea, I'm not entirely sure how I'd approach this from user code.  Any suggestions?

Maybe there's an upstream feature request in here for headless? Chrome must know there's a scrollable layer.

**Comment by MelonHTML5** [comment] 2017-10-27 06:31
I think this is the expected behavior. The same theory applies to background overlay used with modal dialogs. They are expected to be 100% tall.

**Comment by intellix** [comment] 2018-02-10 10:00
I'm noticing something strange here and am not sure whether it's related. We're using a `min-height: 100vh` on our content area to make sure the footer is always below the fold.

For screenshot regression testing I want to take a screenshot of everything including the footer so I'm hacking it by removing the min-height before taking a screenshot:
```js
const height = await page.evaluate(() => {
  document.querySelector('.main-content').style.minHeight = 'auto';
  return document.querySelector('xc-scroll .scroll-content').scrollHeight;
});

page.setViewport({ ...device.viewport, height });
```

It works well on desktop but when we emulate a device with `deviceScaleFactor` we get a screenshot with quadrupled content which I'm guessing is due to some Chrome rendering performance hacks with new content that instantly becomes visible:

![screenshot 2018-02-10 10 55 05](https://user-images.githubusercontent.com/1162531/36060815-02b0de70-0e51-11e8-8dc7-70be05b04054.png)

![screenshot 2018-02-10 11 19 11](https://user-images.githubusercontent.com/1162531/36061006-43236a6a-0e54-11e8-9a0d-1661e3c08d7a.png)

**Update:** It's fixed if I set `fullPage: true`

**Comment by aslushnikov** [comment] 2018-03-14 22:49
There are no plans to address this; closing.

**Closed as completed by aslushnikov** 2018-03-14 22:49 UTC
