### ISSUE TITLE
[Bug]: Puppeteer's interceptors are missing initial redirects

### ISSUE THREAD

**Issue by grcode123** [puppeteer/puppeteer#10901] opened 2023-09-13 16:02 UTC
### Minimal, reproducible example

The use case I'm trying to cover is to read all the traffic from each tab. I'm not controlling the tab page creation and users can create tabs at any time by clicking. Listeners set on the page level for each page like

```TypeScript

await page.setRequestInterception(true);

 page.on("request", (request) => {...

 page.on("requestfinished", async (rq) => {...
```
I'm using `puppeteer.connect(...` method (but the same issue occurs with regular `.launch(...` too) and the actual scenario is when I connect puppeteer and navigate to the link or HTML on the initial/first tab it catches everything, but then the user:

1 - When user clicks on link with target=_blank and the link has initial redirects. Puppeteers will just miss those and attach late;

2 - When the user does a right click and open on new tab, puppeteer will miss those initial redirects/requests.

Currently, I'm using puppeteer's cdp connection on the browser level and fetch API to catch those redirects, but fetch API has way less details that I need compare to cdp network API.

Running puppeteer 19+ if it matters.

TIA

example of HTML for the initial step:
<html>
<body>
<a href="http://google.com target=_blank> Google </a>
<body>
</html>
```


### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

_No response_

### Expectation

Expected when the new tab is opened interceptor should catch all the redirects google has.

### Reality

Missing initial redirects or any information, sometimes `Network.requestwillbesent` sees second redirect

### Puppeteer configuration file (if used)

_No response_

### Puppeteer version

19.6.1

### Node version

14.19.1

### Package manager

npm

### Package manager version

8.5.0

### Operating system

macOS

**Comment by OrKoN** [comment] 2023-09-13 16:04
Currently, there is no support for that use case. Intercepts are per page and target=_blank is a new page. That sounds like a duplicate of this feature request https://github.com/puppeteer/puppeteer/issues/3667

**Closed as not planned by OrKoN** 2023-09-13 16:04 UTC

**Comment by alexrus123** [comment] 2023-09-13 16:34
Thank you for your quick response. 

Is there a reason why Fetch API on the browser level doesn't have the network details?  I think this would solve this use case

**Comment by OrKoN** [comment] 2023-09-13 16:36
@alexrus123 do you mean the Fetch domain in CDP? I guess the intended way is to intercept targets and configure interception there.

**Comment by alexrus123** [comment] 2023-09-13 16:44
@OrKoN yes, Fetch domain (https://chromedevtools.github.io/devtools-protocol/tot/Fetch/) has all the redirects intercepted as well as partial response details when intercepted and request networkId, but because Network is late to attach there is no way to match details. Targets interception is the ideal way. 

Thank you for your replies!

**Comment by OrKoN** [comment] 2023-09-13 16:50
If you want to do it via CDP, you would need to call https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-setAutoAttach with waitForDebuggerOnStart=true and enable the interception for the new targets.

**Comment by alexrus123** [comment] 2023-09-13 17:15
Yes, exactly and this is where it misses the initial redirects because it can run `Network.enable` in time and redirects are already processed and it all comes down to the issue you mentioned above! Anyway, thank you for your quick responses and great chatting! Have a good day!

**Comment by rzinnatullin** [comment] 2025-05-14 09:50
@OrKoN  setAutoAttach works only on subsequent targets in a tab, but not on new tabs (so there's no auto attach when, for example, user clicks on a link and a new tab opens).

**Comment by OrKoN** [comment] 2025-05-14 10:29
> [@OrKoN](https://github.com/OrKoN) setAutoAttach works only on subsequent targets in a tab, but not on new tabs (so there's no auto attach when, for example, user clicks on a link and a new tab opens).

setAutoAttach needs to be called on the browser target to auto-attach to tab targets.

**Comment by rzinnatullin** [comment] 2025-05-14 12:46
> > [@OrKoN](https://github.com/OrKoN) setAutoAttach works only on subsequent targets in a tab, but not on new tabs (so there's no auto attach when, for example, user clicks on a link and a new tab opens).
> 
> setAutoAttach needs to be called on the browser target to auto-attach to tab targets.

Indeed, thanks for pointing this out.
