### ISSUE TITLE
[Bug]: net::ERR_HTTP2_PROTOCOL_ERROR when accessing a http/3 page

### ISSUE THREAD

**Issue by mittster** [puppeteer/puppeteer#11638] opened 2024-01-05 13:53 UTC
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";
var browser = await puppeteer.launch({
    headless:"new" // no error in headful mode
});

let url = "https://www.adobe.com/it/creativecloud/photography/basics/light.html";
const page = await browser.newPage();

await page.goto(url, {waitUntil: "domcontentloaded", timeout: 40000});
let data = await page.$eval("h1",(element)=>{
    return element.innerText;
});
console.log(data)
console.log("done")
```

### Error string

net::ERR_HTTP2_PROTOCOL_ERROR 

### Bug behavior

- [X] Flaky
- [ ] PDF

### Background

I've tested the code on Mac and aws lambda. Same error. It works fine if using` headless:false`. Error occurs in multiple node versions: 20.10.0, also on 18.14.1 and 16.15.0

### Expectation

I am expecting code to visit the page and not crash. The culprit may be that adobe is using http/3. I was not able to confirm it, because other http/3 websites do work ( e.g. https://blog.cloudflare.com/http3-the-past-present-and-future)

### Reality

I get an error:

file:///pathtoproject/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:167
                        ? new Error(`${response.errorText} at ${url}`)
                          ^

Error: net::ERR_HTTP2_PROTOCOL_ERROR at https://www.adobe.com/it/creativecloud/photography/basics/light.html
    at navigate (file:///pathtoproject/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:167:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Deferred.race (file:///pathtoproject/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:80:20)
    at async CdpFrame.goto (file:///pathtoproject/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:133:25)
    at async CdpPage.goto (file:///pathtoproject/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:565:20)
    at async file:///pathtoproject/index.js:9:1

### Puppeteer version

21.7.0

### Node version

20.10.0

### Package manager

npm

### Package manager version

8.5.5

### Operating system

macOS

**Comment by OrKoN** [comment] 2024-01-08 08:33
@Lightning00Blade could you please try to reproduce?

**Comment by Lightning00Blade** [comment] 2024-01-08 10:49
The issue is reproducible, but looks like Adobe has a way to prevent automation, so closing as won't fix.

**Closed as not planned by Lightning00Blade** 2024-01-08 10:49 UTC
Labels: needs-feedback, not-reproducible

**Comment by mmacmillan** [comment] 2024-01-29 19:52
its not just adobe, i have encountered several pages with this error, unable to find a simple resolution; i have tried ignoring HTTPS, using an incognito context, etc:

`import puppeteer from 'puppeteer';
const url = "https://blogs.oracle.com/cloud-infrastructure/post/what-is-new-in-oci";

const browser = await puppeteer.launch({ headless: 'new' });
const page = await browser.newPage();

await page.goto(url)`

**Comment by KillerJulian** [comment] 2024-03-24 16:17
> The issue is reproducible, but looks like Adobe has a way to prevent automation, so closing as won't fix.

It also affects other pages. Unfortunately, specifying a user agend [is no longer sufficient](https://jsoverson.medium.com/how-to-bypass-access-denied-pages-with-headless-chrome-87ddd5f3413c). Are there any ideas on how to circumvent this procedure?

**Comment by cookie720** [comment] 2024-04-04 06:33
I am also getting net::ERR_HTTP2_PROTOCOL_ERROR using chrome trying to POST to login somewhere. Interestingly got the following CORS error using product: 'firefox' at the same point:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at

**Comment by caiomendesc** [comment] 2024-04-24 01:08
using the user agent fixed for me

**Comment by cookie720** [comment] 2024-04-24 01:15
> using the user agent fixed for me

Interesting, no combination of User Agent or any other "tricks" would work for me. It really must depend on the site in question.

Then I discovered puppeteer-extra.

`import puppeteer from 'puppeteer-extra'; 
import StealthPlugin from 'puppeteer-extra-plugin-stealth';
import AdblockerPlugin from 'puppeteer-extra-plugin-adblocker';

   puppeteer.use(StealthPlugin());
    puppeteer.use(AdblockerPlugin({ blockTrackers: true }))`
    
    
After this, everything worked.

**Comment by caiomendesc** [comment] 2024-04-28 10:14
> > using the user agent fixed for me
> 
> Interesting, no combination of User Agent or any other "tricks" would work for me. It really must depend on the site in question
> 
> Then I discovered puppeteer-extra.
> 
> ```ts
> import puppeteer from 'puppeteer-extra'; 
> import StealthPlugin from 'puppeteer-extra-plugin-stealth';
> import AdblockerPlugin from 'puppeteer-extra-plugin-adblocker';
> 
> puppeteer.use(StealthPlugin());
> puppeteer.use(AdblockerPlugin({ blockTrackers: true }))
> ```
> 
> After this, everything worked.

Thanks for this suggestion. Mine stopped working after a while 😆

**Comment by caiomendesc** [comment] 2024-04-28 10:35
UPDATE:

Sometimes the proxy you're using might cause this error, I changed it to a unknown country and it stopped happening

**Comment by XxA7med66xX** [comment] 2024-04-29 13:07
> For anyone coming to this issue
> ```
> page.setUserAgent(ua);
> ```

Thanks, the issue has been fixed.

**Comment by ferrerjoel** [comment] 2024-05-11 13:46
Any update on this matter?

**Comment by kazanemed** [comment] 2024-05-17 12:31
> Any update on this matter?

I'm facing the same problem. Did you find a solution on your end?

**Comment by ferrerjoel** [comment] 2024-05-17 14:13
@kazanemed Honestly no, it seems that in my case it's the web that it's the problem. I'm assuming that the web knows I'm accessing through AWS, and it's not letting me get the data. But I can't say for sure. Try some other websites and see if that can be the problem.

**Comment by kejedi** [comment] 2024-07-18 20:51
setting a user agent resolved the issue for me

**Comment by BatMiles** [comment] 2024-08-01 19:39
setting a user agent also did not work for me. Trying to access sacbee.com

**Comment by AraCoders** [comment] 2024-10-08 10:21
Update: using the `headless: false` flag works for now. however i didn't find any way to do this headlessly. it also seems related to Akamai.

**Comment by JosefHobler** [comment] 2024-12-11 07:01
For me, headless: false does not work, neither does user agent.

**Comment by JosefHobler** [comment] 2024-12-12 09:26
User agent neither "headless: false" worked for me. I am fetching google search results using puppeteer and sometimes the error "net::ERR_HTTP2_PROTOCOL_ERROR" pops up.

`
await page2.goto(
                `https://www.google.com/search?q=${encodeURIComponent(value)}${
                  index === 0
                    ? `&hl=${articlesLanguage2}&gl=${articlesLanguage}`
                    : ""
                }`,
                {
                  waitUntil: "domcontentloaded",
                  timeout: 15000,
                }
              );
`

**Comment by JosefHobler** [comment] 2024-12-12 11:26
What seems to have worked is after the error is thrown, try the page2.goto() again. The success rate is now more than 95%.

**Comment by heksoli** [comment] 2024-12-17 10:10
> What seems to have worked is after the error is thrown, try the page2.goto() again. The success rate is now close to 100%.

You can also visit first the root domain and then the page

**Comment by prabhat-123** [comment] 2025-07-23 17:44
const express = require('express');
const puppeteer = require('puppeteer');

const app = express();
const port = 3001;

app.use(express.json());

let browser;

// Retry logic for page.goto()
async function safeGoto(page, url, retries = 3) {
let attempt = 0;
while (attempt < retries) {
try {
await page.goto(url, {
waitUntil: 'domcontentloaded', // or 'networkidle2' if needed
timeout: 15000
});
return;
} catch (err) {
console.warn(Goto failed (attempt ${attempt + 1}): ${err.message});
if (attempt === retries - 1) throw err;
await new Promise(res => setTimeout(res, 1000 * (attempt + 1))); // backoff
attempt++;
}
}
}

app.post('/extract', async (req, res) => {
const { url } = req.body;

if (!url) return res.status(400).json({ error: "URL is required" });

try {
const page = await browser.newPage();

// Request interception to spoof headers
await page.setRequestInterception(true);
page.on('request', request => {
  const headers = {
    ...request.headers(),
    'accept-language': 'en-US,en;q=0.9',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) ' +
                  'AppleWebKit/537.36 (KHTML, like Gecko) ' +
                  'Chrome/123.0.0.0 Safari/537.36'
  };
  request.continue({ headers });
});

await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) ' +
                        'AppleWebKit/537.36 (KHTML, like Gecko) ' +
                        'Chrome/123.0.0.0 Safari/537.36');

// Run safe goto
await safeGoto(page, url);

// You can adapt this if you want to extract structured Google results
const content = await page.evaluate(() => document.body.innerText);

await page.close();

res.json({ content });
} catch (err) {
res.status(500).json({ error: err.toString() });
}
});

(async () => {
browser = await puppeteer.launch({
headless: 'new', // You can also try false for debug mode
args: [
'--no-sandbox',
'--disable-setuid-sandbox',
'--disable-gpu',
'--disable-dev-shm-usage',
'--window-size=1920,1080',
'--disable-quic'
]
});

app.listen(port, () => {
console.log(Puppeteer microservice running at http://localhost:${port});
});

process.on('exit', async () => {
if (browser) await browser.close();
});
})();

this is the code I have used and it is working fine.
What seems to have worked is after the error is thrown, try the page2.goto() again. The success rate is now close to 100%.
this works.
