### ISSUE TITLE
Page.select not working and not throwing error

### ISSUE THREAD

**Issue by alskdwq** [puppeteer/puppeteer#4483] opened 2019-05-28 10:04 UTC
So I used page.select to choose a an option from a drop down menu, however the program just hangs at the page.select line and doesn't throw error or return a value. I also found out that this code works on some options of that menu, but fails on most options. 
Any idea what may be the cause?

**Comment by aslushnikov** [comment] 2019-06-02 20:38
> Any idea what may be the cause?

@alskdwq no idea. I don't think we can help much unless you provide us with a link and a simple script that reproduces the problem.

This way we would be able to debug the behavior locally, and either find a problem with your approach, or find and fix bug in Puppeteer/Chromium.

I'll close this for now since it's not actionable. If you can share a good repro with us, we'll appreciate if you re-file the issue with more details.

Thanks!

**Closed as completed by aslushnikov** 2019-06-02 20:38 UTC
