### ISSUE TITLE
set --user-data-dir as part of options

### ISSUE THREAD

**Issue by softwarezhu** [puppeteer/puppeteer#460] opened 2017-08-22 07:10 UTC
I'm using puppeteer for website automation, but the target website need to sign in with email confirmation for new sessions. 

So what I want is: 
- keep `--user-data-dir` persistant. So next time I sign in, There won't be email confirmation. 

However, I find that the `--user-data-dir` argumant is set to be `.dev_profile1`, and this directory will be deleted when process exit. 

How about make this argument as an option(but with default value), and make this directory deleted manually? (like Nightmare's userData option)

**Comment by vsemozhetbyt** [comment] 2017-08-22 07:13
See also https://github.com/GoogleChrome/puppeteer/issues/411

**Comment by aslushnikov** [comment] 2017-08-24 00:39
Closing as a dupe of #411

**Closed as completed by aslushnikov** 2017-08-24 00:39 UTC
