### ISSUE TITLE
mouse down,move,up can't be trigger twice

### ISSUE THREAD

**Issue by StoneCode5** [puppeteer/puppeteer#2943] opened 2018-07-24 04:29 UTC
### Steps to reproduce

**Tell us about your environment: 

* Puppeteer version: v1.6.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: v8.11.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
```
const puppeteer = require('puppeteer');
const devices = require('puppeteer/DeviceDescriptors');
const iPhone = devices['iPhone 7'];

function resolveAfter6Seconds (params) {
    return new Promise(resolve => {
        setTimeout(() => {
            console.log(params)
            resolve('resolved');
        }, 6000);
    });
}

(async () => {
    const browser = await puppeteer.launch({ headless: false })
    page = await browser.newPage();
    await page.emulate(iPhone)
    await page.goto('http://u2839250.viewer.maka.im/k/1ZQ3AEQN');

    await resolveAfter6Seconds('fitst 6s')
    await page.mouse.down()
    await page.mouse.move(100, -200)
    await page.mouse.up()
    console.log('first drag end')

    await resolveAfter6Seconds('second 6s')
    await page.mouse.down()
    await page.mouse.move(100, -200)
    await resolveAfter6Seconds('89798')
    await page.mouse.up()
    console.log('second drag end')

    await resolveAfter6Seconds('third 6s')
    await page.mouse.down()
    await page.mouse.move(100, -200)
    await page.mouse.up()
    console.log('third drag end')

    await browser.close();
})();
```
**What is the expected result?**
the second 'mouse.down-mouse.move-mouse.up' should work
the second page should be hidden, the third page show be shown

**What happens instead?**
the first 'mouse.down-mouse.move-mouse.up' works,
but the second doesn't

**Comment by aslushnikov** [comment] 2018-08-02 17:50
@JoelEinbinder can you please take a look?

**Comment by JoelEinbinder** [comment] 2018-08-08 18:08
Unfortunately this is a drag-n-drop bug. Duplicate of #1376.

**Closed as completed by JoelEinbinder** 2018-08-08 18:08 UTC
