### ISSUE TITLE
dragging

### ISSUE THREAD

**Issue by tcurdt** [puppeteer/puppeteer#423] opened 2017-08-20 21:54 UTC
I need to drag something on the screen. I was trying like this:
```
  const mouse = page.mouse
  await mouse.move(x,y)
  await mouse.down()
  await mouse.move(x+400, y)
  await mouse.up()
```
The `down` and `up` work (if I move the mouse between the `down` and `up` events manually the map is being dragged) but the call to `move` between the `down` and `up` seems to get ignored. 

Or what am I missing?

Here is a testcase where the images `1.png` and `2.png` should not look the same:
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: true,
  })

  const page = await browser.newPage()
  await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36')
  await page.setViewport({width: 1200, height: 800, deviceScaleFactor: 1});

  await page.goto('https://www.google.de/maps/@52.4889552,13.4707445,1555m/data=!3m1!1e3')
  await page.waitForNavigation({waitUntil: 'networkidle'})

  await page.screenshot({path: '1.png', fullPage: true})

  const innerWidth = await page.evaluate(_ => {return window.innerWidth})
  const innerHeight = await page.evaluate(_ => {return window.innerHeight})

  const mouse = page.mouse
  await mouse.move(innerWidth/2, innerHeight/2)
  await mouse.down()
  await mouse.move(innerWidth/2+200, innerHeight/2)
  await mouse.up()
  await page.waitForNavigation({waitUntil: 'networkidle'})

  await page.screenshot({path: '2.png', fullPage: true})

  browser.close()
})()
```

**Comment by Garbee** [comment] 2017-08-21 00:21
Duplicate of #343

**Comment by tcurdt** [comment] 2017-08-21 01:20
Sorry, didn't see it as it's closed.
But also makes me wonder why it is closed :)

**Comment by aslushnikov** [comment] 2017-08-24 00:42
@JoelEinbinder Joel, could you please take a loot into this?

**Comment by 3zzy** [comment] 2017-08-26 03:43
+1 would be really useful.

**Comment by aslushnikov** [comment] 2017-08-29 21:19
Looks like google maps are fancy and discard mouse movements with huge delta.

We've added the "steps" option to the `mouse.move` method so that you can send intermediate events. 
The following script works fine for me:
```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: true,
  })

  const page = await browser.newPage()
  await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36')
  await page.setViewport({width: 1200, height: 800, deviceScaleFactor: 1});

  await page.goto('https://www.google.de/maps/@52.4889552,13.4707445,1555m/data=!3m1!1e3')
  await page.waitForNavigation({waitUntil: 'networkidle'})

  await page.screenshot({path: '1.png', fullPage: true})

  const innerWidth = await page.evaluate(_ => {return window.innerWidth})
  const innerHeight = await page.evaluate(_ => {return window.innerHeight})

  const mouse = page.mouse
  await mouse.move(innerWidth/2, innerHeight/2)
  await mouse.down()
  await mouse.move(innerWidth/2+200, innerHeight/2, {steps: 100})
  await mouse.up()
  await page.waitForNavigation({waitUntil: 'networkidle'})

  await page.screenshot({path: '2.png', fullPage: true})

  browser.close()
})()
```

**Closed as completed by aslushnikov** 2017-08-29 21:19 UTC
