### ISSUE TITLE
HTML5 Video does not work

### ISSUE THREAD

**Issue by phawxby** [puppeteer/puppeteer#697] opened 2017-09-06 10:59 UTC
Regular chrome plays videos when opened up directly or embedded using a HTML5 video tag, puppeteer downloads them when browsing to them directly and simply does nothing when included as part of a video tag.

![image](https://user-images.githubusercontent.com/1090602/30108512-8a4b3ec0-92fa-11e7-86b7-cdcf5edfe087.png)

![image](https://user-images.githubusercontent.com/1090602/30108918-31b070da-92fc-11e7-8348-57c4cc6215c4.png)

No network requests either
![image](https://user-images.githubusercontent.com/1090602/30108948-50eafdb2-92fc-11e7-861b-c250ff64f8b6.png)

Puppeteer: 0.10.2
Node: 8.4.0

**Comment by phawxby** [comment] 2017-09-06 11:22
Update, does puppeteer not support mp4??
![image](https://user-images.githubusercontent.com/1090602/30109370-f8698382-92fd-11e7-9c06-09a6a515d53c.png)

**Comment by phawxby** [comment] 2017-09-06 12:31
Ah, so it seems Chromium doesn't support mp4, only Chrome does.
https://www.chromium.org/audio-video

**Comment by Garbee** [comment] 2017-09-06 13:40
duplicate of #291

**Closed as completed** 2017-09-06 14:17 UTC
