### ISSUE TITLE
[Bug]: Download PDF example not working

### ISSUE THREAD

**Issue by CaeldanRodrigues** [puppeteer/puppeteer#12532] opened 2024-06-04 04:30 UTC
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

const genPdf = async () => {
  const browser = await puppeteer.launch({headless: false, timeout: 60000});
  const page = await browser.newPage();

  await page.goto('https://news.ycombinator.com', {
    waitUntil: 'networkidle2',
    timeout: 60000
  });
  // Saves the PDF to hn.pdf.
  try {
    await page.pdf({
      path: './hn.pdf',
    })

  } catch (error) {
    console.log("error", error);
  } finally {
    await browser.close();
  }
};

genPdf();
```

### Error string

TimeoutError: Timed out after waiting 30000ms

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I was running the PDF generation example given in the Puppeteer documentation, but it consistently fails at the page.pdf() part. I attempted running it with headless: false to track the process visually. Despite setting the timeout to 60000ms for both the launch method and the goto method, I still encounter the same 30000ms timeout error.

### Expectation

Generate the pdf and save it in the project folder.

### Reality

No pdf generated.

### Puppeteer version

22.10.0

### Node version

20.11.1

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Windows

**Comment by OrKoN** [comment] 2024-06-04 07:10
Probably duplicate of https://github.com/puppeteer/puppeteer/issues/12471

**Closed as not planned by OrKoN** 2024-06-04 07:10 UTC
Labels: needs-feedback, not-reproducible
