### ISSUE TITLE
Failed to launch chrome!

### ISSUE THREAD

**Issue by chemitaxis** [puppeteer/puppeteer#1085] opened 2017-10-18 09:57 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
"puppeteer": "^0.12.0"
* Platform / OS version:
AWS Elastic Beanstalk 64bit Amazon Linux 2017.03 v4.3.0 running Node.js 6.11.1
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.I have deploy the code in Elastic Beanstalk
2.Try to lauch puppeteer
3. Erro trying to open

**What is the expected result?**
Launch puppeteer

**What happens instead?**

I have this error in the logs:

> 0|printGen | Failed to launch chrome!
> 0|printGen | /var/app/current/node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux/chrome: error while loading shared libraries: libpangocairo-1.0.so.0: cannot open shared object file: No such file or directory
> 0|printGen | TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by ebidel** [comment] 2017-10-18 15:56
Dupe of https://github.com/GoogleChrome/puppeteer/issues/807

**Closed as completed by ebidel** 2017-10-18 15:56 UTC

**Comment by dhruv360code** [comment] 2022-10-15 18:47
could you pls tell me how you made it work ... i am having the same issue
