### ISSUE TITLE
[Bug]: Exception from a finished function: Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by mikiasgebre** [puppeteer/puppeteer#9447] opened 2022-12-21 11:31 UTC
### Bug description

Steps to reproduce the problem:

1. …
I have function use Cloud Scheduler run every min, every day deploy in Google Cloud Function.
In this function, I have use puppeteer and mostly, my function run well locally. When I deploy it to GCP. it throws this error without any more information: 
Exception from a finished function: Error: Failed to launch the browser process!

### Puppeteer version

18.2.1

### Node.js version

18.12.1

### npm version

8.19.2

### What operating system are you seeing the problem on?

Windows

### Configuration file

```JavaScript
name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "18"
  },
  "main": "index.js",
  "dependencies": {
    "chrome-aws-lambda": "^9.1.0",
    "firebase-admin": "^10.0.2",
    "firebase-functions": "^4.1.1",
    "puppeteer": "^18.2.1"
  },
  "devDependencies": {
    "firebase-functions-test": "^0.2.0"
  },
  "private": true
```

### Relevant log output

```Shell
Exception from a finished function: Error: Failed to launch the browser process!
```

**Comment by jrandolf** [comment] 2022-12-22 17:21
Duplicate of https://github.com/puppeteer/puppeteer/issues/9128

**Closed as not planned by jrandolf** 2022-12-22 17:21 UTC
