### ISSUE TITLE
Test "should send mouse wheel events" is failing on Windows for Firefox BiDi

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#12021] opened 2024-02-28 19:39 UTC
See for a failing run https://github.com/puppeteer/puppeteer/actions/runs/8086019769/job/22094839922?pr=12002#step:10:554

At first sight, it looks like nothing has changed except for the new version of Firefox released today and https://github.com/puppeteer/puppeteer/commit/1eb6a33aa0df10560b42008f54d4b4333ac10986 

Last passing day was 2 days ago: https://github.com/puppeteer/puppeteer/actions/runs/8086019769/job/22094839922?pr=12002#step:10:241

cc @whimboo

**Comment by whimboo** [comment] 2024-02-29 09:43
@OrKoN I can reproduce with the latest main pretty constantly but not with the 22.3.0 release. So I feel that this is a regression in Puppeteer. Note that it also fails with older Firefox Nightly builds and Puppeteer main.

**Comment by OrKoN** [comment] 2024-02-29 09:44
@whimboo could it be https://github.com/puppeteer/puppeteer/commit/1eb6a33aa0df10560b42008f54d4b4333ac10986?

**Comment by whimboo** [comment] 2024-02-29 09:48
Yes, I just bisected it to this revision and removing the preference makes it indeed pass. That's very interesting and shows that we really should not run both protocols at the same time. :/ 

I'll have a look what could cause this problem.

**Comment by OrKoN** [comment] 2024-02-29 09:53
Yep, confirmed in https://github.com/puppeteer/puppeteer/pull/12026 Let me know if you find anything. It looks like disabling that test is the way to go instead of reverting the protocol configuration.

**Comment by whimboo** [comment] 2024-02-29 11:12
Running the test with `slowMo` set to `2` makes it pass. So it's some kind of race that we see here.

When testing with `setTimeout` I have to put exactly 68ms between the mouse `move` and `wheel` action to make the test always pass in a loop of 20 iterations.

**Comment by whimboo** [comment] 2024-02-29 11:36
The problem is on our side. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1882748 to get this fixed ASAP.

@OrKoN If you are planning a new release today please backout the regressing revision.

**Comment by whimboo** [comment] 2024-03-05 06:42
@OrKoN the Nightly build with my fix landed and is available now. For me it no longer fails. Can you verify in CI (after cleaning the cache)?

**Comment by whimboo** [comment] 2024-03-05 11:09
The expectation got removed via https://github.com/puppeteer/puppeteer/commit/80d336a11bc50ddcbc8ed423c5a4ee4530637405. So this works fine.

**Closed as completed by whimboo** 2024-03-05 11:09 UTC
Labels: confirmed
