### ISSUE TITLE
Install Puppeteer without Chromium

### ISSUE THREAD

**Issue by hadalin** [puppeteer/puppeteer#614] opened 2017-08-30 12:44 UTC
In README there's 

>Puppeteer bundles Chromium to ensure that the latest features it uses are guaranteed to be available

but sometimes you still want to provide your own Chromium or don't trust `downloadURLs` in [ChromiumDownloader.js](https://github.com/GoogleChrome/puppeteer/blob/master/utils/ChromiumDownloader.js#L30).

Maybe I could even provide a PR, if this is something considered worth doing.

**Comment by Garbee** [comment] 2017-08-30 13:38
Duplicate of #244 

> don't trust downloadURLs in ChromiumDownloader.js.

On this though, those builds are ran by the Chromium team directly. So if you don't trust those downloads you don't trust Chromium in the first place.

**Closed as completed** 2017-08-30 14:25 UTC

**Comment by aslushnikov** [comment] 2017-08-30 18:11
@hadalin #606 will address this

**Comment by hadalin** [comment] 2017-08-30 18:32
Awesome 👍
