### ISSUE TITLE
[Bug]: Header and footertemplate bigger than body content even if both set to same px

### ISSUE THREAD

**Issue by JJTee** [puppeteer/puppeteer#9972] opened 2023-04-05 04:17 UTC
### Bug expectation

I expected header and footer content with text of font size 20px to look the same as body content of font size 20px.

Instead, the header and footer content appear about 25% larger than body content.

### Bug behavior

- [ ] Flaky
- [x] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer"

(async () => {
const header = `<style>div{ font-size: 20px; } p{margin-left: 1em}</style> <div> 
<p> Header/footer</p>
</div>`;

    const body = `<style>div{ font-size: 20px} p{margin-left: 1em}</style> <div>
   <p> Body content: This is a paragraph </p>
   </div>`;
    console.log("Starting browser");
    const browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
      ignoreDefaultArgs: ["--disable-extensions"],
    });
    const page = await browser.newPage();

    await page.setContent(body);

    await page.pdf({
      path: "test.pdf",
      displayHeaderFooter: true,
      headerTemplate: header,
      footerTemplate: header,
      format: "a4",
      margin: {
        top: "100mm",
      },
      printBackground: true,
    });
    await browser.close();
})();
```

### Error string

no error

### Puppeteer version

19.8.3

### Node version

18.15.4

### Package manager

npm

### Package manager version

8.19.2

### Operating system

macOS

**Comment by OrKoN** [comment] 2023-04-05 12:15
Duplicate of https://github.com/puppeteer/puppeteer/issues/9481

**Closed as not planned by OrKoN** 2023-04-05 12:15 UTC
Labels: needs-feedback, not-reproducible

**Comment by codeart1st** [comment] 2024-06-21 13:21
Since Chrome 117+ it's fixed. No need to scale the content with 1.333f

https://github.com/chromium/chromium/commit/f6529c7990744370869e4ab2794caae6c46ba044
