### ISSUE TITLE
Chrome crashes/restarts when generating PDFs

### ISSUE THREAD

**Issue by davidwindell** [puppeteer/puppeteer#1060] opened 2017-10-17 08:59 UTC
We're seeing intermittent sporadic crashing of Chrome when generating PDF's. 

Puppeteer reports `Protocol error (Page.printToPDF): Session closed. Most likely the page has been closed.` and this is what we can see from the Docker container logs that hosts our Chrome instance.

```
17/10/2017 09:44:49  r8: 00000000000000f8  r9: 00000000000000f8 r10: 0000000000000100 r11: 00000000000001ff
17/10/2017 09:44:49 r12: 0000000000000400 r13: 0000000000000000 r14: 0000000000000100 r15: 00000000ffffffff
17/10/2017 09:44:49  di: 00007fc383559000  si: 00000000ffffffff  bp: 00007fc383559000  bx: 00000000000000c9
17/10/2017 09:44:49  dx: 0000000000000100  ax: 00007fc383559000  cx: 0000000000000140  sp: 00007fc385883da8
17/10/2017 09:44:49  ip: 000055c2e72d29a0 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000006
17/10/2017 09:44:49 trp: 000000000000000e msk: 0000000000000000 cr2: 00007fc383559000
17/10/2017 09:44:49[end of stack trace]
17/10/2017 09:44:49Calling _exit(1). Core file will not be generated.
17/10/2017 09:44:57Received signal 7 BUS_ADRERR 7fc383984000
17/10/2017 09:44:57#0 0x55c2e8ab4857 base::debug::StackTrace::StackTrace()
17/10/2017 09:44:57#1 0x55c2e8ab43bf base::debug::(anonymous namespace)::StackDumpSignalHandler()
17/10/2017 09:44:57#2 0x7fc39797b890 <unknown>
17/10/2017 09:44:57#3 0x55c2e72d29a0 avx::memset32()
17/10/2017 09:44:57#4 0x55c2e8bdea51 SkARGB32_Blitter::blitRect()
17/10/2017 09:44:57#5 0x55c2e8c5bdac antifilldot8()
17/10/2017 09:44:57#6 0x55c2e8c5b6bb Received signal 7 BUS_ADRERR 7f5096f0e000
17/10/2017 09:44:57#0 0x5619dd20e857 SkScan::AntiFillRect()
17/10/2017 09:44:57#7 0x55c2e8bd007d base::debug::StackTrace::StackTrace()
17/10/2017 09:44:57#1 0x5619dd20e3bf base::debug::(anonymous namespace)::StackDumpSignalHandler()
17/10/2017 09:44:57#2 0x7f50b241a890 <unknown>
17/10/2017 09:44:57#3 0x7f50ac1cf049 <unknown>
17/10/2017 09:44:57#4 0x5619dd9d1084 SkDraw::drawRect()
17/10/2017 09:44:57#8 0x55c2e8bbe116 net::HttpStreamParser::DoReadBody()
17/10/2017 09:44:57#5 0x5619dd9d0a36 SkBitmapDevice::drawRect()
17/10/2017 09:44:57#9 0x55c2e8bb85b3 net::HttpStreamParser::DoLoop()SkCanvas::onDrawRect()
17/10/2017 09:44:57#10 0x55c2e8bb64fd
17/10/2017 09:44:57#6 0x5619dd9d0c6a SkCanvas::drawRect()
17/10/2017 09:44:57#11 0x55c2e8c730c3 net::HttpStreamParser::ReadResponseBody()
17/10/2017 09:44:57#7 0x5619dd9b2523 SkColorSpaceXformCanvas::onDrawRect()
17/10/2017 09:44:57#12 0x55c2e8bb64fd SkCanvas::drawRect()
17/10/2017 09:44:57#13 0x55c2e913863d cc::$_14::__invoke()
17/10/2017 09:44:57#14 0x55c2e9137b39 net::HttpNetworkTransaction::DoLoop()
17/10/2017 09:44:57#8 0x5619dd9b3023 cc::PaintOpBuffer::Playback()
17/10/2017 09:44:57#15 0x55c2e9137b39 net::HttpNetworkTransaction::Read()
17/10/2017 09:44:57#9 0x5619dd9a7495 cc::PaintOpBuffer::Playback()
17/10/2017 09:44:57#16 0x55c2e97776e0 net::HttpCache::Transaction::DoNetworkRead()
17/10/2017 09:44:57#10 0x5619dd9a1b6e cc::DisplayItemList::Raster()
17/10/2017 09:44:57#17 0x55c2e9776bc1 net::HttpCache::Transaction::DoLoop()
17/10/2017 09:44:57#11 0x5619dd9a2aec cc::RasterSource::PlaybackToCanvas()
17/10/2017 09:44:57#18 0x55c2e9776ad7 net::HttpCache::Transaction::Read()
17/10/2017 09:44:57#12 0x5619ddac31d0 cc::RasterSource::PlaybackToCanvas()
17/10/2017 09:44:57#19 0x55c2e97a55e7 net::URLRequestHttpJob::ReadRawData()
17/10/2017 09:44:57#13 0x5619ddabeb63 cc::RasterBufferProvider::PlaybackToMemory()
17/10/2017 09:44:57#20 0x55c2e97b70e7 cc::(anonymous namespace)::RasterBufferImpl::Playback()
17/10/2017 09:44:57#21 0x55c2e97760a3 net::URLRequestJob::ReadRawDataHelper()
17/10/2017 09:44:57#14 0x5619ddabdbaf cc::(anonymous namespace)::RasterTaskImpl::RunOnWorkerThread()
17/10/2017 09:44:57#22 0x55c2ec07cb57 net::URLRequestJob::Read()
17/10/2017 09:44:57#15 0x5619ddab7748 net::URLRequest::Read()
17/10/2017 09:44:57#16 0x5619dc22655a content::ResourceLoader::ReadMore()
17/10/2017 09:44:58#17 0x5619dc226832 content::CategorizedWorkerPool::RunTaskInCategoryWithLockAcquired()
17/10/2017 09:44:58#23 0x55c2ec07bc9a content::ResourceLoader::PrepareToReadMore()
17/10/2017 09:44:58#18 0x5619dc2259bd content::ResourceLoader::CompleteResponseStarted()
17/10/2017 09:44:58#19 0x5619dc22555a content::ResourceLoader::OnResponseStarted()
17/10/2017 09:44:58#20 0x5619ddabe565 net::URLRequestJob::NotifyHeadersComplete()
17/10/2017 09:44:58#21 0x5619ddac1ff2 content::CategorizedWorkerPool::Run()
17/10/2017 09:44:58#24 0x55c2e8b1a050 net::URLRequestHttpJob::SaveCookiesAndNotifyHeadersComplete()
17/10/2017 09:44:58#22 0x5619ddac18df base::SimpleThread::ThreadMain()
17/10/2017 09:44:58#25 0x55c2e8b15c63 base::(anonymous namespace)::ThreadFunc()
17/10/2017 09:44:58#26 0x7fc397974064 start_thread
17/10/2017 09:44:58#27 0x7fc39178662d clone
17/10/2017 09:44:58  r8: 00000000000000f8  r9: 00000000000000f8 r10: 0000000000000100 r11: 00000000000000fd
17/10/2017 09:44:58 r12: 0000000000000400 r13: 0000000000000000 r14: 0000000000000100 r15: 00000000ffffffff
17/10/2017 09:44:58  di: 00007fc383984000  si: 00000000ffffffff  bp: 00007fc383984000  bx: 0000000000000021
17/10/2017 09:44:58  dx: 0000000000000100  ax: 00007fc383984000  cx: 0000000000000140  sp: 00007fc385883da8
17/10/2017 09:44:58  ip: 000055c2e72d29a0 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000006
17/10/2017 09:44:58 trp: 000000000000000e msk: 0000000000000000 cr2: 00007fc383984000
17/10/2017 09:44:58[end of stack trace]
17/10/2017 09:44:58Calling _exit(1). Core file will not be generated.
17/10/2017 09:44:58net::URLRequestHttpJob::OnStartCompleted()
17/10/2017 09:44:58#23 0x5619dd9a1cd5 net::HttpCache::Transaction::DoLoop()
17/10/2017 09:44:58#24 0x5619dd9b1b94 net::HttpNetworkTransaction::OnIOComplete()
17/10/2017 09:44:58#25 0x5619dd9cff8e net::HttpStreamParser::OnIOComplete()
17/10/2017 09:44:58#26 0x5619dd8fbd0c net::SSLClientSocketImpl::DoReadCallback()
17/10/2017 09:44:58#27 0x5619dd8fbb09 net::SSLClientSocketImpl::RetryAllOperations()
17/10/2017 09:44:58#28 0x5619dda6af6e net::TCPClientSocket::DidCompleteRead()
17/10/2017 09:44:58#29 0x5619dda6c85f net::TCPSocketPosix::ReadIfReadyCompleted()
17/10/2017 09:44:58#30 0x5619dda6ea87 net::SocketPosix::OnFileCanReadWithoutBlocking()
17/10/2017 09:44:58#31 0x5619dd22bd2e base::MessagePumpLibevent::OnLibeventNotification()
17/10/2017 09:44:58#32 0x5619dd2a6cfe event_base_loop
17/10/2017 09:44:58#33 0x5619dd22c025 base::MessagePumpLibevent::Run()
17/10/2017 09:44:58#34 0x5619dd249985 base::RunLoop::Run()
17/10/2017 09:44:58#35 0x5619dc074a36 content::BrowserThreadImpl::IOThreadRun()
17/10/2017 09:44:58#36 0x5619dc074c31 content::BrowserThreadImpl::Run()
17/10/2017 09:44:58#37 0x5619dd274a0a base::Thread::ThreadMain()
17/10/2017 09:44:58#38 0x5619dd26fc63 base::(anonymous namespace)::ThreadFunc()
17/10/2017 09:44:58#39 0x7f50b2413064 start_thread
17/10/2017 09:44:58#40 0x7f50ac22562d clone
17/10/2017 09:44:58  r8: 0000000000000000  r9: 00000000000007a7 r10: 00000000000020bc r11: 0000000000001914
17/10/2017 09:44:58 r12: 0000000000008000 r13: 00003643fdfad030 r14: 00007f5096f0e000 r15: 0000000000000e5f
17/10/2017 09:44:58  di: 00007f5096f0e000  si: 00003643fdf5b1a1  bp: 0000000000000e5f  bx: 00003643fdfaa8c0
17/10/2017 09:44:58  dx: 0000000000000e5f  ax: ffffb6f36704c342  cx: 0000000000001cbe  sp: 00007f509d31d7f8
17/10/2017 09:44:58  ip: 00007f50ac1cf049 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000006
17/10/2017 09:44:58 trp: 000000000000000e msk: 0000000000000000 cr2: 00007f5096f0e000
17/10/2017 09:44:58[end of stack trace]
17/10/2017 09:44:58Calling _exit(1). Core file will not be generated.
17/10/2017 09:44:59DevTools listening on ws://0.0.0.0:9222/devtools/browser/guid-obfuscated
```

Puppeteer connects remote to this Chrome instance from multiple PHP processes to generate PDF's on demand.

Are the container logs any use or is there a better way to get a more detailed crash reason? 

* Puppeteer version: `0.12.0`
* Platform / OS version: `node:8-slim`

**Comment by tglines** [comment] 2017-11-06 19:56
Had a similar issue.  Had to up the space given to `/dev/shm` by Docker, then things worked fine.  
See: https://github.com/GoogleChrome/puppeteer/issues/1024

**Comment by aslushnikov** [comment] 2017-11-07 10:21
Thanks, closing as a dupe of #1024.

**Closed as completed by aslushnikov** 2017-11-07 10:21 UTC

**Comment by davidwindell** [comment] 2017-11-07 10:24
I'll try mounting /dev/shm into the container as --shm-size isn't support on Rancher
