### ISSUE TITLE
[Bug]: Consecutive alerts won't work

### ISSUE THREAD

**Issue by allenelguira16** [puppeteer/puppeteer#9524] opened 2023-01-17 05:39 UTC
### Bug expectation

I expected that there should be two alerts, first was a confirm alert and next is a normal alert. but only first one was executed

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
// sample.js
const puppeteer = require("puppeteer");

const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

(async () => {
  const browser = await puppeteer.launch({ headless: false, slowMo: 100 });
  const page = await browser.newPage();
  page.on('dialog', async (dialog) => {
    console.log(dialog.message());
    await dialog.accept();
  });
  
  await page.goto("test.html", {waitUntil: 'networkidle2'});
  await browser.close();
})();

// test.html
<script>
  if (window.confirm("confirm")) {
    alert('test')
  }
</script>
```

### Error string

no error

### Puppeteer configuration

```TypeScript
launch: {
    dumpio: true,
    headless: false,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-software-rasterizer',
      '--disable-gpu',
      '--start-maximize',
    ],
    defaultViewport: {
      width: 1920,
      height: 1080,
    },
  },
  browserContext: 'default',
```

### Puppeteer version

19.4.1

### Node version

18.12.1

### Package manager

yarn

### Package manager version

3.3.1

### Operating system

Linux

**Comment by AllenKunn16** [comment] 2023-01-17 06:19
Sorry for bugging, it was not a bug. I misunderstood the dialog

I'll close this ticket

**Closed as completed by AllenKunn16** 2023-01-17 06:19 UTC
Labels: needs-feedback, not-reproducible
