### ISSUE TITLE
[Bug]: page.authentication hangs when using NTLM authentication

### ISSUE THREAD

**Issue by teh-obeng** [puppeteer/puppeteer#11626] opened 2024-01-04 08:14 UTC
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

const url = "my-ntlm-url.com";
const username = `${domain}\\${username}`;
const password = "password";

(async () => {
    process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
    const browser = await puppeteer.launch({
      executablePath: "/usr/bin/google-chrome",
      ignoreHTTPSErrors: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        '--auth-server-allowlist="*"',
        '--auth-schemes="digest,ntlm,negotiate"',
      ],
    });
    const page = await browser.newPage();

    // Navigate to the site
    await page.authenticate({
      username,
      password,
    });
    console.log("page.authenticate called");
    await page.goto(url);
    console.log("After goto");
})();
```

### Error string

TimeoutError: Navigation timeout of 30000 ms exceeded

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I've been trying to visit a website that is protected using NTLM authentication. When visiting the url using my laptop's browser it will prompt out login dialog (kinda like basic auth dialog), and when i input the credentials it can works and site can be opened.

But when i use the same credentials using pupeteer, it stucks at `page.authenticate` and then timeout after 30 secs.

Browser version: HeadlessChrome/120.0.6099.129

### Expectation

console.log("After goto");

should be executed

### Reality

TimeoutError: Navigation timeout of 30000 ms exceeded

### Puppeteer version

21.6.1

### Node version

20.10.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

macOS

**Comment by OrKoN** [comment] 2024-01-04 09:07
Is there a test page that requires NTLM authentication?

**Comment by HowardCsie** [comment] 2024-03-05 07:15
same issue here

**Comment by OrKoN** [comment] 2024-03-05 08:17
> Since 2010, Microsoft no longer recommends NTLM in applications

Source: https://en.wikipedia.org/wiki/NTLM

Since there is no reproducible example/available NTLM URL and it is not possible for us to set NTLM up, closing as won't fix. The root cause is probably also in Chrome and not in Puppeteer.

**Closed as not planned by OrKoN** 2024-03-05 08:17 UTC
Labels: needs-feedback, not-reproducible

**Comment by RichardLam007** [comment] 2024-06-10 22:03
it's definitely an issue in Puppeteer as it's not an issue in Playwright with Chrome browser.

**Comment by jlanssie** [comment] 2025-06-27 18:54
I also have this issue. Puppeteer cannot handle NTLM afaik.

**Comment by leonmeijer** [comment] 2025-06-27 19:12
We have it working, can share more on Monday. In a Linux container.

**Comment by jlanssie** [comment] 2025-06-29 20:38
> We have it working, can share more on Monday. In a Linux container.

Looking forward to your workaround / fix 😁
