### ISSUE TITLE
page.screenshot() The specified area screenshot is wrong

### ISSUE THREAD

**Issue by xuxk1** [puppeteer/puppeteer#7542] opened 2021-09-03 01:35 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:10.0.0
* Platform / OS version:Windows 10
* URLs (if applicable):
* Node.js version:v14.15.4

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

'use strict'

const puppeteer = require('puppeteer');
const { expect } = require('chai');
require('mocha-allure-reporter');
const BaiDu = require('../../common/common.js');
const log4js = require('log4js');
const logger = log4js.getLogger();
logger.level = 'info'

describe('Baidu search', () => {

    let browser;
    let page;

    before(async () => {
        browser = await puppeteer.launch({ headless: false, args: [`--window-size=1680,1050`] });
        page = await browser.newPage();
        await page.setViewport({
            width: 1680,
            height: 1042,
            deviceScaleFactor: 1,
            isLandscape: true
        });
        await page.goto('https://www.baidu.com');
        logger.info('打开页面111');
    });

    after(async () => {
        await browser.close();
        logger.info('关闭页面');
    });

    function sleep(ms) {
        return new Promise(resolve => {
            setTimeout(resolve, ms)
        })
    }

    it('page title', async () => {
        const baiDu = new BaiDu(page);
        expect(await baiDu.getTitle()).to.eql('百度一下，你就知道');
        await sleep(5000);
        let img = await page.$('#head_wrapper > div > div');
        await img.screenshot({
            path: 'images/baidu.png'
        });
    });
});

**What is the expected result?**
![image](https://user-images.githubusercontent.com/39721418/131937279-52dd7e29-6af7-46c9-b31e-04c33733f458.png)

**What happens instead?**
![image](https://user-images.githubusercontent.com/39721418/131937207-f1883395-aa88-4de7-87af-ef07869e7c40.png)

**Comment by xuxk1** [comment] 2022-07-05 07:24
> We're marking this issue as unconfirmed because it has not had recent activity and we weren't able to confirm it yet. It will be closed if no further activity occurs within the next 30 days.

OK

**Comment by OrKoN** [comment] 2022-08-02 08:32
it looks like this should be marked as confirmed!

**Comment by OrKoN** [comment] 2024-03-23 15:41
It looks like the bug was fixed and I am not able to reproduce it in the latest version.

**Closed as completed by OrKoN** 2024-03-23 15:41 UTC
Labels: screenshot, confirmed
