### ISSUE TITLE
Send form data as POST programatically 'as if' the form was filled out OR use custom html to send form post?

### ISSUE THREAD

**Issue by voordev** [puppeteer/puppeteer#2146] opened 2018-03-06 09:03 UTC
**Since I have still issues with puppeteer not be able to select all form elements on a page even though they are there I have thought of several workarounds.**

My idea now is to submit form data as if the form was filled, thus, get around the not being able to find all the required selectors.  I found some examples and documentation on how this can be done. 
What would be the best approach...

I think of 2 solutions:

1. Send a custom POST to the URL the form normally would be send to, thus, not filling in any fields but setting the values manually in the POST. Found this in the documentation:
```
 // SUBMIT FORM DATA
    await page.setRequestInterception(true);
    page.on('request', request => {
        const overrides = {};
            overrides.method = 'POST';
            overrides.postData = 'a=b&c=d';
        request.continue(overrides);
    });
```

2. **Use a custom html snippet with all the form fields... inject this in the 'real world' page and use this instead to send the form data?**

**Comment by ebidel** [comment] 2018-03-10 17:46
Please ask questions like this on SO for the slack channel. Closing as this is not a bug or feature request.

**Closed as completed by ebidel** 2018-03-10 17:46 UTC
