### ISSUE TITLE
puppeteer 1.6+ with new chromium version is missing request and response events.

### ISSUE THREAD

**Issue by nlack** [puppeteer/puppeteer#2966] opened 2018-07-27 11:48 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
1.5 and 1.6.1
* Platform / OS version:
arch linux kernel 4.14
* URLs (if applicable):
google.com
* Node.js version:
8.4

**What steps will reproduce the problem?**
Count the events triggered when visiting google.com.
- request
- requestfinished
- requestfailed
- response

_Please include code that reproduces the issue._
```
'use strict';

const Puppeteer = require("puppeteer");


async function run() {
	let requestCounter = 0;
	let requestFailedCounter = 0;
	let requestFinishedCounter = 0;
	let responseCounter = 0;

	const browser = await Puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
	const page = await browser.newPage();
	page.setRequestInterception(true);

	page.on('request', (request) => {
		requestCounter++;

		request.continue();
	});

	page.on('response', (response) => {
		responseCounter++;
	});

	page.on('requestfailed', (request) => {
		requestFailedCounter++;
	});

	page.on('requestfinished', (request) => {
		requestFinishedCounter++;
	});

	await page.goto('https://google.com/');
	await page.waitFor(3500);

	console.log("requests: [" + requestCounter + "].");
	console.log("requestsFailed: [" + requestFailedCounter + "].");
	console.log("requestsFinished: [" + requestFinishedCounter + "].");
	console.log("responses: [" + responseCounter + "].");
}


try {
	run().then(() => { process.exit(0); });
} catch (err) {
	console.error(err);
}
```
**What is the expected result?**
In version 1.5 with chrome version (HeadlessChrome/69.0.3452.0) the output is:
```
requests: [19].
requestsFailed: [0].
requestsFinished: [19].
responses: [19].
```
**What happens instead?**
In version 1.6+ with chrome version (HeadlessChrome/69.0.3494.0) the output is:
```
requests: [20].
requestsFailed: [0].
requestsFinished: [5].
responses: [5].
```

When using the 1.5 chromium binary in the 1.6+ test the result is as expected.

**Comment by JoelEinbinder** [comment] 2018-07-27 21:07
@caseq Looks like something about redirects. Maybe working as intended?

**Comment by slyrz** [comment] 2018-07-28 10:33
I bisected this down to:
https://chromium.googlesource.com/chromium/src/+/78044c8325af946ace4dd560856572a76af07386

Builds up to 565834 show 19 responses, builds starting at 565837 show 5 responses.

5 responses... 5 hosts? Looks like once cookies are set, responses to the follow-up requests go unreported. I can't build Chromium right now, but I guess after delaying the start with

```c++
store->GetCookieListWithOptionsAsync(
    request_details_.url, options,
    base::BindOnce(&DevToolsURLInterceptorRequestJob::StartWithCookies,
                   weak_ptr_factory_.GetWeakPtr()));
```

the cookie store never runs the callback.

**Comment by aslushnikov** [comment] 2018-07-31 00:08
Dupe of #2970.

@slyrz thanks for bisecting!

**Closed as completed by aslushnikov** 2018-07-31 00:08 UTC
