### ISSUE TITLE
Full page screenshots on pages that make use of 100vh

### ISSUE THREAD

**Issue by hgascoigne** [puppeteer/puppeteer#1559] opened 2017-12-08 21:38 UTC
This might be a more generic Chrome bug, but I'm running into it during my experience with puppeteer, so I apologize if it's outside of the scope of this project.

Certain websites that I am trying to render full page screenshots for are not rendering correctly due to their use of `100vh` on containers. I'm assuming this is because before taking a screenshot it sets the viewport height to the height of the entire scrollable page? This causes the `100vh` container to be incredibly tall, which of course breaks the layout of the page. Rendering non-full page screenshots pose no issue.

Is there any possibility to handle this issue without having to manually stitch together multiple smaller screenshots?

**Comment by ebidel** [comment] 2017-12-08 22:52
This is more of a "bug" in headless Chrome, but also expected due to the reasons you mentioned.

100vh gets pretty tricky. The opposite is described in https://github.com/GoogleChrome/puppeteer/issues/746 where the page users a 100vh/100vw container with overflow children content. The full page screenshot result turns out to be just the viewport width/height.

I'm not sure Puppeteer can provide solutions for these edge cases. You may have to stick multiple screenshots together for cases like this :\

**Comment by aslushnikov** [comment] 2017-12-11 08:50
Dupe of #703

**Closed as completed by aslushnikov** 2017-12-11 08:50 UTC
