### ISSUE TITLE
The request stop on first request when set request interception 

### ISSUE THREAD

**Issue by AonzVongsunthorn** [puppeteer/puppeteer#2849] opened 2018-07-06 10:00 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4.0 and 1.5.0
* Platform / OS version: Ubuntu 16.04.6
* URLs (if applicable): - 
* Node.js version:8.11.1

**What steps will reproduce the problem?**

It's working fine if I disabled request interception.
But after i enabled request interception that will stop at first request.
If i run with none-headless it's working fine too.
I not sure the problem related with ignoreHTTPSErrors option or not.

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');
let browser = await puppeteer.launch({ignoreHTTPSErrors: true, args: ['--disable-setuid-sandbox', '--no-sandbox']});
// let browser = await puppeteer.launch({headless: false}, {args: ['--no-sandbox', '--disable-setuid-sandbox']});
let page = await browser.newPage();
let isNeedRequestInterception = true; // just for easier to test, set true means enable request interception.
let url = 'https://www.g l - i n e t.com'.replace(/\s/g, '');

if(isNeedRequestInterception) {

    await page.setRequestInterception(true);

}

page.on('request', interceptedRequest => {

    console.log('request to', interceptedRequest.url());
    if(isNeedRequestInterception) {

         interceptedRequest.continue();

    }

});

console.log('Starting to go-to ->', url);
await page.goto(url, {'waitUntil': 'networkidle0', 'timeout': 0}).catch(e => {

    console.log(e.toString());

});

console.log('Finished to go to -> ', url);
await page.close();
await browser.close();

```

**What is the expected result?**
Should list all the requests and display **Finished to go to -> gl-inet.com**

**Comment by pomerantsev** [comment] 2018-07-08 04:44
@aslushnikov this seems to be related to #1137, and it's still an issue. It's probably a combination of the OS, the website certificate, and the headless mode, because I could only reproduce it on Ubuntu (not on MacOS), only for the above mentioned website (not for others I tested), and only in headless.

Here's a shorter version of the code that's causing issues:
```const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const url = 'https://www.gl-inet.com';
  try {
    await page.goto(url);
    await page.screenshot({path: './test.png'});
  } catch (e) {
    console.log(e.toString());
  }
  await page.close();
  await browser.close();
})();
```

On Ubuntu, it produces the following message: `Error: net::ERR_CERT_AUTHORITY_INVALID at https://www.gl-inet.com`.

But that's not the whole story.

We can make the above code behave by launching Puppeteer with `ignoreHTTPSErrors: true`. If we do so, the screenshot is taken, and everything looks good.

However, as @AonzVongsunthorn mentioned, it doesn't work as well with request interception. So if we simply add two lines to the above code:
```...
const page = await browser.newPage();
await page.setRequestInterception(true);
page.on('request', req => req.continue());
const url = ...
```

then execution hangs, and no screenshot is taken.

Not sure whether it's a single issue, or two unrelated issues, but the behavior's buggy anyway.

**Comment by AonzVongsunthorn** [comment] 2018-07-09 05:34
Currently, I'm enabled NetworkService when lunch the browser. 

```
let browser = await puppeteer.launch({ignoreHTTPSErrors: true, args: ['--disable-setuid-sandbox', '--no-sandbox', '--enable-features=NetworkService']});

const page = await browser.newPage();

.......
```
Then It's work fine for me.

Now i searching more detail about NetworkService.
And i not found too much the detail about NetworkService, so if someone know about any impact please let's me know.

**Comment by aslushnikov** [comment] 2018-07-19 03:03
@pomerantsev thanks for the research. This is indeed a dupe of #1159.

**Closed as completed by aslushnikov** 2018-07-19 03:03 UTC
