### ISSUE TITLE
Puppeteer does not work with heroku

### ISSUE THREAD

**Issue by zenrshon** [puppeteer/puppeteer#9204] opened 2022-11-03 02:06 UTC
### Bug description

I set up the buildpack and arguments according to the following
heroku 20 (tried 22)

https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-heroku

<img width="827" alt="image" src="https://user-images.githubusercontent.com/29056651/199634789-f3ad3d4b-b1cb-4620-a029-35328e602574.png">
<img width="407" alt="image" src="https://user-images.githubusercontent.com/29056651/199634827-5f3dff62-399d-43a8-9389-8c3ef4f6b913.png">

However, the only errors that appear are the following

```2022-11-03T01:37:14.067684+00:00 app[web.1]: /app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:120
2022-11-03T01:37:14.067688+00:00 app[web.1]: throw new Error(`Run \`npm install\` to download the correct Chromium revision (${this.puppeteer.browserRevision}).`);
2022-11-03T01:37:14.067688+00:00 app[web.1]: ^
2022-11-03T01:37:14.067689+00:00 app[web.1]: 
2022-11-03T01:37:14.067690+00:00 app[web.1]: Error: Run `npm install` to download the correct Chromium revision (1056772).
2022-11-03T01:37:14.067691+00:00 app[web.1]: at ChromeLauncher.resolveExecutablePath (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:120:27)
2022-11-03T01:37:14.067691+00:00 app[web.1]: at ChromeLauncher.executablePath (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:166:25)
2022-11-03T01:37:14.067691+00:00 app[web.1]: at ChromeLauncher.launch (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:70:37)
2022-11-03T01:37:14.067693+00:00 app[web.1]: at async Object.getContractInWebsite [as func] (/app/xxx/xxx.js:7:21)
2022-11-03T01:37:14.067693+00:00 app[web.1]: at async /app/index.js:142:20
2022-11-03T01:37:14.067699+00:00 app[web.1]: 
2022-11-03T01:37:14.067700+00:00 app[web.1]: Node.js v18.12.0
```

Is there something wrong with the settings?
I have already spent more than 3 hours...

### Puppeteer version

19.2.1

### Node.js version

v18.12.0

### npm version

8.15.0

### What operating system are you seeing the problem on?

Linux

**Comment by jrandolf** [comment] 2022-11-03 07:59
Duplicate of https://github.com/puppeteer/puppeteer/issues/9162

**Closed as completed by jrandolf** 2022-11-03 07:59 UTC
