### ISSUE TITLE
Can Puppeteer intercept post data from background worker ?

### ISSUE THREAD

**Issue by masnampi** [puppeteer/puppeteer#3701] opened 2018-12-22 22:58 UTC
Can Puppeteer intercept post data from background worker ? i have try to use page.on("request") but not catch the background worker request

i want to modifiy the post data

how to do that ?

**Comment by aslushnikov** [comment] 2019-01-10 01:34
This is a dupe of #2781. Please upvote it to bump priority.

**Closed as completed by aslushnikov** 2019-01-10 01:34 UTC
