### ISSUE TITLE
[Bug]: Headless False/True

### ISSUE THREAD

**Issue by ehotedas** [puppeteer/puppeteer#9980] opened 2023-04-05 16:54 UTC
### Bug expectation

My code when I use headless:false it works and downloads the .txt file, however, when I use it in true, it doesn't download the file.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
        ignoreHTTPSErrors: true, // ignorar erros de certificado SSL
        headless: true, // desativar o modo headless para ver a página em ação
        args: [
          '--ignore-certificate-errors',
          '--disable-features=site-per-process', // desativar as restrições de download em headless mode
          '--disable-web-security', // desativar segurança da web
          '--allow-file-access-from-files' // permitir acesso a arquivos locais
        ], // ignorar erros de certificado SSL
        executablePath: 'C:/Users/gabriel/Downloads/chrome-win/chrome-win/chrome.exe' // caminho para o executável do Chromium
      });
      
      const page = await browser.newPage();
    
      await page.goto('https://192.168.3.252/');
    
      await page.waitForTimeout(3000);
    
      const result = await page.evaluate(() => {
        var dvBlock = blockPage('Autenticando dados');
    
        SendJSON('login', {
          login: 'admin',
          password: 'admin'
        }, function(result) {
          logando = false;
          if (result && 'session' in result) {
            setCookie('session', result.session, 1);
            setCookie('login', 'admin');
            if ($('#page_login #remember').is(':checked'))
              setCookie('password', 'admin');
            window.location.hash = 'page=users';
            unblockPage(dvBlock, function() {
              $('#page_login #div_alert').removeClass('hide');
              GetPage();
            });
          }
        })
    
      });
    
      await page.waitForTimeout(3000); // espera 3 segundos
    
        page.evaluate(() => getAFD("Aguarde, baixando AFD completo...", {}))
    

})();
      
```

### Error string

it doesn't download the file.

### Puppeteer configuration

```TypeScript
const browser = await puppeteer.launch({
        ignoreHTTPSErrors: true, // ignorar erros de certificado SSL
        headless: true, // desativar o modo headless para ver a página em ação
        args: [
          '--ignore-certificate-errors',
          '--disable-features=site-per-process', // desativar as restrições de download em headless mode
          '--disable-web-security', // desativar segurança da web
          '--allow-file-access-from-files' // permitir acesso a arquivos locais
        ], // ignorar erros de certificado SSL
        executablePath: 'C:/Users/gabriel/Downloads/chrome-win/chrome-win/chrome.exe' // caminho para o executável do Chromium
      });
```

### Puppeteer version

Latest

### Node version

Latest

### Package manager

npm

### Package manager version

Latest

### Operating system

Windows

**Comment by OrKoN** [comment] 2023-04-05 18:39
Looks like a duplicate of https://github.com/puppeteer/puppeteer/issues/299 In general, there is no good way to do but there is a workaround involving setting the download behaviour via CDP.

**Closed as not planned by OrKoN** 2023-04-05 18:39 UTC
