### ISSUE TITLE
[Bug]: crash on PDF render

### ISSUE THREAD

**Issue by VagrantAI-c** [puppeteer/puppeteer#8531] opened 2022-06-16 07:36 UTC
### Bug description

Steps to reproduce the problem:

1. clone https://github.com/VagrantAI-c/Puppeteer-pdf-render-repro
2. run `npm ci`
3. run `npm run build`
4. run `npm run serve`

Reproduce from scratch:
```typescript
import { launch } from 'puppeteer';

(async () => {
  const browser = await launch({
    headless: true,
    args: [
      '--disable-gpu',
      '--disable-dev-shm-usage',
      '--disable-setuid-sandbox',
      '--no-sandbox',
    ],
  });
  const page = await browser.newPage();
  const content = '<!doctype html><html lang="en"><head></head><body><h1>Test</h1></body></html>';
  await page.setContent(content, { waitUntil: 'networkidle0' });
  await page.pdf({ format: 'a4' });
  await page.close();
})();
```

This error is happening on https://github.com/puppeteer/puppeteer/blob/ce0dd25349b3141409cf68121a2bf9a770d9ecf7/src/common/util.ts#L387 while running `await page.pdf({ format: 'a4' });`

### Puppeteer version

14.4.0

### Node.js version

18.3.0

### npm version

8.11.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
\dist\main.js:3113
    return new Readable({
           ^

TypeError: Readable is not a constructor
    at Object.getReadableFromProtocolStream (\dist\main.js:3113:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Page.pdf (\dist\main.js:6019:26)
    at async \dist\main.js:35011:5
```

**Comment by OrKoN** [comment] 2022-06-24 10:12
I am not sure exactly why but webpack does not seem to process the dynamic import correctly. Instead of returning the default export, it returns an object that includes `{default: StreamModule}`. I am not very familiar with webpack but perhaps it could be solved by fixing the configuration?

**Comment by VagrantAI-c** [comment] 2022-06-24 10:35
It also might be involved with Typescript configuration. I don't know if there's a correct or incorrect config: Puppeteer doesn't provide working solutions and examples with bundlers, so I believe any config should be fine by default. Moreover, this config produces correct and working output at Puppeteer@13.4.1

**Comment by OrKoN** [comment] 2022-06-24 10:44
Yeah, we don't officially support bundlers (e.g., we don't run tests with them) but we also try to fix issues whenever possible. We made changes to TypeScript configs to support ESM alongside CJS so perhaps it caused it but it's hard to say where exactly the problem is. Which build output (esm or cjs) does webpack use in your example?

**Comment by VagrantAI-c** [comment] 2022-06-24 11:44
I don't know exactly, but I tried some experiments on [Typescript `module` option](https://www.typescriptlang.org/tsconfig#module): changing it from `es2022` to `nodenext`/`node16` helps, but I can't tell exactly why.

**Comment by OrKoN** [comment] 2022-06-24 11:54
perhaps @jrandolf has an idea! Great that there is a workaround.

**Comment by sonrai-samroutledge** [comment] 2022-06-30 15:21
I am seeing this same error in version 14.4.1; downgrading to 13.7.0 resolved it for me.

**Comment by imtanmoy** [comment] 2022-07-28 10:46
I am having the same issue.

**Comment by pjg** [comment] 2022-08-13 16:44
I have also run into this issue. It occurs when webpack (v5 on my end) bundles puppeteer. I have solved it by explicitly declaring a webpack ignore directive when importing a file which uses puppeteer. I did this via dynamic es import, but a static one could be done in a very similar way:

```javascript
const loadModule = async (modulePath) => {
  try {
    return await import(/* webpackIgnore: true */ modulePath)
  } catch (e) {
    throw new ImportError(`Unable to import module ${modulePath}`)
  }
}

const renderPdf = (await loadModule('../../renderPdf/index.js')).default
```

**Comment by rdsedmundo** [comment] 2023-02-24 18:12
This is not an issue with `puppeteer` at all, but with `webpack` by itself. 

A fresh minimal `webpack` repo with the following code also throws for the same reason:

```
async function handler() {
  const { Readable } = await import('node:stream');
  assert(typeof Readable !== 'undefined', 'Readable is undefined.');
}

void handler();
```

See: https://github.com/webpack/webpack/issues/16757

**Comment by DynamicArray** [comment] 2023-05-08 22:15
Definitely a webpack problem, not a puppeteer one.

Moved my bundling to esbuild and it worked first time.

**Comment by OrKoN** [comment] 2023-05-09 05:55
Closing based on previous comments

**Closed as not planned by OrKoN** 2023-05-09 05:55 UTC
Labels: confirmed

**Comment by michaelhays** [comment] 2023-08-21 20:17
I was able to work around this by using [`createRequire`](https://nodejs.org/api/module.html#modulecreaterequirefilename) to load the `cjs` output instead of `esm`.

Change this import:

```ts
import puppeteer from 'puppeteer-core'
```

to this:

```ts
import { createRequire } from 'module'

const require = createRequire(import.meta.url)
const puppeteer = require('puppeteer-core')
```

I'm guessing this has to do with using `"type": "module"` in my `package.json` file and `"moduleResolution": "nodenext"` in my `tsconfig.json` file. I've run into a handful of similar issues with other libraries, like https://github.com/vercel/next.js/issues/46078

**Comment by bradwoo8621** [comment] 2023-12-12 09:45
- TL;DR
  ```typescript
  const puppeteer = require('puppeteer');
  ```

- Reference
  https://github.com/webpack/webpack/issues/16757#issuecomment-1851590537
