### ISSUE TITLE
`backgroundpage.on('console')` not working

### ISSUE THREAD

**Issue by pyrho** [puppeteer/puppeteer#4300] opened 2019-04-17 14:19 UTC
### Steps to reproduce
* Puppeteer version: 1.14.0
* Platform / OS version: macOS 10.14.3
* Node.js version: 11.6.0

**What steps will reproduce the problem?**

1. `git clone https://github.com/pyrho/puppeteer-bug.git`
2. `yarn`
3. `node example.js`

The repo for this issue: https://github.com/pyrho/puppeteer-bug 

**What is the expected result?**
Messages (`console.log`)from the background page are caught by the `backgroundPage.on('console')` handler. 
`bg: PORT CONNECTED" should print in the node console.

**What happens instead?**
Messages are not caught by the handler.

When manually inspecting the background page, we can see that the message is printed in the console tab:
![Screenshot 2019-04-17 at 16 09 00](https://user-images.githubusercontent.com/145502/56294985-512efd00-612c-11e9-9cb5-fc9688f30492.png)

Thank you for your time and this awesome project :)

**Comment by xse** [comment] 2019-04-17 17:08
Hey, maybe it's just happening before your listener being setup ?
If i add like:
```js
await backgroundPage.evaluate(() => console.log('hi'));
```
 anywhere before your listeners in your example.js i don't see anything, but anywhere after i'll see 'bg: hi'
I don't know, since i guess your extension is supposed to run at startup it makes sense to me but maybe i'm wrong.
Have a good day!

**Comment by pyrho** [comment] 2019-04-18 09:33
Hey @xse thank you for the suggestion as this is a classic mistake.
I've changed the code in my extension to call `console.log` in a `setInterval(1000)` (so that listener hook timing shouldn't matter); the log is shown in the background page, but my `backgroundPageTarget.page().on('console')` handler is still not fired.

Have a good one too!

**Comment by xse** [comment] 2019-04-18 20:02
Indeed my bad.
So, excuse my english, i'm pretty bad at explaining things but i'll try since i got those bg messages.
I think the issue is that there is two background pages, i actually got your example working once, but only once so that was strange, then i tried to output all console messages from all targets, it crashed so by filtering with only the targets that seems to be a background page, that works.
If you add this right after the `console.log('closing');` line in your example :
```js
    let test = await browser.targets();
    let foo = [];
    for (let i=0, len=test.length; i<len; i++) {
        console.log('target '+i);
        if (test[i]._targetInfo.url.includes('background_')) {
            console.log(test[i]);
            foo[i] = await test[i].page();
            foo[i]._client.on('Runtime.consoleAPICalled', ({args, executionContextId, timestamp, type, stackTrace, context}) => {
                console.log('Runtime.consoleAPICalled');
                console.log(args);
            });
        }
    }
```
You can see the messages that way.
![working](https://i.imgur.com/pgUwKqq.png)

I think you can get rid of most of the code and use `.on('console', msg => console.log(`bg: ${msg.text()}`));`

The `console.log(test[i]);` outputs two background pages, and since i added the listener to both i don't know witch one is the correct one i did not dig enough into that, but you should be able to filter the correct one. Like if you take a look at the target objects, there are easy ways to differentiates both of them like i think one has your extension name inside.
I don't know if having two background pages when you specify `--disable-extensions-except` is normal behavior.

I don't know if that make sense, i hope it does.
EDIT: typo and maybe more clear.

**Comment by pyrho** [comment] 2019-04-19 08:40
@xse Thank you so much for your precious help !
It does work now.

So apparently Chrome has a "hidden" extension called `CryptoTokenExtension`, (it does not show up in `chrome://extensions/`, even with developper mode enabled) that handles 2FA (see [this](https://askubuntu.com/questions/844090/what-is-cryptotokenextension-in-chromium-extensions)).

I think that in my original code, I was calling `browser.targets()` too early (yielding only 2 targets).
Calling it when where you suggested yields 4 target, including my extension.
So when the first call triggered, my extension was not loaded yet.

As you stated, I guess that the `--disable-extensions-except` flag should also disable `CryptoTokenExtension`, but I guess that's a Chromium bug (the switch is defined [here](https://chromium.googlesource.com/chromium/src/+/master/chrome/common/chrome_switches.cc#208) rather than a puppeteer bug.

Again, thank you so much for your help, I spent all day yesterday faking the `chrome.runtime` API using `page.exposeFunction` ¯\_(ツ)_/¯; it's way better if it just works out of the box! :)

**Closed as completed** 2019-04-19 08:41 UTC

**Comment by aslushnikov** [comment] 2019-07-14 22:56
We should disable the component extensions by default - submitted the https://github.com/GoogleChrome/puppeteer/pull/4704 for this.
