### ISSUE TITLE
`Page.goto` may hang until timeout when `setRequestInterceptionEnabled` is true

### ISSUE THREAD

**Issue by panthony** [puppeteer/puppeteer#1135] opened 2017-10-23 14:25 UTC
When I try to access (some) site with `setRequestInterceptionEnabled`, then `goto` may fails with timeout error.

Using `dumpio` the only difference I can see is that with `setRequestInterceptionEnabled` the service worker fails to register.

With intercept:
> [1023/161747.831982:INFO:CONSOLE(1)] "Service Worker registration failed with SecurityError: Failed to register a ServiceWorker: No URL is associated with the caller's document.", source: https://web-cdn.ttvnw.net/global-85a1009cc55264a2aa3ed514de6eee73.js (1)

Without:
> [1023/161846.327081:INFO:CONSOLE(1)] "Service Worker registration succeeded. Scope is https://www.twitch.tv/", source: https://web-cdn.ttvnw.net/global-85a1009cc55264a2aa3ed514de6eee73.js (1)

And I'm not sure where to go from here.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: macOS Sierra (10.12.6)

**What steps will reproduce the problem?**

```javascript
const puppeteer = require('puppeteer');
(async() => {
  const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'], ignoreHTTPSErrors: true, dumpio: false });
  const page = await browser.newPage();

  await page.setRequestInterceptionEnabled(true);

  page.on('request', request => request.continue());

  const site = 'https://www.twitch.tv/directory/all';
  await page.goto(site, {timeout: 15000});

  await browser.close();
})();
```

**What is the expected result?**

The `goto` should works normally.

**What happens instead?**

The `goto` hang and finally throw a timeout.

**Comment by aslushnikov** [comment] 2017-10-25 00:10
Can't reproduce this on current 0.13.0-alpha. Could you please check if it works for you on tip-of-tree?

**Comment by panthony** [comment] 2017-10-25 06:16
Using ab9b34cd5dad54e170be916016a4e9b4097231ed as dependency, I tried:

```javascript
const puppeteer = require('puppeteer');
(async() => {
  const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'], ignoreHTTPSErrors: true, dumpio: false });
  const page = await browser.newPage();

  await page.setRequestInterception(true);

  page.on('request', request => request.continue());

  const site = 'https://www.twitch.tv/directory/all';
  await page.goto(site, {timeout: 15000});

  await browser.close();
})();
```

And unfortunately same behavior:

 ```bash
 % node test.js
(node:23855) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 15000ms exceeded
```

For now `https://www.twitch.tv/directory/all` is the only website I found where this issue happen.

**Comment by panthony** [comment] 2017-10-26 07:46
@aslushnikov I have this service as a docker image (based on `node:8.6.0`), when running from:
- my laptop, it hangs,
- a remote machine, it hangs,
- a kubernetes cluster on GCE, it respond properly

**Comment by CommanderXL** [comment] 2017-10-27 12:06
@aslushnikov  Well. I have meet the same problem in my mac OS. 

https://github.com/GoogleChrome/puppeteer/issues/1166

**Comment by Xinkai** [comment] 2017-10-31 02:18
I encountered the same problem. I also found that the problem goes away if you specify `{ waitUntil: 'networkidle' }` in the `goto()` call.

Depending on your use case, this may be an acceptable workaround.

Environment: Linux + Node 8.7.0 + puppeteer 0.12.0

**Comment by ohana54** [comment] 2017-11-25 12:53
Happens to me as well, the page simply never loads when interception is enabled.
MacOS + Node 8.7.0 + puppeteer 0.13.0

**Comment by saberworks** [comment] 2017-12-11 20:18
I ran into this problem, too.  Running on MacOS (Sierra) + 8.4.0 + puppeteer 0.10.0 everything was working fine.  Running the same code under Docker (ubuntu artful, puppeteer 0.10.0) was working, then after a build where no code seemed to change, it started hanging.  After finding this issue I commented out the interception enable call and the hanging went away.  I couldn't find anything that would make the hang go away with interception enabled.  Note I am using Chrome (not the bundled chromium) because I need videos to play.

I wonder if the hang was suddenly caused by an upgraded version of chrome being installed?  I can't find anything else that would have changed.

Anyway, I upgraded puppeteer to 0.12.0 (0.13.0 didn't work because it requires me to either use chromium, which doesn't have the video codecs, or an unstable build of chrome, which I don't really want to use), rebuilt my docker container, and everything went back to working ok.  Not sure whether this will help anyone else, but maybe try just upgrading puppeteer.  Or Chrome.

**Comment by setdvd** [comment] 2018-01-12 10:12
Have same issue with puppeteer 1.0.0 and 0.13.0. macOs.

when using self signed cert + ignoreHTTPSErrors: true  + setRequestInterception(true) => page never loads.

If using trusted ssl cert - everythings works fine including interception hooks.

**Comment by aslushnikov** [comment] 2018-01-12 11:11
Closing as a dupe of #1159

**Closed as completed by aslushnikov** 2018-01-12 11:11 UTC

**Comment by wuno** [comment] 2018-06-04 23:40
For anyone that is having this problem. After no sleep for 2 days, @panthony 's example above solved this issue for me when running in Docker. 

`  const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'], ignoreHTTPSErrors: true, dumpio: false });
`

My ultimate goal is to not use Docker, but the fact that I have this working in debian is super promising docker or not.
