### ISSUE TITLE
Chromium fails to launch in CentOS 7.2 (linux-503964, sandbox disabled)

### ISSUE THREAD

**Issue by hparadiz** [puppeteer/puppeteer#904] opened 2017-09-28 20:46 UTC
```shell
$ ./node_modules/puppeteer/.local-chromium/linux-503964/chrome-linux/chrome --headless --no-sandbox --disable-setuid-sandbox
[0928/203844.466538:FATAL:nss_util.cc(632)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required. Please upgrade to the latest NSS, and if you still get this error, contact your distribution maintainer.
#0 0x7f82a938d3b7 base::debug::StackTrace::StackTrace()
#1 0x7f82a93a16f1 logging::LogMessage::~LogMessage()
#2 0x7f82a9cc20d6 base::LazyInstance<>::Get()
#3 0x7f82a9bff985 net::CertDatabase::GetInstance()
#4 0x7f82a9adfca6 net::CachingCertVerifier::CachingCertVerifier()
#5 0x7f82a9a9f75c net::CertVerifier::CreateDefault()
#6 0x7f82a9befc77 net::URLRequestContextBuilder::Build()
#7 0x7f82abc81156 headless::HeadlessURLRequestContextGetter::GetURLRequestContext()
#8 0x7f82a81cb809 content::ChromeAppCacheService::InitializeOnIOThread()
#9 0x7f82a852a4a9 _ZN4base8internal7InvokerINS0_9BindStateIMN7content21ChromeAppCacheServiceEFvRKNS_8FilePathEPNS3_15ResourceContextEPN3net23URLRequestContextGetterE13scoped_refptrIN7storage20SpecialStoragePolicyEEEJSD_IS4_ES5_S9_NS0_18RetainedRefWrapperISB_EENSK_ISF_EEEEEFvvEE7RunOnceEPNS0_13BindStateBaseE
#10 0x7f82a938daf7 base::debug::TaskAnnotator::RunTask()
#11 0x7f82a93a5e64 base::MessageLoop::RunTask()
#12 0x7f82a93a64d1 base::MessageLoop::DoWork()
#13 0x7f82a93a81b9 base::MessagePumpLibevent::Run()
#14 0x7f82a93c4835 base::RunLoop::Run()
#15 0x7f82a8209246 content::BrowserThreadImpl::IOThreadRun()
#16 0x7f82a8209404 content::BrowserThreadImpl::Run()
#17 0x7f82a93e995a base::Thread::ThreadMain()
#18 0x7f82a93e4783 base::(anonymous namespace)::ThreadFunc()
#19 0x7f82a6c01dc5 start_thread
#20 0x7f82a0a51ced __clone

Received signal 6
#0 0x7f82a938d3b7 base::debug::StackTrace::StackTrace()
#1 0x7f82a938cf1f base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7f82a6c09100 <unknown>
#3 0x7f82a09905f7 __GI_raise
#4 0x7f82a0991ce8 __GI_abort
#5 0x7f82a938bf62 base::debug::BreakDebugger()
#6 0x7f82a93a1bac logging::LogMessage::~LogMessage()
#7 0x7f82a9cc20d6 base::LazyInstance<>::Get()
#8 0x7f82a9bff985 net::CertDatabase::GetInstance()
#9 0x7f82a9adfca6 net::CachingCertVerifier::CachingCertVerifier()
#10 0x7f82a9a9f75c net::CertVerifier::CreateDefault()
#11 0x7f82a9befc77 net::URLRequestContextBuilder::Build()
#12 0x7f82abc81156 headless::HeadlessURLRequestContextGetter::GetURLRequestContext()
#13 0x7f82a81cb809 content::ChromeAppCacheService::InitializeOnIOThread()
#14 0x7f82a852a4a9 _ZN4base8internal7InvokerINS0_9BindStateIMN7content21ChromeAppCacheServiceEFvRKNS_8FilePathEPNS3_15ResourceContextEPN3net23URLRequestContextGetterE13scoped_refptrIN7storage20SpecialStoragePolicyEEEJSD_IS4_ES5_S9_NS0_18RetainedRefWrapperISB_EENSK_ISF_EEEEEFvvEE7RunOnceEPNS0_13BindStateBaseE
#15 0x7f82a938daf7 base::debug::TaskAnnotator::RunTask()
#16 0x7f82a93a5e64 base::MessageLoop::RunTask()
#17 0x7f82a93a64d1 base::MessageLoop::DoWork()
#18 0x7f82a93a81b9 base::MessagePumpLibevent::Run()
#19 0x7f82a93c4835 base::RunLoop::Run()
#20 0x7f82a8209246 content::BrowserThreadImpl::IOThreadRun()
#21 0x7f82a8209404 content::BrowserThreadImpl::Run()
#22 0x7f82a93e995a base::Thread::ThreadMain()
#23 0x7f82a93e4783 base::(anonymous namespace)::ThreadFunc()
#24 0x7f82a6c01dc5 start_thread
#25 0x7f82a0a51ced __clone
  r8: 00007f828be68890  r9: 00000000000003f3 r10: 0000000000000008 r11: 0000000000000202
 r12: 00007f828be68d30 r13: 00000000000000ce r14: 00007f828be68d28 r15: 00007f828be68d20
  di: 00000000000022ef  si: 00000000000022fd  bp: 00007f828be68890  bx: 00007f828be68890
  dx: 0000000000000006  ax: 0000000000000000  cx: ffffffffffffffff  sp: 00007f828be686e8
  ip: 00007f82a09905f7 efl: 0000000000000202 cgf: 000c000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[0928/203844.611182:ERROR:broker_posix.cc(43)] Invalid node channel message
[0100/000000.611185:ERROR:broker_posix.cc(43)] Invalid node channel message
```
Weirdly..... I have NSS installed:

```
user@machine:/var/project$ sudo yum install nss-util
Loaded plugins: fastestmirror, langpacks, logchanges
Loading mirror speeds from cached hostfile
Package nss-util-3.21.0-2.2.el7_2.x86_64 already installed and latest version
Nothing to do
user@machine:/var/project$ sudo yum install nss-softokn
Loaded plugins: fastestmirror, langpacks, logchanges
Loading mirror speeds from cached hostfile
Package nss-softokn-3.16.2.3-14.2.el7_2.x86_64 already installed and latest version
Nothing to do
user@machine:/var/project$ sudo yum install nss-sysinit
Loaded plugins: fastestmirror, langpacks, logchanges
Loading mirror speeds from cached hostfile
Package nss-sysinit-3.21.0-9.el7_2.x86_64 already installed and latest version
Nothing to do
user@machine:/var/project$ sudo yum install nss-tools
Loaded plugins: fastestmirror, langpacks, logchanges
Loading mirror speeds from cached hostfile
Package nss-tools-3.21.0-9.el7_2.x86_64 already installed and latest version
Nothing to do
user@machine:/var/project$ sudo yum install nss-softokn-freebl
Loaded plugins: fastestmirror, langpacks, logchanges
Loading mirror speeds from cached hostfile
Package nss-softokn-freebl-3.16.2.3-14.2.el7_2.x86_64 already installed and latest version
Nothing to do
```

When launching from Puppeteer I get:
`Caught error: Error: Protocol error (Network.enable): Target closed.`

Machine info:
```$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core) 
Release:	7.2.1511
Codename:	Core
```

**Comment by ebidel** [comment] 2017-09-28 21:47
Dupe of https://github.com/GoogleChrome/puppeteer/issues/391

**Closed as completed by ebidel** 2017-09-28 21:47 UTC

**Comment by hparadiz** [comment] 2017-09-28 21:51
This is absolutely not a dup! I've done everything in #391 to try to fix this!

**Comment by ebidel** [comment] 2017-09-28 22:00
https://github.com/adieuadieu/serverless-chrome/issues/53 suggests you may need to build a newer version of nss.

**Comment by hparadiz** [comment] 2017-09-28 22:03
@ebidel

I will try. Thank you

**Comment by hparadiz** [comment] 2017-09-29 17:22
Just to give an update.

The VM image on the datacenter's CentOS 7.2 image was frozen at 7.2 so I added a new repo sourced to CentOS 7.4 which had NSS 3.28 so I was able to upgrade and get chromium working.

**Comment by renfufei** [comment] 2018-03-06 10:06
Our Centos7.2 updated library to NSS 3.28 is work!
The CentOS7.4 Release is OK.

If the user is root, by the tips,  use `--no-sandbox` args :
```
      const browser = await puppeteer.launch({
          args : ['--no-sandbox']
      });
```
