### ISSUE TITLE
pagr.click interface broken refuses to function

### ISSUE THREAD

**Issue by nhhockeyplayer** [puppeteer/puppeteer#4466] opened 2019-05-23 22:11 UTC
puppeteer cannot CLICK and get data from this submit button
the click button interfaces are broken and unusable

try to get this submit to work I spent weeks on it already and its been years the click button interface has had issues

composite is always empty
and I have tried a dozen other alternative coding schemes

any help is appreciated this one really burnt me out

the goal being for university quiz to populate table row results into the composite collection

**Comment by Yokutto** [comment] 2019-05-27 14:04
Hi,
I could not even reproduce your code, what is your nodeJS version?

Looking quickly at your code, I see you are using puppeteer functions inside `page.evaluate`.
The `page.evaluate` context is the context of the DevTools console (Browser console context, you can use DOM functions here), NOT FROM NODE. So, if you have an function in nodeJS, that function will not work inside `page.evaluate`, because it is another context.

I think this information could be in [docs](https://pptr.dev/#?product=Puppeteer&version=v1.17.0&show=api-pageevaluatepagefunction-args), this could be a little confusing for new players.

Best

**Comment by nhhockeyplayer** [comment] 2019-05-28 11:14
thanks friend

im on 
node.js v8.12.0
npm 6.9.0

what leg of code would you recommend
can you throw something together quick to show what should work?

**Comment by nhhockeyplayer** [comment] 2019-05-28 11:28
here is another one I tried without success

URL https://www.nhlottery.com/Winning-Numbers

I cannot make anything out of the query params in devtools network on the request so I guessed from what I saw
&ctl00$plcMain$ddlGames=5

sorry if it got out of control this one seems like the one to krack seems so hard falling behind


```
            const thePage = await theBrowser.newPage()

            const startDate = DateUtil.subtractDays(new Date(), environment.days)
            const endDate = today
            const queryParams = '?startDate=' + formatTime(startDate) + '&endDate=' + formatTime(endDate) + '&ctl00$plcMain$ddlGames=5'
            const crazyConst1 = '&ctl00$plcMain$WinningNumbersSubmit=Search >' +
                '&path=/Winning-Numbers' +
                '&scheme=https' +
                '&__VIEWSTATEGENERATOR=2B9B124E'

            const apiUrl = lottery.entryPointUrl

            const response = await thePage.goto(apiUrl + queryParams + crazyConst1)

            const search = '#ctl00_plcMain_WinningNumbersSubmit'
            await thePage.click(search)

            const selector = '#ctl00_plcMain_WinningNumbersResults > div > div > div > div:nth-child(3)'
            let composite = await thePage.evaluate((selector) => {
                return Array.from(document
                    .querySelectorAll(selector))
                    .map((ele: HTMLElement) => ele.innerText)
            })
```

**Comment by nhhockeyplayer** [comment] 2019-05-29 23:32
upgraded to node 12.3.1 and npm 6.9.0
angular 8+

still wont work

**Comment by aslushnikov** [comment] 2019-06-01 17:49
@nhhockeyplayer can you provide us with a small puppeteer script that you expect to work and it doesn't?

Also:
- what's your Puppeteer version?
- do you use bundled chromium version or you run a custom one?

**Comment by nhhockeyplayer** [comment] 2019-06-02 15:03
hi friend

i got latest puppeteer version on npm
puppeteer-core

i just use the latest  chrome browser to run my app

the puppeteer code is executed on my KOA2 server
same specs

its just typescript


i provided enough code to scrap something together
just goto the url and click
then try to evaluate

nothing ever comes back in composite list its always empty

maybe the click is working

if you try the url above and see its worth looking into

**Comment by aslushnikov** [comment] 2019-06-02 19:35
> i provided enough code to scrap something together
> just goto the url and click

@nhhockeyplayer your code doesn't have definition for `formatTime `, nor for the dates you pass as query parameters. `environment.days`, `DateUtils` and other things are not defined as well.

Your code snippet is not runnable.

I went ahead and tried to guess what you actually do. Everything worked fine for me - buttons clicked, date pickers picked dates. I'll go ahead and close this issue.

Next time, please make sure to properly fill in the issue template and respond to all the questions.

**Closed as completed by aslushnikov** 2019-06-02 19:35 UTC

**Comment by nhhockeyplayer** [comment] 2019-06-02 22:16
I will assume you got data back
maybe it was my dates
