### ISSUE TITLE
page.goto waitUntil option is not respected

### ISSUE THREAD

**Issue by playgamemy** [puppeteer/puppeteer#1458] opened 2017-11-23 11:58 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Windows 10, nodejs 8.9.1
* URLs (if applicable):
code:

> const puppeteer = require('puppeteer');
> async function run(url){
> 	var browser = await puppeteer.launch({
> 			headless: false,
> 	});
> 
> 	var page = await browser.newPage();
> 	var test = await page.goto('https://au.yahoo.com', {waitUntil: 'load', timeout: 0});
> 	console.log ('right after url:'+page.url());
> 	console.log ('right after returned promise'+test);
>     await page.waitFor(5000);
>     console.log ('after 5 secs url:'+page.url());
>     console.log ('after 5 secs returned promise'+test);
> }
> run();

output:

> right after url:about:blank
> right after returned promise null
> after 5 secs url:https://au.yahoo.com/
> after 5 secs returned promise null

**What is the expected result and what happened instead?**
Expected with the option, it will return promise after the page is load, in which case async/await is used, the codes will only resume after the page is load (at least after DOM is ready), and therefore the first logged url should be the the url it reached and loaded, instead of about:blank.

and shouldn't the promise resolve and return the response object? why is it still null even after 5 seconds.

P.S. first time using headless browser, if it is purely my misunderstanding on what waitUntil option meant to do, or the definition of 'load' is wrong please let me know.

**Comment by vsemozhetbyt** [comment] 2017-11-23 12:49
I cannot reproduce with puppeteer v1.0.0-rc on Windows 7 x64:
```js
right after url:https://au.yahoo.com/
right after returned promise[object Object]
after 5 secs url:https://au.yahoo.com/
after 5 secs returned promise[object Object]
```

**Comment by playgamemy** [comment] 2017-11-23 13:05
I never know there is release v1.0.0-rc, will try to update my package.json and try again

**Comment by vsemozhetbyt** [comment] 2017-11-23 15:24
@playgamemy You can upgrade to the tip of tree by the
`npm i https://github.com/GoogleChrome/puppeteer/`

**Comment by vonGameTheory** [comment] 2017-11-23 17:10
There was a bug in using timeout:0 -- should be fixed in next release.  See #1417 .

**Comment by aslushnikov** [comment] 2018-01-12 12:12
Should be working fine in pptr v1.0.0.

**Closed as completed by aslushnikov** 2018-01-12 12:12 UTC
