### ISSUE TITLE
[Feature]: Run tests directly without spinning up a test server, in an Angular and Jest.

### ISSUE THREAD

**Issue by zmpo** [puppeteer/puppeteer#12450] opened 2024-05-16 09:36 UTC
### Feature description

Run E2E tests in angular ,
`ng e2e`
This command invariably necessitates running ng serve beforehand, which typically consumes around 2 minutes.

It would be highly convenient for developers if tests could be run directly against an already running service.

**Comment by zmpo** [comment] 2024-05-16 09:40
This seems to be an issue pertaining to Angular.

**Comment by zmpo** [comment] 2024-05-17 02:35
This issue is related to `@puppeteer/ng-schematics:puppeteer`
`async function executeE2ETest(
  options: PuppeteerBuilderOptions,
  context: BuilderContext
): Promise<BuilderOutput> {
  let server: BuilderRun | null = null;
  try {
    message('\n Building tests 🛠️ ... \n', context);
    await executeCommand(context, [`tsc`, '-p', 'e2e/tsconfig.json']);

    server = await startServer(options, context);
    const result = await server.result;

    message('\n Running tests 🧪 ... \n', context);
    const testRunnerCommand = getCommandForRunner(options.testRunner);
    await executeCommand(context, testRunnerCommand, {
      baseUrl: result['baseUrl'],
    });

    message('\n 🚀 Test ran successfully! 🚀 ', context, 'success');
    return {success: true};
  } catch (error) {
    message('\n 🛑 Test failed! 🛑 ', context, 'error');
    if (error instanceof Error) {
      return {success: false, error: error.message};
    }
    return {success: false, error: error as string};
  } finally {
    if (server) {
      await server.stop();
    }
  }
}`
`ng e2e` must start a server, this is a waste of time.

If `ng e2e` can test a exist server, that would be great.

**Comment by pfeileon** [comment] 2024-05-17 12:00
Imho this is a duplicate of https://github.com/puppeteer/puppeteer/issues/12222.

**Closed as completed** 2024-05-20 00:56 UTC
Labels: @puppeteer/ng-schematics
