### ISSUE TITLE
deviceScaleFactor:2 generates clipped screenshots

### ISSUE THREAD

**Issue by bertelli** [puppeteer/puppeteer#1207] opened 2017-10-29 18:34 UTC
I'm using
```
  await page.setViewport({
        width: 400,
        height,
        deviceScaleFactor :2,
      });

```
and full Page=true, but sometimes (not sure why/when) on some websites the screenshots get clipped like in half (width) in the sense that the output jpeg is **800px**  width (400 * scale factor) but it shows only half viewport...

see example https://imgur.com/a/LfC1x

almost like the screenshot happens before the screen get resizes properly...

fiy deviceScaleFactor:1 works well anytime

**Comment by ebidel** [comment] 2017-10-30 19:57
Dupe of https://github.com/GoogleChrome/puppeteer/issues/755. Please reopen if that's not the case.

**Closed as completed by ebidel** 2017-10-30 19:57 UTC

**Comment by bertelli** [comment] 2017-10-30 20:13
so is it only me that i get this error?

**Comment by ebidel** [comment] 2017-10-30 21:15
Others are seeing it too in #755.
