### ISSUE TITLE
[Bug]: Protocol error: Connection closed.

### ISSUE THREAD

**Issue by abine-praveen** [puppeteer/puppeteer#12860] opened 2024-07-31 18:45 UTC
### Minimal, reproducible example

```const puppeteer = require('puppeteer');

class PuppeteerBrowser {
constructor(options = PuppeteerBrowser.defaultOptions) {
this.browser = null;
this.options = options;
}

static get defaultOptions() {
return {};
}

async init() {
if (this.browser) return;

const launchOptions = {
  protocolTimeout: 0,
  executablePath: process.env.CHROME_EXECUTABLE, // Optional: Define if you have a custom executable path
  ignoreHTTPSErrors: true,
  defaultViewport: {
    width: 1920,
    height: 1080,
  },
  args: [
    "--window-size=1920,1080",
    "--disable-gpu",
    "--disable-features=IsolateOrigins,site-per-process",
    "--disable-blink-features=AutomationControlled",
    "--blink-settings=imagesEnabled=true",
    "--enable-features=NetworkService",
    "--disable-dev-shm-usage",
    "--no-sandbox",
    "--disable-setuid-sandbox",
  ],
};

if (process.env.DISABLE_HEADLESS !== "true") {
  launchOptions.headless = true;
  launchOptions.args.push("--headless=new");
} else {
  launchOptions.headless = false;
}

this.browser = await puppeteer.launch(launchOptions);
this.guid = Math.floor(Math.random() * 1000000000);
}

async context() {
await this.init();
return await this.browser.createIncognitoBrowserContext();
}

async close() {
if (!this.browser) return;
await this.browser.close();
this.browser = null;
}
}

module.exports = PuppeteerBrowser;
`
```

### Background

i have been trying to trying to scrape the web site

### Expectation

it should successfully work

### Reality

Lot of Protocol error: Connection closed. error

### Puppeteer version

22.14.0

### Node version

20

### Package manager

npm

### Package manager version

10.8.0

### Operating system

Linux

**Comment by abine-praveen** [comment] 2024-07-31 18:46
is there any issue already ?

**Comment by abine-praveen** [comment] 2024-07-31 18:46
this happening since we upgraded puppeteer to 22.14.0

**Comment by OrKoN** [comment] 2024-07-31 18:56
Please provide a minimal reproducible example.

**Comment by OrKoN** [comment] 2024-08-02 12:55
There are some problems with Alpine https://github.com/puppeteer/puppeteer/pull/12865

**Comment by OrKoN** [comment] 2024-08-02 14:31
We and Chrome do not support Alpine so we do not know if Puppeteer and Chrome works there. Try filing an issue for Alpine or try using our Debian-based image that we automatically test and publish for each release of Puppeteer https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer

**Comment by OrKoN** [comment] 2024-08-02 14:45
Right, that page is largely community driven documentation with various tips to get things working if they happen not to work: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#troubleshooting. The supported system requirements are documented here https://pptr.dev/guides/system-requirements You can probably get Chromium to work on Alpine but you need to keep system dependencies up-to-date and test any updates to the distro.

**Comment by OrKoN** [comment] 2024-08-02 14:48
So if you find a solution for Alpine 3.20, please send a pull request to update the troubleshooting page!

**Comment by abine-praveen** [comment] 2024-08-02 15:17
We are experiencing it with ubuntu

**Comment by abine-praveen** [comment] 2024-08-02 15:19
our config
`const { PROXY_BYPASS } = require("../../config/proxy");
const { setPuppteerPlugins, PuppeteerPlugins } = require("./setPuppeteerPlugins");

class PuppeteerBrowser {
  constructor(options = PuppeteerBrowser.defaultOptions) {
    this.browser = null;
    this.options = options;
  }

  static get defaultOptions() {
    const options = {};
    options[PuppeteerPlugins.AdBlocker] = true;
    options[PuppeteerPlugins.Stealth] = true;
    return options;
  }

  async init() {
    if (this.browser) return;

    // required sometimes to download desired local chromium.
    // -------------------------------------------------------
    // const browserFetcher = puppeteer.createBrowserFetcher();
    // let revisionInfo = await browserFetcher.download('818858');
    // console.log(revisionInfo);

    // --protocolTimeout--
    // default protocolTimeout is 60000. In cases when local timeout
    // is set to a value more then 60000, puppeteer will throw this
    // exception (source - Datanyze package):
    // - ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout'
    //   setting in launch/connect calls for a higher timeout if needed.
    // The workaround is to set protocolTimeout to 0
    // (https://github.com/puppeteer/puppeteer/issues/10144)

    const launchOptions = {
      protocolTimeout: 0,
      executablePath: process.env.CHROME_EXECUTABLE,
      ignoreHTTPSErrors: true,
      defaultViewport: {
        width: 1920,
        height: 1080,
      },
      args: [
        "--window-size=1920,1080",
        "--disable-gpu",
        "--disable-features=IsolateOrigins,site-per-process",
        "-–disable-blink-features=AutomationControlled",
        "--blink-settings=imagesEnabled=true",
        "--enable-features=NetworkService",
        "--disable-dev-shm-usage",
        "--no-sandbox",
        "--disable-setuid-sandbox",
      ],
    };

    if (process.env.DISABLE_HEADLESS !== "true") {
      launchOptions.headless = true;
      launchOptions.args.push("--headless=new");
    } else {
      launchOptions.headless = false;
    }

    const puppeteer = require("puppeteer-extra");
    setPuppteerPlugins(puppeteer, this.options);

    this.browser = await puppeteer.launch(launchOptions);
    this.guid = Math.floor(Math.random() * 1000000000);
  }

  async context(proxy) {
    await this.init();
    return await this.browser.createBrowserContext({
      proxyServer: proxy,
      proxyBypassList: PROXY_BYPASS.split(","),
    });
  }

  async close() {
    if (!this.browser) return;
    await this.browser.close();
    this.browser = null;
  }
}

PuppeteerBrowser.instance = new PuppeteerBrowser();

module.exports = PuppeteerBrowser;
`

**Comment by OrKoN** [comment] 2024-08-02 15:21
@abine-praveen Do you have perhaps as a Dockerfile or alternatively debugging logs https://pptr.dev/guides/debugging#print-browser-logs and details about your Ubuntu version. In the minimal example, please exclude code that is not related to puppeteer and make sure the example can be run standalone.

**Comment by sspread** [comment] 2024-08-07 00:15
I ran into this error sporadically (not sure how to reproduce) after going from 22.6.4 to 22.8.2. This seems relevant; unsure if it's fixed in subsequent versions.

https://github.com/puppeteer/puppeteer/commit/28a8d0ffb6345309df2bb23c9a5e2bd8be2f059d
https://github.com/puppeteer/puppeteer/commit/e36ce8bee18b4a8c7bf4c0692269d0095d186d06

**Comment by abine-praveen** [comment] 2024-08-07 05:15
> I ran into this error sporadically (not sure how to reproduce) after going from 22.6.4 to 22.8.2. This seems relevant; unsure if it's fixed in subsequent versions.
> 
> [28a8d0f](https://github.com/puppeteer/puppeteer/commit/28a8d0ffb6345309df2bb23c9a5e2bd8be2f059d) [e36ce8b](https://github.com/puppeteer/puppeteer/commit/e36ce8bee18b4a8c7bf4c0692269d0095d186d06)

Even i'm facing this odd issue

**Comment by tahamr83** [comment] 2024-08-11 20:14
We are also facing this issue sporadically with `puppeteer==22.10.0`, latest `browserless/chrome` and `alpine 3.19` as well.

**Comment by ab14bhardwaj** [comment] 2024-08-12 21:55
We're also encountering intermittent issues with the following configuration:

- Puppeteer: 22.15.0
- Chromium: 124.0.6367.78-r0
- Alpine: 3.19

**Comment by mchammer1041** [comment] 2024-08-13 11:32
Hello. We have been using for two week and today is the first time this error happened.

- Puppeteer: 22.13.1
- Ubuntu: 22.04.1
- 18.13.0

**Comment by Hasan-Mir** [comment] 2024-08-14 10:39
```ts
let browser: Browser;

const launchBrowser = async () => {
    try {
        browser = await launch();

        console.log('Browser launched successfully.');

        browser.once('disconnected', async () => {
            console.error(`Browser disconnected, attempting to relaunch...`);
            await browser.close();
            await launchBrowser();
        });
    } catch (error) {
        console.error(`Error launching browser: ${error}`);
        setTimeout(launchBrowser, 1000);
    }
};

await launchBrowser();

```

**Comment by kcodesgh** [comment] 2024-08-21 01:47
I'm sure it caused by instant opening and closing of the browser, i decided to remove this codes ```  await self.browser_manager.close_browser()```  from mine , and seems to work fine, i commented this codes  
Using Ubuntu 20v 
with pyppeteer in python

**Comment by kcodesgh** [comment] 2024-08-21 01:49
I'm sure it caused by instant opening and closing of the browser, i decided to remove this codes ```  await self.browser_manager.close_browser()```  from mine , and seems to work fine
Using Ubuntu 20v 
with pyppeteer in python 3.11.9

**Comment by OrKoN** [comment] 2024-08-21 07:10
You generally should not call browser.close() on 'disconnected' since the connection is closed by this point and you cannot send the close command to the browser.

**Closed as not planned** 2024-09-11 08:01 UTC
Labels: needs-feedback, unconfirmed, not-reproducible

**Comment by uson1x** [comment] 2024-10-01 10:01
Also experienced hanging like this when using
- puppeteer 23.4.0
- Docker `node:20.17.0-bookworm` image
- chromium
- for some reason only when I was rendering word-cloud (`d3-cloud`).

But not I think it's fixed. Here is what I did:
- bumped up puppeteer to 23.4.1
- added all the Debian dependencies listed here under "Debian (e.g. Ubuntu) Dependencies" https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux

My full Dockerfile:
```
FROM node:20.17.0-bookworm


# Install Google Chrome Stable and fonts
# Note: this installs the necessary libs to make the browser work with Puppeteer.
RUN apt-get update && apt-get install curl gnupg -y \
  && curl --location --silent https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
  fonts-noto-color-emoji \
  ca-certificates \
  fonts-liberation \
  libasound2 \
  libatk-bridge2.0-0 \
  libatk1.0-0 \
  libc6 \
  libcairo2 \
  libcups2 \
  libdbus-1-3 \
  libexpat1 \
  libfontconfig1 \
  libgbm1 \
  libgcc1 \
  libglib2.0-0 \
  libgtk-3-0 \
  libnspr4 \
  libnss3 \
  libpango-1.0-0 \
  libpangocairo-1.0-0 \
  libstdc++6 \
  libx11-6 \
  libx11-xcb1 \
  libxcb1 \
  libxcomposite1 \
  libxcursor1 \
  libxdamage1 \
  libxext6 \
  libxfixes3 \
  libxi6 \
  libxrandr2 \
  libxrender1 \
  libxss1 \
  libxtst6 \
  lsb-release \
  wget \
  xdg-utils \
  && apt-get install chromium -y --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/app
COPY ./dist ./dist
COPY ./node_modules/@capturi/pdf-report/dist/Package.umd.js ./node_modules/@capturi/pdf-report/dist/Package.umd.js

ENTRYPOINT [ "node", "/usr/app/dist/server.cjs" ]
```

and puppeteer launch options:
```
{
    headless: true,
    executablePath: '/usr/lib/chromium/chromium',
    dumpio: false,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-gpu',
      '--disable-dev-shm-usage',
      '--disable-accelerated-2d-canvas',
      '--no-first-run',
      '--no-zygote',
      '--single-process',
    ],
  }
```

Hope it helps someone.
