### ISSUE TITLE
Page crashed on specific URL

### ISSUE THREAD

**Issue by CssHammer** [puppeteer/puppeteer#1525] opened 2017-12-03 12:41 UTC
I\`m struggling with strange page crash everytime I\`m trying to visit and take screenshot on the following URL: https://bittrex.com/Market/Index?MarketName=BTC-TRIG
I tried to change URL a little but it goes well, for example https://bittrex.com/Market/Index?MarketName=BTC-NEO.

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Ubuntu 16.04.3 LTS Xenial
* URLs (if applicable): https://bittrex.com/Market/Index?MarketName=BTC-TRIG

**What steps will reproduce the problem?**
`node sc.js`

_Please include code that reproduces the issue._
**sc.js**:
```
const puppeteer = require('puppeteer');
const fs = require('fs');
const logger = fs.createWriteStream('log.txt', {
  flags: 'a' // 'a' means appending (old data will be preserved)
});

(async() => {
  log('Starting JS\n');
  var browser = null;
  await puppeteer.launch({
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    })
    .then(
      result => {
        log('Browser launched\n');
        browser = result;
      },
      error => {
        log('Browser wasn`t launched: ' + error + '\n');
      }
    );
  fs.writeFile("endpoint.txt", browser.wsEndpoint(), function(err) {
    if (err) {
      return log(err);
    }
    log('Endpoint was saved!\n');
  });
  var page = null;
  await browser.newPage()
    .then(
      result => {
        log('Page is created\n');
        page = result;
      },
      error => {
        log('Page wasn`t created: ' + error + '\n');
      }
    );
  page.on('error', error => {
    log(error.message + '\n' + error.stack + '\n');
  });
  await page.goto('https://bittrex.com/Market/Index?MarketName=BTC-TRIG')
    .then(
      result => {
        log('Goto succeeded\n');
      },
      error => {
        log('Goto failed: ' + error + '\n');
      }
    );
  await page.setViewport({
    width: 1366,
    height: 768
  }).then(
    result => {
      log('Viewport is set\n');
    },
    error => {
      log('Viewport wasn`t set: ' + error + '\n');
    }
  );
  await page.waitFor(2000)
    .then(
      result => {
        log('Waited for 2 secs\n');
      },
      error => {
        log('Failed to wait for 2 secs: ' + error + '\n');
      }
    );
  await page.screenshot({
    path: "charts/chart-btc-trig.png",
    clip: {
      x: 0,
      y: 59,
      width: 1194,
      height: 678
    },
  }).then(
    result => {
      log('Screenshot is created\n');
    },
    error => {
      log('Screenshot wasn`t created: ' + error + '\n');
    }
  );
  log('Closing browser!\n');
  await browser.close().then(
    result => {
      log('Browser is closed\n');
    },
    error => {
      log('Error while closing browser: ' + error + '\n');
    }
  );
})();

function log(message) {
  var date = new Date();
  logger.write(date.getFullYear() + '/' + (date.getMonth() + 1) + '/' +
    date.getDate() + ' ' + date.getHours() + ':' + date.getMinutes() + ':' +
    date.getSeconds() + message);
}
```
Log:
```
2017/12/3 14:32:30 [BTC] Browser launched
2017/12/3 14:32:30 [BTC] Endpoint was saved!
2017/12/3 14:32:30 [BTC] Page is created
2017/12/3 14:32:33 [BTC] Goto succeeded
2017/12/3 14:32:33 [BTC] Viewport is set
2017/12/3 14:32:35 [BTC] Waited for 2 secs
2017/12/3 14:32:38 [BTC] Page crashed!
Error: Page crashed!
    at Page._onTargetCrashed (/home/dima/js/node_modules/puppeteer/lib/Page.js:102:24)
    at Session.Page.client.on.event (/home/dima/js/node_modules/puppeteer/lib/Page.js:97:56)
    at emitOne (events.js:116:13)
    at Session.emit (events.js:211:7)
    at Session._onMessage (/home/dima/js/node_modules/puppeteer/lib/Connection.js:210:12)
    at Connection._onMessage (/home/dima/js/node_modules/puppeteer/lib/Connection.js:105:19)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (/home/dima/js/node_modules/ws/lib/WebSocket.js:143:47)
    at Receiver.dataMessage (/home/dima/js/node_modules/ws/lib/Receiver.js:389:14)
```

**What is the expected result?**
Screenshot is saved and browser is closed.

**What happens instead?**
Page crash.

I\`ve tried it on Windows 7 and haven`t faced such a problem

**Comment by sukhjitsingh-impactradius** [comment] 2017-12-06 13:49
@CssHammer ~~try not setting the viewport if you're just trying to screenshot the page and you already provide the width and height in your screenshot args.~~ (This is required to get appropriate page width and height) Try launching puppeteer with headless: false to make sure the page is loaded before you attempt to screenshot it.

**Comment by aslushnikov** [comment] 2018-01-04 18:37
@CssHammer I can't reproduce this on current tip-of-tree puppeteer. We've rolled chrome a few times, so the issue might've been resolved.

I'm speculatively closing this; feel free to write back if it reproes for you and you think we can help.

**Closed as completed by aslushnikov** 2018-01-04 18:37 UTC
