### ISSUE TITLE
Download failed: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/puppeteer/.local-chromium' + puppeteer@0.9.0

### ISSUE THREAD

**Issue by unclehking** [puppeteer/puppeteer#367] opened 2017-08-18 06:45 UTC
npm install puppeteer

Download failed: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/puppeteer/.local-chromium'

CentOS  6

**Comment by codenoid** [comment] 2017-08-18 07:38
did you try with `sudo` ?

**Comment by meldron** [comment] 2017-08-18 08:04
What is your `npm.prefix`?

Check it with: `npm prefix -g`

If the directory is located somewhere were a normal user has no write access you will have to `sudo npm install puppeteer` or install it in some project (`npm init`)

**Comment by umpox** [comment] 2017-08-18 10:57
I have the same problem, I'm using it as a dependency on a project I'm working on. If I try to install my project globally using `sudo npm install myProject -g` I get this same error message

**Comment by Garbee** [comment] 2017-08-18 17:15
Also ref #375

**Comment by ebidel** [comment] 2017-08-18 17:23
Shall we mark this as a dupe of https://github.com/GoogleChrome/puppeteer/issues/375?

**Comment by aslushnikov** [comment] 2017-08-18 17:30
Dupe of #375 :)

**Closed as completed by aslushnikov** 2017-08-18 17:30 UTC

**Comment by kauecastro** [comment] 2017-11-06 15:54
Have already you fixed this problem ? Could you show me the solution ? :)

**Comment by antsfee** [comment] 2017-11-14 08:50
init project i use yarn 
I have the same problem. 
then I remove all dependency
 , use npm  reinstall package ,
 ok .
 hope it's usefully

**Comment by sryze** [comment] 2017-12-18 09:41
How come this fails to install even if using sudo? I'm trying to install [critical](https://github.com/addyosmani/critical) using `sudo npm install -g critical` but it gives me this error.

**Comment by proyb6** [comment] 2017-12-22 05:40
@sryze It has the do with Nodejs 8, have you tried using Nodejs 6 or 7?

**Comment by tyt34** [comment] 2018-01-24 15:39
guys, don't use SUDO when you install this module. Вот.

**Comment by laguiz** [comment] 2019-03-15 14:40
Workaround : https://github.com/GoogleChrome/puppeteer/issues/1303#issuecomment-350815938 (works from Dockefile)

**Comment by hopeseekr** [comment] 2019-06-06 01:32
After hunting around the Internet, I found a solution:

`sudo npm install -g puppeteer --unsafe-perm=true`

**Comment by muhammedbasilsk** [comment] 2020-02-24 04:48
@hopeseekr you rock !!!

**Comment by Liberateur** [comment] 2020-06-30 13:39
`sudo npm install -g puppeteer --unsafe-perm=true` works and really thanks ! But I really wanted to understand why I had this error.

For me :
`npm init && npm i puppeteer` -> does not work
`npm init && sudo npm i puppeteer` -> does not work
`sudo npm init && sudo npm i puppeteer` -> works

**Comment by naqashse102** [comment] 2020-09-26 10:51
@hopeseekr you saved my day

**Comment by 76765357** [comment] 2021-03-15 23:46
don't use nvm
