### ISSUE TITLE
[Feature]: Fall back to latest known good version for Chromedriver

### ISSUE THREAD

**Issue by christian-bromann** [puppeteer/puppeteer#10714] opened 2023-08-09 07:12 UTC
### Feature description

I have embedded `@puppeteer/browsers` into WebdriverIO (see [release blog post](https://webdriver.io/blog/2023/07/31/driver-management)) an am using the package to setup Chrome and Chromedriver through the package. In order to not have users always download Chrome when they have the browser installed on their system I first try to detect the Chrome version that is installed on the users machine.

It seems that there isn't always a Chromedriver available for a given Chrome browser. In GitHub Actions it seems that they have installed Chrome `v115.0.5790.171` on Linux. For that, no Chromedriver is available (last known good version is `v115.0.5790.170`).

What do you think, is it useful to have the `install` function check for the last known good version for given major Chrome version rather than throwing a `404` error?

**Comment by OrKoN** [comment] 2023-08-09 08:13
Thanks for the report. It sounds like a duplicate of https://github.com/puppeteer/puppeteer/issues/10713

We are not going to fallback to installing a different version than the one specified in the install command (because it makes installs non-deterministic) but we will add support for milestones and versions without the patch numbers.

**Closed as not planned by OrKoN** 2023-08-09 08:13 UTC

**Comment by christian-bromann** [comment] 2023-08-09 14:50
That makes totally sense, thanks @OrKoN
