### ISSUE TITLE
How rethrowing error inside pageEvaluate function in puppeteer?

### ISSUE THREAD

**Issue by jeudesprits** [puppeteer/puppeteer#4703] opened 2019-07-14 16:36 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.1
* Platform / OS version: Ubuntu 18.04.2 LTS
* URLs (if applicable): -
* Node.js version: v12.6.0

**What steps will reproduce the problem?**

```ts
      const uri = `...`;
      json = await this._sessionPage.evaluate(
        async (uri, headers, locationId) => {
          const response = await window.fetch(uri, {
            method: 'GET',
            mode: 'cors',
            headers: new Headers(headers),
            credentials: 'include',
            referrer: `...`,
            referrerPolicy: 'no-referrer-when-downgrade',
          });
          if (response.status !== 200) {
            throw new Error(`Response code is ${response.statusText}. Something went wrong.`);
          }
          return response.json();
        },
        uri,
        headers,
        locationId,
      );
```

How rethrowing error inside pageEvaluate function in puppeteer?

**Comment by aslushnikov** [comment] 2019-07-14 22:58
Not sure I follow the question. What exactly do you want to rethrow and when?

**Comment by jeudesprits** [comment] 2019-07-15 06:59
> Not sure I follow the question. What exactly do you want to rethrow and when?

Trying to make a request inside a `evaluate` function. In case of an error, I actually throw it. But when I want to catch the error outside the function, I don’t get the message from my `Error` object. It seems that `evaluate` functions simply print an object, not message or stack.

```
error: Error: Evaluation failed: [object Object]
    at ExecutionContext._evaluateInternal (/home/ubuntu/dev/ig-web/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async ExecutionContext.evaluate (/home/ubuntu/dev/ig-web/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
```

**Comment by aslushnikov** [comment] 2019-07-15 07:04
Ah! Yes, this is a dupe of #4651.

Thank you for clarification!

**Closed as completed by aslushnikov** 2019-07-15 07:04 UTC
