### ISSUE TITLE
Problems running puppeteer on CentOS 6.9

### ISSUE THREAD

**Issue by dewijones92** [puppeteer/puppeteer#785] opened 2017-09-14 09:00 UTC
This is the error I am getting:
```
(node:29382) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
/home/osboxes/Documents/testcode/node_modules/puppeteer/.local-chromium/linux-497674/chrome-linux/chrome: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
```
I have gone through the troubleshooting but no luck :(
Please help?
Thanks

**Comment by Garbee** [comment] 2017-09-14 09:56
Duplicate of #497

**Closed as completed** 2017-09-15 17:22 UTC

**Comment by Jaree** [comment] 2018-09-17 10:26
**### ### ###**
