### ISSUE TITLE
[Bug]: Installation error (HTTP 500 from https://edgedl.me.gvt1.com/)

### ISSUE THREAD

**Issue by ru-sh** [puppeteer/puppeteer#11982] opened 2024-02-22 18:08 UTC
### Minimal, reproducible example

```TypeScript
{
"dependencies": {
    "puppeteer": "21.11.0"
  }
}

yarn install
```

### Error string

[cause]: Error: Download failed: server returned code 500. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/linux64/chrome-headless-shell-linux64.zip       at file:///root/bio-editor/frontend/packages/renderer/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:64:31       at ClientRequest.requestCallback (file:///root/bio-editor/frontend/packages/renderer/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:42:13)       at Object.onceWrapper (node:events:628:26)       at ClientRequest.emit (node:events:513:28)       at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)       at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)       at TLSSocket.socketOnData (node:_http_client:534:22)       at TLSSocket.emit (node:events:513:28)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

Successful installation

### Reality

HTTP 500 from the 'edgedl.me.gvt1.com'.

### Puppeteer version

21.11.0

### Node version

16.20

### Package manager

yarn

### Package manager version

1.22.21

### Operating system

Linux

**Comment by OrKoN** [comment] 2024-02-22 18:13
Duplicate of https://github.com/puppeteer/puppeteer/issues/11967

**Closed as not planned by OrKoN** 2024-02-22 18:13 UTC
