### ISSUE TITLE
WebSocket is not open: readyState 2 (CLOSING) when running tests with jest

### ISSUE THREAD

**Issue by dragonflypl** [puppeteer/puppeteer#4009] opened 2019-02-14 09:07 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:    `"puppeteer-core": "1.12.2",`
* Platform / OS version:  Windows 7 Enterprise
* URLs (if applicable):
* Node.js version: v8.11.3

**What steps will reproduce the problem?**

Run test with `jest`:

```js
import puppeteer from 'puppeteer-core';

describe('Puppeteer demo', () => {
  let page = null;
  let browser = null;

  beforeAll(async () => {
    jest.setTimeout(10000000);
    browser = await puppeteer.launch({
      executablePath: 'C:/dev/ChromeDownloads/browser/chrome.exe',
      headless: false,
      // devtools: false,
      slowMo: 250,
      // args: ['--start-fullscreen']
    });
    page = await browser.newPage();
    //await page.setViewport({ width: 1280, height: 800});
  })

  it('should open main page', async() => {
    await page.goto('http://localhost:8080', { waitUntil: 'networkidle2' });
    await page.waitForSelector('.WizardNavigationBar__titleText___hcaEZ');
    const html = await page.$eval('.WizardNavigationBar__titleText___hcaEZ', e => e.innerHTML);
    expect(html).toBe('Hello world');
    await page.click('.DropdownInput__placeholder___3fe3c');
    const firstRow = await page.waitForSelector('.CustodyAccountSelection__portfolio___3fkaw');
    await firstRow.click();
  });

  afterAll(async () => {
    await browser.close();
  })
})
```
**What is the expected result?**

I run tests with `jest`. Tests are executed successfully (all pass) but closing browser in `afterAll` produces error , and it also does not happen always.  I expect that after tests browser is closed gracefully.

**What happens instead?**

I get errors in console

```
C:\dev\web-app>npx jest puppeteer
  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:157
    Unhandled error

  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:158
    Error: WebSocket is not open: readyState 2 (CLOSING)
        at WebSocket.send (C:\dev\web-app\node_modules\puppeteer-core\node_modules\ws\lib\websocket.js:322:19)
        at WebSocketTransport.send (C:\dev\web-app\node_modules\puppeteer-core\lib\WebSocketTransport.js:57:14)
        at Connection._rawSend (C:\dev\web-app\node_modules\puppeteer-core\lib\Connection.js:86:21)
        at CDPSession.send (C:\dev\web-app\node_modules\puppeteer-core\lib\Connection.js:181:33)
        at Function.releaseObject (C:\dev\web-app\node_modules\puppeteer-core\lib\helper.js:92:18)
        at JSHandle.dispose (C:\dev\web-app\node_modules\puppeteer-core\lib\JSHandle.js:109:18)
        at JSHandle.<anonymous> (C:\dev\web-app\node_modules\puppeteer-core\lib\helper.js:109:23)
        at args.forEach.arg (C:\dev\web-app\node_modules\puppeteer-core\lib\Page.js:599:31)
        at Array.forEach (<anonymous>)
        at Page._addConsoleMessage (C:\dev\web-app\node_modules\puppeteer-core\lib\Page.js:599:12)
        at Page._onConsoleAPI (C:\dev\web-app\node_modules\puppeteer-core\lib\Page.js:538:10)
        at CDPSession.Page.client.on.event (C:\dev\web-app\node_modules\puppeteer-core\lib\Page.js:135:57)
        at emitOne (events.js:116:13)
        at CDPSession.emit (events.js:211:7)
        at CDPSession._onMessage (C:\dev\web-app\node_modules\puppeteer-core\lib\Connection.js:200:12)
        at Connection._onMessage (C:\dev\web-app\node_modules\puppeteer-core\lib\Connection.js:112:17)
        at <anonymous>
```

**Comment by weworkwithzoh** [comment] 2019-02-22 22:15
Yup. Also seeing this, but for me it's 100% reproducible. The call to `browser.close()` dies every time, whether I call it in the teardown, or within the test itself.

Edit:
Using jest-puppeteer, even something as simple as:
```
describe('Browser Close', () => {
    it('closes the browser', async () => {
        await browser.close();
    });
});
```
causes this error.

**Comment by aslushnikov** [comment] 2019-03-02 03:09
@weworkwithzoh  @dragonflypl This happens when closing browser that's already been closed. The error is quite cryptic and we probably can do a better job here.

Can you please share a small jest testsuite that illustrates the issue? The set up / tear down parts are of the most interest.

**Comment by nhhockeyplayer** [comment] 2019-05-23 08:54
button clicks are unusable

async/await
promises

nothing is giving

just hangs or crashes out

await thePage.click(buttonSelector)
                    .then((body): void => {
                            console.log('button click body. ' + body)
                        }
                    )
                    .catch((err): void => {
                            console.log('button click rejected. ' + err)
                            process.exit()
                        }
                    )

the selectors are fine and copied right from the page being rendered using chrome menu select

**Comment by aslushnikov** [comment] 2019-06-09 07:50
@nhhockeyplayer please file a separate issue with a good repro - this one is unrelated.

Closing since there's no feedback from the original author.

**Closed as completed by aslushnikov** 2019-06-09 07:50 UTC
