### ISSUE TITLE
Unhandled promise rejection (rejection id: 1): Error: Failed to connect to chrome!

### ISSUE THREAD

**Issue by codenoid** [puppeteer/puppeteer#390] opened 2017-08-19 14:44 UTC
```
root@myvps:/var/app/pup# node app.js
(node:15875) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to connect to chrome!
(node:15875) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Garbee** [comment] 2017-08-19 15:43
Duplicate of #290.

**Closed as completed** 2017-08-19 16:21 UTC
