### ISSUE TITLE
Lang page render bug

### ISSUE THREAD

**Issue by OrangeXC** [puppeteer/puppeteer#1408] opened 2017-11-17 10:49 UTC
* Puppeteer version: 0.13.0
* Platform / OS version: MacOS Node8.7.0

when I use `page.screenshot()` or `page.pdf()` render lang html page

I get error screen，the out put loop show

Demo

```
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('http://7xr2s7.com1.z0.glb.clouddn.com/index.html');
  await page.screenshot({path: 'example.png', fullPage: true});

  await browser.close();
})();
```

I get this `.png` file

![example](https://user-images.githubusercontent.com/16081320/32942749-e10ae032-cbc4-11e7-94b8-1fe374cf7d7c.png)

my html file is this `http://7xr2s7.com1.z0.glb.clouddn.com/index.html` , have 39 div tags.

but render to 33, not have 34 and more, but loop to the top continue render

my div height is 500px, so I think page length about more than 15,000 can trigger error

I have try my own website have the same problem

**Comment by H91011** [comment] 2017-11-17 12:45
document.body.getBoundingClientRect(); output is : 
`{ x: 8,
  y: 8,
  width: 784,
  height: 19500,
  top: 8,
  right: 792,
  bottom: 19508,
  left: 8 }`
 
You can get screenshot as two part with this: 
`(async () => {`
  `const browser = await puppeteer.launch(); `
  `const page = await browser.newPage();`
  `await page.goto('http://7xr2s7.com1.z0.glb.clouddn.com/index.html');`
  `console.log("şimdi çekiyor");`
  `await page.screenshot({path: 'part1.png', clip:{x:0, y:0,width:784,height:10000}});`
  `await page.screenshot({path: 'part2.png', clip:{x:0, y:10000,width:784,height:19508}});`
  `let olcu=await page.evaluate(()=>{`
   ` return document.body.getBoundingClientRect();`
  `});`
  `console.log(olcu);`
 ` await browser.close();`
`})();`


I try  `await page.screenshot({path: 'part2.png', clip:{x:0, y:10000,width:784,height:19508}});`
but result is like your output, it is not take all div

**Comment by ebidel** [comment] 2017-11-17 14:27
Dupe of https://github.com/GoogleChrome/puppeteer/issues/359. Headless chrome currently has a hard limit of ~16000 px for a full page screenshot.

**Closed as completed by ebidel** 2017-11-17 14:27 UTC
