### ISSUE TITLE
page.url() does not reflect pushstate-driven updates...

### ISSUE THREAD

**Issue by busticated** [puppeteer/puppeteer#1736] opened 2018-01-06 04:15 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: macOS 10.13.2
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

i've tried a couple of approaches:

    await Promise.all([
        page.waitForNavigation(), // also w/ the { waitUntil: 'networkidle2' } option
        page.click(<anchor tag selector>)
    ]);

    // alternately, i've tried:
    // await page.click(<anchor tag selector>);
    // await page.waitFor(3000);

    expect(page.url()).toBe(<expected url>); // fails w/ old url - as though the page never navigated

when i use `puppeteer.launch({ headless: false, slowMo: 1000 });` to debug things, i'm able to observe the navigation happening so the `page.click()` bit seems to be working.

**What is the expected result?**

assertion shown above succeeds

**What happens instead?**

assertion shown above fails w/ old url as though the page never navigated

**Comment by yujiosaka** [comment] 2018-01-06 12:48
@busticated 
Have you checked https://github.com/GoogleChrome/puppeteer/issues/257 ?

**Comment by busticated** [comment] 2018-01-06 16:48
@yujiosaka i did but on 2nd review, i noticed [this work-around](https://github.com/GoogleChrome/puppeteer/issues/257#issuecomment-336662440)

with that in place, this does what i want:

    await page.click(<anchor tag selector>);
    await page.waitFor(3000);
    const url = await page.evaluate(() => location.href);

    expect(url).toBe(<expected url>);

i would expect `page.url()` to give me the same result but it does not. nor do its [docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageurl) call out this limitation.

so `¯\_(ツ)_/¯ `

i suppose a related but slightly off-topic question is: does `page.waitForNavigation()` handle pushstate-driven (history api) navigation changes? my impression from #257 is that it does not (though that issue was at least initially about hash-driven navigation - e.g. jumping down to an id in the current page)

**Comment by aslushnikov** [comment] 2018-01-09 02:15
> i suppose a related but slightly off-topic question is: does page.waitForNavigation() handle pushstate-driven (history api) navigation changes?

@busticated it doesn't.

Overall, this is indeed due to the poor support for document-only navigations. Closing as dupe of #257.

**Closed as completed by aslushnikov** 2018-01-09 02:15 UTC

**Comment by busticated** [comment] 2018-01-09 02:53
@aslushnikov ok but what about `page.url()`? that was the main point with this issue - it seems to always return whatever the original url was. is this also related to the spotty history api support?

**Comment by aslushnikov** [comment] 2018-01-09 04:42
@busticated yes, the same root issue: Devtools protocol operates in terms of browser navigations and doesn't take history API into account.
