### ISSUE TITLE
[Bug]: Fails to connect to remote Android Virtual Device

### ISSUE THREAD

**Issue by adamraine** [puppeteer/puppeteer#9625] opened 2023-02-03 20:20 UTC
### Bug expectation

I expected Puppeteer to connect to Chrome running in an Android Virtual Device set up via Android Studio. Is this a supported workflow?

When I attempted to connect to the device with Puppeteer I get the following error:

```
file:///Users/asraine/src/pptr-scripts/node_modules/puppeteer/node_modules/puppeteer-core/lib/esm/puppeteer/common/Browser.js:275
            throw new Error(`Missing target for page (id = ${targetId})`);
                  ^

Error: Missing target for page (id = 15)
    at CDPBrowser._createPageInContext (file:///Users/asraine/src/pptr-scripts/node_modules/puppeteer/node_modules/puppeteer-core/lib/esm/puppeteer/common/Browser.js:275:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///Users/asraine/src/pptr-scripts/remote.js:6:14
```

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
// I set up the debugging port using this workflow:
// https://github.com/GoogleChrome/lighthouse/blob/main/docs/readme.md#testing-on-a-mobile-device
// (Ignore the last command to run Lighthouse, that is replaced with the min repro below)
//
// The device I used was a Pixel 4 w/ Api Level 33 (Tiramisu/Android 13.0)
// I had to go into the device and update Chrome manually, but got Chrome to M109.

import puppeteer from 'puppeteer';

const browser = await puppeteer.connect({
  browserURL: `http://localhost:9222`,
});
const page = await browser.newPage();
await page.goto('https://example.com');

browser.disconnect();
```

### Error string

Missing target for page (id = 15)

### Puppeteer version

19.6.3

### Node version

16.17.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by OrKoN** [comment] 2023-02-04 09:55
That should work but we don't have any test coverage for this setup. Were you able to find the root cause?

**Comment by clowndogloko** [comment] 2023-02-06 09:32
I had the same issue with this bug but I managed to opt out and disappointed the shell developer.

**Comment by OrKoN** [comment] 2023-03-28 13:13
@adamraine could you re-test? I believe this might have been fixed in the latest versions?

**Comment by adamraine** [comment] 2023-03-28 20:59
I just tried this and no error is thrown, however there is this weird screen emulation:

![Screenshot 2023-03-28 at 1 58 32 PM](https://user-images.githubusercontent.com/6752989/228365268-0f387ffa-590f-4a7e-9cfe-18ef808216e8.png)

Repro script
```js
import puppeteer from 'puppeteer';

const browser = await puppeteer.connect({
  browserURL: `http://localhost:9222`,
});
const page = await browser.newPage();
await page.goto('https://example.com');
```

**Comment by adamraine** [comment] 2023-03-28 21:52
Actually, looks like I just need to do `defaultViewport: null` to fix that issue

**Closed as completed** 2023-03-28 22:00 UTC
Labels: upstream, confirmed
