### ISSUE TITLE
Puppeteer on Cloud Function in 2019 - Slow as hell

### ISSUE THREAD

**Issue by whatsdis** [puppeteer/puppeteer#4471] opened 2019-05-24 19:48 UTC
I am using this guide: 

https://rominirani.com/using-puppeteer-in-google-cloud-functions-809a14856e14

On my local machine it takes about 4 seconds.

On GCF it takes a freaking 20 seconds!!!!! 

Is there a way to improve times? At this point offering Chrome headless is a dud because I get faster results with AWS Lambda and using https://github.com/Kikobeats/aws-lambda-chrome

Please fix this Google!!!!!

**Comment by aslushnikov** [comment] 2019-06-03 00:51
@whatsdis There's a lot of good discussion about running on GCP in #3120 - e.g. [this comment](https://github.com/GoogleChrome/puppeteer/issues/3120#issuecomment-450575911). Please, give it a try.

Closing this as a dupe of #3120.

**Closed as completed by aslushnikov** 2019-06-03 00:51 UTC
