### ISSUE TITLE
[BUG] Parallel pages / error Page.handleJavaScriptDialog

### ISSUE THREAD

**Issue by vogloblinsky** [puppeteer/puppeteer#1818] opened 2018-01-17 02:07 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: macOS 10.12.6
* Node.js version: 8.3.0

**What steps will reproduce the problem?**

1. index.html page used for scraping purpose

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head></head>
<body>
    <div id="btGen"></div>
    <hr/>
    <div id="dvTable">TEST</div>
    <script type="text/javascript">
        let match = RegExp('[?&]start=([^&]*)').exec(window.location.search);
        let val = decodeURIComponent(match[1].replace(/\+/g, ' '));
        let randomNumber = Math.random() >= 0.5;

        if (randomNumber) {
            alert(val);
            document.getElementById('btGen').innerHTML = '<button id="btn">Yo</button>';
            document.getElementById('btn').addEventListener('click', () => {
                document.getElementById('dvTable').innerHTML = val;
            });
        } else {
            document.getElementById('dvTable').innerHTML = val;
        }
    </script>
</body>
</html>
```

2. parallel.js Node.js script to do the scraping

```
const puppeteer = require('puppeteer'),
      URL = 'http://localhost/RetD/scraping-parallel-calls/',
      DATA = [],
      ITERATOR = [];

for (let i = 0; i < 5; i++) {
    ITERATOR.push(i * 50);
}

async function run() {

    let startTime = (new Date()).getTime();

    const browserPromise = await puppeteer.launch({
        headless: false
    });

    async function scrapPage(iteration, index) {

        const browser = await browserPromise;

        let page = await browser.newPage();

        let pages = await browser.pages();
        page = pages[index + 1];

        page.on('dialog', async dialog => {
            console.log('> dialog');        
            await dialog.dismiss();
            await page.click('#btn');
        });

        await page.goto(`${URL}?start=${iteration}`, {
            waitUntil : 'domcontentloaded'
        });
    
        const watchDog = page.waitForFunction(`document.querySelector('#dvTable').innerHTML !== 'TEST'`, {
            polling: 100
        });
    
        await watchDog;
    
        let dvTableElements = await page.evaluate((sel) => {
            return document.querySelector(sel).innerHTML;
        }, '#dvTable');
    
        console.log('dvTableElements: ', dvTableElements);

        DATA.push({
            iteration: iteration,
            data: dvTableElements
        });

        page.close();
    }   

    async function processPages(iterations) {
        const promises = iterations.map(scrapPage);

        await Promise.all(promises);

        let finalTime = (new Date()).getTime();

        console.log(DATA);        

        console.log(`Scraping done in ${Math.floor((finalTime - startTime))} mseconds`); // /1000 seconds

        browserPromise.close();
    }

    processPages(ITERATOR);
}

run();
```

**The setup**

This setup is a light setup for debugging purpose of a more complex scraping stuff.
The html page scraped can randomly display an alert.
My scraping script manage that scenario with `page.on('dialog'` event.
I am launching my scraping calls in parallel.

**What is the expected result?**

For pages with alerts, i just want to dismiss the dialog, click by button, puppeteer catch the dvTable content setted with the query parameter in the url.
Pages without alerts works fine.

**What happens instead?**

I got an error in my terminal for pages with alerts

```
> node parallel.js

> dialog
> dialog
> dialog
> dialog
(node:93987) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Page.handleJavaScriptDialog): No dialog is showing undefined
(node:93987) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:93987) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Protocol error (Page.handleJavaScriptDialog): No dialog is showing undefined
(node:93987) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Protocol error (Page.handleJavaScriptDialog): No dialog is showing undefined
dvTableElements:  100
dvTableElements:  200
^C(node:93987) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Protocol error (Runtime.callFunctionOn): Target closed.
```

**Comment by aslushnikov** [comment] 2018-07-19 05:36
I can't reproduce this with Chromium 69 and pptr v1.6.0.
I believe previous chrome versions were auto-closing alert dialogs in certain cases; I don't see this happening any more.

Looks like this is fixed.

**Closed as completed by aslushnikov** 2018-07-19 05:36 UTC
