### ISSUE TITLE
Using fullPage and deviceScaleFactor causes rendering issue in the screenshot.

### ISSUE THREAD

**Issue by haeky** [puppeteer/puppeteer#2123] opened 2018-02-28 21:48 UTC
### Steps to reproduce

**Tell us about your environment:**

I can reproduce in try-puppeteer.appspot.com but it works locally as well.

* Puppeteer version: 1.1.0
* Platform / OS version: Mac OS 10.13.1
* URLs (if applicable): 
* Node.js version: v8.9.0

**What steps will reproduce the problem?**

Here's the code I'm currently using. Currently, the bug only happens intermittently and I can reproduce in https://try-puppeteer.appspot.com

```javascript
const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.setViewport({ width: 375, height: 1200, deviceScaleFactor: 2 })
await page.goto('https://www.apple.com');

console.log(await page.content());
await page.screenshot({path: 'screenshot.png', fullPage: true });

await browser.close();
```

**What is the expected result?**

![image](https://user-images.githubusercontent.com/4105421/36814835-c5c7bac4-1ca6-11e8-934e-e7b06406f58c.png)

**What happens instead?**
![image](https://user-images.githubusercontent.com/4105421/36814945-2334bf0e-1ca7-11e8-86fd-3dbe492cc22a.png)

**Comment by grantstephens** [comment] 2018-02-28 22:14
Yes, this looks like a duplicate of #1576

**Comment by paulirish** [comment] 2020-11-13 19:54
dupe of #1576

**Closed as completed by paulirish** 2020-11-13 19:54 UTC
Labels: chromium
