### ISSUE TITLE
await page.content() is hanging without a response

### ISSUE THREAD

**Issue by kselax** [puppeteer/puppeteer#4065] opened 2019-02-25 19:13 UTC
I have this code
```javascript
...
await Promise.race([
  page.goto(${permalink}, { timeout: 0, waitUntil: 'networkidle0' }),
  page.waitForFunction(`document.querySelector('[selected="true"] a[href*="tab=sdfsdf"]') !== null`)
])

console.log('here we are');
// await page.waitFor(10000)

const content = await page.content()
console.log('here we are2');
...
```

When I do 30 iterations this cod always hanging on the line
const content = await page.content()
here is the output

```
r[0].insertId = 0
r[0].affectedRows = 1
i = 28; permalink = https://some_url
here we are
```

"here we are" and why page.content() is hanging? it doesn't throw any errors.

**Comment by matheusb-comp** [comment] 2019-02-28 10:53
I believe this is related to #4011

**Comment by aslushnikov** [comment] 2019-03-01 03:04
Dupe of #4011

**Closed as completed by aslushnikov** 2019-03-01 03:04 UTC

**Comment by kselax** [comment] 2019-03-17 09:35
No, it's when you open one tab and loading new urls without close/create new page close to the 30th iteration it starts working wrong. (different page functions stop working namely content, click, etc...)
 So you have to always create/close the page when you load a new url

**Comment by aslushnikov** [comment] 2019-03-18 04:44
@kselax does it still fail for you in the latest release of Puppeteer - v1.13.0?
