### ISSUE TITLE
Error: EPERM: operation not permitted, unlink puppeteer\.dev_profile1\CrashpadMetrics-active.pma

### ISSUE THREAD

**Issue by roshkins** [puppeteer/puppeteer#356] opened 2017-08-17 19:02 UTC
Hello! I am testing out the puppeteer api, and the script I'm writing seems to crash partway through execution. Here is the error:

    fs.js:1066
      return binding.unlink(pathModule._makeLong(path));
                     ^

    Error: EPERM: operation not permitted, unlink 'puppeteer\.dev_profile1\CrashpadMetrics-ac
    tive.pma'
        at Object.fs.unlinkSync (fs.js:1066:18)
        at fixWinEPERMSync (rimraf\rimraf.js:210:13)
        at rimrafSync (rimraf\rimraf.js:310:28)
        at rimraf\rimraf.js:341:5
        at Array.forEach (native)
        at rmkidsSync (rimraf\rimraf.js:340:26)
        at rmdirSync (rimraf\rimraf.js:333:7)
        at fixWinEPERMSync (rimraf\rimraf.js:208:5)
        at rimrafSync (rimraf\rimraf.js:310:28)
        at ChildProcess.chromeProcess.on (puppeteer\lib\Launcher.js:87:7)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! okcupid-auto-unlike@1.0.0 start: `node index.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the okcupid-auto-unlike@1.0.0 start script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\roshk\AppData\Roaming\npm-cache\_logs\2017-08-17T18_51_50_095Z-debug.log
    PS D:\projects\okcupid-auto-unlike> node .\index.js
    fs.js:1066
      return binding.unlink(pathModule._makeLong(path));
                     ^

    Error: EPERM: operation not permitted, unlink 'puppeteer\.dev_profile1\CrashpadMetrics-ac
    tive.pma'
        at Object.fs.unlinkSync (fs.js:1066:18)
        at fixWinEPERMSync (rimraf\rimraf.js:210:13)
        at rimrafSync (rimraf\rimraf.js:310:28)
        at rimraf\rimraf.js:341:5
        at Array.forEach (native)
        at rmkidsSync (rimraf\rimraf.js:340:26)
        at rmdirSync (rimraf\rimraf.js:333:7)
        at fixWinEPERMSync (rimraf\rimraf.js:208:5)
        at rimrafSync (rimraf\rimraf.js:310:28)
        at ChildProcess.chromeProcess.on (puppeteer\lib\Launcher.js:87:7)

I've tried removing the fs dependency from my project, that didn't work. 

Smallest code snippet that shows the regression:

```JS
    var p = require("puppeteer");
    var fs = require("fs");
    p
      .launch({
        headless: false
      })
      .then(async browser => {
        try {
          let page = await browser.newPage();

          browser.close();
        } catch (e) {
          console.log("Error! ", e);
        }
      });
```

**Comment by ebidel** [comment] 2017-08-18 17:14
Looks like a duplicate of https://github.com/GoogleChrome/puppeteer/issues/298.

**Closed as completed by ebidel** 2017-08-18 17:14 UTC
