### ISSUE TITLE
[Bug]: puppeteer.connect() sometimes doesn't work for connecting to Google Chrome without clear reasoning

### ISSUE THREAD

**Issue by Xipzer** [puppeteer/puppeteer#12855] opened 2024-07-30 19:36 UTC
### Minimal, reproducible example

```TypeScript
console.log("CONNECTING TO BROWSER...");

const res = await fetch("http://localhost:3364/json/version");
const data = await res.json();

browser = await puppeteer.connect
({
    browserWSEndpoint: data.webSocketDebuggerUrl,
    ignoreHTTPSErrors: true,
    defaultViewport: null,
    headless: false,
}); // This is where the program will hang, if it hangs.

console.log("CONNECTED SUCCESSFULLY!");

const pages = await browser.pages();

console.log("ACCESSING TAB:", pages.length, "of", pages.length);

const page = pages[pages.length - 1];
```

### Background

Google Chrome is being launched via the shell command:
START ""  "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "--remote-debugging-port=3364"

But this issue is consistent by launching Google Chrome via a Shortcut or directly via CMD.

When attempting to connect to a local Google Chrome installation (32-bit or 64-bit) by utilising the remote debugging port launch argument, puppeteer.connect() sometimes hangs forever. 

Closing one of the active tabs can sometimes allow the connection to be reestablished - for example, closing an open GitHub Issues tab (but leaving all other tabs open) can cause the connection to establish (when the above script is re-run) and all tabs to be recognised). For example, if the GitHub Issues tab is the only active tab, opening a new empty tab and closing the GitHub tab can result in the connection to the browser being established.

In the above examples, the GitHub Issues Tab has been the cause (closing any other tab/all other tabs would not make a difference, but closing the GitHub tab would) - though, it's not consistent (sometimes you can reconnect indefinitely, regardless of the tab being open, other times it breaks after the first reconnection). It's happened more than enough times that I've been able to experimentally identify that sometimes there is a problem tab that can be individually closed in order to reestablish browser connectivity.

However, sometimes (after visting a problem site/using a problem tab) closing all active tabs and attempting to reconnect, with only a single new tab, may also cause the indefinite failure to connect. It will simply continue until you finally close Google Chrome and relaunch via the shell command listed above.

This behaviour remains even when calling browser.disconnect() prior to program termination/browser reconnection.

It's not a big issue as the Chrome Browser can always be relaunched with the debugging port command via a shell script, but it can become incredibly inconvenient. 

Another way to trigger this, if you're unable to do so simply via GitHub Issues, is to launch the browser using the debug port argument and then use the browser ordinarily (visit various websites). Then try to connect to the browser with the various tabs you have open/once you've closed down the various tabs.

EDIT: As an example, prior to performing this edit to this issue, I relaunched my Chrome Browser with the command and connected via puppeteer. I then closed my program and opened this issue, then connected via puppeteer again. I then reran the connection via puppeteer and connected again. I then opened various tabs, and went between them and GitHub, and was able to connect via puppeteer again. However, now that I've made edits (pressed the edit button and typed) to this issue, I'm now unable to connect.

### Expectation

Establishing a connection via puppeteer.connect() should not be effected by an active tab.

### Reality

Your browser (and program, depending on the functions you've written/not written) will have to be restarted and you'll have to navigate back to the desired website.

### Puppeteer version

22.13.0

### Node version

21.0.0

### Package manager

npm

### Package manager version

10.2.0

### Operating system

Windows

**Comment by OrKoN** [comment] 2024-07-30 20:00
I would recommend to define a targetFilter in the connect function and see if there are any unusual targets and trying to filter out anything that is not a page or a frame, for example. Usually this sort of thing might happen if there is some unexpected target: e.g., a paused target or a target that blocks the main thread, for example, by running an infinite loop. It could also be some way from some websites to prevent automation (in that case, not much we can do).

**Comment by Xipzer** [comment] 2024-07-30 22:15
Implementing the following:
`        
browser = await puppeteer.connect
({
    browserWSEndpoint: data.webSocketDebuggerUrl,
    ignoreHTTPSErrors: true,
    defaultViewport: null,
    headless: false,
    targetFilter: (target) => !!target.url()
});
`
Seems to have rectified the issue. I will continue testing and see how everything goes. Thanks! 

NOTE: There's quite a few people on various sites encountering this same issue, which may now be solved. This thread would be good to keep around.

**Comment by OrKoN** [comment] 2024-07-31 05:06
Could you investigate more, e.g., by logging the target details in the filter? If it is empty URL, that it sounds like lazy loading frames might be the reason. In that case, the issue might be a duplicate of https://github.com/puppeteer/puppeteer/issues/12814

**Comment by OrKoN** [comment] 2024-07-31 06:27
it is probably not the lazy frames because I cannot repro in a test https://github.com/puppeteer/puppeteer/pull/12859

so it would be really great if you could investigate what causes it. You could use the following targetFilter to print targets that were filtered out:

```
             targetFilter: (target) => {
              const result = !!target.url();
              if (!result) {
                console.log(target.url(), target.type(), target._getTargetInfo());
              }
              return result;
            }
```

**Comment by saitakyn** [comment] 2024-08-02 12:32
We faced exactly the same issue.  
```
        browser = await puppeteer.connect({
            browserURL: 'http://xxx',
            defaultViewport: null,
            headless: false,
        });
        
        console.log("Opening new tab...");
        targetPage = await browser.newPage();
```

Basically everything works, but after certain actions, it stops connecting to the browser. 
After adding targetFilter we can connect to the browser but now it freezes when we open a new tab. Helps to reopen the browser.

The logs from targetFilter: 
```
 other {
  targetId: '06F3141644C19492ADCB1F1AB41E19BE',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 other {
  targetId: '2608DC75D2CC83CBB4944A1EC92911AE',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 other {
  targetId: '2E14159B4A644F3BBCEA60E1A6563066',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 browser {
  targetId: '3564711c-9429-4bcd-9201-1aee068c23ec',
  type: 'browser',
  title: '',
  url: '',
  attached: true,
  canAccessOpener: false
}
 browser {
  targetId: '37cfae93-1d5e-4f53-b8b2-3cb55a4828c4',
  type: 'browser',
  title: '',
  url: '',
  attached: true,
  canAccessOpener: false
}
 other {
  targetId: '3A29A4619703CD6B9DF972387B326762',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 other {
  targetId: '3D430DEB24C8DB41A6BF01BC4C362EB8',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 other {
  targetId: '4B4C2040AFD40193E367F77475204155',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 other {
  targetId: '54F10C389884A24B5FDCDDC978545636',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 browser {
  targetId: '6024687b-897c-4576-a3fe-80e1a2ea7719',
  type: 'browser',
  title: '',
  url: '',
  attached: true,
  canAccessOpener: false
}
 browser {
  targetId: '61665d3b-7654-4433-8780-de3ae96c858b',
  type: 'browser',
  title: '',
  url: '',
  attached: true,
  canAccessOpener: false
}
 other {
  targetId: '6A15058E3D5F120437D7CDA3E434ED58',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 other {
  targetId: '6BBA496E96A3BC5B879F0D7ECD4AC81E',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 other {
  targetId: '7511D859D35F771B9CD871E497EC910E',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 other {
  targetId: '941266942DD2EB969F1E13F86481A793',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 browser {
  targetId: '988cd100-b2f1-4242-bc07-c9d530771b23',
  type: 'browser',
  title: '',
  url: '',
  attached: true,
  canAccessOpener: false
}
 other {
  targetId: 'A686AD75210CC03C02711E2E3EF28393',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 other {
  targetId: 'B0FF259CFE5956BD02DD62A6188E458E',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 other {
  targetId: 'D37657C5217146EF51B0D47D36701E8B',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 other {
  targetId: 'DDB7DDD673A63B69500D6E24A45BAF9F',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 other {
  targetId: 'DF077E523AD085F5CE3399A490CB491D',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 other {
  targetId: 'E61B4DE4F2175E6FD67704FF7FDCAF61',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 other {
  targetId: 'FB231A00C39B2E61AC26029F0EC69603',
  type: 'worker',
  title: '',
  url: '',
  attached: false,
  canAccessOpener: false
}
 browser {
  targetId: 'a3b5388e-ec03-4ecd-a8cf-3b1cf1198cca',
  type: 'browser',
  title: '',
  url: '',
  attached: true,
  canAccessOpener: false
}
 browser {
  targetId: 'adfaf35f-ba89-45f4-97ba-1e711baee0e5',
  type: 'browser',
  title: '',
  url: '',
  attached: true,
  canAccessOpener: false
}
 browser {
  targetId: 'c0ec858e-8500-454e-8f01-48d255e804f4',
  type: 'browser',
  title: '',
  url: '',
  attached: true,
  canAccessOpener: false
}
Focusing on the first page...
Opening new tab...
 tab {
  targetId: 'AC3C73DFDC36439B4A0CB3FB2B504730',
  type: 'tab',
  title: '',
  url: '',
  attached: true,
  canAccessOpener: false,
  browserContextId: '018C7BC94DD474E08B1E516A2DBBD7E4'
}
```

**Comment by OrKoN** [comment] 2024-08-02 12:35
Yeah, that url-based filter would filter out all tab targets which are new pages so Puppeteer would not connect to the new page. All the targets on the list you provided seem fine to connect to.

**Comment by OrKoN** [comment] 2024-08-05 18:11
It sounds like the same issue as https://github.com/puppeteer/puppeteer/issues/12715 related to some left-over service workers after some captcha services have been loaded.

**Closed as not planned by OrKoN** 2024-08-05 18:11 UTC
Labels: needs-feedback
