### ISSUE TITLE
[Bug]: Puppeteer crashes on browser.close() with: Received signal 11 <unknown>

### ISSUE THREAD

**Issue by peterthoeny** [puppeteer/puppeteer#8818] opened 2022-08-19 17:54 UTC
### Bug description

I face an issue with a puppeteer script. The script runs fine and produces a screenshot, except that it crashes at the end in browser.close() with a stack trace.

Steps to reproduce the problem:

1. Run the script to reproduce the issue (see code in "Relevant log output" section below)
2. On browser.close() the log shows a "Received signal 11 <unknown>" error with stack trace (see details in "Relevant log output" section below)
3. See additional environment info in "Relevant log output" section below

FYI, I am using the chromium that npm installs with puppeteer.

### Puppeteer version

16.1.1

### Node.js version

v14.20.0

### npm version

8.18.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
______________________________________________________
Script to reproduce the issue:

import puppeteer from 'puppeteer';
import { PendingXHR } from 'pending-xhr-puppeteer';

const puppeteerOptions = {
    headless:           true,
    dumpio:             true,
    userDataDir:        './user-data',
    defaultViewport:    null,
    args: [
        '--window-size=1200,800',
        '--disable-notifications',
        '--disable-geolocation',
        '--disable-infobars',
        '--disable-extensions',
        '--disable-session-crashed-bubble',
        '--disable-gpu',
        '--disable-features=NetworkService',
        '--disable-audio-output',
        '--mute-audio',
        '--silent-debugger-extension-api',
        '--single-process',
        '--disable-setuid-sandbox',
        '--full-memory-crash-report',
        '--unlimited-storage'
    ]
}
let url = process.argv[2];
if(!url) {
    console.log('Specify URL');
    process.exit(1);
}

const sleep = m => new Promise(r => setTimeout(r, m));  // sleep is a setTimeout that can be awaited

(async() => {
    console.log('==> initialize headless browser');
    const browser = await puppeteer.launch(puppeteerOptions);
    const page = await browser.newPage();
    const pendingXHR = new PendingXHR(page);
    try {
        console.log('==> load ' + url);
        await page.setDefaultNavigationTimeout(0);
        await page.goto(url, { waitUntil: 'networkidle0' });    // wait for page load
        console.log('==> await page.setRequestInterception');
        await page.setRequestInterception(true);                // intercept requests, for next line
        console.log('==> await pendingXHR.waitForAllXhrFinished');
        await pendingXHR.waitForAllXhrFinished();               // wait for all requests to finish
        console.log('==> generate screenshot');
        await page.screenshot({ path: './screenshot.png', fullPage: true });
        await sleep(2000);
    } catch (error) {
        console.log('==> Catch ERROR: ' + error.message);
    }
    console.log('==> page.close()');
    await page.close();
    await sleep(2000);
    console.log('==> browser.close()');
    await browser.close();
    console.log('==> script end');
})();

______________________________________________________
Script run showing error:

-bash-4.2$ node demo https://www.google.com/
==> initialize headless browser
[0818/152036.508006:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.

DevTools listening on ws://127.0.0.1:45180/devtools/browser/82b03d2a-eaba-44b0-b6f5-e571a8cbe093
==> load https://www.google.com/
==> await page.setRequestInterception
==> await pendingXHR.waitForAllXhrFinished
==> generate screenshot
==> page.close()
==> browser.close()
Received signal 11 <unknown> 000000000000
#0 0x5601f8f7c612 base::debug::CollectStackTrace()
#1 0x5601f8edb193 base::debug::StackTrace::StackTrace()
#2 0x5601f8f7c131 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f9371ffd5d0 (/usr/lib64/libpthread-2.17.so+0xf5cf)
#4 0x5601f8f366f4 base::SupportsUserData::GetUserData()
#5 0x5601f6c9ca0e content::RenderProcessHostImpl::UnregisterHost()
#6 0x5601f6c9c1f4 content::RenderProcessHostImpl::~RenderProcessHostImpl()
#7 0x5601f6c9ce2e content::RenderProcessHostImpl::~RenderProcessHostImpl()
#8 0x5601f6c9bfa8 content::RenderProcessHostImpl::ShutDownInProcessRenderer()
#9 0x5601f68ac5df content::BrowserMainLoop::ShutdownThreadsAndCleanUp()
#10 0x5601f68adead content::BrowserMainRunnerImpl::Shutdown()
#11 0x5601fe67a557 headless::HeadlessContentMainDelegate::RunProcess()
#12 0x5601f8a66942 content::RunBrowserProcessMain()
#13 0x5601f8a67ed9 content::ContentMainRunnerImpl::RunBrowser()
#14 0x5601f8a67a70 content::ContentMainRunnerImpl::Run()
#15 0x5601f8a64c54 content::RunContentProcess()
#16 0x5601f8a655e4 content::ContentMain()
#17 0x5601f8abf3ba headless::(anonymous namespace)::RunContentMain()
#18 0x5601f8abf0c5 headless::HeadlessShellMain()
#19 0x5601f52da1e3 ChromeMain
#20 0x7f936d8903d5 __libc_start_main
#21 0x5601f52da02a _start
  r8: 00007ffefefdc440  r9: 0000000000000001 r10: 0000000000000002 r11: 00005601feeeb5a0
 r12: 000004e80065d400 r13: 00005601fee60530 r14: 000004e80023cd08 r15: 000004e80065d400
  di: 000004e80023cd18  si: 00005601f354dd90  bp: 00007ffefefdc470  bx: 000004e80035c700
  dx: badbad00badbad08  ax: 000004e80023cd18  cx: badbad00badbad00  sp: 00007ffefefdc470
  ip: 00005601f8f366f4 efl: 0000000000010206 cgf: 0000000000000033 erf: 0000000000000000
 trp: 000000000000000d msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
==> script end
-bash-4.2$

______________________________________________________
Environment:

-bash-4.2$ uname -a
Linux xxxxxxxx-02 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
-bash-4.2$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
-bash-4.2$ node --version
v14.20.0
-bash-4.2$ npm --version
8.18.0
-bash-4.2$ grep '"version"' /usr/lib/node_modules/puppeteer/package.json
  "version": "16.1.1"
-bash-4.2$ grep '"version"' /usr/lib/node_modules/pending-xhr-puppeteer/package.json
  "version": "2.3.3"
-bash-4.2$ ls /usr/lib/node_modules/puppeteer/.local-chromium/
linux-1022525
-bash-4.2$ /usr/lib/node_modules/puppeteer/.local-chromium/linux-1022525/chrome-linux/chrome --product-version
105.0.5173.0
-bash-4.2$ google-chrome --product-version
104.0.5112.101
```

**Comment by peterthoeny** [comment] 2022-08-22 18:29
Same issue posted on stackoverflow, no answer yet:
https://stackoverflow.com/questions/73410140/puppeteer-crashes-on-browser-close-with-received-signal-11-unknown

**Comment by OrKoN** [comment] 2022-08-23 07:35
Unable to reproduce on Mac. Could you try to reproduce the bug using the `google-chrome` binary (by providing the executable path to the launch function)? If the crash happens there, could you re-launch binary with the same user-data-dir and provide the crash id from chrome://crashes

**Comment by peterthoeny** [comment] 2022-08-25 00:33
@OrKoN: Not sure how to do that. This is a CentOS 7.6 server without GUI. AFAIK I can only run the headless browser on it, which is fine since we only need shell access and provide an REST API on that server.

Anyway to get the detail you need from user-data?

```
-bash-4.2$ ls
data                 logs           package-lock.json  
load-dashboard.json  node_modules   user-data
load-dashboard.js    package.json
-bash-4.2$ ls user-data/
BrowserMetrics  Default  DevToolsActivePort
-bash-4.2$ find user-data/|wc
   7053    7200  379692
-bash-4.2$ find user-data/|head
user-data/
user-data/BrowserMetrics
user-data/BrowserMetrics/BrowserMetrics-6067A59D-22A93.pma
user-data/Default
user-data/Default/Cache
user-data/Default/Cache/Cache_Data
user-data/Default/Cache/Cache_Data/index
user-data/Default/Cache/Cache_Data/328cf810b070fdbd_0
user-data/Default/Cache/Cache_Data/index-dir
user-data/Default/Cache/Cache_Data/index-dir/the-real-index
-bash-4.2$ find user-data/|tail
user-data/Default/databases
user-data/Default/databases/Databases.db
user-data/Default/databases/Databases.db-journal
user-data/Default/Cookies
user-data/Default/Cookies-journal
user-data/Default/Preferences
user-data/Default/QuotaManager
user-data/Default/QuotaManager-journal
user-data/.org.chromium.Chromium.VBth2L
user-data/DevToolsActivePort
-bash-4.2$
```

**Comment by OrKoN** [comment] 2022-08-26 06:26
No, unfortunately, I don't know how to extract it from the user-data. I see crashes with a similar signature though. Let me file a bug upstream for this.

**Comment by OrKoN** [comment] 2022-08-26 07:05
https://crbug.com/1356885

**Comment by peterthoeny** [comment] 2022-08-26 18:40
Thank you @OrKoN!

**Comment by OrKoN** [comment] 2022-10-11 14:33
This should be fixed with m107 which was rolled out.

**Closed as completed by OrKoN** 2022-10-11 14:33 UTC
Labels: upstream, confirmed
