### ISSUE TITLE
setRequestInterception + ignoreHTTPSErrors , Unable to open the site certificate error

### ISSUE THREAD

**Issue by vc1** [puppeteer/puppeteer#1441] opened 2017-11-21 11:52 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: '0.13.0'
* Platform / OS version: windows10 1703
* Chromium: 64.0.3264.0 dev x64
* URLs (if applicable): website with https certificate errors

**What steps will reproduce the problem?**

```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    ignoreHTTPSErrors: true,
    devtools: true
  })
  const page = await browser.newPage()
  await page.setRequestInterception(true)
  page.on('request', request => {
    console.log(request.url)
    request.continue()
  })
  page.goto('https://segmentfault.com', { timeout: 100000 }) // ✔ can load

  const page2 = await browser.newPage()
  await page2.setRequestInterception(true)
  page2.on('request', request => {
    console.log(request.url)
    request.continue()
  })
  page2.goto('https://112.126.83.219/', { timeout: 100000 }) // ❌ pending

  await page2.waitFor(100000)
  await browser.close()
})()
```

**What is the expected result?**
Loading until a timeout has been

**Comment by vc1** [comment] 2017-11-21 16:34
i solve this by use 2 flags
```javascript
const browser = await puppeteer.launch({
    ignoreHTTPSErrors: false, // doesn't matter
    args: [
        '--ignore-certificate-errors',
        '--ignore-certificate-errors-spki-list '
    ]
})
```


may be Chromium's bug (64.0.3264.0 dev x64)
```javascript
  // ignoreHTTPSErrors: true
  const page2 = await browser.newPage()
  await page2._client.send('Security.setOverrideCertificateErrors', { override: true })
  await page2._client.on('Security.certificateError', event => {
    page2._client.send('Security.handleCertificateError', {
      eventId: event.eventId,
      action: 'continue' // ignore error and continue request
    })
  })
  await page2.setRequestInterception(true)
  page2.on('request', request => {
    console.log(request.url)
    console.log(page._ignoreHTTPSErrors) // > true
    request.continue()
  })
  // then  request is still always pending
```

**Comment by boligolov** [comment] 2017-12-15 08:15
The issue is still here... :(

There is no way to pass through certificate error in headless mode.

**Comment by aslushnikov** [comment] 2018-01-12 04:27
Closing as a dupe of #1159.

**Closed as completed by aslushnikov** 2018-01-12 04:27 UTC
