### ISSUE TITLE
Add support for coverage module

### ISSUE THREAD

**Issue by nojvek** [puppeteer/puppeteer#663] opened 2017-09-02 19:07 UTC
Chrome devtools coverage is pretty mind blowing. Its insanely fast. I'm guessing this is because v8 does some magic internally to record this. 

Having puppeteer report coverage would be great. This means I can write asserts on coverage. 

I don't think devtools provides source-mapped coverage info but that would be amazing. 

```
page.enableCoverage({files: []}) // rules on which files to track coverage (could be source mapped ones)
page.coverage.??? // module to show coverage info 
```

**Comment by Garbee** [comment] 2017-09-02 20:00
Duplicate of #320

**Closed as completed** 2017-09-02 23:10 UTC
