### ISSUE TITLE
Navigation Timeout Exceeded when set page.setRequestInterception(true)

### ISSUE THREAD

**Issue by luckhpy** [puppeteer/puppeteer#4018] opened 2019-02-15 08:28 UTC
when i set page.setRequestInterception(true) and run e2e test in these two situation
1. run app in local with localhost:3000 and use nginx to proxy localhost:3000 to test.XXX.com。then i run e2e test and open it in browser it block as Navigation Timeout Exceeded。
2. make the same set and run e2e in origin page XXX.XXX.com it successed.

it is my config below
  const browser = await puppeteer.launch ({
    args: [
      '--disable-setuid-sandbox',
      '--no-sandbox',
      '--ignore-certificate-errors',
    ],
    ignoreHTTPSErrors: true,
    headless: true,
  });

**Comment by aslushnikov** [comment] 2019-03-01 23:16
The request interception hanging problems are usually caused by #3471; closing this as dupe of that issue.

**Closed as completed by aslushnikov** 2019-03-01 23:16 UTC
