### ISSUE TITLE
Screenshots clipped when using deviceScaleFactor:2 and fullPage:true

### ISSUE THREAD

**Issue by chfw** [puppeteer/puppeteer#755] opened 2017-09-11 22:47 UTC
### What I am doing

A number of serial screenshots were taken in order to make a gif animation. Please see the gif in the expected section.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: MacOS 10.11.6
* URLs (if applicable): https://github.com/chfw/echarts-scrappeteer

**What steps will reproduce the problem?**

```
git clone https://github.com/chfw/echarts-scrappeteer.git
cd echarts-scrappeteer
git checkout wrong-behavior
npm install
node src/main.js http://gallery.echartsjs.com/editor.html?c=xrkJtnKJq- -w 2000 -f gif -r 1050,100,1540,1500 -o gf3 -i 300 -c 10 -v 1300,800,2
```

Most significant parameters in my case is:
```
-v, --viewPort <width,height,scaleFactor>  force puppeteer to set viewport. for echarts gallery site only
-r, --clipRectangle <x,y,width,height>     record rectangle when making gif animation
```

**What is the expected result?**

A sharp version of the following gif:

![myanimated](https://user-images.githubusercontent.com/4280312/30299776-32797ede-9749-11e7-9c53-421fff8e9c81.gif)

here is the command to produce above gif 👍 but the image is blurred:
`node src/main.js http://gallery.echartsjs.com/editor.html?c=xrkJtnKJq- -w 2000 -f gif -r 525,50,770,750 -o gf3 -i 300 -c 10 -v 1300,800,1`

**What happens instead?**

`node src/main.js http://gallery.echartsjs.com/editor.html?c=xrkJtnKJq- -w 2000 -f gif -r 1050,100,1540,1500 -o gf3 -i 300 -c 10 -v 1300,800,2` produces

![myanimated](https://user-images.githubusercontent.com/4280312/30299649-82dcf582-9748-11e7-9f50-6e5c614d5ba6.gif)

I also tried `node src/main.js http://gallery.echartsjs.com/editor.html?c=xrkJtnKJq- -w 2000 -f gif -r 525,50,770,750 -o gf3 -i 300 -c 10 -v 1300,800,2` and got the following:

![myanimated](https://user-images.githubusercontent.com/4280312/30300132-edcb47fc-974a-11e7-9976-30825bc7aead.gif)

**Here is the screenshot process**

![out](https://user-images.githubusercontent.com/4280312/30299864-a745ff12-9749-11e7-9bc1-bdb6c6db2dd5.gif)

**Comment by aslushnikov** [comment] 2017-10-05 00:40
Looks like a duplicate of #800

**Comment by chfw** [comment] 2017-10-05 06:12
Issue 800 has deviceScaleFactor as 1. Mine works fine with the factor as 1. However, it does not work when the factor is 2.

**Comment by aslushnikov** [comment] 2017-10-07 08:23
un-duplicating then.

**Comment by kennethaasan** [comment] 2017-10-17 12:59
I'm working on replacing our service that's using PhantomJS to generate screenshots. I found the same bugs as described in this issue with deviceScaleFactor set to 3. I've made many requests now and about every 5th time I get a buggy response.

Working correctly:
![chrome_headless](https://user-images.githubusercontent.com/1437394/31666087-4f943996-b34b-11e7-9297-7f32d9abff69.png)
Bug:
![chrome_headless_bug](https://user-images.githubusercontent.com/1437394/31666088-4fb39a34-b34b-11e7-8a51-ee403a7d4bbb.png)

This is my code:
```js
import { SCREENSHOT } from '../constants';
import puppeteer from 'puppeteer';

const { WIDTH, SCALE, PROXY } = SCREENSHOT;

async function makeScreenshot(url, width = WIDTH, deviceScaleFactor = SCALE) {
  if (!url) {
    throw new Error('url is required');
  }

  const browser = await puppeteer.launch({
    ignoreHTTPSErrors: true,
    args: [`--proxy-server=${PROXY}`],
  });

  const page = await browser.newPage();

  page.on('requestfailed', req => {
    const res = req.response();
    throw new Error(
      `ResourceNotFoundError ${res.url} responded with ${res.status}`
    );
  });

  await page.setViewport({
    width,
    height: 1,
    deviceScaleFactor,
  });

  const res = await page.goto(url, {
    waitUntil: 'networkidle',
  });

  if (!res.ok) {
    const status = await res.text();
    throw new Error(`${url} responded with ${res.status}: ${status}`);
  }

  const screenshot = await page.screenshot({
    fullPage: true,
  });

  await browser.close();

  return screenshot;
}

export default makeScreenshot;

```

When I'm setting fullPage to false and set height to a fixed height it doesn't respond with this bug. So it might be related to the fullPage option.

**Comment by 3fuyu** [comment] 2017-10-30 01:52
@chfw set a timeout between setViewport and screenshot can solve this problem

**Comment by bertelli** [comment] 2017-10-30 21:30
I can add that in my case, i'm using Puppertron as web interface to get the screenshots, but the core is still puppeteer and I get the image clipped in half when using scale factor: 2, **BUT** if I reload it twice the second time or third the page looks good and complete. So my hunch could be timing? page not ready when taking screenshots? just guessing...

**Comment by kennethaasan** [comment] 2017-10-30 21:45
@bertelli Since I have the same problem as you and this is the only bug preventing me from using Headless Chrome instead of PhantomJS in production, I will try to find time to debug this problem later this week and make a PR. Only difference is that I use scale factor: 3.

**Comment by bertelli** [comment] 2017-10-30 21:57
same here: I moved away from PhantomJS that was giving me poor results... and now i love Puppeteer..works flawlessly in scaleFactor 1!
ll try the setInterval solution suggested  ...will see

**Comment by kennethaasan** [comment] 2017-10-30 22:30
I tried setting timeout to 0, 1000 and 10000. Same result

**Comment by chfw** [comment] 2017-10-30 22:41
same result here too.

**Comment by chfw** [comment] 2017-10-30 22:56
tried with latest version 0.12.0 as well. same result.
![gf3](https://user-images.githubusercontent.com/4280312/32199657-7b9c5e36-bdc5-11e7-992f-46a2eda1c66c.gif)

**Comment by jontro** [comment] 2018-02-14 16:44
I even get it randomly after setting setContent. I've reduced the chance of it happening by using the code below. 

However I still think it's really weird that setContent triggers the bug after a lot of successful requests. 

```

let page = null;
puppeteer.launch().then(browser => {
  app.post('/generate', async (req, res, next)  => {
    if (page === null) {
        page = await browser.newPage();
        await page.setViewport({
            width: 100,
            height: 50,
            deviceScaleFactor: 3.125,
        });
        await page.goto(`data:text/html,${req.body.contents}`, { waitUntil: 'networkidle2' });
    }
    await page.setContent(req.body.contents);
    await timeout(50);
    await page.screenshot({
        path: '/tmp/tmp.png',
         fullPage: true,
    
    })
  }
});
```

I also tried setting the Viewport to `document.documentElement.offsetHeight` and skipping the fullPage: true flag. The bug still appears

Using the latest google-chrome-unstable from http://dl.google.com/linux/chrome/deb/ in a Docker environment

**Comment by shennan** [comment] 2018-07-23 15:11
I have a similar issue, only slightly different. When using a scale factor above 1, the screenshot is clipped at varying degrees depending on the scale factor setting. A higher setting produces more of a clipping.

However, this only happens when returning a base64 image. On producing a PNG, written to disk, all is fine, even with scale factor set above 1.

Not sure what implications this has for a fix, but thought the info might be useful.

**my environment**

- Puppeteer 1.6.0
- MacOS Seirra 10.12.6

**Comment by JnStyles** [comment] 2018-09-26 10:38
await page.reload();
This problem can be solved temporarily

**Comment by bestis** [comment] 2020-03-09 09:04
I think it might help if there would be possibily to set some delay before capturing the screenshot after the scaling is done. 

Some parameter for the page.screenshot to allow setting it. As the waiting before the screenshot does not help as the problem is part of taking the screenshot.

As I noticed that deviceScaleFactor 2 => Cut's the screenshot from  right.
deviceScaleFactor 1.5 => Works.

Or this might somehow also be related to viewport size problems that the captures outside viewport size does not work.

**Comment by gmetais** [comment] 2021-03-22 13:24
I am experiencing the same issue when running Puppeteer on an Amazon Lambda machine. I've never had the problem when running on Ubuntu or MacOS.

It doesn't happen on every website I open with Puppeteer. But one website on 5 or 6 shows the issue. For some of them, reloading the page fixes the problem, for some it keeps clipping the screenshot:

![image](https://user-images.githubusercontent.com/498031/111996389-e2c1f900-8b11-11eb-9ad1-c64defa90c92.png)



I'm not using deviceScaleFactor directly, but `page.emulate("Galaxy S5")`, which seems to use it anyway.

**Closed as completed** 2022-07-24 15:24 UTC
Labels: P1, chromium, unconfirmed
