### ISSUE TITLE
[Bug]: cannot install puppeteer in android

### ISSUE THREAD

**Issue by SunPodder** [puppeteer/puppeteer#9463] opened 2023-01-03 13:14 UTC
### Bug description

Steps to reproduce the problem:

When os.platform() returns Android, there is an error that prevents it from being installed

### Puppeteer version

v19.4.1

### Node.js version

v18.12.1

### npm version

8.19.2

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```Shell
All fragments that determine the device according to os.platform()
```

**Comment by SunPodder** [comment] 2023-01-03 13:16
**Don't close without a proper solution.**

Atleast let us know why puppeteer cannot be installed on Android via a linux emulator where we have a browser and nodejs.

**Comment by jrandolf** [comment] 2023-01-04 07:51
Please do not open duplicate issues. Closed issues can always be reopened.

Duplicate of https://github.com/puppeteer/puppeteer/issues/9460

**Closed as not planned by jrandolf** 2023-01-04 07:51 UTC
