### ISSUE TITLE
Hey,I met a big issues with a 302 redirect when i used setRequestInterception(true) function...

### ISSUE THREAD

**Issue by zhaojiyu** [puppeteer/puppeteer#3851] opened 2019-01-28 09:32 UTC
When i set setRequestInterception(true), I can't catch the url result whit market prefix.

**Comment by aslushnikov** [comment] 2019-01-28 16:15
This looks like a dupe of https://github.com/GoogleChrome/puppeteer/issues/3471
However, things got better on tip-of-tree Puppeteer; please try installing puppeteer@next and see if it helps

```js
npm i puppeteer@next
```

Closing as dupe of #3471

**Closed as completed by aslushnikov** 2019-01-28 16:15 UTC
