### ISSUE TITLE
can't launch browser parallel, or some got ECONNRESET

### ISSUE THREAD

**Issue by harkue** [puppeteer/puppeteer#1865] opened 2018-01-21 08:44 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: V1.0.0
* Platform / OS version: CentOS 7.2
* URLs (if applicable): 
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

```
const puppeteer = require('puppeteer');
let chrome_bin_path = null; 
let args = process.argv
let url = args[2] || 'http://www.example.png';
let imgPath = args[3] || 'example.png';

console.log("url:" + url);
console.log("image path: " + imgPath);

(async () => {
    try {
        const browser = await puppeteer.launch({
            executablePath: chrome_bin_path,
            args: ['--no-sandbox'] // , '--disable-setuid-sandbox' // it needs root privilleage
        });
        const page = await browser.newPage();

        await page.setViewport({
            width: 1440,
            height: 6000
        });
        await page.goto(url);

        await page.waitFor(1000);

        let frame = page.mainFrame().childFrames()[0];
        let width;
        let height;
        if (!frame) {
            width = 360;
            height = 640;
        } else {
            const selector = 'div#root';
            await frame.waitFor(selector);

            width = await frame.$eval(selector, e => e.clientWidth);
            height = await frame.$eval(selector, e => e.clientHeight);
        }
        console.log({ width, height });

        await page.screenshot({
            path: imgPath,
            clip: {
                x: 0,
                y: 0,
                width: width,
                height: height
            }
        });


        await page.close();
        await browser.close();
        console.log("Page capture Done!!");
    } catch (err) {
        console.log("page capture failed", err);
        process.exit(1);
    }

})();
```

_Please include code that reproduces the issue._

1. Install puppeteer v1.0.0, and download local chromium successfully.
2. Write a file named page-capture.js, as the code above.
3. Execute "node page-capture.js" in 3 cmd window at the same time.
4. Some process capture failed, it got an error like "ECONNRESET"。

**What is the expected result?**
Expected all print 'Page capture Done!!'

**What happens instead?**

got an error like "ECONNRESET"。

What is the reason?

Can I launch multiply browser instances in the same time?
What is the solution to do page capture parallel?

**Comment by vc1** [comment] 2018-01-21 09:00
www.example.png

 www.example.ORG ??

**Comment by harkue** [comment] 2018-01-26 01:51
www.example.com

**Comment by aslushnikov** [comment] 2018-08-31 16:03
I cannot reproduce on pptr v1.7.0; speculatively closing this.

Also, take a look on #1873 for better parallelization techniques.

**Closed as completed by aslushnikov** 2018-08-31 16:03 UTC
