### ISSUE TITLE
Puppeteer fails with Chromium 72.0.3626.96

### ISSUE THREAD

**Issue by thesocialdev** [puppeteer/puppeteer#4040] opened 2019-02-20 19:06 UTC
Hello everyone, I am working on a Wikimedia project called [chromium render](https://github.com/wikimedia/mediawiki-services-chromium-render) (a.k.a Proton) and we use Debian stretch and its stable channel to run chromium. Recently we had an [issue](https://phabricator.wikimedia.org/T216493) registered after Debian [library upgrade](https://lists.debian.org/debian-security-announce/2019/msg00036.html) to 72.0.3626.96-1~deb9u1.

Now we got the following error when trying to instantiate chromium inside a job queue:

```
Unexpected error: Error: Failed to launch chrome!\n[0219/100722.128782:ERROR:address_tracker_linux.cc(158)] Could not create NETLINK socket: Operation not supported (95)\nFailed to create secure directory (/nonexistent/.config/pulse): No such file or directory\nReceived signal 11 SEGV_MAPERR 000000000080\n#0 0x5631c6f02711 <unknown>\n#1 0x5631c6f02b7b <unknown>\n#2 0x5631c6f031de <unknown>\n#3 0x7f412c3350c0 <unknown>\n#4 0x5631c52ea314 <unknown>\n#5 0x5631c52f51b7 <unknown>\n#6 0x5631ca9dd566 <unknown>\n#7 0x5631ca9dd61a [0219/100722.141180:ERROR:udev_linux.cc(21)] Failed to initialize udev, possibly due to an invalid system configuration. Various device-related browser features may be broken.\n<unknown>\n#8 0x5631c5286fd3 <unknown>\n#9 0x5631c5700c32 <unknown>\n#10 0x5631c5289089 <unknown>\n#11 0x5631c528a039 <unknown>\n#12 0x5631cb4af775 <unknown>\n#13 0x5631c69ad257 <unknown>\n#14 0x5631c69ad501 <unknown>\n#15 0x5631c69ad8b0 <unknown>\n#16 0x5631c69b8b7a <unknown>\n#17 0x5631c69ab6c5 <unknown>\n#18 0x5631ca9e32e3 <unknown>\n#19 0x5631ca9e34d4 <unknown>\n#20 0x5631c69b5d49 <unknown>\n#21 0x5631c4653d6d ChromeMain\n#22 0x7f411e75f2b1 __libc_start_main\n#23 0x5631c4653b8a _start\n  r8: 0000000000000001  r9: 0000000000000030 r10: 00007f40ebfff9d0 r11: 0000000000000202\n r12: 00007ffff50ac1f0 r13: 00005631ce187d30 r14: 00007ffff50ac240 r15: 00005631ce1862c0\n  di: 00007ffff50ac1f0  si: 00005631cba9a770  bp: 00007ffff50ac290  bx: 00005631ce186490\n  dx: 00005631c52ea314  ax: 00007ffff50ac1f0  cx: 0000000000000319  sp: 00007ffff50ac190\n  ip: 00005631c52ea314 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000004\n trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000080\n[end of stack trace]\nCalling _exit(1). Core file will not be generated.\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n
```
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: **v1.11.0**
* Platform / OS version: **debian stretch**
* Node.js version: **6.11+**

**What steps will reproduce the problem?**
I set up a Docker environment to test it:
1. clone https://github.com/mateusbs17/mediawiki-services-chromium-render/tree/puppeteer_stretch
2. 
```
cd path/to/cloned/repo
docker build ./ --file testing.Dockerfile -t proton
docker run -it -p 3030:3030 proton
```
3. If you can see the service startup log, access http://localhost:3030/en.wikipedia.org/v1/pdf/Brazil/letter to test the PDF rendering

**What is the expected result?**
- The server returns 200 and PDF is downloaded successfully

**What happens instead?**
- The server returns 500 and you can see the error mentioned above on the server log.

With the right matching versions between puppeteer and chromium the service works fine. You can reproduce them following steps above with the repos below:
- Puppeteer v1.11.0 with chromium 72.0.3618.0: https://github.com/mateusbs17/mediawiki-services-chromium-render/blob/puppeteer_v1.11.0
- Puppeteer v1.12.2 with chromium 73.0.3679.0: https://github.com/mateusbs17/mediawiki-services-chromium-render/tree/puppeteer_v1.12.2

Thanks in advance.

**Comment by dr-dimitru** [comment] 2019-02-28 10:00
Same here, met this exception right after updating to Chromium 72.0.3626.96

**Comment by rasca** [comment] 2019-03-04 20:14
Same error message in my CI pipeline.

**Comment by aslushnikov** [comment] 2019-03-04 21:27
@mateusbs17 @dr-dimitru @rasca looks like the new chromium fails to launch on your host system. Can you try running it manually - does it launch?

**Comment by dr-dimitru** [comment] 2019-03-04 22:18
@aslushnikov yes, it runs perfectly, with and without flags we pass to Chromium via puppeteer

**Comment by aslushnikov** [comment] 2019-03-04 22:20
@dr-dimitru so the only difference here is that it's spawned from-inside node.js process?

**Comment by dr-dimitru** [comment] 2019-03-04 22:22
@aslushnikov yes, by puppeteer

**Comment by rasca** [comment] 2019-03-06 14:02
For me it happens inside a docker instance when I run

```
$ ng test --browsers=ChromeHeadlessCI --code-coverage=true --watch=false
```

with this flags in my karma.conf.js

```
    customLaunchers: {
      ChromeHeadlessCI: {
        base: 'ChromeHeadless',
        flags: [
          '--no-sandbox',
          '--disable-gpu',
          '--headless'
        ]
      }
    },
```

**Comment by mmuehlenhoff** [comment] 2019-03-11 10:12
JFTR, for the setup described by mateusbs17 we fixed it by upgrading to Chromium 72.0.3626.122, there appears to be a regression in Chromium releases >= 72.0.3626.96 and < 72.0.3626.122 which broke --remote-debugging-port. Not closing the task yet, but maybe others affected by this regression could re-test their setups as well.

**Comment by govindrai** [comment] 2019-04-30 17:26
I can confirm that the --remote-debugging-port flag is causing these errors. Chromium  75.0.3765.0 is also broken. remove it and things work fine, except you have a heck of a time debugging. Any chance puppeteer can upgrade the chromium version?

**Comment by dr-dimitru** [comment] 2019-04-30 21:00
@govindrai can't remove it, we use and need it.

**Comment by maxweber** [comment] 2019-06-28 13:50
I've got a similar error with Chromium 73.0.3683.75

```
[1599:1618:0628/132930.082358:ERROR:address_tracker_linux.cc(177)] Could not bind NETLINK socket: Permission denied (13)
```

In my case adding the flag `--disable-gpu` helped to avoid this error. But I have no clue why ;-)

**Closed as completed** 2022-07-27 10:46 UTC
Labels: unconfirmed
