### ISSUE TITLE
screenshot problem

### ISSUE THREAD

**Issue by Samlin901211** [puppeteer/puppeteer#1150] opened 2017-10-24 14:41 UTC
I run a program in Ubuntu and take a screenshot.But the Chinese words are as same as squares.Howerver,it's ok in Window 7。Someone knows how to solve it?

**Comment by Samlin901211** [comment] 2017-10-24 14:42
LANG=
LANGUAGE=
LC_CTYPE="zh_CN.utf8"
LC_NUMERIC="zh_CN.utf8"
LC_TIME="zh_CN.utf8"
LC_COLLATE="zh_CN.utf8"
LC_MONETARY="zh_CN.utf8"
LC_MESSAGES="zh_CN.utf8"
LC_PAPER="zh_CN.utf8"
LC_NAME="zh_CN.utf8"
LC_ADDRESS="zh_CN.utf8"
LC_TELEPHONE="zh_CN.utf8"
LC_MEASUREMENT="zh_CN.utf8"
LC_IDENTIFICATION="zh_CN.utf8"
LC_ALL=zh_CN.utf8

**Comment by Samlin901211** [comment] 2017-10-24 14:45
![3](https://user-images.githubusercontent.com/8406620/31949900-fbc246a6-b90c-11e7-839b-ed7da001fced.png)

**Comment by Samlin901211** [comment] 2017-10-24 14:46
![2](https://user-images.githubusercontent.com/8406620/31949946-1cce4e76-b90d-11e7-9f38-7f07107b325b.png)

**Comment by drew28** [comment] 2017-10-24 20:58
Try to install the `google-noto-cjk-fonts` package.

**Comment by aslushnikov** [comment] 2017-10-24 23:18
Looks like a dupe of #1143

**Closed as completed by aslushnikov** 2017-10-24 23:18 UTC
