### ISSUE TITLE
Regression with puppeteer 1.7.0+ (listening requests)

### ISSUE THREAD

**Issue by margussipria** [puppeteer/puppeteer#3369] opened 2018-10-08 10:36 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.7.0+ (1.7.0, 1.8.0, 1.9.0 and master - latest commit 07febb63)
* Platform / OS version: Mac and Debian with Travis CI
* URLs (if applicable): 
   - https://github.com/PaymentHighway/paymenthighway-javascript-lib/tree/testing-node-6 (failing branch)
   - https://travis-ci.org/PaymentHighway/paymenthighway-javascript-lib/builds/438531476 (build with 1.6.2)
   - https://travis-ci.org/PaymentHighway/paymenthighway-javascript-lib/builds/438532582 (build with 1.7.0)
* Node.js version: v7.3.0 (at travis v6.14.4, v8.12.0 and v10.11.0)

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. clone repository https://github.com/PaymentHighway/paymenthighway-javascript-lib.git and switch to branch testing-node-6
2. install dependencies
3. compile typescript and run tests

```bash
git clone --single-branch -b testing-node-6 https://github.com/PaymentHighway/paymenthighway-javascript-lib.git
npm install
npm run compile && npm run test
```

**What is the expected result?**
Test to pass

**What happens instead?**
Chrome hangs

I did git bisect between version 1.6.2 and 1.7.0 and found that commit after which this happened is https://github.com/GoogleChrome/puppeteer/commit/1931cb479e02c185a1085e96d678410048340935.

Place where code starts to hang is here https://github.com/PaymentHighway/paymenthighway-javascript-lib/blob/testing-node-6/ts/tests/FormBuilderTest.ts#L106, there is request listener                                         .on('request', emptyOkWhenNonHubUrl) that gets first redirect, but there is 2nd redirect also and and that is not received by `emptyOkWhenNonHubUrl` listener.

Click at line 106 is doing form POST, but if i replace that line with `page.goto` that reproduces same redirects, all works.

**Comment by margussipria** [comment] 2018-10-25 12:33
Pinging @aslushnikov as I can't add participants.

**Comment by aslushnikov** [comment] 2018-10-26 03:47
Hey @margussipria, thanks for submitting and sorry for the long reply.

This seems to be a dupe of #3089 and eventually nails down to request interception issues in our protocol. This is getting really annoying, so we'll try to fix it ASAP.

**Comment by aslushnikov** [comment] 2018-10-30 22:06
Merging this all to a single umbrella bug - #3471.

**Closed as completed by aslushnikov** 2018-10-30 22:06 UTC
