### ISSUE TITLE
Attempting to download a file by writing the buffer from response

### ISSUE THREAD

**Issue by IronCrystal** [puppeteer/puppeteer#908] opened 2017-09-28 22:14 UTC
I'm attempting to download a file using puppeteer while in headless mode.

Since that does not work, as seen in previous issues, I'm attempting to download the file by getting the buffer data of the response.

My issue is that whenever I try to get the buffer data, I get the following error:

> [2017-09-28T22:10:07.009Z] (Network.getResponseBody): No data found for resource with given identifier undefined
        at Session._onMessage ....

When I am in headless: false mode, the file downloads just fine.  Is there a reason the response has no buffer?  Is there another way to get the data?  It seems there are 2 responses that occur when I try to download the file and both return this buffer error.

The file I am attempting to download is of content type "text/csv"

**Comment by nisrulz** [comment] 2017-09-30 08:12
Hi @IronCrystal I believe you are getting that error because you are listening for all urls and trying to download from the first one thats caught by the listener. Instead you should do something like only attempt a download from a url that contains `.csv` extension in it.

I have created and uploaded an example script to do the same [here](https://github.com/nisrulz/puppeteer-examples/blob/master/download_file_redirect_link/main.js). Do check it out.

**Comment by aslushnikov** [comment] 2017-10-04 21:55
@IronCrystal I can't say much about the issue unless there's a snippet that will help me to reproduce the scenario. Please post a specific example so that we'd be able to follow up on this.

Speculatively closing this since @nisrulz might have addressed the issue with his comment.

**Closed as completed by aslushnikov** 2017-10-04 21:55 UTC

**Comment by sonyarianto** [comment] 2018-02-17 15:04
@IronCrystal 
here is my sample of download and save image from response.buffer()

```
var bufferData = await page.goto('http://bolawow.com/wp-content/uploads/2018/02/fcsm-bilbao-1.jpg');
fs.writeFile("./anu.jpg", await viewSource.buffer(), function(err) {
    if(err) {
        return console.log(err);
    }

    console.log("The file was saved!");
});
```
