### ISSUE TITLE
The downloaded PDF has Chinese garbled code.

### ISSUE THREAD

**Issue by luffyZh** [puppeteer/puppeteer#4956] opened 2019-09-19 09:42 UTC
### Steps to reproduce

**The environment:**

* Puppeteer version: v1.19.0
* Platform / OS version: CentOS Linux release 7.6.1810
* Node.js version: v8.14.0

Dependent dependencies have been installed: 
```
yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 -y

yum install ipa-gothic-fonts xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc -y
```
**What steps will reproduce the problem?**
The download pdf code is get buffer then express.res.attachment('xxx.pdf').send(buffer).
```
try {
    const browser = await puppeteer.launch({
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    const page = await browser.newPage();
    await page.goto(
      targetUrl,
      { waitUntil: 'networkidle2' }
    );
    const pdfBuffer = await page.pdf({
      displayHeaderFooter: false,
      preferCSSPageSize: true,
      path: filePath,
      format: 'A4',
      margin: {
        top: "100px",
        bottom: "200px",
        right: "30px",
        left: "30px",
      }
    });
    await browser.close();
    res.status(200).attachment(`${title}.pdf`).send(pdfBuffer);
} catch (e) {
   next(e);
}
```

**What is the expected result?**
No Chinese garbled code

**What happens instead?**
![图片](https://user-images.githubusercontent.com/17840558/65233031-c4d29d00-db04-11e9-9db2-0d1d7387bd96.png)

**Comment by josherich** [comment] 2019-11-11 03:01
Duplicate of #1143

**Closed as completed** 2019-11-11 03:03 UTC
