### ISSUE TITLE
More specific error classes

### ISSUE THREAD

**Issue by ericyhliu** [puppeteer/puppeteer#2879] opened 2018-07-12 21:03 UTC
It would be great if errors contained a specific error class. This would be really helpful in debugging/determining the type of error rather than just searching through the `err.message`. 

For example, something like `Navigation Timeout Exceeded: ...` could be `NavigationTimeoutExceededError`, etc. I think that this could be a quick fix by changing the `name` property of Errors that are thrown, and having documentation for this.

I think that it would result in much more consistent error handling.

**Comment by aslushnikov** [comment] 2018-07-12 21:10
Thanks @eliucs,

This is a dupe of #1694. I have a draft for this; we'll probably have it soon.

**Closed as completed by aslushnikov** 2018-07-12 21:10 UTC
