### ISSUE TITLE
Hanging intercepted request

### ISSUE THREAD

**Issue by itrmit** [puppeteer/puppeteer#759] opened 2017-09-12 10:11 UTC
Hi!

I'm trying to load a URL: https://kyfw.12306.cn/otn/login/init , but the loading is always interrupted due to a hanging OPTIONS request. This only happens when request interception is enabled.

I'm using "puppeteer": "^0.10.2"

```js
const puppeteer = require('puppeteer');

(async() => {
const browser = await puppeteer.launch({
    slowMo: 250, // slow down by 250ms
    headless: false,
    ignoreHTTPSErrors: true,
    dumpio: true,
});
const page = await browser.newPage();
await page.setRequestInterceptionEnabled(true);
page.on('request', request => {
    request.continue(request);
});


await page.goto('https://kyfw.12306.cn/otn/login/init');
browser.close();
})();
```
And this is the console output for the hanging request. No more requests are performed/intercepted afterwards:

```
[97788:45059:0912/180943.664278:ERROR:service_manager.cc(156)] Connection InterfaceProviderSpec prevented service: content_utility from binding interface: content::mojom::FieldTrialRecorder exposed by: content_browser
(node:97787) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 30000ms exceeded
(node:97787) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Thanks!

**Comment by aslushnikov** [comment] 2017-09-14 01:05
@itrmit thank you for the report, I can reproduce. Looks like a bug in chromium, I'll investigate.

**Comment by zlodes** [comment] 2017-09-15 14:37
@aslushnikov same problem with some post requests.

**Comment by zhaopengme** [comment] 2017-09-20 10:26
12306,good question

**Comment by KristerV** [comment] 2017-10-03 12:44
I have narrowed it down. The problem persists when `ignoreHTTPSErrors: true` is used with `page.setRequestInterceptionEnabled(true);` and the loaded website has SSL problems. Same settings work with google.com for example.

Here's a minimal example to test with, just change the `badSite/goodSite` variable
```JavaScript
'use strict';
const puppeteer = require('puppeteer');
(async() => {
const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'], ignoreHTTPSErrors: true });
const page = await browser.newPage();
await page.setRequestInterceptionEnabled(true);
page.on('request', request => request.continue());

const goodSite = 'https://google.com';
const badSite = 'https://expired.badssl.com/';
await page.goto(goodSite, {timeout: 5000});

await browser.close();
})();
```

edit: I found a workaround. Manually trusting my self-signed cert. I gave [this link](https://unix.stackexchange.com/questions/122753/chrome-certificate#122768) to the admin and he fixed it, too much bash for me :)

**Comment by ali-habibzadeh** [comment] 2017-11-06 11:55
I have the same issue. Any updates on this?

**Comment by aslushnikov** [comment] 2018-01-12 09:47
Closing as a duplicate of #1159.

**Closed as completed by aslushnikov** 2018-01-12 09:47 UTC
