### ISSUE TITLE
[Bug]: browser.newPage() and browser.pages hang because of Chromium crashes

### ISSUE THREAD

**Issue by nikita-kov-dev** [puppeteer/puppeteer#12864] opened 2024-08-01 18:11 UTC
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
      headless: true,
      args: [`--disable-extensions-except=${EXTENSION_PATH}`, `--load-extension=${EXTENSION_PATH`]
})

const page = await browser.newPage() or const pages = await browser.pages()
```

### Background

I use Jest + Puppeteer + TS for e2e testing of my Chromium-based browser extension. I have ~220 tests in 9 different files, and 2-3 tests fail in each file because of Chromium crashes:

![image](https://github.com/user-attachments/assets/cf2f66e5-b2cf-45b2-adc9-ad1d7cff2bd5)

I use the latest Puppeteer (22.15.0), Jest (29.7.0), Fedora (40) and WebStorm IDE (2024.1.5). Unfortunately, I didn't find a good way to work around this issue: there is no way to set a timeout for the newPage and pages method. Also, I understand it's probably a browser issue, but I tried different browsers (Vivaldi, Brave, Opera), and they crashed during e2e tests. Still, they work fine in the system outside of e2e tests without any problem.

### Expectation

I expected the code doesn't hang.

### Reality

It hangs, and the beforeEach method throws an exception: "Error: thrown: "Exceeded timeout of 15000 ms for a hook.
Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

### Puppeteer version

22.15.0

### Node version

20.12.2

### Package manager

npm

### Package manager version

10.8.2

### Operating system

Linux

**Comment by OrKoN** [comment] 2024-08-01 18:38
Have you tried setting https://pptr.dev/api/puppeteer.browserconnectoptions/#protocoltimeout to a lower value so that Puppeteer would time out before your test runner? Also, can you provide a minimal reproducible example for us to reproduce? If not, could you reproduce it with the official Chrome builds and submit a bug report to crbug.com/new with the crash ID from chrome://crashes?

**Comment by OrKoN** [comment] 2024-08-01 18:40
Also, can you confirm which Chromium version you are using? Puppeteer v22.15.0 ships with a [Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing) flavour and not Chromium

**Comment by nikita-kov-dev** [comment] 2024-08-01 21:44
> Also, can you confirm which Chromium version you are using? Puppeteer v22.15.0 ships with a [Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing) flavour and not Chromium

I tried installed version: Version 126.0.6478.182 (Official Build) Fedora Project (64-bit) and the default one (Chrome for Testing)

**Comment by nikita-kov-dev** [comment] 2024-08-01 21:49
> Have you tried setting https://pptr.dev/api/puppeteer.browserconnectoptions/#protocoltimeout to a lower value so that Puppeteer would time out before your test runner? Also, can you provide a minimal reproducible example for us to reproduce? If not, could you reproduce it with the official Chrome builds and submit a bug report to crbug.com/new with the crash ID from chrome://crashes?

Thank you very much! I can handle Chrom(e|ium) crashes with protocolTimeout arg

**Comment by nikita-kov-dev** [comment] 2024-08-01 22:11
@OrKoN I'll provide a separate repo with a reproducible example ASAP, but I need some time to set it up.

**Comment by OrKoN** [comment] 2024-08-02 05:48
@nikita-kov-dev also, please try using `dumpio: true` to see what causes the crash. Note that we cannot install system dependencies when the browser is downloaded yet, so you need to check that everything is installed according to Chrome requirements https://source.chromium.org/chromium/chromium/src/+/main:chrome/installer/linux/rpm/dist_package_provides.json

**Comment by nikita-kov-dev** [comment] 2024-08-02 17:04
@OrKoN sure. Here is the console output from one of the crashes:

DevTools listening on ws://127.0.0.1:42449/devtools/browser/8894d5e9-90af-4b4c-b428-f7e7f65de8eb
[1302855:1:0802/200315.589666:ERROR:v8_initializer.cc(815)] V8 process OOM (Failed to reserve virtual memory for CodeRange).
[1302856:1:0802/200315.591892:ERROR:v8_initializer.cc(815)] V8 process OOM (Failed to reserve virtual memory for CodeRange).

**Comment by OrKoN** [comment] 2024-08-02 17:25
This is out of memory crash: is there sufficient free operating memory on the system? any chance that there are memory leaks in the tests or the extension?

**Comment by nikita-kov-dev** [comment] 2024-08-02 17:35
@OrKoN Yes, I have 32GB of RAM; 16 are in use. I have increased WebStorm's memory to 8GB (it was 4GB before) and restarted it, but it didn't resolve the issue. I use Vue3 for a relatively simple extension, but I will try to reproduce the problem with the most straightforward extension possible.

**Comment by nikita-kov-dev** [comment] 2024-08-04 17:32
@OrKoN, Here is the link to the repo with a clean example: https://github.com/nikita-kov-dev/puppeteer-chrome-crash-reproduction. I added an empty extension (it contains only a manifest file and index.html) and the same e2e test configuration as for my project. When I run tests (Test.spec.ts file) from the WebStorm, Chrome crashes:

![image](https://github.com/user-attachments/assets/5ce7781b-1793-427e-ae74-03bf8478f43c)

**Comment by nikita-kov-dev** [comment] 2024-08-04 17:42
Also, it might be helpful in the investigation:

![image](https://github.com/user-attachments/assets/a289edbf-14f7-4d9c-9cf4-62e5048d291e)

**Comment by OrKoN** [comment] 2024-08-04 17:50
@nikita-kov-dev it looks like you launch a browser before each test but never close them, that could lead to an OOM error as each browser instance consumes . You need to close the browser as soon as you do not need it or re-use the same instance between tests. Note that the repo does not trigger an OOM on my machine. Although note that I do not run through WebStrom and not sure if it would affect the memory constrains in any way:

<img width="1410" alt="Screenshot 2024-08-04 at 19 48 59" src="https://github.com/user-attachments/assets/dcc72c6f-80dd-465c-a1cd-b34057e70de9">

Also, depending on how you terminate the script (or how jest does it), if you do not close the browser gracefully by calling `await browser.close()` it might keep running on your system consuming memory, so subsequent runs over time would be more likely to fail.

**Comment by nikita-kov-dev** [comment] 2024-08-04 20:04
@OrKoN, I'm sorry. I forgot `await browser.close()` (it was in the original code). I've added it. However, it doesn't fix crashes. I also tried without WebStorm, and the results were the same.

**Comment by OrKoN** [comment] 2024-08-04 20:35
Even without closing the browser, the issue didn’t reproduce for me. The log also mentions too many open files? Perhaps it hits the limit on open files on your system. Have you tried running the test repo after a system restart? (Just to make sure previous runs didn’t leak any processes).

**Comment by nikita-kov-dev** [comment] 2024-08-04 20:40
@OrKoN I've just restarted my machine and reproduced the issue.

**Comment by nikita-kov-dev** [comment] 2024-08-05 19:07
> So you have tried increasing the [open file limit](https://askubuntu.com/questions/1182021/too-many-open-files) via ulimit?

I tried it, but it didn't resolve the issue.

**Comment by nikita-kov-dev** [comment] 2024-08-05 19:14
Before using your solution with the `protocolTimeout` parameter, I tried installing Chromium via `sudo dnf install chromium` and using it with the `executablePath: '/usr/lib64/chromium-browser/chromium-browser'` parameter. I believe dnf installs all required dependencies. It didn't resolve the issue, so I agree with you it's unlikely the system dependencies problem.

**Comment by OrKoN** [comment] 2024-08-06 07:00
After I pulled the repo, I get errors:

```
  ● Test › Test 9

    TypeError: Cannot read properties of undefined (reading 'close')

      22 |   afterEach(async () => {
      23 |     page = undefined
    > 24 |     await browser.close()
         |                   ^
      25 |   }, 15000)
      26 |
      27 |   test('Test 0', async () => {

      at Object.close (__tests__/Test.spec.ts:24:19)
```

it looks like jest might be running tests in parallel? have you tried jest --runInBand?

**Comment by OrKoN** [comment] 2024-08-06 07:18
It looks like it was caused by node_modules being copied to the docker image, in that case, npm install would not re-install Puppeteer and would not download the browser. I have fixed this and unfortunately, I still cannot reproduce the issue:

<img width="1788" alt="Screenshot 2024-08-06 at 09 18 02" src="https://github.com/user-attachments/assets/e9ec50c1-85a0-4701-921a-975d71b681e2">

P.S. you can ignore dbus errors, they are actually not errors, although the log states otherwise.

**Comment by nikita-kov-dev** [comment] 2024-08-08 17:37
> After I pulled the repo, I get errors:
> 
> ```
>   ● Test › Test 9
> 
>     TypeError: Cannot read properties of undefined (reading 'close')
> 
>       22 |   afterEach(async () => {
>       23 |     page = undefined
>     > 24 |     await browser.close()
>          |                   ^
>       25 |   }, 15000)
>       26 |
>       27 |   test('Test 0', async () => {
> 
>       at Object.close (__tests__/Test.spec.ts:24:19)
> ```
> 
> it looks like jest might be running tests in parallel? have you tried jest --runInBand?

Yes, the same result: 
![Screenshot from 2024-08-07 13-34-08](https://github.com/user-attachments/assets/84b8b97b-bbfc-4842-b736-513749872389)

**Comment by nikita-kov-dev** [comment] 2024-08-08 17:39
> After I pulled the repo, I get errors:
> 
> ```
>   ● Test › Test 9
> 
>     TypeError: Cannot read properties of undefined (reading 'close')
> 
>       22 |   afterEach(async () => {
>       23 |     page = undefined
>     > 24 |     await browser.close()
>          |                   ^
>       25 |   }, 15000)
>       26 |
>       27 |   test('Test 0', async () => {
> 
>       at Object.close (__tests__/Test.spec.ts:24:19)
> ```
> 
> it looks like jest might be running tests in parallel? have you tried jest --runInBand?

Yes, with the same result:
![image](https://github.com/user-attachments/assets/5ea90fb3-ed53-4d2f-8f29-df66c7d90381)

**Comment by nikita-kov-dev** [comment] 2024-08-08 17:49
It looks like Chrom(e|ium) doesn't work correctly on Fedora. So, I believe this issue can be closed since it's not a Puppeteer framework problem. Thank you again for the hint (protocolTimeout parameter); I can now handle these crashes properly.

**Comment by OrKoN** [comment] 2024-08-08 20:00
Fedora is supported by Chrome: https://support.google.com/chrome/a/answer/7100626?hl=en#:~:text=10.15%20or%20later-,Linux,-To%20use%20Chrome

So actually I finally got a chance to install a virtual machine with a fresh Fedora 40 and I am not able to reproduce the issue (I gave the machine 8GB of RAM):

<img width="1678" alt="Screenshot 2024-08-08 at 21 56 19" src="https://github.com/user-attachments/assets/0ccc0cf9-ecd5-441d-8559-54c95cc8ddf4">

I believe the issue you experience is related to the specific installation/hardware/configuration you have and I am not sure we will be able to address it. From the error message, it does look like your machine is low on memory or there is some other reason why a memory cannot be allocated.

**Closed as not planned by OrKoN** 2024-08-08 20:00 UTC
Labels: needs-feedback, not-reproducible

**Comment by EmanueleMicciullaAtCripsy** [comment] 2024-10-26 16:25
I had a similar problem until i notice on puppeteer troubleshooting page this: 
> CAUTION - The current Chromium version in Alpine 3.20 is causing timeout issues with Puppeteer. Downgrading to Alpine 3.19 fixes the issue. See [#11640](https://github.com/puppeteer/puppeteer/issues/11640), [#12637](https://github.com/puppeteer/puppeteer/issues/12637), [#12189](https://github.com/puppeteer/puppeteer/issues/12189)

[https://pptr.dev/troubleshooting#running-on-alpine](https://pptr.dev/troubleshooting#running-on-alpine)

In my case i solved downgrading the alpine version of my app dockerfile, but the problem seems to affect newer versions of chromium and chrome browsers. 

I suggest you to **force puppeteer to use a slightly older version of the browser**. For chrome here [https://github.com/puppeteer/puppeteer/issues/12189](https://github.com/puppeteer/puppeteer/issues/12189) they point out that versions older than 123.0.6312.86 should work fine. (I have no idea which version of chromium would solve)
