### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gsteavenbh** [puppeteer/puppeteer#12924] opened 2024-08-09 05:35 UTC
### Steps to reproduce

I am using puppeteer 22.13.1, we have hyperlinks (used for redirecting to specific page in pdf) in our html. After converting the html to pdf report the we are facing two issues.

1. The hyperlinks redirection is working correctly when opening the report in any pdf reader, but when opening it in any browser the hyperlinks are not redirecting correctly.
2. We have more than 50 table of content for which we have creating hyperlinks but for some reason only first 42 links are working in pdf reader. Not sure if it is any kind of limitation.

### Expected results

The hyperlinks should redirect to correct page.

### Actual results

The hyperlinks are not redirecting correctly.

**Comment by OrKoN** [comment] 2024-08-09 06:08
Sounds like a duplicate of https://github.com/puppeteer/puppeteer/issues/12601

**Closed as not planned by OrKoN** 2024-08-09 06:08 UTC
Labels: @puppeteer/browsers
