### ISSUE TITLE
How to select iframe with a selector?

### ISSUE THREAD

**Issue by sean-hill** [puppeteer/puppeteer#650] opened 2017-09-01 16:50 UTC
Hey there, is there a way to use the `.childFrames()` function to lookup an iFrame with a CSS selector? For instance:

```html
<iframe class="super" src="http://iframe.com" />
```

I'd like to use `iframe.super` as my selector to switch frames with. Thanks!

**Comment by twalpole** [comment] 2017-09-01 17:11
Duplicate of #433

**Comment by aslushnikov** [comment] 2017-09-01 17:43
Thanks @twalpole

**Closed as completed by aslushnikov** 2017-09-01 17:43 UTC
