### ISSUE TITLE
Page loading interrupted due to hanging intercepted request

### ISSUE THREAD

**Issue by FdezRomero** [puppeteer/puppeteer#539] opened 2017-08-25 09:09 UTC
Hi!

I'm trying to load an Angular page that requests data via XHR, but the loading is always interrupted due to a hanging `OPTIONS` request. This only happens when request interception is enabled, even though the handler always continues the requests, e.g. `page.on('request', request => request.continue())`.

You can see the example URL below (not mine): http://www.mybkr.com/shop/#/productdetail/303/SPIKED_JET_500_ML

```js
const page = await browser.newPage();

page.on('request', request => {
  console.log(`Intercepting: ${request.method} ${request.url}`);
  request.continue();
});

page.on('response', response => console.log(`Response: ${response.method} ${response.url}`));

await page.setRequestInterceptionEnabled(true);
await page.goto('http://www.mybkr.com/shop/#/productdetail/303/SPIKED_JET_500_ML', { waitUntil: 'networkidle' });
await page.close();
```

And this is the console output for the hanging request. No more requests are performed/intercepted afterwards:

```text
Intercepting: OPTIONS https://www.mybkr.com/mybkr-ws/services/generic/getAllObjectByQueryId?queryId=get_google_tracking_listing
puppeteer:request request.continue()
puppeteer:session SEND ► {"id":37,"method":"Network.continueInterceptedRequest","params":{"interceptionId":"id-25"}}
puppeteer:protocol SEND ► {"id":39,"method":"Target.sendMessageToTarget","params":{"sessionId":"81d4caf4-0446-4f7a-b121-2d3b7b334763:1","message":"{\"id\":37,\"method\":\"Network.continueInterceptedRequest\",\"params\":{\"interceptionId\":\"id-25\"}}"}}
puppeteer:protocol ◀ RECV {"id":39,"result":{}}
puppeteer:protocol ◀ RECV {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"81d4caf4-0446-4f7a-b121-2d3b7b334763:1","message":"{\"id\":37,\"result\":{}}","targetId":"81d4caf4-0446-4f7a-b121-2d3b7b334763"}}
puppeteer:session ◀ RECV {"id":37,"result":{}}
puppeteer:protocol ◀ RECV {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"81d4caf4-0446-4f7a-b121-2d3b7b334763:1","message":"{\"method\":\"Network.requestIntercepted\",\"params\":{\"interceptionId\":\"id-26\",\"request\":{\"url\":\"https://www.mybkr.com/mybkr-ws/services/generic/getAllObjectByQueryId?queryId=get_google_tracking_listing\",\"method\":\"GET\",\"headers\":{\"Accept\":\"application/json, text/javascript, */*; q=0.01\",\"Origin\":\"http://www.mybkr.com\",\"X-DevTools-Emulate-Network-Conditions-Client-Id\":\"81d4caf4-0446-4f7a-b121-2d3b7b334763\",\"User-Agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3193.0 Safari/537.36\",\"Content-Type\":\"application/json; charset=utf-8\"},\"initialPriority\":\"VeryHigh\",\"referrerPolicy\":\"no-referrer-when-downgrade\"},\"resourceType\":\"XHR\",\"isNavigationRequest\":false}}","targetId":"81d4caf4-0446-4f7a-b121-2d3b7b334763"}}
puppeteer:session ◀ RECV {"method":"Network.requestIntercepted","params":{"interceptionId":"id-26","request":{"url":"https://www.mybkr.com/mybkr-ws/services/generic/getAllObjectByQueryId?queryId=get_google_tracking_listing","method":"GET","headers":{"Accept":"application/json, text/javascript, */*; q=0.01","Origin":"http://www.mybkr.com","X-DevTools-Emulate-Network-Conditions-Client-Id":"81d4caf4-0446-4f7a-b121-2d3b7b334763","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3193.0 Safari/537.36","Content-Type":"application/json; charset=utf-8"},"initialPriority":"VeryHigh","referrerPolicy":"no-referrer-when-downgrade"},"resourceType":"XHR","isNavigationRequest":false}}
Error: Navigation Timeout Exceeded: 30000ms exceeded
    at NavigatorWatcher.waitForNavigation (/Users/rodrigo/Git/Headless/node_modules/puppeteer/lib/NavigatorWatcher.js:74:13)
    at <anonymous>
```

Thanks!

**Comment by aslushnikov** [comment] 2017-08-27 17:47
Dupe of #558

**Closed as completed by aslushnikov** 2017-08-27 17:47 UTC
