### ISSUE TITLE
Neither Page.setViewport() nor paper format can change window width when save as PDF

### ISSUE THREAD

**Issue by winterli** [puppeteer/puppeteer#2333] opened 2018-04-09 07:45 UTC
The doc says
>Puppeteer sets an initial page size to 800px x 600px, which defines the screenshot size. The page size can be customized with Page.setViewport().

But when save as PDF, the window width is always 800px, regardless what been set through `Page.setViewport()`. Even by changing the paper format, window width is always 800px.

### Steps to reproduce

**environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: Mac OS X EI Capitan
* URLs (if applicable): n/a
* Node.js version: v8.9.4

**reproduce steps**

1. Install Puppeteer through NPM
2. Create app.js and paste below code
```
const puppeteer = require('puppeteer');

(async () => {
  const viewPort={width:1280, height:960};	
  const paperFormat="A4";
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const html="<script>document.write('Timestamp:'+new Date()+'<br/>Window Width: '+window.innerWidth);</script>";
  await page.setContent(html);
  await page.setViewport(viewPort);
  await page.pdf({path: 'test.pdf', format: paperFormat, landscape:false, scale:1});
  await browser.close();
  console.log("test.pdf is generated!");
})();
```
3. Run `node app.js`

**What is the expected result?**
Since the viewport is set to {width:1280, height:960}, the window width should be 1280px in the generated PDF.

**What happens instead?**
Instead, it always show 800px

I also tried to call `await page.emulateMedia('screen');` just before `page.pdf()`, but the result is same. Did I misunderstand something here?

**Comment by yrshaikh** [comment] 2018-04-10 03:01
I added the below snippet to your code and everytime I updated the width or height, the log had updated value.

```
let result = await page.evaluate(
        () => {
            return window.innerWidth;
        }
    );

console.log(`Detected window.innerWidth to be ${result}.`);
```

And here is a related issue - https://github.com/GoogleChrome/puppeteer/issues/1183

**Comment by aslushnikov** [comment] 2018-04-10 04:13
Looks like a dupe of #1183, thanks.

**Closed as completed by aslushnikov** 2018-04-10 04:13 UTC

**Comment by winterli** [comment] 2018-04-10 05:04
Thanks @yrshaikh . The code you provided is executed before saving as PDF. So it's not the same value as when generating PDF. If not saving as PDF, but as JPG instead, everything works fine. 
Sorry, I haven't found #1183 before. Thanks for linking them together!

@aslushnikov , I will refer to the existing ticket. Thanks!
