### ISSUE TITLE
Using a proxy per page with Puppeteer

### ISSUE THREAD

**Issue by Nicolas-vrcc** [puppeteer/puppeteer#1948] opened 2018-02-01 22:54 UTC
Hello,

I need to use multiple proxy and change let's say every 1000 page.goto() requests.
Is there a way to do this with puppeteer/chromium ?

Thank you !

**Comment by tomgallagher** [comment] 2018-02-02 12:13
#1861

**Comment by Nicolas-vrcc** [comment] 2018-02-02 12:18
@tomgallagher Yeah but there's no answer

**Comment by tomgallagher** [comment] 2018-02-02 12:44
Not to changing them on the fly, but if you only want to do it every 1000 requests, just count and then `browser.close() `and relaunch the browser with new proxy, as per [this](https://www.chromium.org/developers/design-documents/network-stack/socks-proxy).

So try:

`puppeteer.launch({ args: ['--proxy-server="socks5://myproxy:8080'] });`

or some variant. I agree the docs for this are non-existent.

**Comment by Nicolas-vrcc** [comment] 2018-02-02 13:24
@tomgallagher Thank you so much you saved my day

**Comment by Nicolas-vrcc** [comment] 2018-02-02 13:38
Ok I tried this : 
`await puppeteer.launch({ headless: false, args: ['--proxy-server="socks4://80.211.240.206:1080'] })`
and ended up getting this error : 
`ResidentAdvisor.js
(node:79282) UnhandledPromiseRejectionWarning: Error: net::ERR_NO_SUPPORTED_PROXIES
    at navigate (/Users/nicolas/Desktop/CODE/Puppetteer_scraper/node_modules/puppeteer/lib/Page.js:526:37)`

**Comment by Nicolas-vrcc** [comment] 2018-02-02 13:43
@tomgallagher  Thanks bro

**Comment by tomgallagher** [comment] 2018-02-02 13:45
No problem. You might as well tell everyone what worked if you have a moment. There's a more detailed discussion of proxies at #678.

**Comment by ebidel** [comment] 2018-02-02 19:05
Dupe of https://github.com/GoogleChrome/puppeteer/issues/678

**Closed as completed by ebidel** 2018-02-02 19:05 UTC

**Comment by pariola** [comment] 2018-07-04 00:45
@tomgallagher Thanks for the answer but seems to only work without the quotes `"`

**Comment by coolicer** [comment] 2018-09-21 02:01
I also need it.

**Comment by yi-ge** [comment] 2018-12-22 14:34
I need it, too.

**Comment by thangtv611** [comment] 2019-03-28 10:53
Thanks, I need too.

**Comment by remyzane** [comment] 2019-04-21 15:17
I also need it.

**Comment by xiyuan-fengyu** [comment] 2019-06-02 15:10
try this [PuppeteerUtil.useProxy](https://github.com/xiyuan-fengyu/ppspider/blob/master/src/test/component/ProxyTest.ts)

**Comment by yi-ge** [comment] 2019-06-02 15:26
@xiyuan-fengyu use `http-proxy-agent` to tackle `Puppeteer proxy`, this is a good idea! thank you.

**Comment by xiyuan-fengyu** [comment] 2019-06-02 15:45
> @xiyuan-fengyu use `http-proxy-agent` to tackle `Puppeteer proxy`, this is a good idea! thank you.

you are welcome

**Comment by gajus** [comment] 2020-01-29 18:18
You can use https://github.com/gajus/puppeteer-proxy to set proxy either for entire page or for specific requests only, e.g.

```js
import puppeteer from 'puppeteer';
import {
  createPageProxy,
} from 'puppeteer-proxy';

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  const pageProxy = createPageProxy({
    page,
    proxyUrl: 'http://127.0.0.1:3000',
  });

  await page.setRequestInterception(true);

  page.once('request', async (request) => {
    await pageProxy.proxyRequest(request);
  });

  await page.goto('https://example.com');
})();

```

To skip proxy simply call `request.continue()` conditionally.

Using [puppeteer-proxy](https://github.com/gajus/puppeteer-proxy) `Page` can have multiple proxies.

**Comment by princePeterHansen** [comment] 2020-02-05 21:18
Hi Nicolas,

I have also been looking for a proxy solution when using Puppeteer. One of the easiest solutions I found is using API proxy services.

The basic example will look like this:

```javascript
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  const url = 'https://proxybot.io/api/......?url=https://example.com';

  await page.goto(url);
})();
```

Every page will be opened through random proxy 😉

**Comment by Cuadrix** [comment] 2020-02-09 02:25
It's possible with [**puppeteer-page-proxy**](https://github.com/Cuadrix/puppeteer-page-proxy).
It supports setting a proxy for an entire page, or if you like, it can set a different proxy for each request.

First install it:
```
npm i puppeteer-page-proxy
```
Then require it:
```js
const useProxy = require('puppeteer-page-proxy');
```
**Using it is easy;**
Set proxy for an entire page:
```js
await useProxy(page, 'http://127.0.0.1:8000');
```

If you want a different proxy for each request,then you can simply do this:
```js
await page.setRequestInterception(true);
page.on('request', req => {
    useProxy(req, 'socks5://127.0.0.1:9000');
});
```
Then if you want to be sure that your page's IP has changed, you can look it up;
```js
const data = await useProxy.lookup(page);
console.log(data.ip);
```
It supports **http**, **https**, **socks4** and **socks5** proxies, and it also supports authentication if that is needed:
```js
const proxy = 'http://login:pass@127.0.0.1:8000'
```

Repository:
https://github.com/Cuadrix/puppeteer-page-proxy

**Comment by iLinked1337** [comment] 2020-03-19 10:12
using @Cuadrix's solution, i cannot reach the web page for some reason.

**Comment by huanshiwushuang** [comment] 2020-09-16 04:01
> You can use https://github.com/gajus/puppeteer-proxy to set proxy either for entire page or for specific requests only, e.g.
> 
> ```js
> import puppeteer from 'puppeteer';
> import {
>   createPageProxy,
> } from 'puppeteer-proxy';
> 
> (async () => {
>   const browser = await puppeteer.launch();
>   const page = await browser.newPage();
> 
>   const pageProxy = createPageProxy({
>     page,
>     proxyUrl: 'http://127.0.0.1:3000',
>   });
> 
>   await page.setRequestInterception(true);
> 
>   page.once('request', async (request) => {
>     await pageProxy.proxyRequest(request);
>   });
> 
>   await page.goto('https://example.com');
> })();
> ```
> 
> To skip proxy simply call `request.continue()` conditionally.
> 
> Using [puppeteer-proxy](https://github.com/gajus/puppeteer-proxy) `Page` can have multiple proxies.

——————————————————————————————————————————————
But this library cannot capture the first document request of the page opened by page.click
Perhaps it is because Fetch.requestPaused does not support capture?

**Comment by AneeshQuonain** [comment] 2022-05-14 18:55
@Cuadrix when I try to request a https site it gives me invalid browser request.
if I use proxy on https://example.com, the response will be invalid browser request and for http url its working fine. Can you please give me any solution for this
