### ISSUE TITLE
[Bug]: Puppeteer on GAE Flex (which uses npm ci) fails to install or find chromium

### ISSUE THREAD

**Issue by otrajman** [puppeteer/puppeteer#9190] opened 2022-10-30 03:46 UTC
### Bug description

Install 19.0.0 or later puppeteer (18.2.1 works) in a Google App Engine Flex project.
Launch the browser per example code in main.  Expect this error:

Error: Run `npm install` to download the correct Chromium revision (1056772)

Note everything works fine locally on Ubuntu 22.04.1

### Puppeteer version

19.x.x

### Node.js version

16.7.1

### npm version

8.19.2

### What operating system are you seeing the problem on?

Linux

### Configuration file

```JavaScript
No configuration file used
```

### Relevant log output

```Shell
Error: Run `npm install` to download the correct Chromium revision (1056772)
 at ChromeLauncher.resolveExecutablePath (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:120:27)
 at ChromeLauncher.executablePath (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:166:25)
 at ChromeLauncher.launch (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:70:37)
```

**Comment by kfitzgerald** [comment] 2022-11-01 19:00
Deployed this to a linux environment and also encountered this

**Comment by jrandolf** [comment] 2022-11-02 00:47
Duplicate of #9162

**Closed as not planned by jrandolf** 2022-11-02 00:47 UTC
