### ISSUE TITLE
How to define before tag for only one scenario/feature from more ones

### ISSUE THREAD

**Issue by martin-fabian** [puppeteer/puppeteer#4664] opened 2019-07-04 06:06 UTC
I need to run one before tag for specific scenario. How to do that?

So I have one scenario where I need to set up some request like user no.1. I have my one token getting from system based on provided username and password. This is all set up in before tag in hook file - code no.1

Then I need to run another before tag in hook file to get token as user no.2 different user and finish this task. code no.2

I am not able to differentiate it or my system still gets new token like to be always user no.1

code no.1 - it runs each time

```
Before(async () => {
  const page = World.page;
  const token = retrieveToken();
  console.log('Using environment url: ' + EnvironmentVariables.URL);
  await page.goto(EnvironmentVariables.URL + `/?access_token=${token}&expires_in=3600&token_type=bearer`);
  await page.waitForSelector(SelectorUtils.nameSelector(NavigationComponent.searchClientInputName));
  await waitForSpinnerToEnd();
});
```
code no.2 - here I am trying to use annotation with name of scenario but with no effect. I get token but when I look at console I see login details from code no.1

```
Before({tags: '@SubmitSRForReviewFinish'}, async () => {
  const page = World.page;
  const token = retrieveTokenLogin();
  console.log('Using environment url: ' + EnvironmentVariables.URL);
  await page.goto(EnvironmentVariables.URL + `/?access_token=${token}&expires_in=3600&token_type=bearer`);
  await page.waitForSelector(SelectorUtils.nameSelector(NavigationComponent.searchClientInputName));
  await waitForSpinnerToEnd();
});
```
I need to be able to run before tag only for specific scenario. How to do that? How to log with another scenarion as another user?

**Comment by aslushnikov** [comment] 2019-07-15 03:02
Seems to be a dupe of #4642

**Closed as completed by aslushnikov** 2019-07-15 03:02 UTC
