### ISSUE TITLE
[Bug]: PDF page numbers no longer working in headless: shell

### ISSUE THREAD

**Issue by dannybeckett** [puppeteer/puppeteer#12361] opened 2024-04-28 21:08 UTC
> Ever since updating to version `22.2.0`, the page number no longer appears. Is anyone else experiencing this issue on a Debian server? It seems to be working fine on a Mac.

_Originally posted by @outbackStack in https://github.com/puppeteer/puppeteer/issues/5345#issuecomment-1963292064_

**Comment by dannybeckett** [comment] 2024-04-28 21:13
Created an issue from this comment. I am also experiencing lack of page numbers when using `headless: 'shell'`. I also tried adding `--lang=en-US` to the `args` of `const browser = await puppeteer.launch()`

**Comment by outbackStack** [comment] 2024-04-29 03:46
This issue is currently open at #12196

**Comment by OrKoN** [comment] 2024-04-29 05:58
Duplicate of https://github.com/puppeteer/puppeteer/issues/12196

**Closed as not planned by OrKoN** 2024-04-29 05:58 UTC
