### ISSUE TITLE
Promise.resolve is not a function, waitForSelector does not work for Frame after .click()

### ISSUE THREAD

**Issue by lau-a** [puppeteer/puppeteer#1343] opened 2017-11-10 00:03 UTC
Running puppeteer@0.13.0-alpha

Here's the error I'm receiving:
```
Trace: Error: Evaluation failed: TypeError: Promise.resolve is not a function
    at pollMutation (<anonymous>:18:22)
    at waitForPredicatePageFunction (<anonymous>:8:11)
    at <anonymous>:70:3
    at ExecutionContext.evaluateHandle (/Users/a.lau/Projects/chrome-headless/node_modules/puppeteer/lib/ExecutionContext.js:54:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Object.module.exports.test (/Users/a.lau/Projects/chrome-headless/test.js:316:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
Here's the code I'm using
```
    try {
        await page.goto(url)
        var frame = await page.frames()[0];
        // iframe isn't present from the beginning (for whatever reason)
        await page.waitFor("iframe")
        var child = frame.childFrames()[0]
        // wait for the image cut block to be visible
        await child.waitFor("section[data-type=imagecut]", {timeout: 60000})
        // open the image cut
        let section = await child.$("section[data-type=imagecut] h1")
        await section.click()
        let elements = await child.$$("section[data-type=imagecut] fieldset div a")

        for (let element of elements)
        {
            await element.click()
            console.log('click');
            await child.waitFor("table.boxy-wrapper")
            console.log('wait for table');
            let file_upload = await child.$("input[name=file_upload]")
            await file_upload.uploadFile(file)
            console.log('uploaded');
            await child.waitFor("table.boxy-wrapper", { hidden: true })
            console.log('waited');
        }
    } catch (e) {
        console.trace(e);
    } 
```
The error occurs after 'click' is logged so I'm guessing it's caused by `await child.waitFor("table.boxy-wrapper")`. But `waitFor` returns a promise? 

Can confirm that it's creating this error after the click occurs and then waiting for the table.

**Comment by JoelEinbinder** [comment] 2017-11-10 06:27
That is a really strange error. `Promise.resolve()` definitely should be a function! Are you using a third party promise library? Do you have a global variable called `Promise`?

The code that throws an error is running inside Chrome, so I suspect something modified the `Promise` object in the page you are testing.

**Comment by joelgriffith** [comment] 2017-11-10 17:45
> The code that throws an error is running inside Chrome, so I suspect something modified the Promise object in the page you are testing.

This is incredibly interesting. I wonder if we should sandbox the browser's runtime better so we don't run into globals being overwritten or mutated. Since this code is being ran/injected into pages we don't own we should probably do a better job safeguarding globals or making sure that they are what they think they are.

**Comment by vsemozhetbyt** [comment] 2017-11-10 18:25
A bit like https://github.com/GoogleChrome/puppeteer/issues/1003

**Comment by lau-a** [comment] 2017-11-12 22:04
It could be because of some third party library, I'll have to ask the developers.

**Comment by aslushnikov** [comment] 2018-01-12 11:42
> This is incredibly interesting. I wonder if we should sandbox the browser's runtime better so we don't run into globals being overwritten or mutated

@joelgriffith This is definitely feasible, but will add quite a bit of complexity and will require a good justification. So far it's not that common issue.

Overall, closing as a dupe of #609.

**Closed as completed by aslushnikov** 2018-01-12 11:42 UTC
