### ISSUE TITLE
net::ERR_TOO_MANY_REDIRECTS if I want to open website in puppeteer

### ISSUE THREAD

**Issue by AndrejGajdos** [puppeteer/puppeteer#4919] opened 2019-09-09 12:32 UTC
* Puppeteer version: 1.19.0
* Platform / OS version: macOS Mojave 10.14.6
* URLs (if applicable): https://www.washingtonpost.com/news/acts-of-faith/wp/2017/06/30/trump-promised-to-destroy-the-johnson-amendment-congress-is-targeting-it-now/
* Node.js version: v12.1.0

*app.js*

```js
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  await page.goto('https://www.washingtonpost.com/news/acts-of-faith/wp/2017/06/30/trump-promised-to-destroy-the-johnson-amendment-congress-is-targeting-it-now/');

  const html = await page.content()
  console.log(html)
  await browser.close()
})()
```

**What is the expected result?**

html structure of website

**What happens instead?**

When I try to open a washington post article in puppeteer, I get error:

*Error: net::ERR_TOO_MANY_REDIRECTS*

```
internal/process/warning.js:27 (node:70458) UnhandledPromiseRejectionWarning: Error: net::ERR_TOO_MANY_REDIRECTS at https://www.washingtonpost.com/news/acts-of-faith/wp/2017/06/30/trump-promised-to-destroy-the-johnson-amendment-congress-is-targeting-it-now/
    at navigate (.../node_modules/puppeteer/lib/FrameManager.js:121:37)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
  -- ASYNC --
    at Frame.<anonymous> (.../node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (.../node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (.../node_modules/puppeteer/lib/helper.js:112:23)
    at .../app.js:255:14
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

I tried to abort navigation redirects based on [this](https://github.com/GoogleChrome/puppeteer/issues/1132#issuecomment-393724933), but then I get *Error: net::ERR_FAILED*

```
internal/process/warning.js:27 (node:70488) UnhandledPromiseRejectionWarning: Error: net::ERR_FAILED at https://www.washingtonpost.com/news/acts-of-faith/wp/2017/06/30/trump-promised-to-destroy-the-johnson-amendment-congress-is-targeting-it-now/
    at navigate (.../node_modules/puppeteer/lib/FrameManager.js:121:37)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
  -- ASYNC --
    at Frame.<anonymous> (.../node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (.../node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (.../node_modules/puppeteer/lib/helper.js:112:23)
    at .../app.js:247:14
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by entrptaher** [comment] 2019-09-11 07:38
I don't get any error with your code. Can you try with proxy/vpn? 

![image](https://user-images.githubusercontent.com/8284972/64677424-5a34b800-d499-11e9-8226-70634272fe69.png)

**Comment by mathiasbynens** [comment] 2019-09-11 07:40
This doesn't seem to be a bug in Puppeteer, but rather with the website which redirect-loops in certain scenarios.

**Comment by AndrejGajdos** [comment] 2019-09-11 10:14
@entrptaher I tried VPN and US endpoint and it really works.

@mathiasbynens Yes, website does too many redirects for requests from different location. 

I am wondering, why I get this error in Puppeteer but not in desktop browser?

**Comment by entrptaher** [comment] 2019-09-11 10:49
It's probably checking some fingerprint or anti bot measurements. You can try https://www.npmjs.com/package/puppeteer-extra-plugin-stealth to see if you have any success. Also, you can try with proxies.

**Comment by mathiasbynens** [comment] 2019-09-11 10:56
Closing this as it's not a bug in Puppeteer. Thanks, everyone!

**Closed as completed by mathiasbynens** 2019-09-11 10:56 UTC

**Comment by jiao1187875445** [comment] 2025-02-14 06:25
@mathiasbynens @entrptaher I encountered the same problem, but strangely, the version 19 I used before was good, but when I upgraded to 24.2, this problem occurred. I tried version 23.11.1 again and it was also good. If it's not related to puppeteer, the effect after switching versions should be consistent.

**Comment by chenxicore** [comment] 2025-05-27 07:30
I also encountered this problem. It seems to be a bug introduced in 24.1.0. This error will occur when there is a 302/307 redirect when the website is visited for the first time.

![Image](https://github.com/user-attachments/assets/689e82ac-5f63-4a9c-a1de-a13ce52a96aa)

![Image](https://github.com/user-attachments/assets/17e458f4-2919-4da7-b140-59b46a0c5566)
