### ISSUE TITLE
[Bug]: Can't dismiss xdg-open or open with dialog with puppeteer

### ISSUE THREAD

**Issue by leo-brn** [puppeteer/puppeteer#13038] opened 2024-09-03 09:53 UTC
### Minimal, reproducible example

```TypeScript
await page.goto("protocol:*", { timeout: 120000 });
```

### Expectation

I was expecting to close this dialog like other one

### Reality

We can't prevent this dialog to append or dismiss it

### Puppeteer version

22.12.0

### Node version

18.11.18

### Package manager

npm

### Package manager version

3.0.0

### Operating system

macOS

**Comment by OrKoN** [comment] 2024-09-03 19:22
Not able to reproduce. Please provide a complete example for your issue. xdg-open sounds like it is out of scope for Puppeteer.

**Closed as not planned by OrKoN** 2024-09-03 19:22 UTC
Labels: needs-feedback, not-reproducible
