### ISSUE TITLE
Puppeteer hangs for some websites (Navigation Timeout Exceeded: 30000 ms exceeded.)

### ISSUE THREAD

**Issue by WhatIsACore** [puppeteer/puppeteer#5950] opened 2020-06-01 07:12 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ^3.2.0 (latest on npm)
* Platform / OS version: macOS Catalina 10.15.4
* Node.js version: 12.17.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Run the following code:

```
const puppeteer = require('puppeteer');
var url = 'https://www.gamestop.com/';

(async () => {
  const browser = await puppeteer.launch({headless: true});
  console.log('launched browser');
  const page = await browser.newPage();
  await page.setViewport({width: 1920, height: 926});
  await page.goto(url);
  console.log('navigated to ' + url);
  
  await browser.close();
})();
```

2. output: 
```
> node index.js
launched browser
(node:10275) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded

```

**What is the expected result?**
puppeteer returns 'navigated to http://www.gamestop.com/' then exits.

**What happens instead?**
puppeteer hangs and times out. This also happens with bestbuy.com and several other websites. It looks like someone opened this issue in 2018 (https://github.com/puppeteer/puppeteer/issues/2381) but he was ignored.

**Comment by nicolas-chamand** [comment] 2022-06-26 13:46
Hello,

I have the same problem using puppeteer 15.1.1 and Firefox on https://www.neko-sama.fr. The same link sometimes works, sometimes it doesn't (and then I'm browsing to the URL on my own with Safari to find out it has never been down).

**Comment by OrKoN** [comment] 2022-09-05 12:32
I am unable to reproduce anymore. I believe that was fixed by other issues: please give it a try in the latest version.

**Closed as not planned by OrKoN** 2022-09-05 12:32 UTC
Labels: unconfirmed
