### ISSUE TITLE
Response header value not separated displayed

### ISSUE THREAD

**Issue by ShawnPanxiaoming** [puppeteer/puppeteer#2534] opened 2018-05-11 06:49 UTC
**Tell us about your environment:**

* Puppeteer version: 1.4
* Platform / OS version: centos 7
* URLs (if applicable): https://www.jd.ru
* Node.js version: 8.11

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.page.on('response',response =>{console.log(response.headers())});
2. focus on the resource "https://static.criteo.net/js/ld/ld.js"
3. see the Cache-Control key

**What is the expected result?**
I think puppeteer should print this key like "cache-control":"max-age=86400;public" or "cache-control":"max-age=86400","cache-control":"public"

**What happens instead?**
Actually it displayed "cache-control":"max-age=86400public"
I don't think this is a friendly display because it becomes hard for developer to parse max-age value with number and text not separated.

**Comment by aslushnikov** [comment] 2018-05-17 01:26
@ShawnPanxiaoming yeah, that's the way DevTools Protocol handles header folding. In fact, there's a `\n` right before `public`. What it means is that there are two `cache-control` headers with different values: `max-age=86400` and `public`.

The right way to fix this would be to introduce `response.headerPairs()` or, alternatively, to have `page.headers()['cache-control']` to return an array in this case.

Reproduction script for the record:
```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on('response', r => console.log(r.headers()));
  await page.goto('https://static.criteo.net/js/ld/ld.js');
  await browser.close();
})();
```

**Comment by aslushnikov** [comment] 2018-07-19 06:57
Dupe of #1893.

**Closed as completed by aslushnikov** 2018-07-19 06:57 UTC

**Comment by yaizudamashii** [comment] 2019-11-01 20:22
Actually I am not getting this behavior from puppeteer, using version 1.17~2.0.0.  I get three set-cookie headers and only one of them is displayed when I do response.headers().
