### ISSUE TITLE
[Docs]: docs seem to encourage opening two pages and using only the second one

### ISSUE THREAD

**Issue by lucasrmendonca** [puppeteer/puppeteer#10654] opened 2023-07-28 01:23 UTC
### Feature description

The following code present in the docs seems to be creating two pages, a default blank one and a new one, which is stored into the "page" variable:
```
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  ...
})();
```
Shouldn't the docs be updated to use this code instead that uses the default blank page instead of creating another new page?
```
(async () => {
  const browser = await puppeteer.launch();
  const [page] = await browser.pages();
  ...
})();
```
(If it makes sense, I'd be glad to make a PR)

**Comment by OrKoN** [comment] 2023-07-28 06:19
I think we don't want to encourage that because closing the default page would also close the browser window which is likely not the expected behaviour (and might work differently in different browsers, e.g., in Firefox). Also, using browser.newPage() indicates that it is possible and teaches how to do that which I find useful for majority of the cases.

**Comment by lucasrmendonca** [comment] 2023-07-28 22:37
Hmm so what you mean is that leaving a default blank page is intended to make sure the browser doesn't close itself if we happen to close the page we're working with? And also provide some sort of cross-browser support?

**Comment by OrKoN** [comment] 2023-08-10 13:33
Right, basically, it's better to create a new page for the purposes and the has to be a default page to make the browser visible.

**Closed as not planned by OrKoN** 2023-08-10 13:33 UTC
