### ISSUE TITLE
'website' wants to store files on this device

### ISSUE THREAD

**Issue by Grant-Zander** [puppeteer/puppeteer#1504] opened 2017-11-30 16:17 UTC
I'm having an issue whereby I cant access the selectors I'm after to scrape unless I click on the 'allow' button. However, their does not seem to be a way to do this in puppeteer.

![image](https://user-images.githubusercontent.com/34135356/33440725-a12df1e2-d5e8-11e7-958a-c892de938170.png)

I found a similar topic on Chrome Drivers Users google groups forum [here](https://groups.google.com/forum/#!topic/chromedriver-users/Fvy9HzPzr4k)

And with that in mind tried using the following to do the 'unlimited - storage' argument but it didn't work.
Is there a way around this currently in Puppeteer?

`   const browser = await puppeteer.launch({headless: false},{args:['--unlimited-storage']});
    const page = await browser.newPage();`

**Comment by ebidel** [comment] 2017-12-02 01:29
Duplicate of https://github.com/GoogleChrome/puppeteer/issues/846

**Closed as completed by ebidel** 2017-12-02 01:29 UTC

**Comment by kidandcat** [comment] 2019-01-03 00:12
This is still an issue for me because I can't find the permission (https://pptr.dev/#?product=Puppeteer&version=master&show=api-browsercontextoverridepermissionsorigin-permissions) related to FileSystem API Storage
