### ISSUE TITLE
Simple page.goto doesn't resolves on webapp.

### ISSUE THREAD

**Issue by OrenLX** [puppeteer/puppeteer#1663] opened 2017-12-26 15:53 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Windows 10
* URLs (if applicable):

Hello,

I am working in company which needs to log into third side website, where we can fetch data about our users. The third side website built with angular and uses routers. 

- The first page.goto (the login page) works well.
- After the login - I am triggering a "waitForSelector" to make sure the page is loaded. Works well.
- I am now doing a simple router navigation, using ```await page.goto('https://partners.ondeck.com/v2/resources/#/application/' + data["partner_business_ID"])```, puppeteer successfully get to the page, but the page.goto never resolves.
- Tried to add parameters such ```{
                waitUntil: 'networkidle2',
                timeout: 3000000}```, but still never resolves.
- Tried to do workaround through setting series of clicks on their UI, it very hacky and at some point the click fails to go through the href.

Now, my best guess it because their whole system is built on angular, which makes the pages loading dynamically. I was using older version of puppeteer few months ago and it managed to work, but after I upgraded to 0.13 it stopped to work.

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
await page.goto('URL_TO_THIRD_SIDE_WEBSITE', {
                waitUntil: 'networkidle2',
                timeout: 3000000});
```

**What is the expected result?**
Code should keep run after page.goto resolves.

**What happens instead?**
page.goto never resolves.

**Comment by aslushnikov** [comment] 2017-12-28 04:09
Yes, the hash-only navigations don't work currently. Closing this as dupe of #257 (please upvote the issue to influence our prioritization).

**Closed as completed by aslushnikov** 2017-12-28 04:09 UTC
