### ISSUE TITLE
Firefox: puppeteer never returns from page.goto() with file:// protocol

### ISSUE THREAD

**Issue by michael-brade** [puppeteer/puppeteer#5504] opened 2020-03-12 22:43 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version: Linux
* URLs (if applicable):
* Node.js version: v12.16.1

**What steps will reproduce the problem?**
If you run the following code, "`GOTO`" is logged in the console, but "`After GOTO`" is never reached. After closing the browser window manually, an error is logged:
`(node:4128451) UnhandledPromiseRejectionWarning: Error: Navigation failed because browser has disconnected!`

```js
const puppeteer = require('puppeteer');
global.page = undefined;

(async function(){
  const browser = (await puppeteer.launch({
    product: 'firefox',
    executablePath: '/opt/firefox/firefox',
    headless: false,
    devtools: false,
    defaultViewport: {
      width: 1000,
      height: 0,
      deviceScaleFactor: 2
    }
  }));
  global.page = (await browser.pages())[0];
  console.log("GOTO");
  await page.goto("file://" + process.cwd() + "/dist");
  console.log("After GOTO");

  await browser.close();
})();
```
If you remove the `product` and `executablePath`, it works fine with chrome, it logs 
```
GOTO
After GOTO
```
and then closes the browser window again.

**Comment by michael-brade** [comment] 2020-03-12 22:46
Oh, BTW, I am using today's firefox nightly, version 76.0a1.

**Comment by michael-brade** [comment] 2020-04-16 13:00
Still happening with puppeteer 3.0 and today's firefox nightly.

However, I now know a little bit more: the reason is the `file://` protocol! If I use `http://` it works fine.

**Comment by michael-brade** [comment] 2020-04-16 13:32
And the reason seems to be that `file://` pages never emit any events with `goto`. I have now tried 
```
await page.goto("file://" + process.cwd(), { waitUntil: "networkidle0", timeout: 2000 });
```
but not even that works.

**Comment by SeekDaSky** [comment] 2020-04-20 14:11
I can reproduce this bug with latest Puppeteer V3.0.0, on Linux with Node 13.13.0 and using the Firefox nightly downloaded using `PUPPETEER_PRODUCT=firefox yarn add puppeteer`.

I work around by serving the static website with an embedded server, but there still is issues when using `goto` on the same URL twice. In my case I have a `Vue.js` project and always use `goto` on URL looking like `index.html#/xxx`, the first `goto()` succeed while subsequent `goto()` freeze.

My guess is that firefox treat the second `goto`'s URL as if it was identical, thus not firing a navigation event.

The complete workaround for SPA is to serve your website AND to only navigate using "clicks".

**Comment by mjzffr** [comment] 2020-04-24 02:04
Thanks for the report. The corresponding Firefox bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1549475

If you'd like to tell the team about how your project using Puppeteer, it might help us prioritize upcoming work on Firefox support. You can reach out at https://wiki.mozilla.org/Remote

**Comment by michael-brade** [comment] 2020-04-28 10:46
Thanks Maja! I have looked through this bug you mentioned but I don't see a reference to a "file://" URL bug. Is that still missing and do I have to create one? Or did I miss it?

**Comment by mjzffr** [comment] 2020-05-01 14:21
I thought there was a specific bug, but there wasn't. Filed one: https://bugzilla.mozilla.org/show_bug.cgi?id=1634690

**Comment by tomByrer** [comment] 2021-05-11 05:15
Issue still exists with Fx, though in Chrome the same same code works fine.

**Comment by jlcd** [comment] 2021-09-15 16:26
This is still happening. If someone has any workarounds, please let us know.

**Comment by m90** [comment] 2021-09-15 16:34
> If someone has any workarounds, please let us know.

@jlcd I ported my project to Playwright by now because of this limitation. Works flawlessly using both engines by now.

**Comment by jlcd** [comment] 2021-09-15 16:35
@m90 that's exactly what I'm doing right now, gave up trying to use puppeteer with firefox. Thanks.

**Comment by michael-brade** [comment] 2022-06-24 22:54
This issue is still not fixed.

**Comment by michael-brade** [comment] 2022-06-25 13:28
> And the reason seems to be that `file://` pages never emit any events with `goto`. I have now tried
> 
> ```
> await page.goto("file://" + process.cwd(), { waitUntil: "networkidle0", timeout: 2000 });
> ```
> 
> but not even that works.

Little update: the timeout now works, the default is 30 seconds. It still does not return from `goto` though.

**Comment by OrKoN** [comment] 2022-09-05 12:31
It seems it's not supported by Firefox and there is a similar issue already https://github.com/puppeteer/puppeteer/issues/8817 (it's unlikely to get fixed in Firefox)

**Closed as not planned by OrKoN** 2022-09-05 12:31 UTC
Labels: unconfirmed
