### ISSUE TITLE
[Feature]: Launching the browser always generates an error

### ISSUE THREAD

**Issue by Chimmz** [puppeteer/puppeteer#10399] opened 2023-06-16 13:29 UTC
### Feature description

```
exports.controlPuppeteer = async (req, res) => {
  try {
    const browser = await puppeteer.launch({ headless: false });
    const page = await browser.newPage();
    await page.goto('https://www.zendesk.com/');
    await page.screenshot({ path: 'zendesk.png' });
  } catch (err) {
    return res
      .status(400)
      .json({ status: 'fail', msg: err.message || 'Something wrong happened' });
  }
};
```

When this controller executes, there's an error response saying:

Could not find Chrome (ver. 114.0.5735.133). This can occur if either\n 1. you did not perform an installation before running the script (e.g. `npm install`) or\n 2. your cache path is incorrectly configured (which is: C:\\Users\\Chima Orji\\qribe\\backend\\.cache\\puppeteer).\nFor (2)

Of course I installed Puppeteer, and I have a configuration file named puppeteer.config.js with content:

```
const { join } = require('path');
module.exports = {
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
  skipDownload: false,
};

```

Please I need help. This is a client project I have to deliver soon. Thanks.

**Comment by OrKoN** [comment] 2023-06-17 06:08
Probably duplicate of https://github.com/puppeteer/puppeteer/issues/10388#issuecomment-1595335224 verify that the binary is actually downloaded as it appears the server is having some glitches from time to time. Also, it is not a feature request.

**Closed as not planned** 2023-06-19 06:06 UTC
