### ISSUE TITLE
Target.getBrowserContexts wasn't found

### ISSUE THREAD

**Issue by olanod** [puppeteer/puppeteer#2815] opened 2018-06-28 18:15 UTC
I might be doing something wrong and connecting in the wrong way but it could also be that the command `Target.getBrowserContexts` is no longer available? I am trying to connect to a running instance of Chromium(v67, I'm on linux, using node 10)
```js
(async (url) => {
  let browser
  try {
    browser = await puppeteer.connect({browserWSEndpoint: url})
  } catch({message}) {
    console.error(message)
  }
  // do something with browser
})('valid url')
```
The url is good, the websocket connection happens but it fails trying to execute the mentioned command, which the documentation still shows as [experimental](https://chromedevtools.github.io/devtools-protocol/tot/Target#method-getBrowserContexts), blame shows it's a relatively recent addition hence my guess of it being a bug rather than me not using the function the right way :sweat_smile:. the debugging info shows
```
puppeteer:protocol SEND ► {"id":1,"method":"Target.getBrowserContexts","params":{}} +0ms
puppeteer:protocol ◀ RECV {"error":{"code":-32601,"message":"'Target.getBrowserContexts' wasn't found"},"id":1} +3ms
```
Commenting out [this line](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Launcher.js#L257) and passing an empty array to the `Browser.create` function seems to work.

**Comment by JoelEinbinder** [comment] 2018-06-30 07:07
Closing as a duplicate of #2700.
Puppeteer works with bleeding edge Chromium, not stable Chrome which lags a few months behind. Use an older version of Puppeteer or a newer version of Chrome.

**Closed as completed by JoelEinbinder** 2018-06-30 07:07 UTC
