### ISSUE TITLE
[Bug]: TimeoutError generating simple PDF

### ISSUE THREAD

**Issue by heliocj** [puppeteer/puppeteer#12467] opened 2024-05-20 14:59 UTC
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {

async function GenerateSimplePdf() {

try {
    const browser = await puppeteer.launch({ headless: true, ignoreHTTPSErrors: true });
    const browser_page = await browser.newPage();

      await browser_page.setContent('<p>Testing content...</p>', {
        waitUntil: 'networkidle0',
        timeout: 1 * 60 * 1000,
      });

      await browser_page.pdf({
        printBackground: true,
        format: 'A4',
        landscape: false,
        margin: {
          top: '1cm',
          bottom: '1cm',
          left: '1cm',
          right: '1cm',
        },
        path: 'simple.pdf',
        timeout: 1 * 60 * 1000,
      });

      await browser.close();
} catch (error) {
console.log('Error: something went wrong');
}

}

await GenerateSimplePdf();

})()
```

### Error string

console.log('Error: something went wrong');

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

Generate a PDF file with: Testing content...

### Reality

Error: something went wrong

### Puppeteer version

22.9.0

### Node version

20.13.1

### Package manager

npm

### Package manager version

10.5.2

### Operating system

Windows

**Comment by sbj42** [comment] 2024-05-21 00:51
I was able to reproduce this issue, I don't know why the analyzer could not.

See also #12470 with a simpler example.

**Comment by OrKoN** [comment] 2024-05-21 07:05
Duplicate of https://github.com/puppeteer/puppeteer/issues/12470

**Closed as not planned by OrKoN** 2024-05-21 07:05 UTC
Labels: needs-feedback, not-reproducible
