### ISSUE TITLE
[Bug]: Failed to launch the browser process when headless set to "new"

### ISSUE THREAD

**Issue by fdciabdul** [puppeteer/puppeteer#10517] opened 2023-07-07 06:25 UTC
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");
const paths = process.cwd() + "/extension";
(async () => {
  const browser = await puppeteer.launch({
    headless: "new",
    args: ["--no-sandbox", 
    "--disable-setuid-sandbox",
    `--disable-extensions-except=${paths}`,
    `--load-extension=${paths}`],
    userDataDir: "./tmp",
  });
  const page = await browser.newPage();
  await page.goto("https://www.google.com/");

})();
```

### Error string

Failed to launch the browser process! undefined

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

i've been trying to run puppeteer with headless "new" because headless true will be deprecated soon 

### Expectation

it will run properly

### Reality

it's not , it crash and show the error like this 

```bash
Error: Failed to launch the browser process! undefined
[27051:27051:0707/132159.274812:ERROR:process_singleton_posix.cc(334)] Failed to create /home/fdciabdul/PROJECT/fbchat/tmp/SingletonLock: File exists (17)


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/home/fdciabdul/PROJECT/fbchat/node_modules/@puppeteer/browsers/lib/cjs/launch.js:259:24)
    at ChildProcess.emit (node:events:525:35)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

Node.js v18.14.2

```

but when i set headless to `false` it's work 

### Puppeteer version

20.7.4

### Node version

18.14.2

### Package manager

npm

### Package manager version

9.5.0

### Operating system

Linux

**Comment by fdciabdul** [comment] 2023-07-07 06:27
Update : 

i was update puppeteer version to latest , 20.8.0 

but still this error happen

**Comment by OrKoN** [comment] 2023-07-07 07:16
Could you delete `/home/fdciabdul/PROJECT/fbchat/tmp/SingletonLock`? are you trying to run multiple browsers in parallel?

**Comment by fdciabdul** [comment] 2023-07-07 14:17
> Could you delete `/home/fdciabdul/PROJECT/fbchat/tmp/SingletonLock`? are you trying to run multiple browsers in parallel?

yes deleting the folder will make run properly , but just one time , second time will error again 


![image](https://github.com/puppeteer/puppeteer/assets/31664438/e57deca8-32b4-4331-a61d-1daba96af0b0)

**Comment by fdciabdul** [comment] 2023-07-07 14:18
> Could you delete `/home/fdciabdul/PROJECT/fbchat/tmp/SingletonLock`? are you trying to run multiple browsers in parallel?

note : this error happen just when i set headless to "new" 

headless `false` or `true` it will work

**Comment by fdciabdul** [comment] 2023-07-07 14:56
@OrKoN There might be a bug with the 'userdatadir' in Puppeteer "new" headless mode.

**Comment by OrKoN** [comment] 2023-07-10 07:13
Looks like this happens if the browser is not closed via `browser.close` and instead killed via the process termination.

**Comment by OrKoN** [comment] 2023-07-10 07:16
Tracking link https://crbug.com/1463328

**Comment by jonalan7** [comment] 2023-07-10 17:59
which version is not giving this problem?

**Comment by ShiftaDeband** [comment] 2023-07-10 20:02
> Looks like this happens if the browser is not closed via `browser.close` and instead killed via the process termination.

For what it's worth, I am having this with the new headless mode and am also using `browser.close();`. I have a loop of domains that I'm trying to grab a screenshot of, and my best guess is that the previos session was either still being closed or failed to close and left the lock, then the new process touched it, but I'm not entirely sure if that's the case.

**Comment by fdciabdul** [comment] 2023-07-12 22:50
> 

new version of puppeteer of course

**Comment by fdciabdul** [comment] 2023-07-12 22:52
> Looks like this happens if the browser is not closed via `browser.close` and instead killed via the process termination.

i added `browser.close()` but still same problem happen

**Comment by Kikobeats** [comment] 2023-07-16 09:22
Another way to avoid this is ensuring user data is unique:

```
const PUPPETEER_DIR = path.join(TMP_FOLDER, `puppeteer-${randomUUID()}`)
const DATA_DIR = path.join(PUPPETEER_DIR, 'profile')
```

Passing the flag:

```
`--user-data-dir=${DATA_DIR}`
```

So even the browser is not gracefully browser, a new browser spawn will have associated a different folder.

**Comment by abrdgrt** [comment] 2023-07-22 18:52
I can also confirm this issue, easiest way so far is to first check and delete the file in the code before launching the browser

**Comment by fdciabdul** [comment] 2023-07-28 15:49
> Another way to avoid this is ensuring user data is unique:
> 
> ```js
> const PUPPETEER_DIR = path.join(TMP_FOLDER, `puppeteer-${randomUUID()}`)
> const DATA_DIR = path.join(PUPPETEER_DIR, 'profile')
> ```
> 
> Passing the flag:
> 
> ```js
> `--user-data-dir=${DATA_DIR}`
> ```
> 
> So even the browser is not gracefully browser, a new browser spawn will have associated a different folder.
> 
> On the other hand, even using `browser.close` the directory is not cleaned, so that is clearly buggy.

making unique userdatadir is not what i want , because in here i wanna save the session

**Comment by virtuallyunknown** [comment] 2023-08-15 01:14
I see people are suggesting the `browser.close()` method, but I have a service that is generating screenshots based on user input and for this reason I want to keep the browser instance open instead of re-`launch`-ing it every time (slow and expensive task). Additionally I also use `userDataDir` so caching is implemented since some of the data is coming from outside.

In production this is actually much less of an issue since the service doesn't restart, but in development where restarts are very frequent and the exits aren't clean this is a problem. Would love to see this issue being addressed. Cheers!

```js
// PuppeteerLaunchOptions

{
    headless: 'new',
    ignoreHTTPSErrors: true,
    userDataDir: './some-dir'
}

// puppeteer: 21.0.3
// node: 20.5.1
// os: linux
```

**Comment by adinvadim** [comment] 2023-08-27 14:27
I see the solution in this case now. It is check before launch in user datadir SingletonLock and if it exists delete this

**Comment by fdciabdul** [comment] 2023-09-08 12:47
> I see the solution in this case now. It is check before launch in user datadir SingletonLock and if it exists delete this

that's not solution

**Comment by xx299x** [comment] 2023-09-20 08:09
Just add `--enable-early-process-singleton` to your launch parameters, and you can start it normally.

**Comment by Kikobeats** [comment] 2023-09-20 08:50
@xx299x can you explain a bit what that flag is doing?

**Comment by tranvanba1992** [comment] 2023-09-20 08:54
> Just add `--enable-early-process-singleton` to your launch parameters, and you can start it normally.

Not working :(

**Comment by xx299x** [comment] 2023-09-20 08:55
> > Just add `--enable-early-process-singleton` to your launch parameters, and you can start it normally.
> 
> Not working :(

I'm sorry everyone

**Comment by Kikobeats** [comment] 2023-09-20 09:08
I believe the only issue here is the expectation for the puppeteer to handle the lifecycle of the lock file.

The workarounds are valid (essentially control the lock file in an explicit way, like I [suggested](https://github.com/puppeteer/puppeteer/issues/10517#issuecomment-1637034110)) but I feel puppeteer can do it for us.

**Comment by OrKoN** [comment] 2023-09-20 09:19
This is being fixed in https://bugs.chromium.org/p/chromium/issues/detail?id=1463328 The fix is on the Chromium side and it is expected to roll out in M119.

**Comment by webnoob** [comment] 2023-10-19 11:32
When can we expect puppeteer to download / install M119? I'm not sure how puppeteer decides on its latest version. Is it when the version is considered stable by google i.e When the stable date is hit on this https://chromiumdash.appspot.com/schedule ?

**Comment by cage1618** [comment] 2023-10-23 13:52
What's the status of this issue? I have the same problem

**Comment by fdciabdul** [comment] 2023-10-23 19:30
> What's the status of this issue? I have the same problem

upgrade your puppeteer version to latest , i never face this issue again 

and dont forget using chrome / chromium newer version

**Comment by Kikobeats** [comment] 2023-10-23 21:54
tested with puppeteer@21.4.0 and still happening

**Comment by virtuallyunknown** [comment] 2023-10-24 20:03
> upgrade your puppeteer version to latest , i never face this issue again
> 
> and dont forget using chrome / chromium newer version

The latest version of Puppeteer at the time of writing this comment is `21.4.1` which comes with Chrome `Chrome/118.0.5993.70` so the problem is still present.

**Comment by Kikobeats** [comment] 2023-10-24 21:44
@OrKoN, it could be great to re-open this issue for tracking purposes; it is quite confusing that the issue is still there, but it's "closed", even if the problem isn't on the puppeteer side

**Comment by soyayaos** [comment] 2023-11-02 18:19
@virtuallyunknown @Kikobeats @fdciabdul fixed in 21.5.0

**Comment by fdciabdul** [comment] 2023-11-02 19:03
> @virtuallyunknown @Kikobeats @fdciabdul fixed in 21.5.0

great , i'll close this issue

**Comment by ethyaan** [comment] 2023-11-03 06:50
I upgraded version to `21.5.0` , tested it now, I confirm that the issue is fixed.

**Comment by virtuallyunknown** [comment] 2023-11-03 09:33
Can also confirm it's working for me as well. Thanks a lot for fixing this folks, it was kind of a pain to deal with <3

**Closed as completed** 2023-11-03 16:41 UTC
Labels: upstream, confirmed

**Comment by danielo515** [comment] 2023-11-06 09:44
What is the right tag to use? I am getting this error by using latest

**Comment by dgtlmoon** [comment] 2023-11-17 09:57
@mostafa-hisham no, please read https://github.com/puppeteer/puppeteer/issues/10517#issuecomment-1655913706

**Comment by dgtlmoon** [comment] 2023-11-17 10:08
FWIW to others - I had to set `&headless=true` - actually I had no `headless=` defined (I'm stuck in my architecture running an earlier puppeteer that I dont have much control over), so yeah, also check you have `headless=` set at all if you're on earlier versions, without it it may default to `new`

**Comment by 2jmalvarez** [comment] 2024-03-04 18:15
Fix:
sudo apt-get update
sudo apt-get install -y libgbm-dev

**Comment by Indal-Singh** [comment] 2024-07-11 04:24
I encountered the same issue when deploying on an Ubuntu machine. Here are the steps I followed to resolve it:

1. Installed Chrome manually using these commands:

    ```sh
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo dpkg -i google-chrome-stable_current_amd64.deb
    sudo apt -f install
    sudo snap install chromium
    ```

2. After installing Chrome, Puppeteer showed a display error. To fix this, I installed Xvfb:

    ```sh
    sudo apt-get install -y xvfb
    ```

3. Finally, I ran my script with Xvfb:

    ```sh
    xvfb-run node index.js
    ```

After these steps, everything worked perfectly. You might want to try this as well, it may resolve your issue too.

**Comment by fdciabdul** [comment] 2024-07-11 05:45
> I encountered the same issue when deploying on an Ubuntu machine. Here are the steps I followed to resolve it:
> 
> 1. Installed Chrome manually using these commands:
>    ```shell
>    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
>    sudo dpkg -i google-chrome-stable_current_amd64.deb
>    sudo apt -f install
>    sudo snap install chromium
>    ```
> 2. After installing Chrome, Puppeteer showed a display error. To fix this, I installed Xvfb:
>    ```shell
>    sudo apt-get install -y xvfb
>    ```
> 3. Finally, I ran my script with Xvfb:
>    ```shell
>    xvfb-run node index.js
>    ```
> 
> After these steps, everything worked perfectly. You might want to try this as well, it may resolve your issue too.


you might be set the headless to false

**Comment by Indal-Singh** [comment] 2024-09-13 02:08
I think you not installed chromium. Verify chromium browser installed or not and also created virtual browser display instances virtually you can use xvfb as interpter

**Comment by Himanshu-Agg12** [comment] 2024-09-13 06:10
@Indal-Singh Now the chromium browser launch is fixed but now i am getting some different error.

"TargetCloseError: Protocol error (Target.createTarget): Target closed"
This is happening when i am opening a new page and setting the content of html to convert it to pdf.

Is there anything that i am missing.

**Comment by Indal-Singh** [comment] 2024-09-13 06:34
@Himanshu-Agg12  it may be occurring due to your browser will close after launch you try headless false you can also try to increase time out and untilwait page load in page goto section . And also try to disable javascript script if you don't need .

**Comment by Himanshu-Agg12** [comment] 2024-09-13 07:01
@Indal-Singh , i am using headless true only and also i have a timeout when launching browser and i am closing the page after generating pdf, closing the browser in on module destry in nestjs. Below is my code:

`const customBrowser = await this.launchBrowser()
        const page = await customBrowser.newPage();
        console.log("Browser Opened a new page.");
        
        await page.setContent(htmlContent, { waitUntil: 'domcontentloaded' });
        const defaultPdfSettings = {
            format: 'a4',
            printBackground: true,
            margin: {
              top: '5mm',
              bottom: '5mm',
              left: '10mm',
              right: '10mm',
            },
            scale: 0.50,
          };
        const pdfSettings = customSetting ?? defaultPdfSettings as any;
        const pdfBuffer = await page.pdf(pdfSettings);
        console.log("Generated pdfBuffer.");
        await page.close();
        console.log("Browser closed the page.");
        return Buffer.from(pdfBuffer);`
        
        I am getting the log till Browser opened a new page after that i got error.
        
        Can you help in this now?

**Comment by Indal-Singh** [comment] 2024-09-13 09:36
Try to disable javascript 

page.setJavaScriptEnabled(false);
And also try to increase time. 120 s + 

It might be solved your problem

**Comment by Himanshu-Agg12** [comment] 2024-09-13 10:50
@Indal-Singh , tried now i am getting the following error:
TargetCloseError: Protocol error (Emulation.setScriptExecutionDisabled): Session closed. Most likely the page has been closed."

**Comment by Himanshu-Agg12** [comment] 2024-09-13 21:00
@Indal-Singh , the html is correct. I have tested it locally as well by building the docker image.

**Comment by Indal-Singh** [comment] 2024-09-14 03:23
Yes I know Puppeteer work very well in locally but when we try to deploy it show many error even I faced many error but in my case I resolved all the the error but your last error you sheard I don't have Idea about that .
