### ISSUE TITLE
  When a screenshot is done on a very large web page, there are three duplicate web pages, rather than a complete webpage screenshot

### ISSUE THREAD

**Issue by jiajunli** [puppeteer/puppeteer#2818] opened 2018-06-29 09:35 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.1.1
* Platform / OS version: ubuntu 16.04 LTS
* URLs (if applicable): https://detail.tmall.com/item.htm?spm=a1z10.5-b-s.w4011-14572554292.118.240f2104L8SXzW&id=563021456803&rn=9efa0721815778d8646f5a4d4f18af6d&abbucket=4
* Node.js version: v8.6.0

**What steps will reproduce the problem?**
  
_Please include code that reproduces the issue._

This is a webpage screenshot, but there are 3 repetitions. The results are as follows:
![screen](https://user-images.githubusercontent.com/10512557/42085310-a669a2f2-7bc2-11e8-9e60-df623549414e.jpg)

**What is the expected result?**
Hope to be able to intercept a full page picture

**What happens instead?**

**Comment by pomerantsev** [comment] 2018-06-30 02:46
Probably a duplicate of #1576

**Comment by jiajunli** [comment] 2018-06-30 03:38
How can we solve this problem in view of the height of uncertain web pages?

**Closed as completed** 2022-07-27 19:58 UTC
Labels: chromium, unconfirmed
