### ISSUE TITLE
[Bug]: Browser gets disconnected in Docker without any errors

### ISSUE THREAD

**Issue by sangn-splunk** [puppeteer/puppeteer#12257] opened 2024-04-11 16:22 UTC
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

async function start() {
  const browserOptions = {
    headless: false,
    args: [
      '--window-position=0,0',
      '--kiosk',
      '--disable-gpu',
      '--disable-offline-auto-reload',
      '--disable-offline-auto-reload-visible-only',
      '--no-default-browser-check',
      '--disable-domain-reliability',
      '--disable-features=site-per-process',
      '--disable-site-isolation-trials',
      '--start-fullscreen',
      '--process-per-tab',
      '--display=:99',
      '--no-sandbox',
      '--window-size=1366,768',
      '--homepage',
      'about:blank',
      '--enable-chrome-browser-cloud-management'
    ],
    dumpio: true
  };
  const browser = await puppeteer.launch(browserOptions);
  const page = await browser.newPage();

  await page.goto('https://imperial.ac.uk/jobs/search-internal/');
  await new Promise(r => setTimeout(r, 20000));
  console.log("browser connected?", await browser.isConnected());
  console.log("browser page url", await page.url());
  browser.close();
}

start();
```

### Error string

Error: Requesting main frame too early!

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

The example used totally works when running outside a docker container, but fails for `Error: Requesting main frame too early!` when inside a container.

Chrome `116.0.5845.96-1` and puppeteer `21.1.0` were working for us, but we started seeing this on Chrome `121.0.6167.184-1` and puppeteer `21.9.0`. This is also happening on Chrome 123 and puppeteer `22.6.3`.

This is the dockerfile used to create the issue. It uses a local .deb file for specific chrome versions. I got this directly from google: `wget "http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_123.0.6312.105-1_amd64.deb"`

```
FROM ubuntu:focal
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    curl \
    xvfb \
    gdebi-core \
    libasound2 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgdk-pixbuf2.0-0 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    xdg-utils \
    wget

COPY google-chrome-stable_123.0.6312.105-1_amd64.deb /tmp/google-chrome-123.deb

RUN curl -sL https://deb.nodesource.com/setup_20.x | bash - \
  && apt-get install -y nodejs \
  && node --version \
  && npm --version

RUN gdebi --non-interactive /tmp/google-chrome-123.deb

RUN groupadd -r pptruser && useradd -m -r -g pptruser -G audio,video pptruser \
  && mkdir -p /home/pptruser/Downloads \
  && chown -R pptruser:pptruser /home/pptruser

USER pptruser
WORKDIR /home/pptruser

RUN npm install puppeteer@22.6.3 --save
COPY test.js .

CMD ["sleep", "infinity"]
```

Build: `docker build -t puppeteer-example`
Run: `docker run -d --name puppeteer-example puppeteer-example`

Then exec into the container and run the example:
`docker exec -it SHA_GOES_HERE /bin/sh`
`$ xvfb-run node test.js`

What's interesting is version `google-chrome-stable_116.0.5845.96-1` of Chrome and puppeteer `21.1.0` does not have this error.

### Expectation

I shouldn't see `Error: Requesting main frame too early`, but I do. It seems like something is disconnecting puppeteer too early resulting in this error, but I don't know what.

### Reality

I see `Error: Requesting main frame too early!`

### Puppeteer version

22.6.3

### Node version

20.12.2

### Package manager

npm

### Package manager version

10.5.0

### Operating system

Linux

**Comment by sangn-splunk** [comment] 2024-04-11 16:53
The error still happens without the `--start-fullscreen` and `--kiosk` flags
![image](https://github.com/puppeteer/puppeteer/assets/89856160/a965512c-2589-4ce2-bd70-1e41e99b97d8)

**Comment by OrKoN** [comment] 2024-04-11 16:55
For me it only happens with those flags on MacOS, without Docker. I see in the logs that some target detach events are sent by the browser. Could you clarify if any of the other flags are relevant for the reproduction of the issue?

**Comment by OrKoN** [comment] 2024-04-11 16:58
@sangn-splunk could you try the version 22.6.4 that was just released?

**Comment by sangn-splunk** [comment] 2024-04-11 17:03
While removing all flags did not help, it did seem like 22.6.4 resolved the issue! 🎉 
![image](https://github.com/puppeteer/puppeteer/assets/89856160/7676da36-e30e-4072-920f-917d6263351c)

**Comment by OrKoN** [comment] 2024-04-11 17:15
@sangn-splunk yeah but you still cannot evaluate or do anything with the page or the browser because it has disconnected.

**Comment by OrKoN** [comment] 2024-04-11 17:16
I am not able to reproduce it with default flags only though:

```
const puppeteer = require('puppeteer');

async function start() {
  const browserOptions = {
    headless: false,
    dumpio: true
  };
  const browser = await puppeteer.launch(browserOptions);
  const page = await browser.newPage();

  await page.goto('https://imperial.ac.uk/jobs/search-internal/');

  await new Promise(r => setTimeout(r, 20000));

  console.log("browser connected?", await browser.isConnected());
  console.log("browser page url", await page.url());
  console.log(await page.evaluate(() => 1 + 2))
  browser.close();
}

start();
```

**Comment by sangn-splunk** [comment] 2024-04-11 17:20
Ahh dang I totally missed that the browser is still disconnected :(. I didn't see a stack trace, so I assumed it was all good. This is what I get:

![image](https://github.com/puppeteer/puppeteer/assets/89856160/556375ec-b489-4c16-8a16-85e32be5a157)

Everything seems okay outside a container. The problem is running this inside a container in headful mode.

**Comment by OrKoN** [comment] 2024-04-11 17:22
can you try using the Docker image we provide? https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer

**Comment by OrKoN** [comment] 2024-04-11 17:23
E.g., `docker run -i --init --rm --cap-add=SYS_ADMIN docker pull ghcr.io/puppeteer/puppeteer:22.6.4  node -e "`cat test.js`"`

**Comment by OrKoN** [comment] 2024-04-11 17:25
although you would probably need headless: true for that but that should behave similar to headful

**Comment by sangn-splunk** [comment] 2024-04-11 17:30
Sure! Is it possible to run headful mode with the provided docker image? Do I need xvfb?

**Comment by OrKoN** [comment] 2024-04-11 17:31
@sangn-splunk you can run `headless: true` it is the same as regular Chrome (from v22) with only windows not being rendered

**Comment by sangn-splunk** [comment] 2024-04-11 17:40
Same error, `Attempted to use detached Frame`,  when using `headless: true` against the provided image:

![image](https://github.com/puppeteer/puppeteer/assets/89856160/2babc3b5-733e-4ec4-a9eb-812e6aff9c3f)

**Comment by sangn-splunk** [comment] 2024-04-11 19:18
For what it's worth, this is what seems to be throwing the `disconnected` event:

```javascript
  browser.on('disconnected', async () => {                                                                                                                                                                                  
    Error.stackTraceLimit = 100                                                                                                                                                                                             
    console.log('disconnected caller', (new Error()).stack)                                                                                                                                                                 
  }) 
```

```
disconnected caller Error
    at /home/pptruser/test.js:11:41
    at /home/pptruser/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:62:7
    at Array.map (<anonymous>)
    at Object.emit (/home/pptruser/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:61:20)
    at CdpBrowser.emit (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:83:23)
    at #emitDisconnected (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Browser.js:61:14)
    at /home/pptruser/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:62:7
    at Array.map (<anonymous>)
    at Object.emit (/home/pptruser/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:61:20)
    at Connection.emit (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:83:23)
    at #onClose (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:160:14)
    at WebSocket.<anonymous> (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:47:30)
    at callListener (/home/pptruser/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/home/pptruser/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:514:28)
    at WebSocket.emitClose (/home/pptruser/node_modules/ws/lib/websocket.js:265:10)
    at Socket.socketOnClose (/home/pptruser/node_modules/ws/lib/websocket.js:1289:15)
    at Socket.emit (node:events:514:28)
    at TCP.<anonymous> (node:net:337:12)
```

Also this did not happen on Chrome 116.0.5845.96-1 and puppeteer 21.1.0. I hope this helps.

**Comment by OrKoN** [comment] 2024-04-11 19:27
@sangn-splunk yeah it is the websocket connection being closed by the browser

**Comment by OrKoN** [comment] 2024-04-12 06:16
It also seems to be happening on this specific page. E.g., it does not happen with wikipedia.org

**Comment by OrKoN** [comment] 2024-04-12 07:00
So it is a Crash and in Chrome and I see in the bugtracker that it was fixed in M124+. I will try it later.

**Comment by sangn-splunk** [comment] 2024-04-12 07:07
Ah nice! I can find more example sites as well. Here's another one: `https://www.imperial.ac.uk/monitoring/saml/attributes-json/`

Can you share the link to the bug tracker?

**Comment by sangn-splunk** [comment] 2024-04-12 07:15
I also had a `pageerror` event registered, but I didn't see any output there, so I didn't think it was a crash.

**Comment by OrKoN** [comment] 2024-04-12 07:21
@sangn-splunk it is not possible to get a page error if the whole browser crashes. I have reproduced it with the build that has crash reporting

**Comment by OrKoN** [comment] 2024-04-12 07:22
The crash report is not public but the version that is says it is fixed in 124.0.6367.18

**Comment by OrKoN** [comment] 2024-04-12 07:25
Unfortunately, it does not look like it has been fixed.

**Comment by OrKoN** [comment] 2024-04-12 07:37
I filed https://crbug.com/333945847

**Comment by OrKoN** [comment] 2024-04-12 08:22
As a workaround, you could try

```
     args: [
      '--disable-features=NetworkServiceInProcess2'
    ]
```

but it might be important for some Puppeteer features such as network interception.

**Comment by sangn-splunk** [comment] 2024-04-12 14:21
the `--disable-features=NetworkServiceInProcess2` flag seems to work!

**Closed as completed** 2024-04-12 20:46 UTC
Labels: upstream, confirmed, P2
