### ISSUE TITLE
WaitFor not working in 1.0.0

### ISSUE THREAD

**Issue by juliorenner** [puppeteer/puppeteer#1945] opened 2018-02-01 21:16 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: Ubuntu 14.04
* URLs (if applicable):
* Node.js version: v8.9.3

**What steps will reproduce the problem?**

When executing `await page.waitFor("input#j_username");` the execution breaks.
Debugging a bit, the issue seems to happen when function `waitForPredicatePageFunction` is executed and calls `const predicate = new Function('...args', predicateBody);`.

The args used are:
["input#j_username", false, false]

It was working in the previous version (0.13)

**What is the expected result?**
Resolve the promise and continue with the execution.

**What happens instead?**

```
Evaluation failed: EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'nonce-JFN7+qcS35Px4qr15v2hvFVCETSFT73mKmp4chHyOig='".
    at new Function (<anonymous>)
    at waitForPredicatePageFunction (<anonymous>:2:21)
      at ExecutionContext.evaluateHandle (node_modules/puppeteer/lib/ExecutionContext.js:70:13)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ebidel** [comment] 2018-02-02 20:07
Dupe of https://github.com/GoogleChrome/puppeteer/issues/1229

**Closed as completed by ebidel** 2018-02-02 20:07 UTC
