### ISSUE TITLE
Puppeteer can't handle the location auth.

### ISSUE THREAD

**Issue by CommanderXL** [puppeteer/puppeteer#1840] opened 2018-01-18 08:29 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: MacOS
* URLs (if applicable):
* Node.js version: 8.4.0

**What steps will reproduce the problem?**

In my application, I used the `navigator.geolocation.getCurrentPosition` to get the user location.But chromium will alert the auth dialog when I open it everytime. Like this:

![location](https://user-images.githubusercontent.com/9695264/35087830-8315acfe-fc6c-11e7-9394-3846c12ddfe2.png)

Well, it seems that puppeteer didn't have the api to auth the location.

_Please include code that reproduces the issue._

**What is the expected result?**

If puppeteer has api to auth the location. So the code that `navigator.geolocation.getCurrentPosition` works well.

**What happens instead?**

**Comment by aslushnikov** [comment] 2018-01-18 18:23
Dupe of #846.

**Closed as completed by aslushnikov** 2018-01-18 18:23 UTC
