### ISSUE TITLE
Page crashed!

### ISSUE THREAD

**Issue by 3fuyu** [puppeteer/puppeteer#890] opened 2017-09-27 03:12 UTC
Puppeteer version: 0.11.0
Platform/ OS version: MacOS 16G and CentOS7 8G

I create 10 chromium instance, and create enough page for a high QPS about 300. And happened this problem. I think it happened because of too many pages opened. But it's necessary  because of business. so

1. What can I do for this problem? 
2. And  are there some way I can catch the page crashed？
3. If the QPS more than 300, chromium instance will crashed too,  can I catch it ?

```
Error: Page crashed!
    at Page._onTargetCrashed (/Users/yehua/Code/chu-ko-no/node_modules/_puppeteer@0.11.0@puppeteer/node6/Page.js:118:24)
    at Session.Page.client.on.event (/Users/yehua/Code/chu-ko-no/node_modules/_puppeteer@0.11.0@puppeteer/node6/Page.js:114:56)
    at emitOne (events.js:96:13)
    at Session.emit (events.js:188:7)
    at Session._onMessage (/Users/yehua/Code/chu-ko-no/node_modules/_puppeteer@0.11.0@puppeteer/node6/Connection.js:277:12)
    at Connection.<anonymous> (/Users/yehua/Code/chu-ko-no/node_modules/_puppeteer@0.11.0@puppeteer/node6/Connection.js:150:19)
    at next (native)
    at step (/Users/yehua/Code/chu-ko-no/node_modules/_puppeteer@0.11.0@puppeteer/node6/Connection.js:113:24)
    at Promise (/Users/yehua/Code/chu-ko-no/node_modules/_puppeteer@0.11.0@puppeteer/node6/Connection.js:131:12)
    at fn (/Users/yehua/Code/chu-ko-no/node_modules/_puppeteer@0.11.0@puppeteer/node6/Connection.js:109:10)
```

```

[0927/105044.594206:FATAL:waitable_event_mac.cc(202)] Check failed: wait_many.is_valid(). kqueue: Too many open files in system (23)
0   Chromium Framework                  0x000000010a21b9ac ChromeMain + 28467404
1   Chromium Framework                  0x000000010a2353c0 ChromeMain + 28572384
2   Chromium Framework                  0x000000010a235d8e ChromeMain + 28574894
3   Chromium Framework                  0x000000010a27cfa7 ChromeMain + 28866247
4   Chromium Framework                  0x000000010ad7566c ChromeMain + 40369548
5   Chromium Framework                  0x000000010ad718f0 ChromeMain + 40353808
6   Chromium Framework                  0x000000010ad710ca ChromeMain + 40351722
7   Chromium Framework                  0x000000010ad677fb ChromeMain + 40312603
8   Chromium Framework                  0x00000001089c7e50 ChromeMain + 2958704
9   Chromium Framework                  0x000000010e0d482e ChromeMain + 94236494
10  Chromium Framework                  0x000000010d7a2d14 ChromeMain + 84595764
11  Chromium Framework                  0x000000010d1d75f1 ChromeMain + 78519569
12  Chromium Framework                  0x000000010cc95c48 ChromeMain + 73007976
13  Chromium Framework                  0x0000000109523471 ChromeMain + 14867345
14  Chromium Framework                  0x00000001095a8473 ChromeMain + 15412115
15  Chromium Framework                  0x00000001095a7dee ChromeMain + 15410446
16  Chromium Framework                  0x000000010995975b ChromeMain + 19283579
17  Chromium Framework                  0x00000001098d34e9 ChromeMain + 18734089
18  Chromium Framework                  0x00000001098db79c ChromeMain + 18767548
19  ???                                 0x00002d9cc5d8449d 0x0 + 50151357432989
```

Thanks very much! ~~~

**Comment by ebidel** [comment] 2017-09-27 18:36
Dupe of https://github.com/GoogleChrome/puppeteer/issues/485.

Are you creating a page per request? 300 QPS is quite high. With only 8GB on the CentOS7, seems like you're definitely running into limits.

> What can I do for this problem?

Apart from throwing more machines at the problem, could load balance the requests even more, provide a request queue, or introduce throttling? Unfortunately, this starts to get outside the scope of the project.

> And are there some way I can catch the page crashed？

See `page.on('error')`. https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-error

> If the QPS more than 300, chromium instance will crashed too, can I catch it ?

@aslushnikov do we have a signal for the browser crashing?

**Comment by 3fuyu** [comment] 2017-09-28 06:12
Thank you very much. The puppeteer you invent change something huge, it's powerful !
> Are you creating a page per request? 300 QPS is quite high. With only 8GB on the CentOS7, seems like you're definitely running into limits.

Yes, one request one page.

> Apart from throwing more machines at the problem, could load balance the requests even more, provide a request queue, or introduce throttling? Unfortunately, this starts to get outside the scope of the project.

The 300 QPS just a example, actually higher than this. Load balancing and server clustering already have. But it's not enough. So, I'm going to do a message queue, thanks.

> If the QPS more than 300, chromium instance will crashed too, can I catch it ?

@aslushnikov  aha, if you have, please. thanks~~

**Another question, if page crashing , I can get the url from ````page.url()```` to recover the request,  and if the browser crashing, I can't get anything useful for the request , some API provide?**

**Comment by aslushnikov** [comment] 2017-10-03 04:37
> Another question, if page crashing , I can get the url from page.url() to recover the request, and if the browser crashing, I can't get anything useful for the request , some API provide?

There's a #554 that will give you the `browser.pages()` API. Should be helpful.

For this issue to be addressed, browser instance should emit 'close' event when the browser connection is closed.

**Comment by aslushnikov** [comment] 2017-10-04 22:20
Filed a separate issue for the API: #952

**Closed as completed by aslushnikov** 2017-10-04 22:20 UTC
