### ISSUE TITLE
[Bug]: When using headless new, true in Windows operating systems, the browser still appears

### ISSUE THREAD

**Issue by mdervisaygan** [puppeteer/puppeteer#13132] opened 2024-09-26 14:12 UTC
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer')
async function test() {
    const browser = await puppeteer.launch({
        headless: "new",
        ignoreDefaultArgs: ['--enable-automation'],
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu'],
    })
    
}
test()
```

### Background

Headless new and true not working correctly in Windows operating systems

### Expectation

the browser must be opened incognito when headless new and true

### Reality

when headless is new and true, the browser opens as a white screen, but processes continue in the background

https://github.com/user-attachments/assets/ac04b5ab-8055-4ead-a4b8-61d1d9767cef

### Puppeteer version

^23.4.1

### Node version

v20.17.0

### Package manager

npm

### Package manager version

10.8.2

### Operating system

Windows

**Comment by OrKoN** [comment] 2024-09-26 14:22
Duplicate of https://github.com/puppeteer/puppeteer/issues/13012

**Closed as not planned by OrKoN** 2024-09-26 14:22 UTC
