### ISSUE TITLE
[Bug]: Multiple tabs in single browser times out vs multiple instances in headless mode

### ISSUE THREAD

**Issue by sduluganti** [puppeteer/puppeteer#8693] opened 2022-07-24 05:52 UTC
### Bug description

Run the below code:

```js
const puppeteer = require('puppeteer');

const urls = [
  'https://www.massagewarehouse.com',
  'https://www.massagewarehouse.com/checkout/cart',
  'https://www.massagewarehouse.com/shop-by-department/ppe',
  'https://www.massagewarehouse.com/catalogsearch/advanced',
  'https://www.massagewarehouse.com/customer/account/create',
  'https://www.massagewarehouse.com/shop-by-department/aromatherapy',
  'https://www.massagewarehouse.com/massage-warehouse-shipping-offer',
  'https://www.massagewarehouse.com/shop-by-department/massage-equipment',
];

/*************************Finishes without timeout**************************/
(async () => {
  console.time('crawl');
  await Promise.all(
    urls.map(async (url) => {
      const browser = await puppeteer.launch();
      const page = await browser.newPage();
      await page.goto(url);
      return browser.close();
    })
  );
  console.timeEnd('crawl');
})();

/*************************Errors out with timeout**************************/
(async () => {
  console.time('crawl');
  const browser = await puppeteer.launch();
  await Promise.all(
    urls.map(async (url) => {
      const page = await browser.newPage();
      return page.goto(url);
    })
  );
  await browser.close();
  console.timeEnd('crawl');
})();
```
When I open multiple instances of browser simultaneously in headless mode, the execution finishes within 30 seconds of default timeout (taking around 10-15 secs actually). Where as in the second case, where I'm opening multiple tabs in a single browser instance, it is timing out with `TimeoutError: Navigation timeout of 30000 ms exceeded`. And my CPU is hitting 100%.

<img width="2170" alt="image" src="https://user-images.githubusercontent.com/11040416/180634236-d806249b-aa01-4f5b-97f3-bdc7d10de5be.png">

**It is happening only headless mode**. When I set `headless: false`, it is the opposite (what I expect). In headful mode, the multiple browser instances scenario is timing out sometimes, where as the multiple tabs in single browser case finishes without timeout (around in 10 secs). Which is expected, because, IMO, single browser with multiple should take up less resources when compared to spinning up multiple whole browser instances.

**Platform:**
- MacBook Pro (16-inch, 2019)
- 2.4 GHz Intel Core i9  (8-Core)
- Memory - 32 GB DDR4

### Puppeteer version

15.4.0

### Node.js version

16.14.0

### npm version

8.3.1

### What operating system are you seeing the problem on?

macOS

**Comment by OrKoN** [comment] 2022-07-24 07:00
Looks like some bug in CDP or the handling of CDP messages by Puppeteer. The CPU is 100% in the browser process? so could be also some sort of Chromium issue.

**Comment by sduluganti** [comment] 2022-07-24 23:30
> The CPU is 100% in the browser process?

Sorry, I'm not sure how I can check if CPU is 100% in browser process.

**Comment by OrKoN** [comment] 2022-07-25 12:35
After having a brief look, I discovered that the underlying issue that one of the pages never sends a load event when multiple pages are created in parallel. For example, if you add `{ waitUntil: 'domcontentloaded' }` to the `goto` call, nothing times out. Is it possible that the test website timeout/take longer to load when multiple requests are being sent?

**Comment by OrKoN** [comment] 2022-07-25 12:37
It does not seem to happen with other sites. @sduluganti could it be the issue with the site itself?

**Comment by sduluganti** [comment] 2022-07-25 17:27
I've tested with other sites. It is happening only with this site. Also,

1. it is not happening with `{ headless: false }`, but, only in headless mode. 
2. It is also not happening in case of opening multiple browser instances.
3. The `load` event should be fired by the browser. Isn't it?. Does site have to send that event?

**Comment by OrKoN** [comment] 2022-07-25 18:23
The load event is fired by the browser, yes, but it is fired when all resources (img/css etc) finished loading. It looks like when you launch multiple instances some resource on the site gets really slow.

**Comment by sduluganti** [comment] 2022-07-25 19:09
> It looks like when you launch multiple instances some resource on the site gets really slow.

Hmm, but it is not happening in **headful** mode or in case of multiple browser instances. Could be an issue with headless?

**Comment by OrKoN** [comment] 2022-07-26 05:14
On that level (e.g., loading events, DOM) there should be no difference between headful and headless but I cannot rule out that there is something specific to headless that triggers this. On the other hand, it also seems to be specific to this website. Are there any special web features that it uses? I will see if I find a root cause later.

**Comment by sduluganti** [comment] 2022-07-28 21:35
Sorry, for the late reply. There are no special features for the site AFAIK.

**Comment by Kikobeats** [comment] 2022-07-29 18:08
Hello, I just wanted to say I'm suffering this too.

My current setup is one browser process and create a browser (incognito) context for taking a screenshot, close the context after that. 

Eventually, the system collapses in a way `page.goto` works, but `page.screenshot`that is immediately after that doesn't be resolved on time.

The service is taking around 10M screenshots per month, and my assumption creating a browser context will penalty less than spawning the browser every time, but isn't happening right now.

**Comment by jsmonkey** [comment] 2023-02-09 06:09
Bump up. Having the same issue for arm arch. Opening multiple pages of the same website within the same browser instance makes it work only for a single page, the rest of them drop with timeout error eventually.

**Comment by t0mm4rx** [comment] 2023-10-12 14:56
This problem is still a thing in v16.2.
I have multiple instances headless browsers doing parallel operations, the first one works well but the other ones hangs on random operations like page.screenshot or page.$x.

On Ubuntu x86_64.

**Comment by OrKoN** [comment] 2024-08-08 20:44
I am unable to reproduce using the latest version. So either something fixed in Chrome/Puppeteer or on the website.

**Closed as completed by OrKoN** 2024-08-08 20:44 UTC
Labels: confirmed, P3
