### ISSUE TITLE
[Bug]: Error: Could not find expected browser (chrome) locally when running puppeteer 19 with a google cloud function

### ISSUE THREAD

**Issue by Wizzel1** [puppeteer/puppeteer#9131] opened 2022-10-18 17:45 UTC
### Bug description

Steps to reproduce the problem:

1. Create a google cloud function that uses puppeteer 19
2. Trigger the function

### Puppeteer version

19.0.0

### Node.js version

16.14.2

### npm version

8.5.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
"Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (1045629).
    at ChromeLauncher.launch (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:69:23)
    at PuppeteerNode.launch (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/PuppeteerNode.js:149:31)
    at PuppeteerExtra.launch (/workspace/node_modules/puppeteer-extra/dist/index.cjs.js:128:41)
    at async upload (/workspace/lib/uploaders/uploader/uploader.js:91:21)
    at async /workspace/lib/uploaders/amazon_uploader/amazon_uploader.js:59:20"
```

**Comment by Wizzel1** [comment] 2022-10-18 17:53
Downgrading to the previously installed version (18.2.1) doesn't fix this issue.

**Comment by jrandolf** [comment] 2022-10-19 00:48
Duplicate of https://github.com/puppeteer/puppeteer/issues/9128

**Closed as not planned** 2022-10-19 00:48 UTC
