### ISSUE TITLE
"Non-headless" mode appears sometimes required when launched from an IIS hosted web api service.  

### ISSUE THREAD

**Issue by BugRaptor** [puppeteer/puppeteer#1485] opened 2017-11-28 11:36 UTC
I'm new to both NodeJS and puppeteer and the issue I'm reporting might be a misuse or a misconfiguration of something on IIS or in the puppeteer usage im my .js script. If so, I apologize.

Let me explain what I did, what was the issue and how I finally solved it with a curious workaround.

I'm using puppeteer and headless chromium to get some swiss map extracts from the following swiss geographical portal: [http://www.geo.vd.ch](http://www.geo.vd.ch)

I wrote a simple getmap.js script to screenshot this webpage for a given location in Switzerland.

for example, querying the following url displays a swiss map extract at the given location (given by its swiss coordinates):

[http://www.geo.vd.ch/theme/localisation_thm?map_x=537971.000&map_y=156015.000&map_zoom=6&tree_group_layers_donnees_base_grp=cop_lad_canton%2Cloc_pt_adresse&tree_group_layers_cadastre_donnees_grp=cad_adr_p_label&baselayer_opacity=100&baselayer_ref=plan](http://www.geo.vd.ch/theme/localisation_thm?map_x=537971.000&map_y=156015.000&map_zoom=6&tree_group_layers_donnees_base_grp=cop_lad_canton%2Cloc_pt_adresse&tree_group_layers_cadastre_donnees_grp=cad_adr_p_label&baselayer_opacity=100&baselayer_ref=plan)
 
The getmap.js script launches puppeteer, sets the right viewport and then goes to this url and saves a screenshot as a .png file exactly like in the documentation examples.

```
address = 'http://www.geo.vd.ch/theme/localisation_thm' 
    + '?map_x=' + x + '.000'
    + '&map_y=' + y + '.000'
    + '&map_zoom=' + zoom 
    + '&tree_group_layers_donnees_base_grp=cop_lad_canton%2Cloc_pt_adresse'
    + '&tree_group_layers_cadastre_donnees_grp=cad_adr_p_label'
    + '&baselayer_opacity=' + opacity 
    + '&baselayer_ref=plan';

const puppeteer = require('puppeteer');
		
(
	async() => 
	{
		const browser = await puppeteer.launch(); 
		const page = await browser.newPage();
		await page.setViewport({width: imageWidth + leftClipRect + rightMarginClipRect, height: imageHeight + topClipRect + bottomMarginClipRect})
		await page.goto(address, {waitUntil: 'networkidle2'});
		// {waitUntil: 'networkidle2'} is required to wait for the complete display of the map.
		await page.screenshot(
		{
			path: imageFileName, 
			clip: // cliping the displayed map only:
			{
				x: leftClipRect,
				y: topClipRect,
				width: widthClipRect,
				height: heightClipRect
			}
		});
		browser.close();
	}
)();
```

When launched manually with node.exe in a Windows command cmd.exe (on Windows 10 or on Windows Web server 2008 R2, with Node.exe: v8.9.1, pupeeteer: 0.13.0, chromium rev: 515411) everything is fine and the .png image file is correctly captured and saved in the current folder.

I then wrote a ASP.NET Web API service handling http requests and having to return the requested map extract. To do this, it launches a windows process running Node.exe, itself running the getmap.js script with the right parameters. It then reads the .png file, returns the attachement stream and deletes the local .png file.

I hosted this web api service on my IIS 7 web server hosted on a Windows Web server 2008 R2.

You can test it with this URL returning a map.png file as attachement:

[www.raptordev.ch/api/maps/getimagefile/photo=false,x=537971,y=156015,zoom=6,imagewidth=800,imageheight=800 ](www.raptordev.ch/api/maps/getimagefile/photo=false,x=537971,y=156015,zoom=6,imagewidth=800,imageheight=800)

(I actually query this URL from another php script to display some map extracts, but that's another story...)

So you'll say that everything seems to be ok, so what is the issue ?

Actually if the getmap.js script  is written so, this doesn't work ! 

For an unknown reason, when my getmap.js script is launched by node.exe, itself launched as a new Windows process from my IIS Web Api service, when the headless browser launched by pupeeter goes to the requested URL, it mysteriously hangs and never returns !

Again, if Node.exe is manually launched in a cmd window with the getmap.js script as argument, it works without problem.

And, surprisingly, after a long debugging process to understand what happens, I finally found the following workaround: I simply launched puppeteer in non-headless mode:

```
	async() => 
	{
		const browser = await puppeteer.launch({headless: false}); 
		// Surprisingly, the "not headless" mode is required for an unknown reason when this js script is executed  by launching a node.exe windows 
		// process from an ASP.NET web API service hosted on an IIS server to access the http://www.geo.vd.ch geographic map web site.
		// If not, the page.goto() will never return. (Using {waitUntil: 'networkidle2'} or not.)
```

And now it works when launched from my Web API service !

Note that the issue does not appear with some other target URL, like https://example.com ! Maybe some redirections or delays in the [http://www.geo.vd.ch](http://www.geo.vd.ch) url cause the issue. I really do not know.

I neither don't know if the issue is related to the puppeteer implementation itself or in headless chromium or maybe in my IIS configuration...

Please, let me know if you have any idea about this issue. Thanks.

**Comment by MrSco** [comment] 2017-11-28 13:53
Yes, i believe I’ve been experiencing the same behavior and came to the same bass ackwards work around by turning headless mode off. Maybe @aslushnikov can help ...?

**Comment by vonGameTheory** [comment] 2017-11-28 18:06
Headless or not, if I try to go to the raptordev.ch url, it seems like nothing is happening at all.  No events are fired: no framenavigated event, not even a request event,  and dumpio displays nothing.  However, it DOES actually go to the page, and the map is created -- but the process never gets it.  (I see can see this by running it through a proxy even in headless mode.)  That page is pretty weird though -- it is returning an html document with a map.png as as attachment.   If your script returned an image directly as an image (with image headers, not as as attachment) it would probably work.  (Although I'm mystified why no events are fired at start of process.)  Is this the same thing as trying to navigate to a pdf (which docs say doesn't work)?

**Comment by BugRaptor** [comment] 2017-11-30 15:19
@vonGameTheory I think there is a misunderstanding. The raptordev url I placed in my post ([www.raptordev.ch/api/maps/getimagefile/photo=false,x=537971,y=156015,zoom=6,imagewidth=800,imageheight=800](www.raptordev.ch/api/maps/getimagefile/photo=false,x=537971,y=156015,zoom=6,imagewidth=800,imageheight=800)) is not an URL causing trouble when navigated with a puppeteer's headless browser. It's a URL pointing to my Web API service - hosted on my IIS web server - which starts a Windows process running node.exe, itself executing my getmap.js script which itself launches puppeteer in headfull mode to query the www.geo.vd.ch portal in order to extract the requested map. This getimagefile web API service simply returns the requested map as a map.png attached file. The point is only why does the puppeteer's page.goto() call not work when launched in that specific server side context in headless mode ? Again it works fine if the getmap.js launches puppeteer normally (in headless mode) and is executed from a cmd Windows manually launched in a Windows user session on the same PC.

**Comment by vonGameTheory** [comment] 2017-11-30 16:09
I get the exact same behavior headless or not -- that is, Chromium does navigate to the page but Puppeteer/Node gives no any indication it is doing so -- no events whatsoever seem to be fired, nothing is returned.  (It times out eventually Node-side.)  In headful mode you can of course see the browser and click on the created attachment manually and download it.  In headless mode you can't tell if anything is happening at all (except I can, because I run it through a proxy so I can see what it is doing).  HTML pages returning images as attachments rather than images directly is not something I have experience with, but I do know there is a puppeteer issue with pdf pages and I'm wondering if this is a similar case.  

So I don't know what the problem is, just suggesting a workaround in the meantime might be to have your server send an image directly as an image, not a page with attachments, and see if that works better.

**Comment by BugRaptor** [comment] 2017-11-30 16:21
The issue is not in the way the web API service sends the image, since when it lauches puppeteer in headless mode from the process started by my web API service, the puppeteer page.goto() call will hang and will not reach the www.geo.vd.ch page. This of course happens before beeing able to capture the screenshot. and sending it in the http response...
Again, if the getmap.js script is executed normally from a user session, it works fine in headless mode or not. The issue appears only in the server side context.

**Comment by vonGameTheory** [comment] 2017-11-30 16:40
What I am seeing is the page.goto() hang (headless or headful) and Chromium itself goes to geo.vd.ch in both cases, the map image is created, etc.  Except there is no communication (apparently) back to node/puppeteer.  In other words, I am seeing no difference between headless and headful going to that url, in both cases even though Chromium does in-fact navigate to the page, not even a single 'request' event is fired in puppeteer at the start of the process.  So I would tend to suspect the attachment thing as being an odd case, but I don't really know, or maybe just something weird about your server that puppeteer doesn't know what to do with (initial response headers or something).  But headless vs headful are each showing exact same behavior for me.  I will set-up a local server to serve up attachment-laden html files for testing and see if that is a general problem...

**Comment by vonGameTheory** [comment] 2017-12-04 17:12
Yeah, so I tested this and as I suspected, puppeteer is just not handling attachments like this, so I suppose that's an actual bug?  (Anybody else reading this?)

Anyway, your rapordev.ch server is returning the map with headers like:

Content-Disposition:attachment; filename=map.png
Content-Type:text/html
Content-Length: 1503283


If instead it sent image headers:

Content-Type:image/png
Content-Length: 1503283

Then it ought to work fine.

**Comment by BugRaptor** [comment] 2017-12-05 07:32
Hi @vonGameTheory. And thank you for your help. But again I think there is a misunderstanding, I'm afraid.
I do NOT use Puppeteer to query my www.raptordev web API url. Pupeeteer/Chromium is hanging when trying to go to the given http://www.geo.vd.ch URL. (In headless mode only when launched from the Web API service on my IIS server).
It never returns from the following asynchronous call:

`await page.goto(address, {waitUntil: 'networkidle2'});`

where the address URL value is:

`http://www.geo.vd.ch/theme/localisation_thm?map_x=537971.000&map_y=156015.000&map_zoom=6&tree_group_layers_donnees_base_grp=cop_lad_canton%2Cloc_pt_adresse&tree_group_layers_cadastre_donnees_grp=cad_adr_p_label&baselayer_opacity=100&baselayer_ref=plan`

This URL does NOT return any map/file image or html/text attachement. It simply displays the map on the browser's page and I intend to capture the displayed map with the following page.screenshot() call:

```
		await page.screenshot(
		{
			path: imageFileName, 
			clip: // cliping the displayed map only:
			{
				x: leftClipRect,
				y: topClipRect,
				width: widthClipRect,
				height: heightClipRect
			}
		});
```

But I cannot, since the page.goto() call hangs. (except if Pupeeteer is launched in headfull mode).

So my only question is: "Why does the puppeteer headless mode make page.goto() hang on this www.geo.vd.ch URL when launched from an IIS Web API service context ?"

**Comment by aslushnikov** [comment] 2017-12-11 11:49
> So my only question is: "Why does the puppeteer headless mode make page.goto() hang on this www.geo.vd.ch URL when launched from an IIS Web API service context ?"

@BugRaptor I'm not sure about the IIS, but on OS X the following script works fine for me:

```js
const puppeteer = require('.');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('http://www.geo.vd.ch/');
  await browser.close();
})();
```

I'm afraid we won't be able to help much if the issues arise only in case of IIS.

**Comment by BugRaptor** [comment] 2017-12-11 12:49
> I'm afraid we won't be able to help much if the issues arise only in case of IIS.

It's not very troublesome since launching puppeteer in headfull ou headless mode makes no difference in an IIS Web service which anyway has no visible UI. But it was surprising and I lost some time to findout this workaround... Thanks for your help anyway.

**Comment by vonGameTheory** [comment] 2017-12-11 15:51
Note to admin (if you didn't follow this closely):

Even though I totally missed the issue of the OP, looks like we found a bug accidentally in this thread: puppeteer is seemingly unable to handle that attachment stuff, seemingly this header:

Content-Disposition:attachment; filename=map.png

As I noted above, it doesn't even fire a request event at all, which I find bizarre -- I figured that would be fired before the request even started, but something apparently that is fired after the request is sent to the browser (because the browser actually does go to the page) -- but back in node nothing happens and it times out.

**Comment by aslushnikov** [comment] 2018-01-10 05:07
> Note to admin (if you didn't follow this closely):
>
> Even though I totally missed the issue of the OP, looks like we found a bug accidentally in this thread: puppeteer is seemingly unable to handle that attachment stuff, seemingly this header:

> Content-Disposition:attachment; filename=map.png
>
> As I noted above, it doesn't even fire a request event at all, which I find bizarre -- I figured that would be fired before the request even started, but something apparently that is fired after the request is sent to the browser (because the browser actually does go to the page) -- but back in node nothing happens and it times out.

@vonGameTheory This seems to be related to #299.

> It's not very troublesome since launching puppeteer in headfull ou headless mode makes no difference in an IIS Web service which anyway has no visible UI. But it was surprising and I lost some time to findout this workaround... Thanks for your help anyway.

@BugRaptor thanks to reaching out to us! Closing this since we can't help much with the issue.

**Closed as completed by aslushnikov** 2018-01-10 05:07 UTC

**Comment by QuentinWangWJJ** [comment] 2018-04-06 17:40
I met the same issue. const page = await browser.newPage(); seems not work on iis7
