### ISSUE TITLE
Missing antialiasing on boxes

### ISSUE THREAD

**Issue by manast** [puppeteer/puppeteer#886] opened 2017-09-26 13:23 UTC
I am not sure if this is a wrong setting or an issue. I could not find anything on the documentation or stackoverflow regarding this. 
I am on Mac OS Sierra, tested on puppeter version 0.11 and 0.12 alpha. In 0.12 the div edges were better rendered but still no antialiasing, which does not look very good. I attached screenshots and example code:
```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('file:///Users/manuel/dev/raviteq/url2img/index.html');
  await page.screenshot({
    path: 'example.png',
    clip: {
      x:0,
      y:0,
      width: 300,
      height: 250
    }
  });

  await browser.close();
})();
```
Original html file:
[index.html.zip](https://github.com/GoogleChrome/puppeteer/files/1333283/index.html.zip)

Original rendered image with puppeteer:
![example](https://user-images.githubusercontent.com/95200/30862460-696db136-a2ce-11e7-80f5-36da5040d7e3.png)

Zoom in into edge:
![image](https://user-images.githubusercontent.com/95200/30862451-631c0526-a2ce-11e7-8768-c988f5997ec0.png)

Result rendered in standard google chrome:
![image](https://user-images.githubusercontent.com/95200/30862498-8f1973ca-a2ce-11e7-8d47-dd74791099be.png)

**Comment by Garbee** [comment] 2017-09-26 14:11
We run with `--disable-gpu` [enabled by default](https://github.com/GoogleChrome/puppeteer/blob/86b05dadd5eab23f83185e0d5d16d3df00732681/lib/Launcher.js#L69) on the launched Chrome instances. With that in mind, this looks expected to me depending on how exactly the boxes get rendered.

**Comment by manast** [comment] 2017-09-26 14:58
I understand. How can I override this setting, and also, why would the software renderer not support antialiasing, is it a chrome limitation?

**Comment by Garbee** [comment] 2017-09-26 15:05
Currently you can't override this from what I can tell. I think if we switch to the `chrome-launcher` package (which as I recall is being looked into) then it should be possible to enable GPU stuff.

As to why it isn't supported, that isn't something I'm able to answer. Perhaps someone from the team can provide some detailed information on that one.

**Comment by ebidel** [comment] 2017-09-26 15:24
https://github.com/GoogleChrome/puppeteer/issues/872 will allow overriding default flags.

**Comment by aslushnikov** [comment] 2017-10-03 03:44
Thanks Eric, closing as a dupe of #872.

**Closed as completed by aslushnikov** 2017-10-03 03:44 UTC
