### ISSUE TITLE
How to disbale the chrome_crashpad_handler process?

### ISSUE THREAD

**Issue by akitaTian** [puppeteer/puppeteer#13419] opened 2024-12-18 08:03 UTC
## ENV
node v22.11.0
puppetee 21.9.0
chrome 125.0.6422.141

## script launch args 
    const chromeArgs = [
        '--no-sandbox',
        '--no-zygote',
        '--disable-setuid-sandbox',
        '--disable-gpu',
        '--single-process',
        '--mute-audio',
        '--ignore-certificate-errors',
        '--ignore-certificate-errors-spki-list',
        '--ssl-version-max=tls1.3',
        '--ssl-version-min=tls1',
        '--disable-web-security',
        '--allow-running-insecure-content',
        '--proxy-bypass-list=<-loopback>',
        '--disable-application-cache',
        '--disable-crashpad-for-testing',
        `--window-size=${options.windowSize.join(",")}`,
    ];
    
  ## problem
when laucnh my script, will launch two chrome_crashpad_handler processes ,  Is there any way to turn them off?
```
chrome_crashpad_handler --monitor-self --monitor-self-annotation=ptype=crashpad-handler
chrome_crashpad_handler --no-periodic-tasks --monitor-self-annotation=ptype=crashpad-handler
```

**Comment by OrKoN** [comment] 2024-12-18 08:14
Is it on Windows? sounds like duplicate of https://github.com/puppeteer/puppeteer/issues/2778

**Closed as not planned** 2024-12-18 08:14 UTC
