### ISSUE TITLE
How to get runtime coverage (without stopJSCoverage) ? 

### ISSUE THREAD

**Issue by realdennis** [puppeteer/puppeteer#3603] opened 2018-11-28 11:59 UTC
**What is the expected result?**

I used `startJSCoverage` to track my script coverage, but after I call the `stopJSCoverage` method to get the result, the current coverage state has been reset ... how to resume last coverage state?

I need to try some sequential user action, need the previous coverage info and each coverage result will affect what the next action I need to use (I try to make a guided testing),  how could I resume the current coverage state?  Or some coverage API get result without stopJSCoverage.

**Comment by aslushnikov** [comment] 2018-12-14 02:36
This is a dupe of #1887 

Shouldn't be hard to implement btw - please upvote to bump priority.

**Closed as completed by aslushnikov** 2018-12-14 02:36 UTC
Labels: chromium
