### ISSUE TITLE
page.waitForFileChooser stopped uploading file after upgrade to 2.1.0

### ISSUE THREAD

**Issue by divyamvn** [puppeteer/puppeteer#5384] opened 2020-02-03 21:27 UTC
Issue Description:
File chooser worked perfectly on v2.0.0. It would happily upload any number of files. Once I upgraded to v2.1.0 last week, there is no error...everything goes smoothly, but no file is uploaded.
I again reverted back to v2.0.0 and things are back to normal

### Steps to reproduce

* Puppeteer version: v2.1.0
* Platform / OS version: macOS sierra/windows 10
* URLs (if applicable):
* Node.js version: v12.14.1

**What steps will reproduce the problem?**

const [ fileChooser ] = await Promise.all( [
            page.waitForFileChooser(),
            page.click( 'button.fileAttach' ), // button that triggers file selection
        ] );
        await fileChooser.accept( [filePath ] );
        await forms.click( page, 'button.fileSend' );

**What is the expected result?**
Files get uploaded.

**What happens instead?**
False Positive!!! Files are neither uploaded nor an error thrown...Things run smoothly, execution is over, but when I go check the Files view, there are no files uploaded. I ran it slowly with break points to see if its a sync issue (As sometimes, big files has sync problem)
So I revert back to v2.0.0 and file upload works properly again.

**Comment by tomothumb** [comment] 2020-02-04 14:22
v2.1.0. A method input.uploadFile() doesn't work as well.

**Comment by andreabisello** [comment] 2020-02-06 13:30
same issue here,
i solved changing my package.json from
"puppeteer": "^2.0.0",
to
"puppeteer": "2.0.0"

this downloaded chromium 79 instead of chromium 80,
and it works again.

**Comment by wardnath** [comment] 2020-02-06 23:45
@andreabisello Same issue & solution for me as as well. Confirmed that the file upload fails silently with no logging to the console.

**Comment by Georgegriff** [comment] 2020-02-13 23:36
Looks like a fix was attempted in 2.1.1 but im still seeing this file uploads not working in 2.1.1 via codeceptjs, reference code thats not working anymore.

hard-coding to 2.0.0 the problem goes awaay

```javascript
   */
  async attachFile(locator, pathToFile) {
    const file = path.join(global.codecept_dir, pathToFile);

    if (!fileExists(file)) {
      throw new Error(`File at ${file} can not be found on local system`);
    }
    const els = await findFields.call(this, locator);
    assertElementExists(els, 'Field');
    await els[0].uploadFile(file);
    return this._waitForAction();
  }
```

**Comment by vfa-minhtv** [comment] 2020-02-20 09:06
I have the same problem too! =(

**Comment by wardnath** [comment] 2020-02-21 21:32
Hey all, I believe the way I solved the problem was to add 

```
    args: [
      '--disable-features=site-per-process',
    ]

```

to the puppeteer launch params

**Comment by dtboy1995** [comment] 2020-03-09 12:29
same issue

**Comment by sebastiandittrich** [comment] 2020-03-16 15:43
> same issue here,
> i solved changing my package.json from
> "puppeteer": "^2.0.0",
> to
> "puppeteer": "2.0.0"
> 
> this downloaded chromium 79 instead of chromium 80,
> and it works again.

Yes, downgrading to 2.0.0 solved this issue also for me.

**Comment by paullewis** [comment] 2020-04-17 09:05
This should be fixed as of 532ae573d29063ffd081ed9ee340d71b25320dec as we changed the underlying implementation to use `DOM.setFileInputFiles`, which behaves a lot more as expected. Going to close this issue, but please let us know if it's not fixed.

**Closed as completed by paullewis** 2020-04-17 09:05 UTC

**Comment by andreabisello** [comment] 2020-04-17 09:13
@paullewis what version should i put on package.json in order to install puppeteer with this fix? so i will try

**Comment by paullewis** [comment] 2020-04-17 09:16
@mathiasbynens Can you help here? I presume we're not released with this fix yet?

**Comment by mathiasbynens** [comment] 2020-04-17 09:37
@andreabisello We'll cut a new patch release soon. Until then, you can install from GitHub to try the fix: `npm install https://github.com/GoogleChrome/puppeteer`

**Comment by Georgegriff** [comment] 2020-04-17 09:38
Im not sure if this is related but ive switched to 3.0.0 and i'm seeing that when i do file uploads of images/pdfs my mimetype isn't being set correctly, seems to all be application/octet-stream rather than image/* or application/pdf

**Comment by paullewis** [comment] 2020-04-17 09:50
@Georgegriff Right, the published version on npm won't have it yet, once we get a release out it will :)

**Comment by Georgegriff** [comment] 2020-04-17 09:56
Awesomeness, I'll try out the instructions above

**Comment by divyamvn** [comment] 2020-04-17 18:30
beautiful. It works on 3.0.0. Thanks a ton!!
