### ISSUE TITLE
request interception wont trigger for resources within html (using file://)

### ISSUE THREAD

**Issue by Riuujin** [puppeteer/puppeteer#2382] opened 2018-04-16 08:28 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: Windows
* Node.js version: 8.11.1

**What steps will reproduce the problem?**

```
const puppeteer = require('puppeteer');

puppeteer.launch().then(async browser => {
    const page = await browser.newPage();
    await page.setRequestInterception(true);
    page.on('request', interceptedRequest => {
        console.log(interceptedRequest.url());
        interceptedRequest.continue();
    });
    await page.goto('file:///c:/test.html');
    await browser.close();
});
```

```
<!DOCTYPE html>
<html>
<head>
    <link type="text/css" rel="stylesheet" href="/style.css" />
</head>
<body> 
  <p>test</p>
</body>
</html>
```

**What is the expected result?**
The url of the request for the 'file:///C:/style.css' should be printed in the console.

**What happens instead?**
Only the html file request itself is printed.

**Comment by aslushnikov** [comment] 2018-04-17 02:32
This is a dupe of #1506.

**Closed as completed by aslushnikov** 2018-04-17 02:32 UTC
