### ISSUE TITLE
Adobe acrobat custom fonts error in pdf?

### ISSUE THREAD

**Issue by manking99** [puppeteer/puppeteer#3664] opened 2018-12-13 14:57 UTC
Hello!

Getting error text message when open PDF in adobe acrobat reader
Error with T3Font_4

![image](https://user-images.githubusercontent.com/5559817/49945732-8ae1c400-fefe-11e8-8cdc-06a8bf62423f.png)
![image](https://user-images.githubusercontent.com/5559817/49945969-03488500-feff-11e8-8102-d8921e5bbf69.png)

![image](https://user-images.githubusercontent.com/5559817/49946336-d8126580-feff-11e8-96ec-3910e4dc3cea.png)

**In wkhtml2pdf library everything is correct. Font RussianRailGProRegular included in PDF and opens successfully in adobe acrobat reader**
![image](https://user-images.githubusercontent.com/5559817/49946475-20318800-ff00-11e8-9c71-f43c67aaecb8.png)

Is there any way to fix this?

**Comment by aslushnikov** [comment] 2018-12-13 20:08
Hey @manking99,

If I understand correctly, you've generated a PDF with Puppeteer and then trying to open it in Adobe Acrobat Reader. 

If this is the case, than issue is either with the way Chrome generates PDF's (likely) or Acrobat reader opening them (unlikely). I'd recommend filing a bug upstream to https://crbug.com/new with a reproduction steps to let developers generate this PDF locally and see the problem for themselves.

Closing this since it falls outside of the scope of the project.

**Closed as completed by aslushnikov** 2018-12-13 20:08 UTC
