### ISSUE TITLE
page.goto is stuck on some websites on firebase cloud functions

### ISSUE THREAD

**Issue by alexandrzavalii** [puppeteer/puppeteer#4194] opened 2019-03-21 19:44 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.13.0
* Platform / OS version: Google Cloud
* URLs (if applicable):
* Node.js version: 8
* 2GB

A bit more information:
- I tried literally all versions of puppeteer starting from **1.1.0** to **1.14.0** 
- the problem occurs only in **google cloud** (cloud functions). it works on any other cloud platform or locally.
- My website has ssl error.

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

await.page.goto("somewebsite.com")

**What is the expected result?**
Page expected to be loaded.

**What happens instead?**
Instead I receive timeout in google cloud.

**I didn't share the code because there is no problem with running it locally or on AWS.**

I am stuck on this for few weeks already. The website does not load ONLY on Google Cloud however it does load locally or in AWS lambda. 
The problem is that the error is **not helpful** at all, the page.goto is just timing out.

`Navigation Timeout Exceeded`

I was wondering if there is a **proper way to debug this**. 
Could it be OS issue? 
but then again, AWS and Google cloud are both Linux based?

Note: After opening a ticket on google cloud support, I was redirected to firebase support.
Looks like its firebase related

**Comment by RebliNk17** [comment] 2019-03-27 11:25
Same for: svyaznoy.ru
When increasing the timeout to a really big number (like 500000000) it's just stuck...
with puppeteer-firefox it's working fast...

Versions:
v1.8.0 & v1.13.0

**Comment by limenote135** [comment] 2019-04-03 17:14
I have the same problem with v1.7.0 & v1.14.0.

It shows following logs.

```
Function execution started
Unhandled rejection
TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/srv/functions/node_modules/puppeteer/lib/LifecycleWatcher.js:143:21)
  -- ASYNC --
    at Frame.<anonymous> (/srv/functions/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.goto (/srv/functions/node_modules/puppeteer/lib/Page.js:656:49)
    at Page.<anonymous> (/srv/functions/node_modules/puppeteer/lib/helper.js:111:23)
    at Main (/srv/functions/index.js:46:20)
Function execution took 32783 ms, finished with status: 'crash'
```

**Comment by aslushnikov** [comment] 2019-04-05 01:03
+cc @steren 

This looks like a dupe of #3120

**Comment by alexandrzavalii** [comment] 2019-04-05 07:57
@aslushnikov no, this is not duplicate. It's not about being slow. It's about not being resolved at all. 
`page.goto` is always timing out. no matter what.
- I tried literally all versions of puppeteer starting from **1.1.0** to **1.14.0** 
- RAM is set to **2GB** in google cloud.
- the problem occurs only in **google cloud** (cloud functions). it works on any other cloud platform or locally
- My website has ssl error

**Comment by Robula** [comment] 2019-04-05 14:19
I'm getting sporadic timeouts (usually every 3-4 requests) on my GCP Cloud Function, either with `goto` or `setContent`. I've tried different runtimes (8, 10) and regions to no avail.

I'm getting timeouts but no stack traces or even basic debug logging on these requests

**Comment by gamesbykevin** [comment] 2019-04-09 04:28
I previously submitted a ticket to support and I no longer receive the error
They mentioned my memory usage and suggested I increase from 512mb to 1GB
In addition node 8 was previously in beta and recommended to run in node 6, I don't think node 8 is beta anymore
They also told me that node 8 and node 6 were running on a different linux OS behind scenes
I also copied my function to a new one

**Comment by alexandrzavalii** [comment] 2019-04-09 07:38
@gamesbykevin Thanks, I also opened a ticket.
apparently in my case it is related to firebase environment

**Comment by aslushnikov** [comment] 2019-04-12 01:10
Looks like this has to do with Firebase rather than with Puppeteer.

**Closed as completed by aslushnikov** 2019-04-12 01:10 UTC

**Comment by giovannibonetti** [comment] 2019-06-19 17:55
Hey, @alexandrzavalii, did you find a workaround for this problem `TimeoutError: Navigation Timeout Exceeded` on Cloud Functions when you try to access a website with a bad certificate?

I'm currently struggling with the same problem... 😅

**Comment by ix-xerri** [comment] 2019-08-28 11:25
Was there any solution to this? Trying to add html directly inside `goTo()` with `data:text/html` but no matter what the timeout time is I still get `TimeoutError: Navigation Timeout Exceeded`.

**Comment by marcosouvereyns** [comment] 2020-03-14 14:34
> I'm getting sporadic timeouts (usually every 3-4 requests) on my GCP Cloud Function, either with `goto` or `setContent`. I've tried different runtimes (8, 10) and regions to no avail.
> 
> I'm getting timeouts but no stack traces or even basic debug logging on these requests

Been getting this issue as well when trying to navigate multiple pages one after another

**Comment by BenMoses** [comment] 2020-12-03 18:35
I am having the exact same issues and this is my code - No idea what to do. Contacted firebase and they say they're not puppeteer experts and so can't help 😢 

```
exports.exampleBug = functions
  .region("europe-west2")
  .runWith({ timeoutSeconds: 300, memory: "2GB" })
  .pubsub.schedule("05 17 * * *")
  .timeZone('Europe/London')
  .onRun(async (/*context*/) => {
    const puppeteer = require("puppeteer");
    const browser = await puppeteer.launch({
          args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });
    const page = await browser.newPage()
    console.log('navigate');
    await page.goto("https://publicaccess.aylesburyvaledc.gov.uk/online-applications/search.do?action=weeklyList");
    console.log('success');
});
```
