### ISSUE TITLE
[Feature]: When intercept a request, how can I get the real response?

### ISSUE THREAD

**Issue by ysyfff** [puppeteer/puppeteer#10455] opened 2023-06-27 07:37 UTC
### Feature description

Here is the situation:

When set setRequestInterception to true and intercept the request, we can easily mock the response with request.respond. **But what if I want to get the real response and then modify some fields and values and then call request.respond？** There is no way to get the real response unless we called request.continue, but this not what I need. What about add a method called **request.getResponse()** to do this job. I think this feature is very useful for testing！

**Comment by OrKoN** [comment] 2023-06-27 07:55
It's not possible to get a response without continuing the request, right? You probably want a response interception feature?

**Comment by OrKoN** [comment] 2023-06-27 07:55
Duplicate of https://github.com/puppeteer/puppeteer/issues/1191

**Closed as not planned by OrKoN** 2023-06-27 07:55 UTC

**Comment by ysyfff** [comment] 2023-06-27 08:01
> It's not possible to get a response without continuing the request, right? You probably want a response interception feature?

My purpose is to get the real response and modify some fields and values and then return it to browser, if the response interception can do that, it will be wonderful!

**Comment by ysyfff** [comment] 2023-06-27 08:02
> Duplicate of #1191

This is it
