### ISSUE TITLE
[Feature]: Integrate chrome-headless-shell binaries

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#10736] opened 2023-08-16 07:15 UTC
### Feature description

See https://googlechromelabs.github.io/chrome-for-testing/

- [x] Support in `@puppeteer/browsers`
- [ ] Support in `puppeteer` 

In Puppeteer, we probably want to download the chrome-headless-shell binary by default as well as launch it when the user configures the `headless: true`.

**Comment by OrKoN** [comment] 2023-08-16 07:22
cc @mathiasbynens

**Comment by Sparticuz** [comment] 2023-10-18 20:11
I'm working on getting `chrome-headless-shell` working on the upcoming amazon linux 2023 lambda containers, so right now I'm working on getting it running inside a docker image (amazonlinux:2023), but I'm getting an error running it after downloading in @puppeteer/browsers. Looking up that error brings me to https://chromium.googlesource.com/chromium/src/base/+/master/i18n/icu_util.cc#240, which leads me to a private issue https://bugs.chromium.org/p/chromium/issues/detail?id=445616

Any ideas?

```shell
sh-5.2# npx @puppeteer/browsers install chrome-headless-shell    
Downloading chrome-headless-shell r120.0.6073.0 - 76 MB [====================] 100% 0.0s 
chrome-headless-shell@120.0.6073.0 /root/chrome-headless-shell/linux-120.0.6073.0/chrome-headless-shell-linux64/chrome-headless-shell
sh-5.2# cd chrome-headless-shell/linux-120.0.6073.0/chrome-headless-shell-linux64/
sh-5.2# ls 
ABOUT  chrome-headless-shell
sh-5.2# ./chrome-headless-shell --headless --remote-debugging-port=9222 https://chromium.org
[1018/195318.101023:ERROR:icu_util.cc(240)] Invalid file descriptor to ICU data received.
Trace/breakpoint trap
```

**Comment by Lightning00Blade** [comment] 2024-01-26 17:31
Closing as completed in https://github.com/puppeteer/puppeteer/pull/11754,
@Sparticuz if the issue is still present please open a separate issue for it.

**Closed as completed by Lightning00Blade** 2024-01-26 17:31 UTC
