### ISSUE TITLE
Puppeteer stalls after 33 click + Meta Refresh in a row (using waitForNavigation)

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#4179] opened 2019-03-18 22:05 UTC
The loop below stalls after 33 iterations on my computer

```javascript
const puppeteer = require('puppeteer')
const express = require('express')

const siteAPort = 10000
const siteBPort = 10001
const siteAUrl = `http://localhost:${siteAPort}`
const siteBUrl = `http://localhost:${siteBPort}`

let browser
let page

const main = async () => {
  await setupSites()

  const options = {
    args: ['--window-size=50,50'],
    headless: false
  }
  browser = await puppeteer.launch(options)
  page = await browser.newPage()

  let counter = 0
  while (true) {
    await page.goto(siteAUrl)
    await page.click('a')
    await page.waitForNavigation()
    console.log(counter++)
  }
}

main()

async function setupSites () {
  const siteA = express()
  siteA.use(pageWithLink)
  await new Promise(resolve => siteA.listen(siteAPort, resolve))
  const siteB = express()
  siteB.use(redirector)
  await new Promise(resolve => siteB.listen(siteBPort, resolve))

  function pageWithLink (req, res) {
    res.send(`<a href="${siteBUrl}">Link</a>`)
  }

  async function redirector (req, res) {
    const metaRefreshRedirect = `
      <html>
        <head>
          <meta http-equiv="refresh" content="0;URL='${siteAUrl}'">
        </head>
        <body></body>
      </html>
    `

    res.send(metaRefreshRedirect)
  }
}
```

**Comment by aslushnikov** [comment] 2019-03-19 01:43
Dupe of #4011 

This is fixed in v1.13.0

**Closed as completed by aslushnikov** 2019-03-19 01:43 UTC
