### ISSUE TITLE
[Bug]: Header/Footer placeholders stopped working in chrome-headless-shell in Docker

### ISSUE THREAD

**Issue by josiasmontag** [puppeteer/puppeteer#12196] opened 2024-04-03 13:58 UTC
### Minimal, reproducible example

```TypeScript
const { writeFile } = require('fs/promises');
const { launch } = require('puppeteer');

const puppeteerOptions = {
    margin: { top: 100, bottom: 100, left: 100, right: 100 },
    format: 'a4',
    displayHeaderFooter: true,
    headerTemplate: '<div style="font-size:20px; padding-left: 20px;">Page: <span class="pageNumber"></span> / <span class="totalPages"></span></div>',
    footerTemplate: '<div style="font-size:20px; padding-left: 20px;">Page: <span class="pageNumber"></span> / <span class="totalPages"></span></div>',
};

async function main() {
    const browser = await launch({
        args: ['--no-sandbox', '--disable-dev-shm-usage'],
        headless: 'shell',
    });

    const page = await browser.newPage();
    await page.setContent('<div>Hello, World!</div>', { waitUntil: 'networkidle0' });

    const pdf = await page.pdf(puppeteerOptions);

    await browser.close();

    writeFile('./output/output.pdf', pdf);
}

 main();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

Since Puppeteer v22, the magic CSS classes stopped working on Linux and  old headless (`shell`) mode:

![image](https://github.com/puppeteer/puppeteer/assets/1945577/a845b7bd-74be-4846-a40e-b4175a708053)

It works correctly:
* On Linux and new headless
* On MacOS and new headless 
* On MacOS and old headless (`shell`)

![image](https://github.com/puppeteer/puppeteer/assets/1945577/15525477-9c88-4ae6-a4e1-630120521580)

Reproducer using Docker and the script above:

`docker run -i --init --cap-add=SYS_ADMIN --rm -v .:/home/pptruser/output/ ghcr.io/puppeteer/puppeteer:latest node -e "$(cat test.js)"`

Also see #10024 (last 2 comments)

### Expectation

I expected to get the `pageNumber` and `totalPages` placeholder to be replaced.

### Reality

It does not get replaced on Linux with headless `shell`. 

### Puppeteer version

22.6.2

### Node version

20.11.1

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Linux

**Comment by OrKoN** [comment] 2024-04-04 10:48
I am able to reproduce in docker but not able to reproduce on a full Linux distro.

**Comment by outbackStack** [comment] 2024-04-08 11:07
Maybe we are missing some additional packages to run on Linux? That's my current  additional installs which was working before v22
- wget 
- ca-certificates 
- libnss3 
- libatk1.0-0 
- libatk-bridge2.0-0 
- libcups2 
- libdrm2 
- libxkbcommon-x11-0 
- libxcomposite1 
- libxdamage1 
- libgbm1 
- libpangocairo-1.0-0 
- libasound2 
- libxfixes3 
- libxrandr2

**Comment by Peque** [comment] 2024-04-19 10:43
@josiasmontag Did you find any workaround?

I can confirm it is working just fine under Linux while developing, but when building the Docker image the header/footer are missing.

**Comment by OrKoN** [comment] 2024-04-24 10:49
It has to be some missing packages (fonts maybe?), I tried a bunch and so far has not been able to identify it

**Comment by outbackStack** [comment] 2024-04-24 11:01
I don't think it's the fonts as the word "Page" is showing.

` <li>Page: <span class="pageNumber"></span>/<span class="totalPages"></span></li>`

**Comment by OrKoN** [comment] 2024-04-24 11:11
So in the browser the parameters for the footer/header are executed as a script https://source.chromium.org/chromium/chromium/src/+/main:components/printing/renderer/print_render_frame_helper.cc;l=680;drc=f0f5f3ceebb00da9363ccc7a1e2c0f17b6b383ba and that ends up on the page for the footer/header https://source.chromium.org/chromium/chromium/src/+/main:components/printing/resources/print_header_footer_template_page.html;l=83;drc=f6529c7990744370869e4ab2794caae6c46ba044 

I do not see so far why the values could be empty so I currently assume that something happens with the rendering

**Comment by OrKoN** [comment] 2024-04-24 11:16
Perhaps there is some sort of script execution error.

**Comment by outbackStack** [comment] 2024-04-24 11:17
All fonts are embedded. 

<img width="438" alt="Screenshot 2024-04-24 at 9 12 13 PM" src="https://github.com/puppeteer/puppeteer/assets/16639496/31dca1d2-de04-44bf-a586-55921306f35a">

**Comment by outbackStack** [comment] 2024-04-24 11:25
I will try to see if I could log `pageNumber` number

`
 for (const cssClass of ['date', 'title', 'url', 'pageNumber', 'totalPages']) {
    for (const element of document.querySelectorAll(`.${cssClass}`)) {
      element.textContent = options[cssClass];
    }
  }
`

**Comment by OrKoN** [comment] 2024-04-24 11:50
I don't think you can log from the footer/header frame

**Comment by OrKoN** [comment] 2024-04-24 13:40
I have built a tip-of-trip headless shell and I am not able to reproduce an issue with it in Docker. Perhaps, something produced by the build is missing.

**Comment by outbackStack** [comment] 2024-04-24 19:44
@OrKoN Would you be able to send us your docker file so we can test on our Linux VM?

**Comment by OrKoN** [comment] 2024-04-25 17:45
The Dockerfile is here https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile

**Comment by OrKoN** [comment] 2024-04-25 19:24
@Peque this issue description already provides this information. As for color, sounds unrelated: in general, the printing with headless Chrome (not shell) should match printing using the print dialog in headful Chrome.

**Comment by dannybeckett** [comment] 2024-04-29 20:07
This is probably unrelated but another time that page numbers broke on Docker installs (when working fine on normal Linux installs), the solution was to copy the `locales` dir in to the Docker image - per a [chromedp issue](https://github.com/chromedp/chromedp/issues/922#issuecomment-937500493)

I haven't tried this as I'm unsure as to where to copy the dir to for `FROM ghcr.io/puppeteer/puppeteer:latest` (the OP was using `FROM chromedp/headless-shell:stable`)

**Comment by dannybeckett** [comment] 2024-04-29 20:13
From another user:

> Ever since updating to version `22.2.0`, the page number no longer appears. Is anyone else experiencing this issue on a Debian server? It seems to be working fine on a Mac.

_Originally posted by @outbackStack in https://github.com/puppeteer/puppeteer/issues/5345#issuecomment-1963292064_

**Comment by dannybeckett** [comment] 2024-04-29 20:14
From myself on a new issue closed as a dupe of this one:

> I am also experiencing lack of page numbers when using `headless: 'shell'`. I also tried adding `--lang=en-US` to the `args` of `const browser = await puppeteer.launch()` as suggested on #5345

The footer adds, but displays "Page of" instead of "Page 3 of 12" E.G.

Whereas without `headless: 'shell'` (using the default `headless` setting), the page numbers display without any problem.

Similar to the OP I am running Debian (latest). I am using Docker (latest) to install and run Puppeteer (latest).

_Originally posted by @dannybeckett in https://github.com/puppeteer/puppeteer/issues/12361#issuecomment-2081658259_

**Comment by OrKoN** [comment] 2024-04-30 05:48
I filed an upstream issue https://crbug.com/337047877 as it does look like something is missing from chrome-headless-shell

**Comment by OrKoN** [comment] 2024-04-30 08:57
I can confirm it is caused by locales (thanks for the hint). Copying locales from chromium seems to help but also setting `export LANG=en_US.UTF-8` helps.

**Comment by outbackStack** [comment] 2024-04-30 09:15
yah! thanks everyone! I can get my page number back! LOL

**Comment by OrKoN** [comment] 2024-05-02 09:25
This was also fixed upstream to properly detect en_US.POSIX locale and https://crbug.com/338179885 filed to include locales into the headless shell distribution to support other locales. With this, I am closing the issue and the fix will be out with the next release.

**Closed as completed by OrKoN** 2024-05-02 09:25 UTC
Labels: confirmed, P2
