### ISSUE TITLE
waiting until domcontentloaded with request interception always times out on certain sites

### ISSUE THREAD

**Issue by dj-nitehawk** [puppeteer/puppeteer#3674] opened 2018-12-14 14:05 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform: tried on windows 10 and ubuntu 18.04
* URLs: http://uam.es/UAM/Home.htm?language=es
* Node.js version: v10 on Windows / v8 on Ubuntu

**What steps will reproduce the problem?**
try to run the following code snippet. error is reproducible every time. 

    (async () => {
      const puppeteer = require('puppeteer');

      const browser = await puppeteer.launch({ dumpio: true })
      const page = await browser.newPage()

      await page.setRequestInterception(true)
      page.on('request', request => {
        request.continue()
      })

      try {
        page.evaluateOnNewDocument(() => {
          setInterval(() => {
            console.log(document.readyState)
          }, 1000);
        })
        await page.goto('http://uam.es/UAM/Home.htm?language=es',
          {
            timeout: 15000,
            waitUntil: 'domcontentloaded'
          })
      } catch (error) {
        console.log("ERROR: " + error.message)
      }

      const title = await page.title()
      console.log("TITLE: " + title)

      await browser.close()
    })()

**What is the expected result?**
`goto` method should not timeout when request interception is enabled and waiting until `domcontentloaded`. turning off request interception fixes the issue. this is definitely a bug which occurs only on certain sites like the above.

**What happens instead?**
looks like `domcontentloaded` event is never fired and the `goto` method times out no matter the timeout seconds specified. even though the method times out, the page seems to be fully rendered.

**Comment by aslushnikov** [comment] 2018-12-14 18:19
A dupe of #3471

**Closed as completed by aslushnikov** 2018-12-14 18:19 UTC
