### ISSUE TITLE
Switching to New Tab?

### ISSUE THREAD

**Issue by floydtagle** [puppeteer/puppeteer#978] opened 2017-10-08 03:40 UTC
Is there a way to switch to a new Tab and go back to the current tab? It seems I cannot find a way to handle multiple  page/tab on one browser using puppeteer. Thanks

**Comment by vsemozhetbyt** [comment] 2017-10-08 09:14
There may be soon: https://github.com/GoogleChrome/puppeteer/pull/554

**Comment by floydtagle** [comment] 2017-10-09 03:17
@vsemozhetbyt I see.. Thanks a lot.

**Comment by aslushnikov** [comment] 2017-10-10 07:08
Dupe of #386

**Closed as completed by aslushnikov** 2017-10-10 07:08 UTC
