### ISSUE TITLE
[Regression]: `page.goto` API throws a `TypeError` if Firefox uses the WebDriverBiDi protocol

### ISSUE THREAD

**Issue by timvandermeij** [puppeteer/puppeteer#11938] opened 2024-02-17 18:25 UTC
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

const browser = await puppeteer.launch({
  product: "firefox",
  headless: false,
  protocol: "webDriverBiDi",
});
const pages = await browser.pages();
const page = pages[0];
await page.goto("https://github.com/puppeteer/puppeteer");
```

### Error string

TypeError: Cannot read properties of undefined (reading 'goto')

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

For Mozilla's PDF.js project we use Puppeteer to run our browser tests, and recently in https://github.com/mozilla/pdf.js/pull/17172 the test suite was updated to let Firefox run with the WebDriverBiDi protocol. However, updating Puppeteer from 22.0.0 to 22.1.0 today suddenly caused Firefox to no longer start with `TypeError: Cannot read properties of undefined (reading 'goto')` when trying to visit our test runner page.

The issue is reproducible with the following steps:

1. Install Puppeteer 22.0.0.
2. Create `repro.js` with the provider reproducer script.
3. Run `node repro.js` and notice that Firefox works and navigates to the Puppeteer GitHub page.
4. Install Puppeteer 22.1.0.
5. Run `node repro.js` again and notice that Firefox quickly shows up and then exits once the `page.goto` API is called. The type error mentioned above is logged.

Note that the reproducer script works fine in Puppeteer 22.1.0 if the protocol is set to CDP, so this seems to be a WebDriverBiDi-specific issue. Unless I've missed something I can't find anything in the Puppeteer 22.1.0 changelog that would suggest that this way of using `page.goto` is no longer valid (and that'd probably be a breaking change anyway so I wouldn't expect that in a minor version release as well).

/cc @whimboo @OrKoN as you might be interested in this given that the introduction of WebDriverBiDi in PDF.js was also done to spot any WebDriverBiDi issues as soon as possible now that WebDriverBiDi development is ongoing.

### Expectation

The reproducer script should correctly launch Firefox and open the Puppeteer GitHub page in both Puppeteer 22.0.0 and Puppeteer 22.1.0.

### Reality

The reproducer script only correctly launches Firefox and opens the Puppeteer GitHub page in Puppeteer 22.0.0, but in Puppeteer 22.1.0 a `TypeError` is thrown.

### Puppeteer version

22.1.0

### Node version

21.6.2

### Package manager

npm

### Package manager version

10.4.0

### Operating system

Linux

**Comment by timvandermeij** [comment] 2024-02-17 18:31
I'm not sure why the analyzer run above failed because the error seems unrelated to this issue:

```
/home/runner/work/puppeteer/puppeteer/node_modules/semver/classes/semver.js:38
      throw new TypeError(`Invalid Version: ${version}`)
            ^

TypeError: Invalid Version: 18
```

I have double-checked that the reproducer script works locally to make sure there is no problem with it.

**Comment by OrKoN** [comment] 2024-02-17 19:20
Thanks for filing. It looks like this is not goto throwing but rather the initial page is undefined.

**Comment by OrKoN** [comment] 2024-02-17 19:21
@jrandolf PTAL

**Comment by whimboo** [comment] 2024-02-18 08:36
@OrKoN maybe #11915 was not a dupe?

**Comment by OrKoN** [comment] 2024-02-19 07:07
It does not sound like because `should fail when navigating and show the url at the error message` is passing now and it does create a fresh page instead of getting the default page created by the browser. I am not sure we have test coverage for this use case.

**Comment by whimboo** [comment] 2024-02-19 07:59
I probably mis-read your `initial page` comment from above. 

I tried to reproduce but I'm not able to replicate the error message. Instead the navigation just hangs for me and the `page.goto` never completes. But that also happened in 22.0.0, and so it might even be something else.

**Comment by OrKoN** [comment] 2024-02-19 08:05
Actually, I do not seem to be able to reproduce with the latest Firefox nightly. Which Firefox version did you use?

**Comment by whimboo** [comment] 2024-02-19 09:47
I was using latest Nightly as well. It's not clear to me what the `page.goto` command is waiting for. The `domContententLoaded` event has been emitted and that's what should be needed when the command is called like: 

```
{"id":5,"method":"browsingContext.navigate","params":{"context":"0c283dc0-a2cc-4280-bb86-6a53d15abb37","url":"https://github.com/puppeteer/puppeteer","wait":"interactive"}}
```

**Comment by OrKoN** [comment] 2024-02-19 09:49
@whimboo the report says that in this code

```
const pages = await browser.pages();
const page = pages[0];
```

page is undefined. I don't think it ever goes to goto.

**Comment by OrKoN** [comment] 2024-02-19 09:54
@whimboo are you sure that in your tests the command is actually timing out? in the repro, there is no browser.close so the script will be running till the browser is closed.

I have tested on a Mac and on a Linux and so far I am not able to reproduce this bug.

**Comment by whimboo** [comment] 2024-02-19 10:35
I can actually reproduce with the following steps:

1. Clone https://github.com/mozilla/pdf.js
2. Modify https://github.com/mozilla/pdf.js/blob/master/package.json to require Puppeteer 22.1.0
3. Run `npm install`
4. Run `gulp browsertest --noChrome`

Here is the log output when enabling trace logs:

```
1708338816364	RemoteAgent	DEBUG	WebDriverBiDiConnection 9e593e1f-d815-4d15-afa4-75441ddce5dc -> {"id":1,"method":"session.new","params":{"capabilities":{"alwaysMatch":{"acceptInsecureCerts":false,"webSocketUrl":true}}}}
1708338816367	WebDriver BiDi	DEBUG	Connection 9e593e1f-d815-4d15-afa4-75441ddce5dc attached to session 517b4fbd-9606-41ba-b8d8-a7470182d487
1708338816367	WebDriver BiDi	DEBUG	Waiting for initial application window
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
1708338817020	RemoteAgent	TRACE	Received observer notification browser-idle-startup-tasks-finished
1708338817022	WebDriver BiDi	DEBUG	Registered session handler: /session/517b4fbd-9606-41ba-b8d8-a7470182d487
1708338817022	RemoteAgent	DEBUG	WebDriverBiDiConnection 9e593e1f-d815-4d15-afa4-75441ddce5dc <- {"type":"success","id":1,"result":{"sessionId":"517b4fbd-9606-41ba-b8d8-a7470182d487","capabilities":{"browserName":"firefox","browserVersion":"124.0a1","platformName":"mac","acceptInsecureCerts":false,"proxy":{},"setWindowRect":true,"moz:accessibilityChecks":false,"moz:buildID":"20240130045011","moz:headless":false,"moz:platformVersion":"23.2.0","moz:processID":15343,"moz:profile":"/var/folders/sd/hgkqcwv90sz_q1pqjww78nfm0000gn/T/puppeteer_dev_firefox_profile-u8pOvN","moz:shutdownTimeout":60000,"moz:windowless":false}}}
DevTools listening on ws://127.0.0.1:55114/devtools/browser/c39b3c45-496d-456d-aa0e-b8f31feb4ba8
1708338817023	RemoteAgent	DEBUG	WebDriverBiDiConnection 9e593e1f-d815-4d15-afa4-75441ddce5dc -> {"id":2,"method":"browser.getUserContexts","params":{}}
1708338817025	RemoteAgent	TRACE	Registered MessageHandlerFrame actors
1708338817026	RemoteAgent	TRACE	Created MessageHandler ROOT for session 517b4fbd-9606-41ba-b8d8-a7470182d487
1708338817026	RemoteAgent	TRACE	Module root/browser.sys.mjs found for ROOT
1708338817026	RemoteAgent	TRACE	Received command browser.getUserContexts for destination ROOT
1708338817026	RemoteAgent	TRACE	Module root/browser.sys.mjs found for ROOT
1708338817026	RemoteAgent	TRACE	Module root/browser.sys.mjs found for ROOT
1708338817026	RemoteAgent	DEBUG	WebDriverBiDiConnection 9e593e1f-d815-4d15-afa4-75441ddce5dc <- {"type":"success","id":2,"result":{"userContexts":[{"userContext":"default"},{"userContext":"f6de1749-7851-4cc5-8bec-337cf792a7fd"},{"userContext":"658980df-23c3-40c5-81de-4c893e82a75e"},{"userContext":"4f072b8c-400a-4e5e-9b92-f4f98b2a0e02"},{"userContext":"c47eb33e-6e2e-40f4-8123-fcc2af9c45da"}]}}
1708338817027	RemoteAgent	DEBUG	WebDriverBiDiConnection 9e593e1f-d815-4d15-afa4-75441ddce5dc -> {"id":3,"method":"browsingContext.getTree","params":{}}
1708338817028	RemoteAgent	TRACE	Module root/browsingContext.sys.mjs found for ROOT
1708338817028	RemoteAgent	TRACE	Received command browsingContext.getTree for destination ROOT
1708338817028	RemoteAgent	TRACE	Module root/browsingContext.sys.mjs found for ROOT
1708338817028	RemoteAgent	TRACE	Module root/browsingContext.sys.mjs found for ROOT
1708338817029	RemoteAgent	DEBUG	WebDriverBiDiConnection 9e593e1f-d815-4d15-afa4-75441ddce5dc <- {"type":"success","id":3,"result":{"contexts":[{"context":"d01e6ae0-4505-47fc-9314-168202554758","url":"about:blank","children":[],"parent":null}]}}
1708338817029	RemoteAgent	DEBUG	WebDriverBiDiConnection 9e593e1f-d815-4d15-afa4-75441ddce5dc -> {"id":4,"method":"session.subscribe","params":{"events":["browsingContext","network","log","script"]}}
1708338817030	RemoteAgent	TRACE	Module root/session.sys.mjs found for ROOT
1708338817030	RemoteAgent	TRACE	Received command session.subscribe for destination ROOT
1708338817030	RemoteAgent	TRACE	Module root/session.sys.mjs found for ROOT
1708338817030	RemoteAgent	TRACE	Module root/session.sys.mjs found for ROOT
1708338817030	RemoteAgent	TRACE	Module root/browsingContext.sys.mjs found for ROOT
1708338817030	RemoteAgent	TRACE	Module root/network.sys.mjs found for ROOT
1708338817031	RemoteAgent	TRACE	Module root/log.sys.mjs found for ROOT
1708338817031	RemoteAgent	TRACE	Module root/script.sys.mjs found for ROOT
1708338817032	RemoteAgent	TRACE	Module windowglobal-in-root/browsingContext.sys.mjs found for WINDOW_GLOBAL
1708338817032	RemoteAgent	TRACE	Module windowglobal/browsingContext.sys.mjs found for WINDOW_GLOBAL
1708338817032	RemoteAgent	TRACE	Received command browsingContext._applySessionData for destination WINDOW_GLOBAL
1708338817032	RemoteAgent	TRACE	Module windowglobal-in-root/browsingContext.sys.mjs found for WINDOW_GLOBAL
1708338817032	RemoteAgent	TRACE	Module windowglobal/browsingContext.sys.mjs found for WINDOW_GLOBAL
1708338817032	RemoteAgent	TRACE	Module windowglobal-in-root/browsingContext.sys.mjs found for WINDOW_GLOBAL
1708338817032	RemoteAgent	TRACE	Module root/browsingContext.sys.mjs found for ROOT
1708338817032	RemoteAgent	TRACE	Received command browsingContext._applySessionData for destination ROOT
1708338817032	RemoteAgent	TRACE	Module root/browsingContext.sys.mjs found for ROOT
1708338817033	RemoteAgent	TRACE	Module windowglobal-in-root/network.sys.mjs not found for WINDOW_GLOBAL
1708338817033	RemoteAgent	TRACE	Module windowglobal/network.sys.mjs not found for WINDOW_GLOBAL
1708338817033	RemoteAgent	TRACE	Module root/network.sys.mjs found for ROOT
1708338817033	RemoteAgent	TRACE	Received command network._applySessionData for destination ROOT
1708338817033	RemoteAgent	TRACE	Module root/network.sys.mjs found for ROOT
1708338817033	RemoteAgent	TRACE	Module root/network.sys.mjs found for ROOT
1708338817034	RemoteAgent	TRACE	Module windowglobal-in-root/log.sys.mjs found for WINDOW_GLOBAL
1708338817034	RemoteAgent	TRACE	Module windowglobal/log.sys.mjs found for WINDOW_GLOBAL
1708338817034	RemoteAgent	TRACE	Received command log._applySessionData for destination WINDOW_GLOBAL
1708338817034	RemoteAgent	TRACE	Module windowglobal-in-root/log.sys.mjs found for WINDOW_GLOBAL
1708338817034	RemoteAgent	TRACE	Module windowglobal/log.sys.mjs found for WINDOW_GLOBAL
1708338817034	RemoteAgent	TRACE	Module windowglobal-in-root/log.sys.mjs found for WINDOW_GLOBAL
1708338817034	RemoteAgent	TRACE	Module root/log.sys.mjs found for ROOT
1708338817034	RemoteAgent	TRACE	Module windowglobal-in-root/script.sys.mjs found for WINDOW_GLOBAL
1708338817034	RemoteAgent	TRACE	Module windowglobal/script.sys.mjs found for WINDOW_GLOBAL
1708338817034	RemoteAgent	TRACE	Received command script._applySessionData for destination WINDOW_GLOBAL
1708338817034	RemoteAgent	TRACE	Module windowglobal-in-root/script.sys.mjs found for WINDOW_GLOBAL
1708338817035	RemoteAgent	TRACE	Module windowglobal/script.sys.mjs found for WINDOW_GLOBAL
1708338817035	RemoteAgent	TRACE	Module windowglobal-in-root/script.sys.mjs found for WINDOW_GLOBAL
1708338817035	RemoteAgent	TRACE	Module root/script.sys.mjs found for ROOT
1708338817035	RemoteAgent	TRACE	Received command script._applySessionData for destination ROOT
1708338817035	RemoteAgent	TRACE	Module root/script.sys.mjs found for ROOT
1708338817035	RemoteAgent	TRACE	Module root/script.sys.mjs found for ROOT
1708338817035	RemoteAgent	TRACE	Created MessageHandler WINDOW_GLOBAL for session 517b4fbd-9606-41ba-b8d8-a7470182d487
1708338817035	RemoteAgent	TRACE	Received command browsingContext._applySessionData for destination WINDOW_GLOBAL
1708338817035	RemoteAgent	TRACE	Module windowglobal-in-root/realm-created.sys.mjs not found for WINDOW_GLOBAL
1708338817035	RemoteAgent	DEBUG	WebDriverBiDiConnection 9e593e1f-d815-4d15-afa4-75441ddce5dc <- {"type":"event","method":"script.realmCreated","params":{"realm":"ee949ae6-ac4d-4482-b3c0-93236b3f6d0e","origin":"null","context":"d01e6ae0-4505-47fc-9314-168202554758","type":"window"}}
1708338817035	RemoteAgent	TRACE	Module windowglobal-in-root/window-global-handler-created.sys.mjs not found for WINDOW_GLOBAL
1708338817035	RemoteAgent	TRACE	Module windowglobal/browsingContext.sys.mjs found for WINDOW_GLOBAL
1708338817035	RemoteAgent	TRACE	Module windowglobal/browsingContext.sys.mjs found for WINDOW_GLOBAL
1708338817036	RemoteAgent	TRACE	Received command log._applySessionData for destination WINDOW_GLOBAL
1708338817036	RemoteAgent	TRACE	Module windowglobal/log.sys.mjs found for WINDOW_GLOBAL
1708338817036	RemoteAgent	TRACE	Module windowglobal/log.sys.mjs found for WINDOW_GLOBAL
1708338817036	RemoteAgent	TRACE	Received command script._applySessionData for destination WINDOW_GLOBAL
1708338817037	RemoteAgent	TRACE	Module windowglobal/script.sys.mjs found for WINDOW_GLOBAL
1708338817037	RemoteAgent	TRACE	Module windowglobal/script.sys.mjs found for WINDOW_GLOBAL
1708338817037	RemoteAgent	DEBUG	WebDriverBiDiConnection 9e593e1f-d815-4d15-afa4-75441ddce5dc <- {"type":"success","id":4,"result":{}}
Error while starting firefox: Cannot read properties of undefined (reading 'goto')
```

The command `browsingContext.getTree` clearly returns a single open top-level browsing context.

**Comment by whimboo** [comment] 2024-02-19 10:39
Interestingly the cached version of Firefox was from January 30th. Removing it and re-fetching the latest Nightly build fixes the issue for me.

@timvandermeij can you please check if you have an older Nightly build cached (in CI) as well?

**Comment by whimboo** [comment] 2024-02-27 12:45
Just spoke internally about this problem and it's not visible anymore when [upgrading to 22.3.0](https://github.com/mozilla/pdf.js/pull/17733). 

I would suggest closing the issue.

**Closed as not planned by whimboo** 2024-02-27 12:45 UTC
Labels: P1, needs-feedback

**Comment by 0x0480** [comment] 2024-02-27 14:42
```
puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:92
    #error = new ProtocolError();
             ^

ProtocolError: Protocol error (browser.getUserContexts): unknown command browser.getUserContexts 

RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5
UnknownCommandError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:784:5
execute@chrome://remote/content/shared/webdriver/Session.sys.mjs:271:13
onPacket@chrome://remote/content/webdriver-bidi/WebDriverBiDiConnection.sys.mjs:211:37
onMessage@chrome://remote/content/server/WebSocketTransport.sys.mjs:127:18
handleEvent@chrome://remote/content/server/WebSocketTransport.sys.mjs:109:14

    at <instance_members_initializer> (puppeteer-core/lib/esm/puppeteer/common/
CallbackRegistry.js:92:14)
    at new Callback (puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.j
s:96:16)
    at CallbackRegistry.create (puppeteer-core/lib/esm/puppeteer/common/Callbac
kRegistry.js:19:26)
    at BidiConnection.send (puppeteer-core/lib/esm/puppeteer/bidi/Connection.js
:51:32)
    at Session.send (puppeteer-core/lib/esm/puppeteer/bidi/core/Session.js:175:
42)
    at Session.<anonymous> (puppeteer-core/lib/esm/puppeteer/util/decorators.js
:94:27)
    at #syncUserContexts (puppeteer-core/lib/esm/puppeteer/bidi/core/Browser.js
:145:70)
    at #initialize (puppeteer-core/lib/esm/puppeteer/bidi/core/Browser.js:141:4
1)
    at Browser.from (puppeteer-core/lib/esm/puppeteer/bidi/core/Browser.js:113:
38)
    at #initialize (puppeteer-core/lib/esm/puppeteer/bidi/core/Session.js:131:4
2)
```

also facing similar issue on 22.3.0

**Comment by whimboo** [comment] 2024-02-27 16:45
@0x0480 this is a different issue, and it looks like that you have an outdated browser version. Make sure to clean the Puppeteer cache and re-download the latest Firefox Nightly build.

**Comment by timvandermeij** [comment] 2024-03-20 12:59
> Just spoke internally about this problem and it's not visible anymore when [upgrading to 22.3.0](https://github.com/mozilla/pdf.js/pull/17733).
> 
> I would suggest closing the issue.

Thank you for looking into this! Since we're on Puppeteer 2.5.0 by now on the PDF.js side that confirms that the issue was indeed only visible in the older Nightly version.
