### ISSUE TITLE
"Mixed Content" error for blocked requests not intercept-able

### ISSUE THREAD

**Issue by crsc7** [puppeteer/puppeteer#2142] opened 2018-03-05 15:23 UTC
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
1.1.1
* Platform / OS version:
ubuntu 16.04
* URLs (if applicable):
https://a.df-srv.de/v2/view/lePQD7Tyr8SNUYizE5Yy/a.html
* Node.js version:
9.7.1

**What steps will reproduce the problem?**
Load a page over `https://` that has a `http://` resource embeded in an `<iframe>` object.
(Example page: https://a.df-srv.de/v2/view/lePQD7Tyr8SNUYizE5Yy/a.html)

The debug console if `devtools:true` is enabled will show:
`Mixed Content: The page at 'https://a.df-srv.de/v2/view/lePQD7Tyr8SNUYizE5Yy/a.html' was loaded over HTTPS, but requested an insecure resource 'http://ende.de/'. This request has been blocked; the content must be served over HTTPS.` 

However this message is not seen by puppeteer, even in the ` DEBUG=puppeteer:*` logs there is no sign of the blocked request.

_Please include code that reproduces the issue._

1. Load https://a.df-srv.de/v2/view/lePQD7Tyr8SNUYizE5Yy/a.html
2. See `Mixed Content: The page at 'https://a.df-srv.de/v2/view/lePQD7Tyr8SNUYizE5Yy/a.html' was loaded over HTTPS, but requested an insecure resource 'http://ende.de/'. This request has been blocked; the content must be served over HTTPS.`
3. Not intercept-able via `requestfailed`, `Network.loadingFailed`, `Network.requestIntercepted`, `Network.requestWillBeSent` or any other event.

**What is the expected result?**

Some way to catch the blocked `Mixed Content` log shown in the debug console.

**What happens instead?**

Nothing.

**Comment by MichaelErmer** [comment] 2018-03-05 15:49
Related https://github.com/GoogleChrome/puppeteer/issues/1936

**Comment by aslushnikov** [comment] 2018-04-10 23:37
These violations are reported via the [Log domain](https://vanilla.aslushnikov.com/#Log.clear) that we don't enable yet. We need to enable domain and introduce a new `page` event that forwards messages
from Log domain to the clients.

I'll be happy to review a PR.

**Comment by aslushnikov** [comment] 2018-04-11 01:13
Closing as dupe of #1939.

**Closed as completed by aslushnikov** 2018-04-11 01:13 UTC
Labels: good first issue
