### ISSUE TITLE
Track unhandled errors with source mapped stacktraces

### ISSUE THREAD

**Issue by nojvek** [puppeteer/puppeteer#664] opened 2017-09-02 19:12 UTC
Chrome Devtools exceptions shows mapped stacktraces.

Would be great if puppeteer could do that too. It's very common for devs to use webpack to bundle files. 

Could be even a helper function to convert bundled stacktrace to source mapped stack trace. 

We do this in vscode console : https://github.com/Microsoft/vscode-chrome-debug-core/pull/190 and its been a super helpful feature.

**Comment by aslushnikov** [comment] 2017-10-31 07:16
Closing as a dupe of #985

**Closed as completed by aslushnikov** 2017-10-31 07:16 UTC
